// Made by tools/build-catalog.mjs — do not edit by hand.
// The example presentations of templates/*.js: key → { name, summary, cat, file }, and each file's loader.
export const CATALOG = {"biz_strategy":{"name":"Plan estratégico y OKR","summary":"Estilo limpio en blanco: cifras que entran en cadena, pirámide, prioridades con iconos, tabla de OKR, barras de avance, radar y galones","cat":"biz","file":"biz"},
  "biz_board":{"name":"Resultados trimestrales al consejo","summary":"Azul oscuro y dorado: indicadores grandes animados con sonido, cascada, embudo, barras apiladas y tabla con fórmulas frente a presupuesto","cat":"biz","file":"biz"},
  "biz_marketing":{"name":"Plan de marketing de campaña","summary":"Estilo cálido: texto en círculo, público objetivo, embudo, mezcla de canales, calendario en tabla, presupuesto con fórmula y votación","cat":"biz","file":"biz"},
  "biz_sales":{"name":"Ventas y previsión anual","summary":"Minimalista en gris: barras y líneas combinadas, escenarios, fórmula de previsión, tabla con fórmulas, barras apiladas y horizontales","cat":"biz","file":"biz"},
  "biz_onboarding":{"name":"Bienvenida a nuevos empleados","summary":"Estilo amable: robot 3D que saluda y recorre la semana andando, organigrama uno a uno, valores con iconos y actividad de emparejar","cat":"biz","file":"biz"},
  "biz_proposal":{"name":"Propuesta comercial a un cliente","summary":"Estilo papel: sello, proceso uno a uno, maquetas en portátil y móvil, precios, presupuesto con IVA en fórmulas, cronología y garantías","cat":"biz","file":"biz"},
  "biz_swot":{"name":"Análisis DAFO y competencia","summary":"Fondo grafito: DAFO por cuadrantes, matriz de estrategias, mapa de posicionamiento, barras agrupadas, Venn, tarta y votación múltiple","cat":"biz","file":"biz"},
  "biz_roadmap":{"name":"Hoja de ruta de un proyecto","summary":"Estilo técnico oscuro: galones uno a uno, diagrama de Gantt animado, cronología, coche 3D que avanza con Transformar y tabla de estado","cat":"biz","file":"biz"},
  "biz_climate":{"name":"Encuesta de clima laboral","summary":"Violeta y participativo: cuenta atrás, barras al 100 %, valoración de 1 a 5, nube de palabras, elección múltiple y preguntas del público","cat":"biz","file":"biz"},
  "biz_investment":{"name":"Presentación para inversores","summary":"Negro y oro: producto 3D que gira y viaja con Transformar, cifras gigantes, mercado en círculos, tracción, uso de fondos y equipo","cat":"biz","file":"biz"},
  "creative_brutalism":{"name":"Brutalismo: manifiesto web","summary":"Estilo brutalista: tipografía gigante, bloques negros, texto vertical, sombras duras, tachado animado, tabla y votación","cat":"creative","file":"creative"},
  "creative_synthwave":{"name":"Synthwave: festival Neón 86","summary":"Estilo retro años 80: sol con degradado, rejilla que se dibuja, neón con brillo, Transformar, robot 3D que baila y nube de palabras","cat":"creative","file":"creative"},
  "creative_watercolor":{"name":"Acuarela: huerto en el balcón","summary":"Estilo acuarela y papel: manchas con degradado radial, formas a mano alzada, letra manuscrita, dibujo que se traza solo y 3D","cat":"creative","file":"creative"},
  "creative_glass":{"name":"Glassmorphism: app de finanzas","summary":"Tarjetas translúcidas sobre brillos de color, móvil con la app, gráfico de dona, Transformar una tarjeta y votación de valoración","cat":"creative","file":"creative"},
  "creative_comic":{"name":"Cómic: superpoderes animales","summary":"Estilo cómic: viñetas, bocadillos de diálogo y pensamiento, onomatopeyas en Text Art que rebotan, zorro 3D, gráfico y concurso","cat":"creative","file":"creative"},
  "creative_fashion":{"name":"Revista de moda: otoño lento","summary":"Estilo revista: cabecera en serif, reloj 3D en portada, columnas con capitular, cita grande, paleta de temporada y gráfico","cat":"creative","file":"creative"},
  "creative_zen":{"name":"Minimalismo japonés: el té","summary":"Minimalismo japonés: mucho blanco, sol rojo que se transforma, texto vertical, ensō que se pinta solo y cuenta atrás","cat":"creative","file":"creative"},
  "creative_bauhaus":{"name":"Bauhaus: forma y función","summary":"Arte geométrico Bauhaus: composición de formas primarias que giran y rebotan, cronología, Transformar una retícula y actividad de emparejar","cat":"creative","file":"creative"},
  "creative_space":{"name":"Galaxia: mirar al pasado","summary":"Estilo espacial: estrellas, nebulosas con brillo, modelos 3D de la NASA, sonda que recorre los planetas, texto curvo y concurso","cat":"creative","file":"creative"},
  "creative_pixel":{"name":"Pixel art: tu primer videojuego","summary":"Estilo videojuego retro: sprites de píxeles, marcador, personajes 3D que andan y saltan, código por pasos, concurso y cuenta atrás","cat":"creative","file":"creative"},
  "data_sales_regions":{"name":"Ventas por región","summary":"Barras agrupadas, apiladas y al 100 %, gráfico combinado con objetivo, tabla con totales por fórmula y KPIs animados","cat":"data","file":"data"},
  "data_satisfaction":{"name":"Encuesta de satisfacción","summary":"Anillo con leyenda, radares comparados, columnas con etiquetas, NPS, valoración y nube de palabras en directo","cat":"data","file":"data"},
  "data_home_finance":{"name":"Finanzas personales","summary":"Cascada del sueldo al ahorro, gráfico circular, líneas y área, tablas con SUMA, PROMEDIO, MAX y MIN","cat":"data","file":"data"},
  "data_web_metrics":{"name":"Métricas web y marketing","summary":"KPIs con minigráficos, líneas de cuatro series, áreas, embudo de conversión, combinado y tabla con fórmulas","cat":"data","file":"data"},
  "data_market_study":{"name":"Estudio de mercado","summary":"Cifras grandes, gráfico de rectángulos, burbujas, dispersión, barras horizontales de dos series y matriz 2 × 2","cat":"data","file":"data"},
  "data_population":{"name":"Población y demografía","summary":"Pirámide de población, histograma, barras horizontales, líneas que se cruzan y tabla de indicadores con fórmulas","cat":"data","file":"data"},
  "data_season_stats":{"name":"Temporada en cifras","summary":"Cifras gigantes con sonido, clasificación con fórmulas, barras negativas, líneas, apiladas y radar del equipo","cat":"data","file":"data"},
  "data_energy":{"name":"Energía y consumo","summary":"Áreas apiladas por hora, líneas de tres series, rectángulos, columnas con etiquetas y tabla de tarifas calculada","cat":"data","file":"data"},
  "data_ab_test":{"name":"Experimento A/B","summary":"Ecuaciones, dispersión de dos series, columnas con etiquetas, tabla de conversión con fórmulas y cifras de significación","cat":"data","file":"data"},
  "data_exec_panel":{"name":"Panel ejecutivo mensual","summary":"KPIs con semáforos y minigráficos, combinado frente a presupuesto, múltiplos pequeños, anillo y votación","cat":"data","file":"data"},
  "edu_volcanoes":{"name":"Los volcanes","summary":"Estilo fuego: erupción animada con sonido, partes del volcán para etiquetar, tabla, cuestionario con tiempo y cuenta atrás","cat":"edu","file":"edu"},
  "edu_cell":{"name":"La célula","summary":"Célula dibujada con formas, partes una a una, Transformar para acercarse, unir parejas, diagrama, planta 3D y valoración","cat":"edu","file":"edu"},
  "edu_revolution":{"name":"La Revolución Francesa","summary":"Estilo papel antiguo: texto en círculo, Transformar, pirámide social, cronología animada con sonido, ordenar hechos y votación","cat":"edu","file":"edu"},
  "edu_fractions":{"name":"Fracciones","summary":"Estilo neón: pizzas dibujadas, ecuaciones paso a paso, suma con Transformar, completar huecos, cuestionario y reto con cuenta atrás","cat":"edu","file":"edu"},
  "edu_body":{"name":"El cuerpo humano","summary":"Estilo laboratorio: figura 3D con Transformar, personaje que camina por un recorrido, gráfico de barras, etiquetar el cuerpo y cuestionario","cat":"edu","file":"edu"},
  "edu_water":{"name":"El ciclo del agua","summary":"Diagrama de ciclo uno a uno, paisaje con gotas que suben y lluvia animada con sonido, gráficos de dona, unir parejas y satélite 3D","cat":"edu","file":"edu"},
  "edu_quixote":{"name":"El Quijote","summary":"Estilo tinta y papel: molino que gira con sonido, texto curvo, citas animadas, Transformar, cronología, completar huecos y cuestionario","cat":"edu","file":"edu"},
  "edu_renewables":{"name":"Energías renovables","summary":"Aerogenerador que gira, tarjetas, gráficos de área, dona y barras agrupadas, nube de palabras en directo, votación y cuenta atrás","cat":"edu","file":"edu"},
  "edu_spain":{"name":"Geografía de España","summary":"Estilo atlas: rosa de los vientos, relieve en diana, tabla de ríos con fórmulas, gráficos de picos y lluvias, unir parejas y cuestionario","cat":"edu","file":"edu"},
  "edu_english":{"name":"English for beginners","summary":"Modo aula: tarjetas que giran con sonido, robot 3D que anda y saluda, zorro 3D, tres preguntas con puntos, clasificación y aplausos","cat":"edu","file":"edu"},
  "life_wedding":{"name":"Invitación de boda","summary":"Tipografía clásica y oro: Text Art, texto curvo, cronología de la pareja, mapa con recorrido animado, votación y cuenta atrás","cat":"life","file":"life"},
  "life_kids_party":{"name":"Cumpleaños infantil","summary":"Colores vivos: robot 3D que baila, personajes que celebran, globos a mano alzada, concurso con puntos y cuenta atrás","cat":"life","file":"life"},
  "life_cv":{"name":"Currículum visual","summary":"Texto en círculo, cifras, cronología uno a uno, barras de habilidades animadas, radar, pantallas en dispositivos y contacto","cat":"life","file":"life"},
  "life_italy":{"name":"Viaje por Italia","summary":"Texto en círculo, ruta con conectores y recorrido animado, cronología, presupuesto con fórmulas, gráficos y actividad de emparejar","cat":"life","file":"life"},
  "life_recipe":{"name":"Receta: guacamole","summary":"Aguacate 3D que viaja entre diapositivas (Transformar), ingredientes con fórmulas, pasos uno a uno, cuenta atrás y valoración","cat":"life","file":"life"},
  "life_fitness":{"name":"Plan de entrenamiento: 5 km","summary":"Corredor 3D, Text Art fuego, fases con degradados, semana con fórmulas, gráficos de progreso, pirámide, cuenta atrás y nube de palabras","cat":"life","file":"life"},
  "life_bookclub":{"name":"Club de lectura","summary":"Estantería a mano alzada, portada con formas, citas que se transforman, diagrama radial, valoración y votación del próximo libro","cat":"life","file":"life"},
  "life_moving":{"name":"Mudanza y nuevo hogar","summary":"Casa con formas a mano, cronología, lista que se tacha, muebles 3D que pasan al plano con Transformar, presupuesto y actividad de ordenar","cat":"life","file":"life"},
  "life_graduation":{"name":"Graduación y fin de curso","summary":"Text Art oro, birretes con formas, polaroids que giran al entrar, cifras con redoble, agradecimientos, nube de palabras y aplausos","cat":"life","file":"life"},
  "life_garden":{"name":"Huerto urbano","summary":"Planta 3D con Transformar, calendario de siembra en tabla de colores, ciclo, Venn, gráficos de riego y crecimiento, actividad de etiquetar","cat":"life","file":"life"},
  "product_watch":{"name":"Lanzamiento: reloj inteligente","summary":"Negro y oro: reloj 3D que viaja por tres diapositivas con Transformar y llegadas distintas, Text Art oro, radar y precios","cat":"product","file":"product"},
  "product_car":{"name":"Presentación: coche eléctrico","summary":"Coche 3D sin corte en los bordes que da la vuelta al entrar, Transformar, cifras, gráficos de área y barras, tabla y votación","cat":"product","file":"product"},
  "product_app":{"name":"Presentación de app móvil","summary":"App en móvil, tableta y portátil, Transformar, recorrido en galones, cifras, gráfico de retención y nube de palabras","cat":"product","file":"product"},
  "product_keynote":{"name":"Keynote de hardware","summary":"Estilo blanco premium: lámpara iridiscente y botella 3D, Transformar con etiquetas, flotar y acercar, cifras, tabla y precios","cat":"product","file":"product"},
  "product_saas":{"name":"Demo de plataforma SaaS","summary":"Panel en ventana de navegador con llamadas numeradas, radial, embudo, indicadores, barras apiladas, código por pasos y preguntas","cat":"product","file":"product"},
  "product_roadmap":{"name":"Hoja de ruta de producto","summary":"Camino que se dibuja solo, pirámide, cronología uno a uno, ahora y después, matriz, barras apiladas y votación múltiple y de ordenar","cat":"product","file":"product"},
  "product_furniture":{"name":"Colección de muebles","summary":"Estilo editorial: sofás y sillas 3D, Transformar con vistas distintas, balanceo y vuelta, muestras de color, tableta y presupuesto","cat":"product","file":"product"},
  "product_robot":{"name":"Robot asistente industrial","summary":"Estilo industrial: robot 3D que saluda, anda por un recorrido, encadena animaciones y baila; organigrama, ciclo, gráfico y concurso","cat":"product","file":"product"},
  "product_security":{"name":"Seguridad del producto","summary":"Neón verde: diana de capas, flujo con conectores que aparece paso a paso, código resaltado, gráfico, escalera y actividad de emparejar","cat":"product","file":"product"},
  "product_eco":{"name":"Sostenibilidad del producto","summary":"Verde eco: planta 3D con Transformar, ciclo de vida, cascada de huella, barras de materiales, líneas con objetivo y rellenar huecos","cat":"product","file":"product"},
  "sci_mars":{"name":"Misión a Marte","summary":"Estilo espacial óxido: rover 3D de la NASA con Transformar, astronauta flotando, órbita animada, ecuación y concurso","cat":"sci","file":"sci"},
  "sci_solar":{"name":"El sistema solar","summary":"Planetas a escala que aparecen en cadena, tres sondas 3D con vistas y movimientos distintos, tabla, diagrama radial y emparejar","cat":"sci","file":"sci"},
  "sci_newton":{"name":"Física: las leyes de Newton","summary":"Cuaderno de física: ecuaciones, coche 3D en movimiento, tiro parabólico que se dibuja, tabla con fórmulas y rellenar huecos","cat":"sci","file":"sci"},
  "sci_chem":{"name":"Química: tabla periódica","summary":"Laboratorio limpio: tabla periódica que se monta en cascada, moléculas con formas, brasero 3D, ecuaciones, dona y emparejar","cat":"sci","file":"sci"},
  "sci_stats":{"name":"Estadística y probabilidad","summary":"Estilo editorial: campana que se dibuja, fórmulas, histograma, dispersión, área, barras y burbujas, y pregunta con puntos","cat":"sci","file":"sci"},
  "sci_python":{"name":"Programación en Python","summary":"Estilo editor oscuro: terminal que se escribe sola, código con pasos de resaltado, salida animada, ordenar líneas y reto con cuenta atrás","cat":"sci","file":"sci"},
  "sci_ai":{"name":"Inteligencia artificial","summary":"Neón violeta: robot 3D que saluda y viaja con Transformar, cronología, organigrama, red neuronal que se enciende, gráfico y nube de palabras","cat":"sci","file":"sci"},
  "sci_thesis":{"name":"Defensa de TFG","summary":"Académico sobrio: portada institucional, índice, metodología con ecuación, tabla con totales, resultados en gráficos, bibliografía y Q&A","cat":"sci","file":"sci"},
  "sci_climate":{"name":"Cambio climático en datos","summary":"Bandas de calentamiento, gráficos de línea, área y rectángulos, efecto invernadero que se dibuja, satélite 3D, ciclo y votación múltiple","cat":"sci","file":"sci"},
  "sci_brain":{"name":"Neurociencia: el cerebro","summary":"Estilo oscuro con brillos: neurona dibujada con impulso animado, figura 3D que camina, radial, organigrama, barras y etiquetar una imagen","cat":"sci","file":"sci"},
  "showcase_transitions":{"name":"Catálogo: transiciones","summary":"Las 22 transiciones de diapositiva, una a una: entrada, salida distinta, direcciones, velocidad y avance automático","cat":"showcase","file":"showcase"},
  "showcase_animations":{"name":"Catálogo: animaciones","summary":"Todas las animaciones de objeto: entrada, énfasis, salida, trayectorias, dibujar, encadenadas, sonidos y varias en un objeto","cat":"showcase","file":"showcase"},
  "showcase_3d":{"name":"Catálogo: el 3D a fondo","summary":"Modelos 3D con todas sus opciones: vistas, movimientos al entrar, giro, bordes, margen, clips, andar y llegada con Transformar","cat":"showcase","file":"showcase"},
  "showcase_morph":{"name":"Catálogo: Transformar","summary":"Transformar (Morph) paso a paso: texto que cambia de tamaño y sitio, formas, barras que crecen, imagen, 3D y letras que se reordenan","cat":"showcase","file":"showcase"},
  "showcase_text":{"name":"Catálogo: Text Art y tipografía","summary":"Los 10 estilos de Text Art, texto curvo, columnas, cinco niveles de viñetas, los 8 pares de letra, alineación y espaciado","cat":"showcase","file":"showcase"},
  "showcase_shapes":{"name":"Catálogo: formas","summary":"Todas las formas por categorías con su nombre, líneas y guiones, degradados, opacidad, trazo a mano, sombras, texto dentro y giro","cat":"showcase","file":"showcase"},
  "showcase_charts":{"name":"Catálogo: gráficos","summary":"Los 15 tipos de gráfico, dos por diapositiva, con series, combinado, cuadrícula, etiquetas y títulos de ejes, y la tabla de opciones","cat":"showcase","file":"showcase"},
  "showcase_diagrams":{"name":"Catálogo: diagramas","summary":"Los 15 diseños de diagrama escritos como esquema, los 4 esquemas de color y la aparición uno a uno al presentar","cat":"showcase","file":"showcase"},
  "showcase_polls":{"name":"Catálogo: votaciones y actividades","summary":"Los 11 tipos de votación y actividad desde el móvil, cuenta atrás en sus tres estilos, clasificación y modo aula","cat":"showcase","file":"showcase"},
  "showcase_objects":{"name":"Catálogo: multimedia y objetos","summary":"Código con pasos, ecuaciones, iconos, cinco dispositivos, tablas con estilos y fórmulas, zoom de diapositiva y conectores","cat":"showcase","file":"showcase"}};
export const BROKEN = [];
export const LOADERS = {
  "biz": () => import('./biz.js'),
  "creative": () => import('./creative.js'),
  "data": () => import('./data.js'),
  "edu": () => import('./edu.js'),
  "life": () => import('./life.js'),
  "product": () => import('./product.js'),
  "sci": () => import('./sci.js'),
  "showcase": () => import('./showcase.js'),
};
