// Curated 3D models, free to use (their licences read from each model's
// metadata: CC0 or CC BY, plus trademark notes), several of them animated.
// Khronos glTF Sample Assets, three.js examples, KayKit (Kay Lousberg) and
// Kenney characters, served by jsDelivr at a fixed commit of each repository (cached for good, and nothing changes
// under us: a branch could). Characters say which of their clips
// is resting, walking and arriving (rest, walk, arrive): moved along a path,
// they walk. Thumbnails without a published image are made by us (assets/).
// Models under restrictive licences (non-commercial, EULAs) are left out.
export const LIBRARY_3D = [
  {"id": "kk-Knight", "label": "Caballero (anda, corre, saluda, se sienta…)", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0@672074b73ba276876a19e8816ecdc5241817ab47/addons/kaykit_character_pack_adventures/Characters/gltf/Knight.glb", "thumb": "assets/library3d/kk-Knight.webp", "licenses": ["CC0-1.0"], "credit": "KayKit — Kay Lousberg, kaylousberg.com (CC0-1.0)", "page": "https://github.com/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0", "rest": "Idle", "walk": "Walking_A", "arrive": "Cheer"},
  {"id": "kk-Barbarian", "label": "Bárbaro", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0@672074b73ba276876a19e8816ecdc5241817ab47/addons/kaykit_character_pack_adventures/Characters/gltf/Barbarian.glb", "thumb": "assets/library3d/kk-Barbarian.webp", "licenses": ["CC0-1.0"], "credit": "KayKit — Kay Lousberg, kaylousberg.com (CC0-1.0)", "page": "https://github.com/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0", "rest": "Idle", "walk": "Walking_A", "arrive": "Cheer"},
  {"id": "kk-Mage", "label": "Mago", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0@672074b73ba276876a19e8816ecdc5241817ab47/addons/kaykit_character_pack_adventures/Characters/gltf/Mage.glb", "thumb": "assets/library3d/kk-Mage.webp", "licenses": ["CC0-1.0"], "credit": "KayKit — Kay Lousberg, kaylousberg.com (CC0-1.0)", "page": "https://github.com/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0", "rest": "Idle", "walk": "Walking_A", "arrive": "Cheer"},
  {"id": "kk-Rogue", "label": "Pícaro", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0@672074b73ba276876a19e8816ecdc5241817ab47/addons/kaykit_character_pack_adventures/Characters/gltf/Rogue.glb", "thumb": "assets/library3d/kk-Rogue.webp", "licenses": ["CC0-1.0"], "credit": "KayKit — Kay Lousberg, kaylousberg.com (CC0-1.0)", "page": "https://github.com/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0", "rest": "Idle", "walk": "Walking_A", "arrive": "Cheer"},
  {"id": "kk-Rogue_Hooded", "label": "Pícaro con capucha", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0@672074b73ba276876a19e8816ecdc5241817ab47/addons/kaykit_character_pack_adventures/Characters/gltf/Rogue_Hooded.glb", "thumb": "assets/library3d/kk-Rogue_Hooded.webp", "licenses": ["CC0-1.0"], "credit": "KayKit — Kay Lousberg, kaylousberg.com (CC0-1.0)", "page": "https://github.com/KayKit-Game-Assets/KayKit-Character-Pack-Adventures-1.0", "rest": "Idle", "walk": "Walking_A", "arrive": "Cheer"},
  {"id": "kk-Skeleton_Warrior", "label": "Esqueleto guerrero", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KayKit-Game-Assets/KayKit-Character-Pack-Skeletons-1.0@15b62b9bad122f72926c10fb14d622c73819fa54/addons/kaykit_character_pack_skeletons/Characters/gltf/Skeleton_Warrior.glb", "thumb": "assets/library3d/kk-Skeleton_Warrior.webp", "licenses": ["CC0-1.0"], "credit": "KayKit — Kay Lousberg, kaylousberg.com (CC0-1.0)", "page": "https://github.com/KayKit-Game-Assets/KayKit-Character-Pack-Skeletons-1.0", "rest": "Idle", "walk": "Walking_A", "arrive": "Cheer"},
  {"id": "kk-Skeleton_Mage", "label": "Esqueleto mago", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KayKit-Game-Assets/KayKit-Character-Pack-Skeletons-1.0@15b62b9bad122f72926c10fb14d622c73819fa54/addons/kaykit_character_pack_skeletons/Characters/gltf/Skeleton_Mage.glb", "thumb": "assets/library3d/kk-Skeleton_Mage.webp", "licenses": ["CC0-1.0"], "credit": "KayKit — Kay Lousberg, kaylousberg.com (CC0-1.0)", "page": "https://github.com/KayKit-Game-Assets/KayKit-Character-Pack-Skeletons-1.0", "rest": "Idle", "walk": "Walking_A", "arrive": "Cheer"},
  {"id": "kk-Skeleton_Rogue", "label": "Esqueleto pícaro", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KayKit-Game-Assets/KayKit-Character-Pack-Skeletons-1.0@15b62b9bad122f72926c10fb14d622c73819fa54/addons/kaykit_character_pack_skeletons/Characters/gltf/Skeleton_Rogue.glb", "thumb": "assets/library3d/kk-Skeleton_Rogue.webp", "licenses": ["CC0-1.0"], "credit": "KayKit — Kay Lousberg, kaylousberg.com (CC0-1.0)", "page": "https://github.com/KayKit-Game-Assets/KayKit-Character-Pack-Skeletons-1.0", "rest": "Idle", "walk": "Walking_A", "arrive": "Cheer"},
  {"id": "kk-Skeleton_Minion", "label": "Esqueleto esbirro", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KayKit-Game-Assets/KayKit-Character-Pack-Skeletons-1.0@15b62b9bad122f72926c10fb14d622c73819fa54/addons/kaykit_character_pack_skeletons/Characters/gltf/Skeleton_Minion.glb", "thumb": "assets/library3d/kk-Skeleton_Minion.webp", "licenses": ["CC0-1.0"], "credit": "KayKit — Kay Lousberg, kaylousberg.com (CC0-1.0)", "page": "https://github.com/KayKit-Game-Assets/KayKit-Character-Pack-Skeletons-1.0", "rest": "Idle", "walk": "Walking_A", "arrive": "Cheer"},
  {"id": "kn-soldier", "label": "Soldado (también en silla de ruedas)", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KenneyNL/Starter-Kit-Basic-Scene@a6927e66ff8dd8e173660ce4825abe773c65f683/sample/Mini%20Arena/Models/GLB%20format/character-soldier.glb", "thumb": "assets/library3d/kn-soldier.webp", "licenses": ["CC0-1.0"], "credit": "Kenney, kenney.nl (CC0-1.0)", "page": "https://github.com/KenneyNL/Starter-Kit-Basic-Scene", "rest": "idle", "walk": "walk", "arrive": "emote-yes"},
  {"id": "kn-character", "label": "Personaje de plataformas", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KenneyNL/Starter-Kit-3D-Platformer@3fa8a04b1c01ab23db43123d4ce814a34c3fc7f0/models/character.glb", "thumb": "assets/library3d/kn-character.webp", "licenses": ["CC0-1.0"], "credit": "Kenney, kenney.nl (CC0-1.0)", "page": "https://github.com/KenneyNL/Starter-Kit-3D-Platformer", "rest": "idle", "walk": "walk", "arrive": "jump"},
  {"id": "three-RobotExpressive", "label": "Robot expresivo (baila, saluda, corre…)", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/mrdoob/three.js@29339892dcfc58dbb321a56bd9fffd204c50af70/examples/models/gltf/RobotExpressive/RobotExpressive.glb", "thumb": "https://cdn.jsdelivr.net/gh/mrdoob/three.js@29339892dcfc58dbb321a56bd9fffd204c50af70/examples/screenshots/webgl_animation_skinning_morph.jpg", "licenses": ["CC0-1.0"], "credit": "Model: Tomás Laulhé (CC0-1.0); morph targets: Don McCurdy", "page": "https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/RobotExpressive", "rest": "Idle", "walk": "Walking", "arrive": "Wave"},
  {"id": "kh-Fox", "label": "Zorro", "animated": true, "cat": "animales", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/Fox/glTF-Binary/Fox.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/Fox/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "CC0-1.0"], "credit": "Model: PixelMannen (CC0-1.0); Rigging & Animation: tomkranis (CC-BY-4.0); Conversion to glTF: @AsoboStudio and @scurest (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/Fox", "rest": "Survey", "walk": "Walk"},
  {"id": "kh-CesiumMan", "label": "Hombre caminando", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/CesiumMan/glTF-Binary/CesiumMan.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/CesiumMan/screenshot/screenshot.gif", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-Cesium"], "credit": "Everything: Cesium (CC-BY-4.0); Cesium logo: Non-copyrightable logo (LicenseRef-LegalMark-Cesium)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/CesiumMan"},
  {"id": "kh-CesiumMilkTruck", "label": "Camión de leche", "animated": true, "cat": "vehículos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/CesiumMilkTruck/screenshot/screenshot.gif", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-Cesium"], "credit": "Everything: Cesium (CC-BY-4.0); Cesium logo: Non-copyrightable logo (LicenseRef-LegalMark-Cesium)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/CesiumMilkTruck"},
  {"id": "kh-RiggedFigure", "label": "Figura articulada", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/RiggedFigure/glTF-Binary/RiggedFigure.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/RiggedFigure/screenshot/screenshot.gif", "licenses": ["CC-BY-4.0"], "credit": "Everything: Cesium (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/RiggedFigure"},
  {"id": "kh-AnimatedMorphCube", "label": "Cubo que se transforma", "animated": true, "cat": "formas", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/AnimatedMorphCube/glTF-Binary/AnimatedMorphCube.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/AnimatedMorphCube/screenshot/screenshot.gif", "licenses": ["CC0-1.0"], "credit": "Everything: Microsoft (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnimatedMorphCube"},
  {"id": "kh-BoxAnimated", "label": "Cajas animadas", "animated": true, "cat": "formas", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/BoxAnimated/glTF-Binary/BoxAnimated.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/BoxAnimated/screenshot/screenshot.gif", "licenses": ["CC-BY-4.0"], "credit": "Everything: Cesium (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/BoxAnimated"},
  {"id": "kh-SheenChair", "label": "Silla", "animated": false, "cat": "muebles", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/SheenChair/glTF-Binary/SheenChair.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/SheenChair/screenshot/screenshot.jpg", "licenses": ["CC0-1.0"], "credit": "Everything: Eric Chadwick (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SheenChair"},
  {"id": "kh-ToyCar", "label": "Coche de juguete", "animated": false, "cat": "vehículos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/ToyCar/glTF-Binary/ToyCar.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/ToyCar/screenshot/screenshot.jpg", "licenses": ["CC0-1.0"], "credit": "Initial car model: Guido Odendahl (CC0-1.0); Extensions and scene composition: Eric Chadwick (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/ToyCar"},
  {"id": "kh-SunglassesKhronos", "label": "Gafas de sol", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/SunglassesKhronos/glTF-Binary/SunglassesKhronos.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/SunglassesKhronos/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-Khronos"], "credit": "Model and textures and all images in the README.md: Eric Chadwick (CC-BY-4.0); Khronos logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos); 3D Commerce logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SunglassesKhronos"},
  {"id": "kh-ChairDamaskPurplegold", "label": "Butaca", "animated": false, "cat": "muebles", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/ChairDamaskPurplegold/glTF-Binary/ChairDamaskPurplegold.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/ChairDamaskPurplegold/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0"], "credit": "Models and Textures: Eric Chadwick (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/ChairDamaskPurplegold"},
  {"id": "kh-GlamVelvetSofa", "label": "Sofá de terciopelo", "animated": false, "cat": "muebles", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/GlamVelvetSofa/glTF-Binary/GlamVelvetSofa.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/GlamVelvetSofa/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0"], "credit": "Everything: Eric Chadwick (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/GlamVelvetSofa"},
  {"id": "kh-IridescenceLamp", "label": "Lámpara iridiscente", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/IridescenceLamp/glTF-Binary/IridescenceLamp.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/IridescenceLamp/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0"], "credit": "Everything: Eric Chadwick (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/IridescenceLamp"},
  {"id": "kh-ChronographWatch", "label": "Reloj", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/ChronographWatch/glTF-Binary/ChronographWatch.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/ChronographWatch/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-DGG", "LicenseRef-LegalMark-Khronos"], "credit": "Model and textures: Eric Chadwick (CC-BY-4.0); Khronos logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos); 3D Commerce logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos); DGG logo: Copyrightable logo (LicenseRef-LegalMark-DGG)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/ChronographWatch"},
  {"id": "kh-PotOfCoals", "label": "Brasero", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/PotOfCoals/glTF-Binary/PotOfCoals.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/PotOfCoals/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-Khronos"], "credit": "Model and textures: Eric Chadwick (CC-BY-4.0); Khronos logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos); glTF logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/PotOfCoals"},
  {"id": "kh-SheenWoodLeatherSofa", "label": "Sofá de cuero", "animated": false, "cat": "muebles", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/SheenWoodLeatherSofa/glTF-Binary/SheenWoodLeatherSofa.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/SheenWoodLeatherSofa/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "CC0-1.0"], "credit": "Improvements: Eric Chadwick (CC-BY-4.0); Original asset: Fran Calvente (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SheenWoodLeatherSofa"},
  {"id": "kh-DiffuseTransmissionPlant", "label": "Planta", "animated": false, "cat": "naturaleza", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/DiffuseTransmissionPlant/glTF-Binary/DiffuseTransmissionPlant.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/DiffuseTransmissionPlant/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "CC0-1.0"], "credit": "Materials and animation: Eric Chadwick (CC-BY-4.0); Original asset: Rico Cilliers (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/DiffuseTransmissionPlant"},
  {"id": "kh-AnisotropyBarnLamp", "label": "Lámpara de granero", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/AnisotropyBarnLamp/glTF-Binary/AnisotropyBarnLamp.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/AnisotropyBarnLamp/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0"], "credit": "Everything: Eric Chadwick (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyBarnLamp"},
  {"id": "kh-CarConcept", "label": "Coche conceptual", "animated": false, "cat": "vehículos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/CarConcept/glTF-Binary/CarConcept.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/CarConcept/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-Khronos"], "credit": "Model and textures: Eric Chadwick (CC-BY-4.0); Khronos logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos); 3D Commerce logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/CarConcept"},
  {"id": "kh-Avocado", "label": "Aguacate", "animated": false, "cat": "naturaleza", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/Avocado/glTF-Binary/Avocado.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/Avocado/screenshot/screenshot.jpg", "licenses": ["CC0-1.0"], "credit": "Everything: Microsoft (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/Avocado"},
  {"id": "kh-WaterBottle", "label": "Botella", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/WaterBottle/glTF-Binary/WaterBottle.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/WaterBottle/screenshot/screenshot.jpg", "licenses": ["CC0-1.0"], "credit": "Everything: Microsoft (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/WaterBottle"},
  {"id": "kh-Lantern", "label": "Farol", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/Lantern/glTF-Binary/Lantern.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@edc7c9e67c639d230715049ee31f9a96a6babbbe/Models/Lantern/screenshot/screenshot.jpg", "licenses": ["CC0-1.0"], "credit": "Initial version: sbtron (CC0-1.0); Draco compression: Frank Galligan (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/Lantern"},
];
