// Curated 3D models, free to use (their licences read from each model's
// metadata: CC0 or CC BY, plus trademark notes), several of them animated.
// Khronos glTF Sample Assets and three.js examples, served by jsDelivr.
// Models under restrictive licences (non-commercial, EULAs) are left out.
export const LIBRARY_3D = [
  {"id": "three-RobotExpressive", "label": "Robot expresivo (baila, saluda, corre…)", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/mrdoob/three.js@dev/examples/models/gltf/RobotExpressive/RobotExpressive.glb", "thumb": "https://cdn.jsdelivr.net/gh/mrdoob/three.js@dev/examples/screenshots/webgl_animation_skinning_morph.jpg", "licenses": ["CC0-1.0"], "credit": "Model: Tomás Laulhé (CC0-1.0); morph targets: Don McCurdy", "page": "https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/RobotExpressive"},
  {"id": "kh-Fox", "label": "Zorro", "animated": true, "cat": "animales", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/Fox/glTF-Binary/Fox.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/Fox/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "CC0-1.0"], "credit": "Model: PixelMannen (CC0-1.0); Rigging & Animation: tomkranis (CC-BY-4.0); Conversion to glTF: @AsoboStudio and @scurest (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/Fox"},
  {"id": "kh-CesiumMan", "label": "Hombre caminando", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/CesiumMan/glTF-Binary/CesiumMan.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/CesiumMan/screenshot/screenshot.gif", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-Cesium"], "credit": "Everything: Cesium (CC-BY-4.0); Cesium logo: Non-copyrightable logo (LicenseRef-LegalMark-Cesium)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/CesiumMan"},
  {"id": "kh-CesiumMilkTruck", "label": "Camión de leche", "animated": true, "cat": "vehículos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/CesiumMilkTruck/glTF-Binary/CesiumMilkTruck.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/CesiumMilkTruck/screenshot/screenshot.gif", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-Cesium"], "credit": "Everything: Cesium (CC-BY-4.0); Cesium logo: Non-copyrightable logo (LicenseRef-LegalMark-Cesium)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/CesiumMilkTruck"},
  {"id": "kh-RiggedFigure", "label": "Figura articulada", "animated": true, "cat": "personajes", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/RiggedFigure/glTF-Binary/RiggedFigure.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/RiggedFigure/screenshot/screenshot.gif", "licenses": ["CC-BY-4.0"], "credit": "Everything: Cesium (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/RiggedFigure"},
  {"id": "kh-AnimatedMorphCube", "label": "Cubo que se transforma", "animated": true, "cat": "formas", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/AnimatedMorphCube/glTF-Binary/AnimatedMorphCube.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/AnimatedMorphCube/screenshot/screenshot.gif", "licenses": ["CC0-1.0"], "credit": "Everything: Microsoft (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnimatedMorphCube"},
  {"id": "kh-BoxAnimated", "label": "Cajas animadas", "animated": true, "cat": "formas", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/BoxAnimated/glTF-Binary/BoxAnimated.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/BoxAnimated/screenshot/screenshot.gif", "licenses": ["CC-BY-4.0"], "credit": "Everything: Cesium (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/BoxAnimated"},
  {"id": "kh-SheenChair", "label": "Silla", "animated": false, "cat": "muebles", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/SheenChair/glTF-Binary/SheenChair.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/SheenChair/screenshot/screenshot.jpg", "licenses": ["CC0-1.0"], "credit": "Everything: Eric Chadwick (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SheenChair"},
  {"id": "kh-ToyCar", "label": "Coche de juguete", "animated": false, "cat": "vehículos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/ToyCar/glTF-Binary/ToyCar.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/ToyCar/screenshot/screenshot.jpg", "licenses": ["CC0-1.0"], "credit": "Initial car model: Guido Odendahl (CC0-1.0); Extensions and scene composition: Eric Chadwick (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/ToyCar"},
  {"id": "kh-SunglassesKhronos", "label": "Gafas de sol", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/SunglassesKhronos/glTF-Binary/SunglassesKhronos.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/SunglassesKhronos/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-Khronos"], "credit": "Model and textures and all images in the README.md: Eric Chadwick (CC-BY-4.0); Khronos logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos); 3D Commerce logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SunglassesKhronos"},
  {"id": "kh-ChairDamaskPurplegold", "label": "Butaca", "animated": false, "cat": "muebles", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/ChairDamaskPurplegold/glTF-Binary/ChairDamaskPurplegold.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/ChairDamaskPurplegold/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0"], "credit": "Models and Textures: Eric Chadwick (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/ChairDamaskPurplegold"},
  {"id": "kh-GlamVelvetSofa", "label": "Sofá de terciopelo", "animated": false, "cat": "muebles", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/GlamVelvetSofa/glTF-Binary/GlamVelvetSofa.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/GlamVelvetSofa/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0"], "credit": "Everything: Eric Chadwick (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/GlamVelvetSofa"},
  {"id": "kh-IridescenceLamp", "label": "Lámpara iridiscente", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/IridescenceLamp/glTF-Binary/IridescenceLamp.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/IridescenceLamp/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0"], "credit": "Everything: Eric Chadwick (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/IridescenceLamp"},
  {"id": "kh-ChronographWatch", "label": "Reloj", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/ChronographWatch/glTF-Binary/ChronographWatch.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/ChronographWatch/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-DGG", "LicenseRef-LegalMark-Khronos"], "credit": "Model and textures: Eric Chadwick (CC-BY-4.0); Khronos logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos); 3D Commerce logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos); DGG logo: Copyrightable logo (LicenseRef-LegalMark-DGG)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/ChronographWatch"},
  {"id": "kh-PotOfCoals", "label": "Brasero", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/PotOfCoals/glTF-Binary/PotOfCoals.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/PotOfCoals/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-Khronos"], "credit": "Model and textures: Eric Chadwick (CC-BY-4.0); Khronos logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos); glTF logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/PotOfCoals"},
  {"id": "kh-SheenWoodLeatherSofa", "label": "Sofá de cuero", "animated": false, "cat": "muebles", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/SheenWoodLeatherSofa/glTF-Binary/SheenWoodLeatherSofa.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/SheenWoodLeatherSofa/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "CC0-1.0"], "credit": "Improvements: Eric Chadwick (CC-BY-4.0); Original asset: Fran Calvente (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SheenWoodLeatherSofa"},
  {"id": "kh-DiffuseTransmissionPlant", "label": "Planta", "animated": false, "cat": "naturaleza", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/DiffuseTransmissionPlant/glTF-Binary/DiffuseTransmissionPlant.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/DiffuseTransmissionPlant/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "CC0-1.0"], "credit": "Materials and animation: Eric Chadwick (CC-BY-4.0); Original asset: Rico Cilliers (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/DiffuseTransmissionPlant"},
  {"id": "kh-AnisotropyBarnLamp", "label": "Lámpara de granero", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/AnisotropyBarnLamp/glTF-Binary/AnisotropyBarnLamp.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/AnisotropyBarnLamp/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0"], "credit": "Everything: Eric Chadwick (CC-BY-4.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyBarnLamp"},
  {"id": "kh-CarConcept", "label": "Coche conceptual", "animated": false, "cat": "vehículos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/CarConcept/glTF-Binary/CarConcept.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/CarConcept/screenshot/screenshot.jpg", "licenses": ["CC-BY-4.0", "LicenseRef-LegalMark-Khronos"], "credit": "Model and textures: Eric Chadwick (CC-BY-4.0); Khronos logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos); 3D Commerce logo: Non-copyrightable logo (LicenseRef-LegalMark-Khronos)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/CarConcept"},
  {"id": "kh-Avocado", "label": "Aguacate", "animated": false, "cat": "naturaleza", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/Avocado/glTF-Binary/Avocado.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/Avocado/screenshot/screenshot.jpg", "licenses": ["CC0-1.0"], "credit": "Everything: Microsoft (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/Avocado"},
  {"id": "kh-WaterBottle", "label": "Botella", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/WaterBottle/glTF-Binary/WaterBottle.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/WaterBottle/screenshot/screenshot.jpg", "licenses": ["CC0-1.0"], "credit": "Everything: Microsoft (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/WaterBottle"},
  {"id": "kh-Lantern", "label": "Farol", "animated": false, "cat": "objetos", "src": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/Lantern/glTF-Binary/Lantern.glb", "thumb": "https://cdn.jsdelivr.net/gh/KhronosGroup/glTF-Sample-Assets@main/Models/Lantern/screenshot/screenshot.jpg", "licenses": ["CC0-1.0"], "credit": "Initial version: sbtron (CC0-1.0); Draco compression: Frank Galligan (CC0-1.0)", "page": "https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/Lantern"},
];
