// Made from the examples' texts: their translations, { key: { lang: { Spanish: translation } } } (multilang.js).
// Machine-assisted translation: corrections welcome.
export default {
"telescopes": {
"en": {
"Telescopios espaciales: de Hubble a Webb": "Space telescopes: from Hubble to Webb",
"El telescopio James Webb en 3D (NASA): da una vuelta al entrar y se puede girar con el ratón.": "The James Webb telescope in 3D (NASA): it turns around as it appears and can be rotated with the mouse.",
"CIENCIAS · EL UNIVERSO": "SCIENCE · THE UNIVERSE",
"Ojos en el espacio": "Eyes in space",
"De Hubble a Webb: cómo vemos el universo": "From Hubble to Webb: how we see the universe",
"El telescopio espacial James Webb en 3D": "The James Webb Space Telescope in 3D",
"Cada tarjeta aparece con un clic. Pregunta antes: ¿por qué las estrellas parpadean?": "Each card appears with a click. Ask first: why do stars twinkle?",
"¿Por qué subirlo al espacio?": "Why put it in space?",
"<b>Sin aire que tiemble</b><br>La atmósfera desenfoca las estrellas: allí arriba la imagen es nítida.": "<b>No shaking air</b><br>The atmosphere blurs the stars: up there the image is sharp.",
"<b>Luz que no llega al suelo</b><br>El aire bloquea casi todo el infrarrojo y el ultravioleta.": "<b>Light that never reaches the ground</b><br>The air blocks almost all infrared and ultraviolet.",
"<b>Día y noche, todo el año</b><br>Sin nubes ni amaneceres: puede observar sin parar.": "<b>Day and night, all year round</b><br>No clouds, no sunrises: it can observe non-stop.",
"El Hubble flota en el espacio. Las cifras entran una tras otra con un solo clic.": "Hubble floats in space. The figures come in one after another with a single click.",
"Hubble: 35 años mirando": "Hubble: 35 years of looking",
"El telescopio espacial Hubble en 3D": "The Hubble Space Telescope in 3D",
"<span style=\"color:#f5c451;font-weight:800\">1990</span><br>puesto en órbita": "<span style=\"color:#f5c451;font-weight:800\">1990</span><br>put into orbit",
"<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Tierra": "<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>above the Earth",
"<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espejo": "<span style=\"color:#f5c451;font-weight:800\">2.4 m</span><br>mirror",
"Transformar: el Webb de la portada llega aquí más grande. Si preguntan cómo cabe en un cohete, baja (↓): está debajo.": "Transform: the Webb from the cover arrives here bigger. If they ask how it fits in a rocket, go down (↓): it’s below.",
"Webb: un espejo de oro": "Webb: a golden mirror",
"<ul><li>Lanzado en 2021</li><li>Un espejo de 6,5 m hecho de 18 hexágonos</li><li>Ve en infrarrojo: atraviesa el polvo</li></ul>": "<ul><li>Launched in 2021</li><li>A 6.5 m mirror made of 18 hexagons</li><li>Sees in infrared: through the dust</li></ul>",
"Diapositiva debajo de la anterior: solo si hace falta. Cuatro clics, un paso cada uno. Vuelve arriba (↑) para seguir.": "A slide below the previous one: only if needed. Four clicks, one step each. Go back up (↑) to continue.",
"Así se despliega": "How it unfolds",
"<b>1</b> · Viaja plegado dentro del cohete": "<b>1</b> · It travels folded inside the rocket",
"<b>2</b> · Abre el parasol: del tamaño de una pista de tenis": "<b>2</b> · It opens the sunshield: the size of a tennis court",
"<b>3</b> · Despliega el espejo secundario y las alas": "<b>3</b> · It unfolds the secondary mirror and the wings",
"<b>4</b> · Alinea sus 18 espejos con precisión de nanómetros": "<b>4</b> · It aligns its 18 mirrors to within nanometres",
"Clic: el cohete sigue un recorrido curvo y gira hacia donde va.": "Click: the rocket follows a curved path and turns towards where it’s going.",
"Un viaje de 1,5 millones de km": "A 1.5-million-km journey",
"Tierra": "Earth",
"Punto L2": "L2 point",
"Allí la Tierra, la Luna y el Sol quedan siempre detrás de su parasol: el telescopio está a la sombra y muy frío.": "There the Earth, the Moon and the Sun always stay behind its sunshield: the telescope is in the shade and very cold.",
"Tres clics: cada distancia con lo que tarda su luz en llegarnos.": "Three clicks: each distance with how long its light takes to reach us.",
"La luz es una máquina del tiempo": "Light is a time machine",
"<b>El Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>": "<b>The Sun</b><br><span style=\"color:#f5c451\">8 minutes</span>",
"<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millones de años</span>": "<b>Andromeda</b><br><span style=\"color:#f5c451\">2.5 million years</span>",
"<b>Las galaxias de Webb</b><br><span style=\"color:#f5c451\">más de 13.000 millones de años</span>": "<b>Webb’s galaxies</b><br><span style=\"color:#f5c451\">over 13 billion years</span>",
"Lo que vemos es la luz que salió hace tanto tiempo: cuanto más lejos miramos, más atrás en el tiempo.": "What we see is light that left so long ago: the farther we look, the further back in time.",
"Votación en directo: escanean el QR con el móvil y el gráfico crece al momento.": "Live poll: they scan the QR with their phone and the chart grows instantly.",
"¿Qué te gustaría que observara Webb?": "What would you like Webb to look at?",
"Planetas con agua": "Planets with water",
"Agujeros negros": "Black holes",
"Las primeras galaxias": "The first galaxies",
"Nuestro sistema solar": "Our solar system",
"¿Preguntas?": "Questions?",
"Modelos 3D: NASA 3D Resources": "3D models: NASA 3D Resources"
},
"fr": {
"Telescopios espaciales: de Hubble a Webb": "Télescopes spatiaux : de Hubble à Webb",
"El telescopio James Webb en 3D (NASA): da una vuelta al entrar y se puede girar con el ratón.": "Le télescope James Webb en 3D (NASA) : il fait un tour en apparaissant et peut être tourné avec la souris.",
"CIENCIAS · EL UNIVERSO": "SCIENCES · L’UNIVERS",
"Ojos en el espacio": "Des yeux dans l’espace",
"De Hubble a Webb: cómo vemos el universo": "De Hubble à Webb : comment nous voyons l’univers",
"El telescopio espacial James Webb en 3D": "Le télescope spatial James Webb en 3D",
"Cada tarjeta aparece con un clic. Pregunta antes: ¿por qué las estrellas parpadean?": "Chaque carte apparaît d’un clic. Demandez d’abord : pourquoi les étoiles scintillent-elles ?",
"¿Por qué subirlo al espacio?": "Pourquoi l’envoyer dans l’espace ?",
"<b>Sin aire que tiemble</b><br>La atmósfera desenfoca las estrellas: allí arriba la imagen es nítida.": "<b>Pas d’air qui tremble</b><br>L’atmosphère brouille les étoiles : là-haut, l’image est nette.",
"<b>Luz que no llega al suelo</b><br>El aire bloquea casi todo el infrarrojo y el ultravioleta.": "<b>Une lumière qui n’atteint pas le sol</b><br>L’air bloque presque tout l’infrarouge et l’ultraviolet.",
"<b>Día y noche, todo el año</b><br>Sin nubes ni amaneceres: puede observar sin parar.": "<b>Jour et nuit, toute l’année</b><br>Ni nuages ni levers de soleil : il peut observer sans arrêt.",
"El Hubble flota en el espacio. Las cifras entran una tras otra con un solo clic.": "Hubble flotte dans l’espace. Les chiffres arrivent l’un après l’autre d’un seul clic.",
"Hubble: 35 años mirando": "Hubble : 35 ans à observer",
"El telescopio espacial Hubble en 3D": "Le télescope spatial Hubble en 3D",
"<span style=\"color:#f5c451;font-weight:800\">1990</span><br>puesto en órbita": "<span style=\"color:#f5c451;font-weight:800\">1990</span><br>mis en orbite",
"<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Tierra": "<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>au-dessus de la Terre",
"<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espejo": "<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de miroir",
"Transformar: el Webb de la portada llega aquí más grande. Si preguntan cómo cabe en un cohete, baja (↓): está debajo.": "Transformer : le Webb de la couverture arrive ici plus grand. S’ils demandent comment il tient dans une fusée, descendez (↓) : c’est en dessous.",
"Webb: un espejo de oro": "Webb : un miroir d’or",
"<ul><li>Lanzado en 2021</li><li>Un espejo de 6,5 m hecho de 18 hexágonos</li><li>Ve en infrarrojo: atraviesa el polvo</li></ul>": "<ul><li>Lancé en 2021</li><li>Un miroir de 6,5 m fait de 18 hexagones</li><li>Voit en infrarouge : à travers la poussière</li></ul>",
"Diapositiva debajo de la anterior: solo si hace falta. Cuatro clics, un paso cada uno. Vuelve arriba (↑) para seguir.": "Diapositive sous la précédente : seulement si besoin. Quatre clics, une étape chacun. Remontez (↑) pour continuer.",
"Así se despliega": "Comment il se déploie",
"<b>1</b> · Viaja plegado dentro del cohete": "<b>1</b> · Il voyage plié dans la fusée",
"<b>2</b> · Abre el parasol: del tamaño de una pista de tenis": "<b>2</b> · Il ouvre le pare-soleil : de la taille d’un court de tennis",
"<b>3</b> · Despliega el espejo secundario y las alas": "<b>3</b> · Il déploie le miroir secondaire et les ailes",
"<b>4</b> · Alinea sus 18 espejos con precisión de nanómetros": "<b>4</b> · Il aligne ses 18 miroirs au nanomètre près",
"Clic: el cohete sigue un recorrido curvo y gira hacia donde va.": "Clic : la fusée suit une trajectoire courbe et s’oriente vers où elle va.",
"Un viaje de 1,5 millones de km": "Un voyage de 1,5 million de km",
"Tierra": "Terre",
"Punto L2": "Point L2",
"Allí la Tierra, la Luna y el Sol quedan siempre detrás de su parasol: el telescopio está a la sombra y muy frío.": "Là-bas, la Terre, la Lune et le Soleil restent toujours derrière son pare-soleil : le télescope est à l’ombre et très froid.",
"Tres clics: cada distancia con lo que tarda su luz en llegarnos.": "Trois clics : chaque distance avec le temps que met sa lumière à nous parvenir.",
"La luz es una máquina del tiempo": "La lumière est une machine à remonter le temps",
"<b>El Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>": "<b>Le Soleil</b><br><span style=\"color:#f5c451\">8 minutes</span>",
"<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millones de años</span>": "<b>Andromède</b><br><span style=\"color:#f5c451\">2,5 millions d’années</span>",
"<b>Las galaxias de Webb</b><br><span style=\"color:#f5c451\">más de 13.000 millones de años</span>": "<b>Les galaxies de Webb</b><br><span style=\"color:#f5c451\">plus de 13 milliards d’années</span>",
"Lo que vemos es la luz que salió hace tanto tiempo: cuanto más lejos miramos, más atrás en el tiempo.": "Ce que nous voyons, c’est la lumière partie il y a si longtemps : plus nous regardons loin, plus nous remontons le temps.",
"Votación en directo: escanean el QR con el móvil y el gráfico crece al momento.": "Vote en direct : ils scannent le QR avec leur téléphone et le graphique grandit aussitôt.",
"¿Qué te gustaría que observara Webb?": "Qu’aimeriez-vous que Webb observe ?",
"Planetas con agua": "Des planètes avec de l’eau",
"Agujeros negros": "Les trous noirs",
"Las primeras galaxias": "Les premières galaxies",
"Nuestro sistema solar": "Notre système solaire",
"¿Preguntas?": "Des questions ?",
"Modelos 3D: NASA 3D Resources": "Modèles 3D : NASA 3D Resources"
},
"de": {
"Telescopios espaciales: de Hubble a Webb": "Weltraumteleskope: von Hubble bis Webb",
"El telescopio James Webb en 3D (NASA): da una vuelta al entrar y se puede girar con el ratón.": "Das James-Webb-Teleskop in 3D (NASA): Es dreht sich beim Erscheinen und lässt sich mit der Maus drehen.",
"CIENCIAS · EL UNIVERSO": "NATURWISSENSCHAFTEN · DAS UNIVERSUM",
"Ojos en el espacio": "Augen im All",
"De Hubble a Webb: cómo vemos el universo": "Von Hubble bis Webb: wie wir das Universum sehen",
"El telescopio espacial James Webb en 3D": "Das James-Webb-Weltraumteleskop in 3D",
"Cada tarjeta aparece con un clic. Pregunta antes: ¿por qué las estrellas parpadean?": "Jede Karte erscheint mit einem Klick. Frag vorher: Warum funkeln die Sterne?",
"¿Por qué subirlo al espacio?": "Warum ins All damit?",
"<b>Sin aire que tiemble</b><br>La atmósfera desenfoca las estrellas: allí arriba la imagen es nítida.": "<b>Keine flimmernde Luft</b><br>Die Atmosphäre macht die Sterne unscharf: dort oben ist das Bild scharf.",
"<b>Luz que no llega al suelo</b><br>El aire bloquea casi todo el infrarrojo y el ultravioleta.": "<b>Licht, das den Boden nicht erreicht</b><br>Die Luft blockiert fast das ganze Infrarot und Ultraviolett.",
"<b>Día y noche, todo el año</b><br>Sin nubes ni amaneceres: puede observar sin parar.": "<b>Tag und Nacht, das ganze Jahr</b><br>Keine Wolken, kein Sonnenaufgang: Es kann ohne Pause beobachten.",
"El Hubble flota en el espacio. Las cifras entran una tras otra con un solo clic.": "Hubble schwebt im All. Die Zahlen erscheinen mit einem Klick nacheinander.",
"Hubble: 35 años mirando": "Hubble: 35 Jahre Beobachtung",
"El telescopio espacial Hubble en 3D": "Das Hubble-Weltraumteleskop in 3D",
"<span style=\"color:#f5c451;font-weight:800\">1990</span><br>puesto en órbita": "<span style=\"color:#f5c451;font-weight:800\">1990</span><br>in die Umlaufbahn gebracht",
"<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Tierra": "<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>über der Erde",
"<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espejo": "<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>Spiegel",
"Transformar: el Webb de la portada llega aquí más grande. Si preguntan cómo cabe en un cohete, baja (↓): está debajo.": "Verwandeln: Das Webb vom Titel kommt hier größer an. Fragen sie, wie es in eine Rakete passt, geh nach unten (↓): Es steht darunter.",
"Webb: un espejo de oro": "Webb: ein goldener Spiegel",
"<ul><li>Lanzado en 2021</li><li>Un espejo de 6,5 m hecho de 18 hexágonos</li><li>Ve en infrarrojo: atraviesa el polvo</li></ul>": "<ul><li>Gestartet 2021</li><li>Ein 6,5-m-Spiegel aus 18 Sechsecken</li><li>Sieht im Infrarot: durch den Staub hindurch</li></ul>",
"Diapositiva debajo de la anterior: solo si hace falta. Cuatro clics, un paso cada uno. Vuelve arriba (↑) para seguir.": "Folie unter der vorherigen: nur bei Bedarf. Vier Klicks, ein Schritt pro Klick. Geh wieder nach oben (↑), um weiterzumachen.",
"Así se despliega": "So entfaltet es sich",
"<b>1</b> · Viaja plegado dentro del cohete": "<b>1</b> · Es reist gefaltet in der Rakete",
"<b>2</b> · Abre el parasol: del tamaño de una pista de tenis": "<b>2</b> · Es öffnet den Sonnenschild: so groß wie ein Tennisplatz",
"<b>3</b> · Despliega el espejo secundario y las alas": "<b>3</b> · Es entfaltet den Sekundärspiegel und die Flügel",
"<b>4</b> · Alinea sus 18 espejos con precisión de nanómetros": "<b>4</b> · Es richtet seine 18 Spiegel auf Nanometer genau aus",
"Clic: el cohete sigue un recorrido curvo y gira hacia donde va.": "Klick: Die Rakete folgt einer Kurve und dreht sich in Flugrichtung.",
"Un viaje de 1,5 millones de km": "Eine Reise von 1,5 Millionen km",
"Tierra": "Erde",
"Punto L2": "Punkt L2",
"Allí la Tierra, la Luna y el Sol quedan siempre detrás de su parasol: el telescopio está a la sombra y muy frío.": "Dort bleiben Erde, Mond und Sonne immer hinter seinem Sonnenschild: Das Teleskop liegt im Schatten und ist sehr kalt.",
"Tres clics: cada distancia con lo que tarda su luz en llegarnos.": "Drei Klicks: jede Entfernung mit der Zeit, die ihr Licht bis zu uns braucht.",
"La luz es una máquina del tiempo": "Licht ist eine Zeitmaschine",
"<b>El Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>": "<b>Die Sonne</b><br><span style=\"color:#f5c451\">8 Minuten</span>",
"<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millones de años</span>": "<b>Andromeda</b><br><span style=\"color:#f5c451\">2,5 Millionen Jahre</span>",
"<b>Las galaxias de Webb</b><br><span style=\"color:#f5c451\">más de 13.000 millones de años</span>": "<b>Webbs Galaxien</b><br><span style=\"color:#f5c451\">über 13 Milliarden Jahre</span>",
"Lo que vemos es la luz que salió hace tanto tiempo: cuanto más lejos miramos, más atrás en el tiempo.": "Was wir sehen, ist Licht, das vor so langer Zeit losging: Je weiter wir schauen, desto weiter zurück in der Zeit.",
"Votación en directo: escanean el QR con el móvil y el gráfico crece al momento.": "Live-Abstimmung: Sie scannen den QR-Code mit dem Handy und das Diagramm wächst sofort.",
"¿Qué te gustaría que observara Webb?": "Was soll Webb deiner Meinung nach beobachten?",
"Planetas con agua": "Planeten mit Wasser",
"Agujeros negros": "Schwarze Löcher",
"Las primeras galaxias": "Die ersten Galaxien",
"Nuestro sistema solar": "Unser Sonnensystem",
"¿Preguntas?": "Fragen?",
"Modelos 3D: NASA 3D Resources": "3D-Modelle: NASA 3D Resources"
},
"it": {
"Telescopios espaciales: de Hubble a Webb": "Telescopi spaziali: da Hubble a Webb",
"El telescopio James Webb en 3D (NASA): da una vuelta al entrar y se puede girar con el ratón.": "Il telescopio James Webb in 3D (NASA): fa un giro quando appare e si può ruotare con il mouse.",
"CIENCIAS · EL UNIVERSO": "SCIENZE · L’UNIVERSO",
"Ojos en el espacio": "Occhi nello spazio",
"De Hubble a Webb: cómo vemos el universo": "Da Hubble a Webb: come vediamo l’universo",
"El telescopio espacial James Webb en 3D": "Il telescopio spaziale James Webb in 3D",
"Cada tarjeta aparece con un clic. Pregunta antes: ¿por qué las estrellas parpadean?": "Ogni scheda appare con un clic. Chiedi prima: perché le stelle brillano a intermittenza?",
"¿Por qué subirlo al espacio?": "Perché mandarlo nello spazio?",
"<b>Sin aire que tiemble</b><br>La atmósfera desenfoca las estrellas: allí arriba la imagen es nítida.": "<b>Niente aria che trema</b><br>L’atmosfera sfoca le stelle: lassù l’immagine è nitida.",
"<b>Luz que no llega al suelo</b><br>El aire bloquea casi todo el infrarrojo y el ultravioleta.": "<b>Luce che non arriva a terra</b><br>L’aria blocca quasi tutto l’infrarosso e l’ultravioletto.",
"<b>Día y noche, todo el año</b><br>Sin nubes ni amaneceres: puede observar sin parar.": "<b>Giorno e notte, tutto l’anno</b><br>Niente nuvole né albe: può osservare senza sosta.",
"El Hubble flota en el espacio. Las cifras entran una tras otra con un solo clic.": "Hubble fluttua nello spazio. Le cifre entrano una dopo l’altra con un solo clic.",
"Hubble: 35 años mirando": "Hubble: 35 anni di osservazioni",
"El telescopio espacial Hubble en 3D": "Il telescopio spaziale Hubble in 3D",
"<span style=\"color:#f5c451;font-weight:800\">1990</span><br>puesto en órbita": "<span style=\"color:#f5c451;font-weight:800\">1990</span><br>messo in orbita",
"<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Tierra": "<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sopra la Terra",
"<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espejo": "<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>di specchio",
"Transformar: el Webb de la portada llega aquí más grande. Si preguntan cómo cabe en un cohete, baja (↓): está debajo.": "Trasforma: il Webb della copertina arriva qui più grande. Se chiedono come entra in un razzo, scendi (↓): è sotto.",
"Webb: un espejo de oro": "Webb: uno specchio d’oro",
"<ul><li>Lanzado en 2021</li><li>Un espejo de 6,5 m hecho de 18 hexágonos</li><li>Ve en infrarrojo: atraviesa el polvo</li></ul>": "<ul><li>Lanciato nel 2021</li><li>Uno specchio di 6,5 m fatto di 18 esagoni</li><li>Vede nell’infrarosso: attraversa la polvere</li></ul>",
"Diapositiva debajo de la anterior: solo si hace falta. Cuatro clics, un paso cada uno. Vuelve arriba (↑) para seguir.": "Diapositiva sotto la precedente: solo se serve. Quattro clic, un passo ciascuno. Torna su (↑) per continuare.",
"Así se despliega": "Così si dispiega",
"<b>1</b> · Viaja plegado dentro del cohete": "<b>1</b> · Viaggia piegato dentro il razzo",
"<b>2</b> · Abre el parasol: del tamaño de una pista de tenis": "<b>2</b> · Apre lo scudo solare: grande come un campo da tennis",
"<b>3</b> · Despliega el espejo secundario y las alas": "<b>3</b> · Dispiega lo specchio secondario e le ali",
"<b>4</b> · Alinea sus 18 espejos con precisión de nanómetros": "<b>4</b> · Allinea i suoi 18 specchi con precisione nanometrica",
"Clic: el cohete sigue un recorrido curvo y gira hacia donde va.": "Clic: il razzo segue un percorso curvo e si gira verso dove va.",
"Un viaje de 1,5 millones de km": "Un viaggio di 1,5 milioni di km",
"Tierra": "Terra",
"Punto L2": "Punto L2",
"Allí la Tierra, la Luna y el Sol quedan siempre detrás de su parasol: el telescopio está a la sombra y muy frío.": "Lì la Terra, la Luna e il Sole restano sempre dietro il suo scudo: il telescopio è all’ombra e molto freddo.",
"Tres clics: cada distancia con lo que tarda su luz en llegarnos.": "Tre clic: ogni distanza con il tempo che la sua luce impiega ad arrivarci.",
"La luz es una máquina del tiempo": "La luce è una macchina del tempo",
"<b>El Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>": "<b>Il Sole</b><br><span style=\"color:#f5c451\">8 minuti</span>",
"<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millones de años</span>": "<b>Andromeda</b><br><span style=\"color:#f5c451\">2,5 milioni di anni</span>",
"<b>Las galaxias de Webb</b><br><span style=\"color:#f5c451\">más de 13.000 millones de años</span>": "<b>Le galassie di Webb</b><br><span style=\"color:#f5c451\">più di 13 miliardi di anni</span>",
"Lo que vemos es la luz que salió hace tanto tiempo: cuanto más lejos miramos, más atrás en el tiempo.": "Quello che vediamo è la luce partita tanto tempo fa: più lontano guardiamo, più indietro nel tempo.",
"Votación en directo: escanean el QR con el móvil y el gráfico crece al momento.": "Sondaggio in diretta: inquadrano il QR con il telefono e il grafico cresce subito.",
"¿Qué te gustaría que observara Webb?": "Che cosa vorresti che osservasse Webb?",
"Planetas con agua": "Pianeti con acqua",
"Agujeros negros": "Buchi neri",
"Las primeras galaxias": "Le prime galassie",
"Nuestro sistema solar": "Il nostro sistema solare",
"¿Preguntas?": "Domande?",
"Modelos 3D: NASA 3D Resources": "Modelli 3D: NASA 3D Resources"
},
"pt": {
"Telescopios espaciales: de Hubble a Webb": "Telescópios espaciais: do Hubble ao Webb",
"El telescopio James Webb en 3D (NASA): da una vuelta al entrar y se puede girar con el ratón.": "O telescópio James Webb em 3D (NASA): dá uma volta ao entrar e pode ser rodado com o rato.",
"CIENCIAS · EL UNIVERSO": "CIÊNCIAS · O UNIVERSO",
"Ojos en el espacio": "Olhos no espaço",
"De Hubble a Webb: cómo vemos el universo": "Do Hubble ao Webb: como vemos o universo",
"El telescopio espacial James Webb en 3D": "O telescópio espacial James Webb em 3D",
"Cada tarjeta aparece con un clic. Pregunta antes: ¿por qué las estrellas parpadean?": "Cada cartão aparece com um clique. Pergunta antes: porque é que as estrelas cintilam?",
"¿Por qué subirlo al espacio?": "Porquê levá-lo para o espaço?",
"<b>Sin aire que tiemble</b><br>La atmósfera desenfoca las estrellas: allí arriba la imagen es nítida.": "<b>Sem ar a tremer</b><br>A atmosfera desfoca as estrelas: lá em cima a imagem é nítida.",
"<b>Luz que no llega al suelo</b><br>El aire bloquea casi todo el infrarrojo y el ultravioleta.": "<b>Luz que não chega ao solo</b><br>O ar bloqueia quase todo o infravermelho e o ultravioleta.",
"<b>Día y noche, todo el año</b><br>Sin nubes ni amaneceres: puede observar sin parar.": "<b>Dia e noite, todo o ano</b><br>Sem nuvens nem amanheceres: pode observar sem parar.",
"El Hubble flota en el espacio. Las cifras entran una tras otra con un solo clic.": "O Hubble flutua no espaço. Os números entram um após outro com um só clique.",
"Hubble: 35 años mirando": "Hubble: 35 anos a observar",
"El telescopio espacial Hubble en 3D": "O telescópio espacial Hubble em 3D",
"<span style=\"color:#f5c451;font-weight:800\">1990</span><br>puesto en órbita": "<span style=\"color:#f5c451;font-weight:800\">1990</span><br>colocado em órbita",
"<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Tierra": "<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>acima da Terra",
"<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espejo": "<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espelho",
"Transformar: el Webb de la portada llega aquí más grande. Si preguntan cómo cabe en un cohete, baja (↓): está debajo.": "Transformar: o Webb da capa chega aqui maior. Se perguntarem como cabe num foguetão, desce (↓): está por baixo.",
"Webb: un espejo de oro": "Webb: um espelho de ouro",
"<ul><li>Lanzado en 2021</li><li>Un espejo de 6,5 m hecho de 18 hexágonos</li><li>Ve en infrarrojo: atraviesa el polvo</li></ul>": "<ul><li>Lançado em 2021</li><li>Um espelho de 6,5 m feito de 18 hexágonos</li><li>Vê em infravermelho: atravessa a poeira</li></ul>",
"Diapositiva debajo de la anterior: solo si hace falta. Cuatro clics, un paso cada uno. Vuelve arriba (↑) para seguir.": "Diapositivo abaixo do anterior: só se for preciso. Quatro cliques, um passo cada. Volta acima (↑) para continuar.",
"Así se despliega": "Assim se abre",
"<b>1</b> · Viaja plegado dentro del cohete": "<b>1</b> · Viaja dobrado dentro do foguetão",
"<b>2</b> · Abre el parasol: del tamaño de una pista de tenis": "<b>2</b> · Abre o escudo solar: do tamanho de um campo de ténis",
"<b>3</b> · Despliega el espejo secundario y las alas": "<b>3</b> · Abre o espelho secundário e as asas",
"<b>4</b> · Alinea sus 18 espejos con precisión de nanómetros": "<b>4</b> · Alinha os seus 18 espelhos com precisão de nanómetros",
"Clic: el cohete sigue un recorrido curvo y gira hacia donde va.": "Clique: o foguetão segue um percurso curvo e vira-se para onde vai.",
"Un viaje de 1,5 millones de km": "Uma viagem de 1,5 milhões de km",
"Tierra": "Terra",
"Punto L2": "Ponto L2",
"Allí la Tierra, la Luna y el Sol quedan siempre detrás de su parasol: el telescopio está a la sombra y muy frío.": "Ali a Terra, a Lua e o Sol ficam sempre atrás do escudo: o telescópio está à sombra e muito frio.",
"Tres clics: cada distancia con lo que tarda su luz en llegarnos.": "Três cliques: cada distância com o tempo que a sua luz demora a chegar-nos.",
"La luz es una máquina del tiempo": "A luz é uma máquina do tempo",
"<b>El Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>": "<b>O Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>",
"<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millones de años</span>": "<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 milhões de anos</span>",
"<b>Las galaxias de Webb</b><br><span style=\"color:#f5c451\">más de 13.000 millones de años</span>": "<b>As galáxias do Webb</b><br><span style=\"color:#f5c451\">mais de 13 mil milhões de anos</span>",
"Lo que vemos es la luz que salió hace tanto tiempo: cuanto más lejos miramos, más atrás en el tiempo.": "O que vemos é a luz que partiu há tanto tempo: quanto mais longe olhamos, mais para trás no tempo.",
"Votación en directo: escanean el QR con el móvil y el gráfico crece al momento.": "Votação em direto: leem o QR com o telemóvel e o gráfico cresce na hora.",
"¿Qué te gustaría que observara Webb?": "O que gostarias que o Webb observasse?",
"Planetas con agua": "Planetas com água",
"Agujeros negros": "Buracos negros",
"Las primeras galaxias": "As primeiras galáxias",
"Nuestro sistema solar": "O nosso sistema solar",
"¿Preguntas?": "Perguntas?",
"Modelos 3D: NASA 3D Resources": "Modelos 3D: NASA 3D Resources"
},
"ca": {
"Telescopios espaciales: de Hubble a Webb": "Telescopis espacials: de Hubble a Webb",
"El telescopio James Webb en 3D (NASA): da una vuelta al entrar y se puede girar con el ratón.": "El telescopi James Webb en 3D (NASA): fa una volta en entrar i es pot girar amb el ratolí.",
"CIENCIAS · EL UNIVERSO": "CIÈNCIES · L’UNIVERS",
"Ojos en el espacio": "Ulls a l’espai",
"De Hubble a Webb: cómo vemos el universo": "De Hubble a Webb: com veiem l’univers",
"El telescopio espacial James Webb en 3D": "El telescopi espacial James Webb en 3D",
"Cada tarjeta aparece con un clic. Pregunta antes: ¿por qué las estrellas parpadean?": "Cada targeta apareix amb un clic. Pregunta abans: per què les estrelles parpellegen?",
"¿Por qué subirlo al espacio?": "Per què pujar-lo a l’espai?",
"<b>Sin aire que tiemble</b><br>La atmósfera desenfoca las estrellas: allí arriba la imagen es nítida.": "<b>Sense aire que tremoli</b><br>L’atmosfera desenfoca les estrelles: allà dalt la imatge és nítida.",
"<b>Luz que no llega al suelo</b><br>El aire bloquea casi todo el infrarrojo y el ultravioleta.": "<b>Llum que no arriba a terra</b><br>L’aire bloqueja gairebé tot l’infraroig i l’ultraviolat.",
"<b>Día y noche, todo el año</b><br>Sin nubes ni amaneceres: puede observar sin parar.": "<b>Dia i nit, tot l’any</b><br>Sense núvols ni albades: pot observar sense parar.",
"El Hubble flota en el espacio. Las cifras entran una tras otra con un solo clic.": "El Hubble sura a l’espai. Les xifres entren una darrere l’altra amb un sol clic.",
"Hubble: 35 años mirando": "Hubble: 35 anys mirant",
"El telescopio espacial Hubble en 3D": "El telescopi espacial Hubble en 3D",
"<span style=\"color:#f5c451;font-weight:800\">1990</span><br>puesto en órbita": "<span style=\"color:#f5c451;font-weight:800\">1990</span><br>posat en òrbita",
"<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Tierra": "<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Terra",
"<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espejo": "<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de mirall",
"Transformar: el Webb de la portada llega aquí más grande. Si preguntan cómo cabe en un cohete, baja (↓): está debajo.": "Transformar: el Webb de la portada arriba aquí més gran. Si pregunten com cap en un coet, baixa (↓): és a sota.",
"Webb: un espejo de oro": "Webb: un mirall d’or",
"<ul><li>Lanzado en 2021</li><li>Un espejo de 6,5 m hecho de 18 hexágonos</li><li>Ve en infrarrojo: atraviesa el polvo</li></ul>": "<ul><li>Llançat el 2021</li><li>Un mirall de 6,5 m fet de 18 hexàgons</li><li>Veu en infraroig: travessa la pols</li></ul>",
"Diapositiva debajo de la anterior: solo si hace falta. Cuatro clics, un paso cada uno. Vuelve arriba (↑) para seguir.": "Diapositiva sota l’anterior: només si cal. Quatre clics, un pas cadascun. Torna amunt (↑) per continuar.",
"Así se despliega": "Així es desplega",
"<b>1</b> · Viaja plegado dentro del cohete": "<b>1</b> · Viatja plegat dins del coet",
"<b>2</b> · Abre el parasol: del tamaño de una pista de tenis": "<b>2</b> · Obre el para-sol: de la mida d’una pista de tennis",
"<b>3</b> · Despliega el espejo secundario y las alas": "<b>3</b> · Desplega el mirall secundari i les ales",
"<b>4</b> · Alinea sus 18 espejos con precisión de nanómetros": "<b>4</b> · Alinea els seus 18 miralls amb precisió de nanòmetres",
"Clic: el cohete sigue un recorrido curvo y gira hacia donde va.": "Clic: el coet segueix un recorregut corb i gira cap on va.",
"Un viaje de 1,5 millones de km": "Un viatge d’1,5 milions de km",
"Tierra": "Terra",
"Punto L2": "Punt L2",
"Allí la Tierra, la Luna y el Sol quedan siempre detrás de su parasol: el telescopio está a la sombra y muy frío.": "Allà la Terra, la Lluna i el Sol queden sempre darrere del para-sol: el telescopi és a l’ombra i molt fred.",
"Tres clics: cada distancia con lo que tarda su luz en llegarnos.": "Tres clics: cada distància amb el que tarda la seva llum a arribar-nos.",
"La luz es una máquina del tiempo": "La llum és una màquina del temps",
"<b>El Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>": "<b>El Sol</b><br><span style=\"color:#f5c451\">8 minuts</span>",
"<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millones de años</span>": "<b>Andròmeda</b><br><span style=\"color:#f5c451\">2,5 milions d’anys</span>",
"<b>Las galaxias de Webb</b><br><span style=\"color:#f5c451\">más de 13.000 millones de años</span>": "<b>Les galàxies de Webb</b><br><span style=\"color:#f5c451\">més de 13.000 milions d’anys</span>",
"Lo que vemos es la luz que salió hace tanto tiempo: cuanto más lejos miramos, más atrás en el tiempo.": "El que veiem és la llum que va sortir fa tant de temps: com més lluny mirem, més enrere en el temps.",
"Votación en directo: escanean el QR con el móvil y el gráfico crece al momento.": "Votació en directe: escanegen el QR amb el mòbil i el gràfic creix a l’instant.",
"¿Qué te gustaría que observara Webb?": "Què t’agradaria que observés Webb?",
"Planetas con agua": "Planetes amb aigua",
"Agujeros negros": "Forats negres",
"Las primeras galaxias": "Les primeres galàxies",
"Nuestro sistema solar": "El nostre sistema solar",
"¿Preguntas?": "Preguntes?",
"Modelos 3D: NASA 3D Resources": "Models 3D: NASA 3D Resources"
},
"gl": {
"Telescopios espaciales: de Hubble a Webb": "Telescopios espaciais: do Hubble ao Webb",
"El telescopio James Webb en 3D (NASA): da una vuelta al entrar y se puede girar con el ratón.": "O telescopio James Webb en 3D (NASA): dá unha volta ao entrar e pódese xirar co rato.",
"CIENCIAS · EL UNIVERSO": "CIENCIAS · O UNIVERSO",
"Ojos en el espacio": "Ollos no espazo",
"De Hubble a Webb: cómo vemos el universo": "Do Hubble ao Webb: como vemos o universo",
"El telescopio espacial James Webb en 3D": "O telescopio espacial James Webb en 3D",
"Cada tarjeta aparece con un clic. Pregunta antes: ¿por qué las estrellas parpadean?": "Cada tarxeta aparece cun clic. Pregunta antes: por que escintilan as estrelas?",
"¿Por qué subirlo al espacio?": "Por que subilo ao espazo?",
"<b>Sin aire que tiemble</b><br>La atmósfera desenfoca las estrellas: allí arriba la imagen es nítida.": "<b>Sen aire que trema</b><br>A atmosfera desenfoca as estrelas: alí arriba a imaxe é nítida.",
"<b>Luz que no llega al suelo</b><br>El aire bloquea casi todo el infrarrojo y el ultravioleta.": "<b>Luz que non chega ao chan</b><br>O aire bloquea case todo o infravermello e o ultravioleta.",
"<b>Día y noche, todo el año</b><br>Sin nubes ni amaneceres: puede observar sin parar.": "<b>Día e noite, todo o ano</b><br>Sen nubes nin amenceres: pode observar sen parar.",
"El Hubble flota en el espacio. Las cifras entran una tras otra con un solo clic.": "O Hubble flota no espazo. As cifras entran unha tras outra cun só clic.",
"Hubble: 35 años mirando": "Hubble: 35 anos mirando",
"El telescopio espacial Hubble en 3D": "O telescopio espacial Hubble en 3D",
"<span style=\"color:#f5c451;font-weight:800\">1990</span><br>puesto en órbita": "<span style=\"color:#f5c451;font-weight:800\">1990</span><br>posto en órbita",
"<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Tierra": "<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre a Terra",
"<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espejo": "<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espello",
"Transformar: el Webb de la portada llega aquí más grande. Si preguntan cómo cabe en un cohete, baja (↓): está debajo.": "Transformar: o Webb da portada chega aquí máis grande. Se preguntan como cabe nun foguete, baixa (↓): está debaixo.",
"Webb: un espejo de oro": "Webb: un espello de ouro",
"<ul><li>Lanzado en 2021</li><li>Un espejo de 6,5 m hecho de 18 hexágonos</li><li>Ve en infrarrojo: atraviesa el polvo</li></ul>": "<ul><li>Lanzado en 2021</li><li>Un espello de 6,5 m feito de 18 hexágonos</li><li>Ve en infravermello: atravesa o po</li></ul>",
"Diapositiva debajo de la anterior: solo si hace falta. Cuatro clics, un paso cada uno. Vuelve arriba (↑) para seguir.": "Diapositiva debaixo da anterior: só se fai falta. Catro clics, un paso cada un. Volve arriba (↑) para seguir.",
"Así se despliega": "Así se desprega",
"<b>1</b> · Viaja plegado dentro del cohete": "<b>1</b> · Viaxa pregado dentro do foguete",
"<b>2</b> · Abre el parasol: del tamaño de una pista de tenis": "<b>2</b> · Abre o parasol: do tamaño dunha pista de tenis",
"<b>3</b> · Despliega el espejo secundario y las alas": "<b>3</b> · Desprega o espello secundario e as ás",
"<b>4</b> · Alinea sus 18 espejos con precisión de nanómetros": "<b>4</b> · Aliña os seus 18 espellos con precisión de nanómetros",
"Clic: el cohete sigue un recorrido curvo y gira hacia donde va.": "Clic: o foguete segue un percorrido curvo e xira cara a onde vai.",
"Un viaje de 1,5 millones de km": "Unha viaxe de 1,5 millóns de km",
"Tierra": "Terra",
"Punto L2": "Punto L2",
"Allí la Tierra, la Luna y el Sol quedan siempre detrás de su parasol: el telescopio está a la sombra y muy frío.": "Alí a Terra, a Lúa e o Sol quedan sempre detrás do parasol: o telescopio está á sombra e moi frío.",
"Tres clics: cada distancia con lo que tarda su luz en llegarnos.": "Tres clics: cada distancia co que tarda a súa luz en chegarnos.",
"La luz es una máquina del tiempo": "A luz é unha máquina do tempo",
"<b>El Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>": "<b>O Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>",
"<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millones de años</span>": "<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millóns de anos</span>",
"<b>Las galaxias de Webb</b><br><span style=\"color:#f5c451\">más de 13.000 millones de años</span>": "<b>As galaxias do Webb</b><br><span style=\"color:#f5c451\">máis de 13.000 millóns de anos</span>",
"Lo que vemos es la luz que salió hace tanto tiempo: cuanto más lejos miramos, más atrás en el tiempo.": "O que vemos é a luz que saíu hai tanto tempo: canto máis lonxe miramos, máis atrás no tempo.",
"Votación en directo: escanean el QR con el móvil y el gráfico crece al momento.": "Votación en directo: escanean o QR co móbil e o gráfico medra ao momento.",
"¿Qué te gustaría que observara Webb?": "Que che gustaría que observase o Webb?",
"Planetas con agua": "Planetas con auga",
"Agujeros negros": "Buratos negros",
"Las primeras galaxias": "As primeiras galaxias",
"Nuestro sistema solar": "O noso sistema solar",
"¿Preguntas?": "Preguntas?",
"Modelos 3D: NASA 3D Resources": "Modelos 3D: NASA 3D Resources"
},
"eu": {
"Telescopios espaciales: de Hubble a Webb": "Espazio-teleskopioak: Hubbletik Webbera",
"El telescopio James Webb en 3D (NASA): da una vuelta al entrar y se puede girar con el ratón.": "James Webb teleskopioa 3Dn (NASA): sartzean bira bat ematen du eta saguarekin biratu daiteke.",
"CIENCIAS · EL UNIVERSO": "ZIENTZIAK · UNIBERTSOA",
"Ojos en el espacio": "Begiak espazioan",
"De Hubble a Webb: cómo vemos el universo": "Hubbletik Webbera: nola ikusten dugun unibertsoa",
"El telescopio espacial James Webb en 3D": "James Webb espazio-teleskopioa 3Dn",
"Cada tarjeta aparece con un clic. Pregunta antes: ¿por qué las estrellas parpadean?": "Txartel bakoitza klik batekin agertzen da. Galdetu aurretik: zergatik egiten dute izarrek dir-dir?",
"¿Por qué subirlo al espacio?": "Zergatik eraman espaziora?",
"<b>Sin aire que tiemble</b><br>La atmósfera desenfoca las estrellas: allí arriba la imagen es nítida.": "<b>Dardarka egiten duen airerik gabe</b><br>Atmosferak izarrak lausotzen ditu: goian irudia garbia da.",
"<b>Luz que no llega al suelo</b><br>El aire bloquea casi todo el infrarrojo y el ultravioleta.": "<b>Lurrera iristen ez den argia</b><br>Aireak ia infragorri eta ultramore guztia blokeatzen du.",
"<b>Día y noche, todo el año</b><br>Sin nubes ni amaneceres: puede observar sin parar.": "<b>Egunez eta gauez, urte osoan</b><br>Hodeirik eta egunsentirik gabe: etenik gabe beha dezake.",
"El Hubble flota en el espacio. Las cifras entran una tras otra con un solo clic.": "Hubble espazioan flotatzen ari da. Zifrak bata bestearen atzetik sartzen dira klik bakar batekin.",
"Hubble: 35 años mirando": "Hubble: 35 urte begira",
"El telescopio espacial Hubble en 3D": "Hubble espazio-teleskopioa 3Dn",
"<span style=\"color:#f5c451;font-weight:800\">1990</span><br>puesto en órbita": "<span style=\"color:#f5c451;font-weight:800\">1990</span><br>orbitan jarria",
"<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Tierra": "<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>Lurraren gainetik",
"<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espejo": "<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>ispilua",
"Transformar: el Webb de la portada llega aquí más grande. Si preguntan cómo cabe en un cohete, baja (↓): está debajo.": "Eraldatu: azaleko Webb handiago iristen da hona. Kohete batean nola sartzen den galdetzen badute, jaitsi (↓): azpian dago.",
"Webb: un espejo de oro": "Webb: urrezko ispilu bat",
"<ul><li>Lanzado en 2021</li><li>Un espejo de 6,5 m hecho de 18 hexágonos</li><li>Ve en infrarrojo: atraviesa el polvo</li></ul>": "<ul><li>2021ean jaurtia</li><li>18 hexagonoz egindako 6,5 m-ko ispilua</li><li>Infragorrian ikusten du: hautsa zeharkatzen du</li></ul>",
"Diapositiva debajo de la anterior: solo si hace falta. Cuatro clics, un paso cada uno. Vuelve arriba (↑) para seguir.": "Aurrekoaren azpiko diapositiba: behar bada bakarrik. Lau klik, urrats bat bakoitzak. Itzuli gora (↑) jarraitzeko.",
"Así se despliega": "Horrela zabaltzen da",
"<b>1</b> · Viaja plegado dentro del cohete": "<b>1</b> · Tolestuta bidaiatzen du koheteen barruan",
"<b>2</b> · Abre el parasol: del tamaño de una pista de tenis": "<b>2</b> · Eguzki-babesa zabaltzen du: tenis-pista baten tamainakoa",
"<b>3</b> · Despliega el espejo secundario y las alas": "<b>3</b> · Bigarren mailako ispilua eta hegalak zabaltzen ditu",
"<b>4</b> · Alinea sus 18 espejos con precisión de nanómetros": "<b>4</b> · Bere 18 ispiluak nanometroko zehaztasunez lerrokatzen ditu",
"Clic: el cohete sigue un recorrido curvo y gira hacia donde va.": "Klik: koheteak bide kurbatu bati jarraitzen dio eta doan norabidera biratzen da.",
"Un viaje de 1,5 millones de km": "1,5 milioi km-ko bidaia",
"Tierra": "Lurra",
"Punto L2": "L2 puntua",
"Allí la Tierra, la Luna y el Sol quedan siempre detrás de su parasol: el telescopio está a la sombra y muy frío.": "Han Lurra, Ilargia eta Eguzkia beti geratzen dira eguzki-babesaren atzean: teleskopioa itzalean eta oso hotz dago.",
"Tres clics: cada distancia con lo que tarda su luz en llegarnos.": "Hiru klik: distantzia bakoitza, bere argiak guregana iristeko behar duen denborarekin.",
"La luz es una máquina del tiempo": "Argia denbora-makina bat da",
"<b>El Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>": "<b>Eguzkia</b><br><span style=\"color:#f5c451\">8 minutu</span>",
"<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millones de años</span>": "<b>Andromeda</b><br><span style=\"color:#f5c451\">2,5 milioi urte</span>",
"<b>Las galaxias de Webb</b><br><span style=\"color:#f5c451\">más de 13.000 millones de años</span>": "<b>Webben galaxiak</b><br><span style=\"color:#f5c451\">13.000 milioi urte baino gehiago</span>",
"Lo que vemos es la luz que salió hace tanto tiempo: cuanto más lejos miramos, más atrás en el tiempo.": "Ikusten duguna aspaldi irten zen argia da: zenbat eta urrunago begiratu, orduan eta atzerago denboran.",
"Votación en directo: escanean el QR con el móvil y el gráfico crece al momento.": "Zuzeneko bozketa: QRa mugikorrarekin eskaneatzen dute eta grafikoa berehala hazten da.",
"¿Qué te gustaría que observara Webb?": "Zer gustatuko litzaizuke Webbek behatzea?",
"Planetas con agua": "Ura duten planetak",
"Agujeros negros": "Zulo beltzak",
"Las primeras galaxias": "Lehen galaxiak",
"Nuestro sistema solar": "Gure eguzki-sistema",
"¿Preguntas?": "Galderarik?",
"Modelos 3D: NASA 3D Resources": "3D ereduak: NASA 3D Resources"
},
"nl": {
"Telescopios espaciales: de Hubble a Webb": "Ruimtetelescopen: van Hubble tot Webb",
"El telescopio James Webb en 3D (NASA): da una vuelta al entrar y se puede girar con el ratón.": "De James Webb-telescoop in 3D (NASA): draait een rondje bij het verschijnen en is met de muis te draaien.",
"CIENCIAS · EL UNIVERSO": "NATUURWETENSCHAPPEN · HET HEELAL",
"Ojos en el espacio": "Ogen in de ruimte",
"De Hubble a Webb: cómo vemos el universo": "Van Hubble tot Webb: hoe we het heelal zien",
"El telescopio espacial James Webb en 3D": "De James Webb-ruimtetelescoop in 3D",
"Cada tarjeta aparece con un clic. Pregunta antes: ¿por qué las estrellas parpadean?": "Elke kaart verschijnt met een klik. Vraag eerst: waarom twinkelen sterren?",
"¿Por qué subirlo al espacio?": "Waarom de ruimte in?",
"<b>Sin aire que tiemble</b><br>La atmósfera desenfoca las estrellas: allí arriba la imagen es nítida.": "<b>Geen trillende lucht</b><br>De atmosfeer maakt sterren wazig: daarboven is het beeld scherp.",
"<b>Luz que no llega al suelo</b><br>El aire bloquea casi todo el infrarrojo y el ultravioleta.": "<b>Licht dat de grond niet bereikt</b><br>De lucht houdt bijna al het infrarood en ultraviolet tegen.",
"<b>Día y noche, todo el año</b><br>Sin nubes ni amaneceres: puede observar sin parar.": "<b>Dag en nacht, het hele jaar</b><br>Geen wolken of zonsopkomst: hij kan onafgebroken kijken.",
"El Hubble flota en el espacio. Las cifras entran una tras otra con un solo clic.": "Hubble zweeft in de ruimte. De cijfers komen met één klik na elkaar binnen.",
"Hubble: 35 años mirando": "Hubble: 35 jaar kijken",
"El telescopio espacial Hubble en 3D": "De Hubble-ruimtetelescoop in 3D",
"<span style=\"color:#f5c451;font-weight:800\">1990</span><br>puesto en órbita": "<span style=\"color:#f5c451;font-weight:800\">1990</span><br>in een baan gebracht",
"<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Tierra": "<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>boven de aarde",
"<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espejo": "<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>spiegel",
"Transformar: el Webb de la portada llega aquí más grande. Si preguntan cómo cabe en un cohete, baja (↓): está debajo.": "Transformeren: de Webb van de titeldia komt hier groter binnen. Vragen ze hoe hij in een raket past, ga naar beneden (↓): het staat eronder.",
"Webb: un espejo de oro": "Webb: een gouden spiegel",
"<ul><li>Lanzado en 2021</li><li>Un espejo de 6,5 m hecho de 18 hexágonos</li><li>Ve en infrarrojo: atraviesa el polvo</li></ul>": "<ul><li>Gelanceerd in 2021</li><li>Een spiegel van 6,5 m uit 18 zeshoeken</li><li>Ziet in infrarood: dwars door stof</li></ul>",
"Diapositiva debajo de la anterior: solo si hace falta. Cuatro clics, un paso cada uno. Vuelve arriba (↑) para seguir.": "Dia onder de vorige: alleen als het nodig is. Vier klikken, één stap per klik. Ga terug omhoog (↑) om verder te gaan.",
"Así se despliega": "Zo vouwt hij zich uit",
"<b>1</b> · Viaja plegado dentro del cohete": "<b>1</b> · Hij reist opgevouwen in de raket",
"<b>2</b> · Abre el parasol: del tamaño de una pista de tenis": "<b>2</b> · Hij opent het zonnescherm: zo groot als een tennisbaan",
"<b>3</b> · Despliega el espejo secundario y las alas": "<b>3</b> · Hij vouwt de secundaire spiegel en de vleugels uit",
"<b>4</b> · Alinea sus 18 espejos con precisión de nanómetros": "<b>4</b> · Hij lijnt zijn 18 spiegels uit tot op de nanometer",
"Clic: el cohete sigue un recorrido curvo y gira hacia donde va.": "Klik: de raket volgt een gebogen baan en draait in de richting waarin hij gaat.",
"Un viaje de 1,5 millones de km": "Een reis van 1,5 miljoen km",
"Tierra": "Aarde",
"Punto L2": "Punt L2",
"Allí la Tierra, la Luna y el Sol quedan siempre detrás de su parasol: el telescopio está a la sombra y muy frío.": "Daar blijven de aarde, de maan en de zon altijd achter het zonnescherm: de telescoop staat in de schaduw en is erg koud.",
"Tres clics: cada distancia con lo que tarda su luz en llegarnos.": "Drie klikken: elke afstand met hoe lang het licht erover doet om ons te bereiken.",
"La luz es una máquina del tiempo": "Licht is een tijdmachine",
"<b>El Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>": "<b>De zon</b><br><span style=\"color:#f5c451\">8 minuten</span>",
"<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millones de años</span>": "<b>Andromeda</b><br><span style=\"color:#f5c451\">2,5 miljoen jaar</span>",
"<b>Las galaxias de Webb</b><br><span style=\"color:#f5c451\">más de 13.000 millones de años</span>": "<b>De sterrenstelsels van Webb</b><br><span style=\"color:#f5c451\">meer dan 13 miljard jaar</span>",
"Lo que vemos es la luz que salió hace tanto tiempo: cuanto más lejos miramos, más atrás en el tiempo.": "Wat we zien is licht dat zo lang geleden vertrok: hoe verder we kijken, hoe verder terug in de tijd.",
"Votación en directo: escanean el QR con el móvil y el gráfico crece al momento.": "Live-peiling: ze scannen de QR-code met hun telefoon en de grafiek groeit meteen.",
"¿Qué te gustaría que observara Webb?": "Waar zou je Webb naar willen laten kijken?",
"Planetas con agua": "Planeten met water",
"Agujeros negros": "Zwarte gaten",
"Las primeras galaxias": "De eerste sterrenstelsels",
"Nuestro sistema solar": "Ons zonnestelsel",
"¿Preguntas?": "Vragen?",
"Modelos 3D: NASA 3D Resources": "3D-modellen: NASA 3D Resources"
},
"ar": {
"Telescopios espaciales: de Hubble a Webb": "التلسكوبات الفضائية: من هابل إلى ويب",
"El telescopio James Webb en 3D (NASA): da una vuelta al entrar y se puede girar con el ratón.": "تلسكوب جيمس ويب ثلاثي الأبعاد (ناسا): يدور عند ظهوره ويمكن تدويره بالفأرة.",
"CIENCIAS · EL UNIVERSO": "العلوم · الكون",
"Ojos en el espacio": "عيون في الفضاء",
"De Hubble a Webb: cómo vemos el universo": "من هابل إلى ويب: كيف نرى الكون",
"El telescopio espacial James Webb en 3D": "تلسكوب جيمس ويب الفضائي ثلاثي الأبعاد",
"Cada tarjeta aparece con un clic. Pregunta antes: ¿por qué las estrellas parpadean?": "تظهر كل بطاقة بنقرة. اسأل أولاً: لماذا تتلألأ النجوم؟",
"¿Por qué subirlo al espacio?": "لماذا نرسله إلى الفضاء؟",
"<b>Sin aire que tiemble</b><br>La atmósfera desenfoca las estrellas: allí arriba la imagen es nítida.": "<b>بلا هواء يرتجف</b><br>يُشوّش الغلاف الجوي صورة النجوم: هناك في الأعلى تكون الصورة واضحة.",
"<b>Luz que no llega al suelo</b><br>El aire bloquea casi todo el infrarrojo y el ultravioleta.": "<b>ضوء لا يصل إلى الأرض</b><br>يحجب الهواء معظم الأشعة تحت الحمراء وفوق البنفسجية.",
"<b>Día y noche, todo el año</b><br>Sin nubes ni amaneceres: puede observar sin parar.": "<b>ليلاً ونهاراً، طوال العام</b><br>بلا غيوم ولا شروق: يمكنه الرصد دون توقف.",
"El Hubble flota en el espacio. Las cifras entran una tras otra con un solo clic.": "يطفو هابل في الفضاء. تظهر الأرقام واحداً تلو الآخر بنقرة واحدة.",
"Hubble: 35 años mirando": "هابل: 35 عاماً من الرصد",
"El telescopio espacial Hubble en 3D": "تلسكوب هابل الفضائي ثلاثي الأبعاد",
"<span style=\"color:#f5c451;font-weight:800\">1990</span><br>puesto en órbita": "<span style=\"color:#f5c451;font-weight:800\">1990</span><br>وُضع في المدار",
"<span style=\"color:#f5c451;font-weight:800\">547 km</span><br>sobre la Tierra": "<span style=\"color:#f5c451;font-weight:800\">547 كم</span><br>فوق الأرض",
"<span style=\"color:#f5c451;font-weight:800\">2,4 m</span><br>de espejo": "<span style=\"color:#f5c451;font-weight:800\">2.4 م</span><br>قطر المرآة",
"Transformar: el Webb de la portada llega aquí más grande. Si preguntan cómo cabe en un cohete, baja (↓): está debajo.": "تحويل: يصل ويب من الغلاف إلى هنا أكبر حجماً. إن سألوا كيف يتسع في صاروخ، انزل (↓): الجواب في الأسفل.",
"Webb: un espejo de oro": "ويب: مرآة من ذهب",
"<ul><li>Lanzado en 2021</li><li>Un espejo de 6,5 m hecho de 18 hexágonos</li><li>Ve en infrarrojo: atraviesa el polvo</li></ul>": "<ul><li>أُطلق عام 2021</li><li>مرآة قطرها 6.5 م مكوّنة من 18 سداسياً</li><li>يرى بالأشعة تحت الحمراء: يخترق الغبار</li></ul>",
"Diapositiva debajo de la anterior: solo si hace falta. Cuatro clics, un paso cada uno. Vuelve arriba (↑) para seguir.": "شريحة أسفل السابقة: عند الحاجة فقط. أربع نقرات، خطوة لكل نقرة. اصعد (↑) للمتابعة.",
"Así se despliega": "هكذا ينفتح",
"<b>1</b> · Viaja plegado dentro del cohete": "<b>1</b> · يسافر مطوياً داخل الصاروخ",
"<b>2</b> · Abre el parasol: del tamaño de una pista de tenis": "<b>2</b> · يفتح الدرع الشمسي: بحجم ملعب تنس",
"<b>3</b> · Despliega el espejo secundario y las alas": "<b>3</b> · ينشر المرآة الثانوية والجناحين",
"<b>4</b> · Alinea sus 18 espejos con precisión de nanómetros": "<b>4</b> · يحاذي مراياه الثماني عشرة بدقة النانومتر",
"Clic: el cohete sigue un recorrido curvo y gira hacia donde va.": "نقرة: يتبع الصاروخ مساراً منحنياً ويتّجه نحو وجهته.",
"Un viaje de 1,5 millones de km": "رحلة طولها 1.5 مليون كم",
"Tierra": "الأرض",
"Punto L2": "النقطة L2",
"Allí la Tierra, la Luna y el Sol quedan siempre detrás de su parasol: el telescopio está a la sombra y muy frío.": "هناك تبقى الأرض والقمر والشمس دائماً خلف درعه الشمسي: فيظل التلسكوب في الظل وبارداً جداً.",
"Tres clics: cada distancia con lo que tarda su luz en llegarnos.": "ثلاث نقرات: كل مسافة مع الزمن الذي يستغرقه ضوؤها ليصل إلينا.",
"La luz es una máquina del tiempo": "الضوء آلة زمن",
"<b>El Sol</b><br><span style=\"color:#f5c451\">8 minutos</span>": "<b>الشمس</b><br><span style=\"color:#f5c451\">8 دقائق</span>",
"<b>Andrómeda</b><br><span style=\"color:#f5c451\">2,5 millones de años</span>": "<b>أندروميدا</b><br><span style=\"color:#f5c451\">2.5 مليون سنة</span>",
"<b>Las galaxias de Webb</b><br><span style=\"color:#f5c451\">más de 13.000 millones de años</span>": "<b>مجرات ويب</b><br><span style=\"color:#f5c451\">أكثر من 13 مليار سنة</span>",
"Lo que vemos es la luz que salió hace tanto tiempo: cuanto más lejos miramos, más atrás en el tiempo.": "ما نراه هو ضوء انطلق منذ زمن بعيد: كلما نظرنا أبعد، عدنا أكثر إلى الوراء في الزمن.",
"Votación en directo: escanean el QR con el móvil y el gráfico crece al momento.": "تصويت مباشر: يمسحون رمز QR بالهاتف فيكبر الرسم البياني فوراً.",
"¿Qué te gustaría que observara Webb?": "ماذا تودّ أن يرصد ويب؟",
"Planetas con agua": "كواكب فيها ماء",
"Agujeros negros": "الثقوب السوداء",
"Las primeras galaxias": "المجرات الأولى",
"Nuestro sistema solar": "نظامنا الشمسي",
"¿Preguntas?": "أسئلة؟",
"Modelos 3D: NASA 3D Resources": "نماذج ثلاثية الأبعاد: NASA 3D Resources"
}
},
"storyrobot": {
"en": {
"Cuento: el robot que quería hablar con todos": "Story: the robot who wanted to talk to everyone",
"Arriba a la derecha de la vista compartida, cada alumno elige su idioma.": "At the top right of the shared view, each student chooses their language.",
"El robot que quería hablar con todos": "The robot who wanted to talk to everyone",
"Un cuento para leer en tu idioma": "A story to read in your language",
"Robo, el robot": "Robo, the robot",
"Clic: Robo entra andando, saluda y dice hola.": "Click: Robo walks in, waves and says hello.",
"Había una vez un robot llamado Robo. Le encantaba saludar a todo el mundo.": "Once upon a time there was a robot called Robo. He loved saying hello to everyone.",
"¡Hola! ¿Quieres jugar?": "Hi! Do you want to play?",
"La zorra llega andando… y no se entienden. Otro clic: Robo niega con la cabeza.": "The fox walks in… and they can’t understand each other. Another click: Robo shakes his head.",
"Una zorra se acercó, pero no entendía a Robo: hablaba otra lengua.": "A fox came closer, but she couldn’t understand Robo: she spoke another language.",
"La zorra": "The fox",
"La maga entra andando y lo celebra al llegar.": "The sorceress walks in and celebrates when she arrives.",
"Entonces llegó una maga sabia.": "Then a wise sorceress arrived.",
"La maga": "The sorceress",
"Escuchar con atención es la primera lengua de todos.": "Listening carefully is everyone’s first language.",
"Cuatro clics, una palabra cada uno. Pregunta cómo se dice cada una en las lenguas de la clase.": "Four clicks, one word each. Ask how each one is said in the languages of the class.",
"Aprendieron sus palabras": "They learned each other’s words",
"<b>Hola</b>": "<b>Hello</b>",
"<b>Gracias</b>": "<b>Thank you</b>",
"<b>Amigo</b>": "<b>Friend</b>",
"<b>Jugamos</b>": "<b>Let’s play</b>",
"Cada uno enseñó sus palabras a los demás.": "Each one taught their words to the others.",
"Clic: Robo baila y la maga lo celebra.": "Click: Robo dances and the sorceress celebrates.",
"Y desde ese día, los tres jugaron juntos cada tarde.": "And from that day on, the three of them played together every afternoon.",
"¡Ahora hablamos con todos!": "Now we can talk to everyone!",
"Nube de palabras: cada alumno escribe «hola» en su lengua desde el móvil.": "Word cloud: each student writes “hello” in their language from their phone.",
"¿Cómo se dice «hola» en tu idioma?": "How do you say “hello” in your language?",
"Fin": "The end",
"¿Qué otras palabras te gustaría enseñar?": "What other words would you like to teach?",
"3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)": "3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)"
},
"fr": {
"Cuento: el robot que quería hablar con todos": "Conte : le robot qui voulait parler à tout le monde",
"Arriba a la derecha de la vista compartida, cada alumno elige su idioma.": "En haut à droite de la vue partagée, chaque élève choisit sa langue.",
"El robot que quería hablar con todos": "Le robot qui voulait parler à tout le monde",
"Un cuento para leer en tu idioma": "Un conte à lire dans ta langue",
"Robo, el robot": "Robo, le robot",
"Clic: Robo entra andando, saluda y dice hola.": "Clic : Robo entre en marchant, fait signe et dit bonjour.",
"Había una vez un robot llamado Robo. Le encantaba saludar a todo el mundo.": "Il était une fois un robot appelé Robo. Il adorait dire bonjour à tout le monde.",
"¡Hola! ¿Quieres jugar?": "Salut ! Tu veux jouer ?",
"La zorra llega andando… y no se entienden. Otro clic: Robo niega con la cabeza.": "La renarde arrive en marchant… et ils ne se comprennent pas. Un autre clic : Robo secoue la tête.",
"Una zorra se acercó, pero no entendía a Robo: hablaba otra lengua.": "Une renarde s’approcha, mais elle ne comprenait pas Robo : elle parlait une autre langue.",
"La zorra": "La renarde",
"La maga entra andando y lo celebra al llegar.": "La magicienne entre en marchant et fête son arrivée.",
"Entonces llegó una maga sabia.": "Alors arriva une sage magicienne.",
"La maga": "La magicienne",
"Escuchar con atención es la primera lengua de todos.": "Écouter attentivement est la première langue de tous.",
"Cuatro clics, una palabra cada uno. Pregunta cómo se dice cada una en las lenguas de la clase.": "Quatre clics, un mot chacun. Demandez comment chacun se dit dans les langues de la classe.",
"Aprendieron sus palabras": "Ils ont appris leurs mots",
"<b>Hola</b>": "<b>Bonjour</b>",
"<b>Gracias</b>": "<b>Merci</b>",
"<b>Amigo</b>": "<b>Ami</b>",
"<b>Jugamos</b>": "<b>On joue</b>",
"Cada uno enseñó sus palabras a los demás.": "Chacun a appris ses mots aux autres.",
"Clic: Robo baila y la maga lo celebra.": "Clic : Robo danse et la magicienne fait la fête.",
"Y desde ese día, los tres jugaron juntos cada tarde.": "Et depuis ce jour, tous les trois ont joué ensemble chaque après-midi.",
"¡Ahora hablamos con todos!": "Maintenant on parle avec tout le monde !",
"Nube de palabras: cada alumno escribe «hola» en su lengua desde el móvil.": "Nuage de mots : chaque élève écrit « bonjour » dans sa langue depuis son téléphone.",
"¿Cómo se dice «hola» en tu idioma?": "Comment dit-on « bonjour » dans ta langue ?",
"Fin": "Fin",
"¿Qué otras palabras te gustaría enseñar?": "Quels autres mots aimerais-tu enseigner ?",
"3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)": "3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)"
},
"de": {
"Cuento: el robot que quería hablar con todos": "Geschichte: der Roboter, der mit allen reden wollte",
"Arriba a la derecha de la vista compartida, cada alumno elige su idioma.": "Oben rechts in der geteilten Ansicht wählt jedes Kind seine Sprache.",
"El robot que quería hablar con todos": "Der Roboter, der mit allen reden wollte",
"Un cuento para leer en tu idioma": "Eine Geschichte zum Lesen in deiner Sprache",
"Robo, el robot": "Robo, der Roboter",
"Clic: Robo entra andando, saluda y dice hola.": "Klick: Robo kommt herein, winkt und sagt hallo.",
"Había una vez un robot llamado Robo. Le encantaba saludar a todo el mundo.": "Es war einmal ein Roboter namens Robo. Er grüßte für sein Leben gern alle.",
"¡Hola! ¿Quieres jugar?": "Hallo! Willst du spielen?",
"La zorra llega andando… y no se entienden. Otro clic: Robo niega con la cabeza.": "Die Füchsin kommt herein… und sie verstehen sich nicht. Noch ein Klick: Robo schüttelt den Kopf.",
"Una zorra se acercó, pero no entendía a Robo: hablaba otra lengua.": "Eine Füchsin kam näher, aber sie verstand Robo nicht: Sie sprach eine andere Sprache.",
"La zorra": "Die Füchsin",
"La maga entra andando y lo celebra al llegar.": "Die Zauberin kommt herein und jubelt, als sie ankommt.",
"Entonces llegó una maga sabia.": "Da kam eine weise Zauberin.",
"La maga": "Die Zauberin",
"Escuchar con atención es la primera lengua de todos.": "Gut zuhören ist die erste Sprache von allen.",
"Cuatro clics, una palabra cada uno. Pregunta cómo se dice cada una en las lenguas de la clase.": "Vier Klicks, ein Wort pro Klick. Frag, wie jedes in den Sprachen der Klasse heißt.",
"Aprendieron sus palabras": "Sie lernten ihre Wörter",
"<b>Hola</b>": "<b>Hallo</b>",
"<b>Gracias</b>": "<b>Danke</b>",
"<b>Amigo</b>": "<b>Freund</b>",
"<b>Jugamos</b>": "<b>Wir spielen</b>",
"Cada uno enseñó sus palabras a los demás.": "Jeder brachte den anderen seine Wörter bei.",
"Clic: Robo baila y la maga lo celebra.": "Klick: Robo tanzt und die Zauberin jubelt.",
"Y desde ese día, los tres jugaron juntos cada tarde.": "Und seit diesem Tag spielten die drei jeden Nachmittag zusammen.",
"¡Ahora hablamos con todos!": "Jetzt reden wir mit allen!",
"Nube de palabras: cada alumno escribe «hola» en su lengua desde el móvil.": "Wortwolke: Jedes Kind schreibt „hallo“ in seiner Sprache vom Handy aus.",
"¿Cómo se dice «hola» en tu idioma?": "Wie sagt man „hallo“ in deiner Sprache?",
"Fin": "Ende",
"¿Qué otras palabras te gustaría enseñar?": "Welche anderen Wörter möchtest du beibringen?",
"3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)": "3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)"
},
"it": {
"Cuento: el robot que quería hablar con todos": "Racconto: il robot che voleva parlare con tutti",
"Arriba a la derecha de la vista compartida, cada alumno elige su idioma.": "In alto a destra della vista condivisa, ogni studente sceglie la sua lingua.",
"El robot que quería hablar con todos": "Il robot che voleva parlare con tutti",
"Un cuento para leer en tu idioma": "Un racconto da leggere nella tua lingua",
"Robo, el robot": "Robo, il robot",
"Clic: Robo entra andando, saluda y dice hola.": "Clic: Robo entra camminando, saluta e dice ciao.",
"Había una vez un robot llamado Robo. Le encantaba saludar a todo el mundo.": "C’era una volta un robot di nome Robo. Adorava salutare tutti.",
"¡Hola! ¿Quieres jugar?": "Ciao! Vuoi giocare?",
"La zorra llega andando… y no se entienden. Otro clic: Robo niega con la cabeza.": "La volpe arriva camminando… e non si capiscono. Un altro clic: Robo scuote la testa.",
"Una zorra se acercó, pero no entendía a Robo: hablaba otra lengua.": "Una volpe si avvicinò, ma non capiva Robo: parlava un’altra lingua.",
"La zorra": "La volpe",
"La maga entra andando y lo celebra al llegar.": "La maga entra camminando e festeggia quando arriva.",
"Entonces llegó una maga sabia.": "Allora arrivò una maga saggia.",
"La maga": "La maga",
"Escuchar con atención es la primera lengua de todos.": "Ascoltare con attenzione è la prima lingua di tutti.",
"Cuatro clics, una palabra cada uno. Pregunta cómo se dice cada una en las lenguas de la clase.": "Quattro clic, una parola ciascuno. Chiedi come si dice ognuna nelle lingue della classe.",
"Aprendieron sus palabras": "Impararono le loro parole",
"<b>Hola</b>": "<b>Ciao</b>",
"<b>Gracias</b>": "<b>Grazie</b>",
"<b>Amigo</b>": "<b>Amico</b>",
"<b>Jugamos</b>": "<b>Giochiamo</b>",
"Cada uno enseñó sus palabras a los demás.": "Ognuno insegnò le sue parole agli altri.",
"Clic: Robo baila y la maga lo celebra.": "Clic: Robo balla e la maga festeggia.",
"Y desde ese día, los tres jugaron juntos cada tarde.": "E da quel giorno, i tre giocarono insieme ogni pomeriggio.",
"¡Ahora hablamos con todos!": "Ora parliamo con tutti!",
"Nube de palabras: cada alumno escribe «hola» en su lengua desde el móvil.": "Nuvola di parole: ogni studente scrive «ciao» nella sua lingua dal telefono.",
"¿Cómo se dice «hola» en tu idioma?": "Come si dice «ciao» nella tua lingua?",
"Fin": "Fine",
"¿Qué otras palabras te gustaría enseñar?": "Quali altre parole ti piacerebbe insegnare?",
"3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)": "3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)"
},
"pt": {
"Cuento: el robot que quería hablar con todos": "Conto: o robô que queria falar com todos",
"Arriba a la derecha de la vista compartida, cada alumno elige su idioma.": "No canto superior direito da vista partilhada, cada aluno escolhe o seu idioma.",
"El robot que quería hablar con todos": "O robô que queria falar com todos",
"Un cuento para leer en tu idioma": "Um conto para ler no teu idioma",
"Robo, el robot": "Robo, o robô",
"Clic: Robo entra andando, saluda y dice hola.": "Clique: o Robo entra a andar, acena e diz olá.",
"Había una vez un robot llamado Robo. Le encantaba saludar a todo el mundo.": "Era uma vez um robô chamado Robo. Adorava cumprimentar toda a gente.",
"¡Hola! ¿Quieres jugar?": "Olá! Queres brincar?",
"La zorra llega andando… y no se entienden. Otro clic: Robo niega con la cabeza.": "A raposa chega a andar… e não se entendem. Outro clique: o Robo abana a cabeça.",
"Una zorra se acercó, pero no entendía a Robo: hablaba otra lengua.": "Uma raposa aproximou-se, mas não percebia o Robo: falava outra língua.",
"La zorra": "A raposa",
"La maga entra andando y lo celebra al llegar.": "A maga entra a andar e festeja ao chegar.",
"Entonces llegó una maga sabia.": "Então chegou uma maga sábia.",
"La maga": "A maga",
"Escuchar con atención es la primera lengua de todos.": "Ouvir com atenção é a primeira língua de todos.",
"Cuatro clics, una palabra cada uno. Pregunta cómo se dice cada una en las lenguas de la clase.": "Quatro cliques, uma palavra cada. Pergunta como se diz cada uma nas línguas da turma.",
"Aprendieron sus palabras": "Aprenderam as palavras uns dos outros",
"<b>Hola</b>": "<b>Olá</b>",
"<b>Gracias</b>": "<b>Obrigado</b>",
"<b>Amigo</b>": "<b>Amigo</b>",
"<b>Jugamos</b>": "<b>Vamos brincar</b>",
"Cada uno enseñó sus palabras a los demás.": "Cada um ensinou as suas palavras aos outros.",
"Clic: Robo baila y la maga lo celebra.": "Clique: o Robo dança e a maga festeja.",
"Y desde ese día, los tres jugaron juntos cada tarde.": "E desde esse dia, os três brincaram juntos todas as tardes.",
"¡Ahora hablamos con todos!": "Agora falamos com todos!",
"Nube de palabras: cada alumno escribe «hola» en su lengua desde el móvil.": "Nuvem de palavras: cada aluno escreve «olá» na sua língua a partir do telemóvel.",
"¿Cómo se dice «hola» en tu idioma?": "Como se diz «olá» na tua língua?",
"Fin": "Fim",
"¿Qué otras palabras te gustaría enseñar?": "Que outras palavras gostarias de ensinar?",
"3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)": "3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)"
},
"ca": {
"Cuento: el robot que quería hablar con todos": "Conte: el robot que volia parlar amb tothom",
"Arriba a la derecha de la vista compartida, cada alumno elige su idioma.": "A dalt a la dreta de la vista compartida, cada alumne tria el seu idioma.",
"El robot que quería hablar con todos": "El robot que volia parlar amb tothom",
"Un cuento para leer en tu idioma": "Un conte per llegir en el teu idioma",
"Robo, el robot": "Robo, el robot",
"Clic: Robo entra andando, saluda y dice hola.": "Clic: en Robo entra caminant, saluda i diu hola.",
"Había una vez un robot llamado Robo. Le encantaba saludar a todo el mundo.": "Hi havia una vegada un robot anomenat Robo. Li encantava saludar tothom.",
"¡Hola! ¿Quieres jugar?": "Hola! Vols jugar?",
"La zorra llega andando… y no se entienden. Otro clic: Robo niega con la cabeza.": "La guineu arriba caminant… i no s’entenen. Un altre clic: en Robo nega amb el cap.",
"Una zorra se acercó, pero no entendía a Robo: hablaba otra lengua.": "Una guineu s’hi va acostar, però no entenia en Robo: parlava una altra llengua.",
"La zorra": "La guineu",
"La maga entra andando y lo celebra al llegar.": "La maga entra caminant i ho celebra en arribar.",
"Entonces llegó una maga sabia.": "Llavors va arribar una maga sàvia.",
"La maga": "La maga",
"Escuchar con atención es la primera lengua de todos.": "Escoltar amb atenció és la primera llengua de tothom.",
"Cuatro clics, una palabra cada uno. Pregunta cómo se dice cada una en las lenguas de la clase.": "Quatre clics, una paraula cadascun. Pregunta com es diu cadascuna en les llengües de la classe.",
"Aprendieron sus palabras": "Van aprendre les seves paraules",
"<b>Hola</b>": "<b>Hola</b>",
"<b>Gracias</b>": "<b>Gràcies</b>",
"<b>Amigo</b>": "<b>Amic</b>",
"<b>Jugamos</b>": "<b>Juguem</b>",
"Cada uno enseñó sus palabras a los demás.": "Cadascú va ensenyar les seves paraules als altres.",
"Clic: Robo baila y la maga lo celebra.": "Clic: en Robo balla i la maga ho celebra.",
"Y desde ese día, los tres jugaron juntos cada tarde.": "I des d’aquell dia, tots tres van jugar junts cada tarda.",
"¡Ahora hablamos con todos!": "Ara parlem amb tothom!",
"Nube de palabras: cada alumno escribe «hola» en su lengua desde el móvil.": "Núvol de paraules: cada alumne escriu «hola» en la seva llengua des del mòbil.",
"¿Cómo se dice «hola» en tu idioma?": "Com es diu «hola» en el teu idioma?",
"Fin": "Fi",
"¿Qué otras palabras te gustaría enseñar?": "Quines altres paraules t’agradaria ensenyar?",
"3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)": "3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)"
},
"gl": {
"Cuento: el robot que quería hablar con todos": "Conto: o robot que quería falar con todos",
"Arriba a la derecha de la vista compartida, cada alumno elige su idioma.": "Arriba á dereita da vista compartida, cada alumno escolle o seu idioma.",
"El robot que quería hablar con todos": "O robot que quería falar con todos",
"Un cuento para leer en tu idioma": "Un conto para ler no teu idioma",
"Robo, el robot": "Robo, o robot",
"Clic: Robo entra andando, saluda y dice hola.": "Clic: Robo entra andando, saúda e di ola.",
"Había una vez un robot llamado Robo. Le encantaba saludar a todo el mundo.": "Había unha vez un robot chamado Robo. Encantáballe saudar a todo o mundo.",
"¡Hola! ¿Quieres jugar?": "Ola! Queres xogar?",
"La zorra llega andando… y no se entienden. Otro clic: Robo niega con la cabeza.": "A raposa chega andando… e non se entenden. Outro clic: Robo nega coa cabeza.",
"Una zorra se acercó, pero no entendía a Robo: hablaba otra lengua.": "Unha raposa achegouse, pero non entendía a Robo: falaba outra lingua.",
"La zorra": "A raposa",
"La maga entra andando y lo celebra al llegar.": "A maga entra andando e celébrao ao chegar.",
"Entonces llegó una maga sabia.": "Entón chegou unha maga sabia.",
"La maga": "A maga",
"Escuchar con atención es la primera lengua de todos.": "Escoitar con atención é a primeira lingua de todos.",
"Cuatro clics, una palabra cada uno. Pregunta cómo se dice cada una en las lenguas de la clase.": "Catro clics, unha palabra cada un. Pregunta como se di cada unha nas linguas da clase.",
"Aprendieron sus palabras": "Aprenderon as súas palabras",
"<b>Hola</b>": "<b>Ola</b>",
"<b>Gracias</b>": "<b>Grazas</b>",
"<b>Amigo</b>": "<b>Amigo</b>",
"<b>Jugamos</b>": "<b>Xogamos</b>",
"Cada uno enseñó sus palabras a los demás.": "Cada un ensinou as súas palabras aos demais.",
"Clic: Robo baila y la maga lo celebra.": "Clic: Robo baila e a maga celébrao.",
"Y desde ese día, los tres jugaron juntos cada tarde.": "E desde aquel día, os tres xogaron xuntos cada tarde.",
"¡Ahora hablamos con todos!": "Agora falamos con todos!",
"Nube de palabras: cada alumno escribe «hola» en su lengua desde el móvil.": "Nube de palabras: cada alumno escribe «ola» na súa lingua desde o móbil.",
"¿Cómo se dice «hola» en tu idioma?": "Como se di «ola» no teu idioma?",
"Fin": "Fin",
"¿Qué otras palabras te gustaría enseñar?": "Que outras palabras che gustaría ensinar?",
"3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)": "3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)"
},
"eu": {
"Cuento: el robot que quería hablar con todos": "Ipuina: guztiekin hitz egin nahi zuen robota",
"Arriba a la derecha de la vista compartida, cada alumno elige su idioma.": "Partekatutako ikuspegiaren goiko eskuinean, ikasle bakoitzak bere hizkuntza aukeratzen du.",
"El robot que quería hablar con todos": "Guztiekin hitz egin nahi zuen robota",
"Un cuento para leer en tu idioma": "Zure hizkuntzan irakurtzeko ipuina",
"Robo, el robot": "Robo, robota",
"Clic: Robo entra andando, saluda y dice hola.": "Klik: Robo oinez sartzen da, agurtzen du eta kaixo esaten du.",
"Había una vez un robot llamado Robo. Le encantaba saludar a todo el mundo.": "Bazen behin Robo izeneko robot bat. Mundu guztia agurtzea maite zuen.",
"¡Hola! ¿Quieres jugar?": "Kaixo! Jolastu nahi duzu?",
"La zorra llega andando… y no se entienden. Otro clic: Robo niega con la cabeza.": "Azeria oinez iristen da… eta ez dira ulertzen. Beste klik bat: Robok ezetz egiten du buruarekin.",
"Una zorra se acercó, pero no entendía a Robo: hablaba otra lengua.": "Azeri bat hurbildu zen, baina ez zuen Robo ulertzen: beste hizkuntza bat hitz egiten zuen.",
"La zorra": "Azeria",
"La maga entra andando y lo celebra al llegar.": "Magoa oinez sartzen da eta iristean ospatzen du.",
"Entonces llegó una maga sabia.": "Orduan mago jakintsu bat iritsi zen.",
"La maga": "Magoa",
"Escuchar con atención es la primera lengua de todos.": "Arretaz entzutea da guztion lehen hizkuntza.",
"Cuatro clics, una palabra cada uno. Pregunta cómo se dice cada una en las lenguas de la clase.": "Lau klik, hitz bat bakoitzak. Galdetu nola esaten den bakoitza gelako hizkuntzetan.",
"Aprendieron sus palabras": "Elkarren hitzak ikasi zituzten",
"<b>Hola</b>": "<b>Kaixo</b>",
"<b>Gracias</b>": "<b>Eskerrik asko</b>",
"<b>Amigo</b>": "<b>Laguna</b>",
"<b>Jugamos</b>": "<b>Jolastu dezagun</b>",
"Cada uno enseñó sus palabras a los demás.": "Bakoitzak bere hitzak irakatsi zizkien besteei.",
"Clic: Robo baila y la maga lo celebra.": "Klik: Robok dantza egiten du eta magoak ospatzen du.",
"Y desde ese día, los tres jugaron juntos cada tarde.": "Eta egun hartatik aurrera, hirurek elkarrekin jolastu zuten arratsalde guztietan.",
"¡Ahora hablamos con todos!": "Orain guztiekin hitz egiten dugu!",
"Nube de palabras: cada alumno escribe «hola» en su lengua desde el móvil.": "Hitz-hodeia: ikasle bakoitzak «kaixo» idazten du bere hizkuntzan mugikorretik.",
"¿Cómo se dice «hola» en tu idioma?": "Nola esaten da «kaixo» zure hizkuntzan?",
"Fin": "Amaiera",
"¿Qué otras palabras te gustaría enseñar?": "Zer beste hitz irakatsi nahiko zenituzke?",
"3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)": "3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)"
},
"nl": {
"Cuento: el robot que quería hablar con todos": "Verhaal: de robot die met iedereen wilde praten",
"Arriba a la derecha de la vista compartida, cada alumno elige su idioma.": "Rechtsboven in de gedeelde weergave kiest elke leerling zijn taal.",
"El robot que quería hablar con todos": "De robot die met iedereen wilde praten",
"Un cuento para leer en tu idioma": "Een verhaal om in je eigen taal te lezen",
"Robo, el robot": "Robo, de robot",
"Clic: Robo entra andando, saluda y dice hola.": "Klik: Robo loopt binnen, zwaait en zegt hallo.",
"Había una vez un robot llamado Robo. Le encantaba saludar a todo el mundo.": "Er was eens een robot die Robo heette. Hij zei graag iedereen gedag.",
"¡Hola! ¿Quieres jugar?": "Hoi! Wil je spelen?",
"La zorra llega andando… y no se entienden. Otro clic: Robo niega con la cabeza.": "De vos komt aanlopen… en ze begrijpen elkaar niet. Nog een klik: Robo schudt zijn hoofd.",
"Una zorra se acercó, pero no entendía a Robo: hablaba otra lengua.": "Er kwam een vos dichterbij, maar ze begreep Robo niet: ze sprak een andere taal.",
"La zorra": "De vos",
"La maga entra andando y lo celebra al llegar.": "De tovenares loopt binnen en juicht als ze aankomt.",
"Entonces llegó una maga sabia.": "Toen kwam er een wijze tovenares.",
"La maga": "De tovenares",
"Escuchar con atención es la primera lengua de todos.": "Goed luisteren is ieders eerste taal.",
"Cuatro clics, una palabra cada uno. Pregunta cómo se dice cada una en las lenguas de la clase.": "Vier klikken, één woord per klik. Vraag hoe elk woord heet in de talen van de klas.",
"Aprendieron sus palabras": "Ze leerden elkaars woorden",
"<b>Hola</b>": "<b>Hallo</b>",
"<b>Gracias</b>": "<b>Dank je</b>",
"<b>Amigo</b>": "<b>Vriend</b>",
"<b>Jugamos</b>": "<b>We spelen</b>",
"Cada uno enseñó sus palabras a los demás.": "Ieder leerde de anderen zijn eigen woorden.",
"Clic: Robo baila y la maga lo celebra.": "Klik: Robo danst en de tovenares juicht.",
"Y desde ese día, los tres jugaron juntos cada tarde.": "En vanaf die dag speelden ze met z’n drieën elke middag samen.",
"¡Ahora hablamos con todos!": "Nu praten we met iedereen!",
"Nube de palabras: cada alumno escribe «hola» en su lengua desde el móvil.": "Woordwolk: elke leerling schrijft „hallo” in zijn taal vanaf de telefoon.",
"¿Cómo se dice «hola» en tu idioma?": "Hoe zeg je „hallo” in jouw taal?",
"Fin": "Einde",
"¿Qué otras palabras te gustaría enseñar?": "Welke andere woorden zou je willen leren?",
"3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)": "3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)"
},
"ar": {
"Cuento: el robot que quería hablar con todos": "قصة: الروبوت الذي أراد أن يتحدث مع الجميع",
"Arriba a la derecha de la vista compartida, cada alumno elige su idioma.": "في أعلى يمين العرض المشترك، يختار كل طالب لغته.",
"El robot que quería hablar con todos": "الروبوت الذي أراد أن يتحدث مع الجميع",
"Un cuento para leer en tu idioma": "قصة تقرؤها بلغتك",
"Robo, el robot": "روبو، الروبوت",
"Clic: Robo entra andando, saluda y dice hola.": "نقرة: يدخل روبو ماشياً، يلوّح ويقول مرحباً.",
"Había una vez un robot llamado Robo. Le encantaba saludar a todo el mundo.": "كان يا ما كان روبوت اسمه روبو. كان يحب أن يحيّي الجميع.",
"¡Hola! ¿Quieres jugar?": "مرحباً! هل تريد أن تلعب؟",
"La zorra llega andando… y no se entienden. Otro clic: Robo niega con la cabeza.": "تصل الثعلبة ماشية… ولا يفهم أحدهما الآخر. نقرة أخرى: يهزّ روبو رأسه نافياً.",
"Una zorra se acercó, pero no entendía a Robo: hablaba otra lengua.": "اقتربت ثعلبة، لكنها لم تفهم روبو: كانت تتكلم لغة أخرى.",
"La zorra": "الثعلبة",
"La maga entra andando y lo celebra al llegar.": "تدخل الساحرة ماشية وتحتفل عند وصولها.",
"Entonces llegó una maga sabia.": "ثم وصلت ساحرة حكيمة.",
"La maga": "الساحرة",
"Escuchar con atención es la primera lengua de todos.": "الإصغاء بانتباه هو اللغة الأولى للجميع.",
"Cuatro clics, una palabra cada uno. Pregunta cómo se dice cada una en las lenguas de la clase.": "أربع نقرات، كلمة لكل نقرة. اسأل كيف تُقال كل كلمة بلغات الصف.",
"Aprendieron sus palabras": "تعلّموا كلمات بعضهم",
"<b>Hola</b>": "<b>مرحباً</b>",
"<b>Gracias</b>": "<b>شكراً</b>",
"<b>Amigo</b>": "<b>صديق</b>",
"<b>Jugamos</b>": "<b>لنلعب</b>",
"Cada uno enseñó sus palabras a los demás.": "علّم كلٌّ منهم كلماته للآخرين.",
"Clic: Robo baila y la maga lo celebra.": "نقرة: يرقص روبو وتحتفل الساحرة.",
"Y desde ese día, los tres jugaron juntos cada tarde.": "ومنذ ذلك اليوم، لعب الثلاثة معاً كل مساء.",
"¡Ahora hablamos con todos!": "الآن نتحدث مع الجميع!",
"Nube de palabras: cada alumno escribe «hola» en su lengua desde el móvil.": "سحابة كلمات: يكتب كل طالب «مرحباً» بلغته من هاتفه.",
"¿Cómo se dice «hola» en tu idioma?": "كيف تقول «مرحباً» بلغتك؟",
"Fin": "النهاية",
"¿Qué otras palabras te gustaría enseñar?": "ما الكلمات الأخرى التي تودّ أن تعلّمها؟",
"3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)": "3D: Robot — Tomás Laulhé (CC0) · Fox — PixelMannen (CC0), tomkranis (CC BY 4.0) · Mage — KayKit (CC0)"
}
}
};
