// Animated stickers: Google's Noto animated emoji (CC BY 4.0), served as GIF
// from fonts.gstatic.com. [code, words to search by (Spanish and English)].
export const STICKERS = [
  ['1f600', "sonrisa feliz smile happy"],
  ['1f603', "alegre contento joy"],
  ['1f602', "risa lágrimas laugh"],
  ['1f923', "partirse de risa rofl"],
  ['1f60a', "sonrojado blush"],
  ['1f607', "angelito angel"],
  ['1f970', "enamorado corazones love"],
  ['1f60d', "ojos corazón love heart"],
  ['1f929', "estrellas star struck"],
  ['1f618', "beso kiss"],
  ['1f60b', "delicioso yum"],
  ['1f61c', "guiño lengua wink"],
  ['1f92a', "loco crazy"],
  ['1f917', "abrazo hug"],
  ['1f914', "pensando thinking"],
  ['1f928', "sospecha raised eyebrow"],
  ['1f610', "neutral"],
  ['1f644', "ojos en blanco eye roll"],
  ['1f60f', "pícaro smirk"],
  ['1f62c', "mueca grimace"],
  ['1f60c', "aliviado relieved"],
  ['1f614', "pensativo pensive"],
  ['1f634', "dormido sleep"],
  ['1f637', "mascarilla mask"],
  ['1f912', "enfermo sick"],
  ['1f922', "náuseas nausea"],
  ['1f975', "calor hot"],
  ['1f976', "frío cold"],
  ['1f92f', "mente explota mind blown"],
  ['1f973', "fiesta party"],
  ['1f60e', "gafas guay cool"],
  ['1f913', "empollón nerd"],
  ['1f615', "confuso confused"],
  ['1f62e', "sorpresa surprise"],
  ['1f632', "asombro astonished"],
  ['1f633', "vergüenza flushed"],
  ['1f97a', "por favor pleading"],
  ['1f622', "triste llorar sad cry"],
  ['1f62d', "llanto sob"],
  ['1f631', "miedo grito scream"],
  ['1f621', "enfadado angry"],
  ['1f480', "calavera skull"],
  ['1f47b', "fantasma ghost"],
  ['1f47d', "extraterrestre alien"],
  ['1f916', "robot"],
  ['1f4a9', "caca poop"],
  ['1f44d', "pulgar arriba like thumbs up"],
  ['1f44e', "pulgar abajo dislike"],
  ['1f44f', "aplausos clap"],
  ['1f44b', "saludo hola wave"],
  ['1f64c', "manos arriba celebrar hands"],
  ['1f64f', "gracias por favor pray"],
  ['1f4aa', "fuerza músculo muscle"],
  ['270c_fe0f', "victoria paz peace"],
  ['1f91e', "suerte dedos cruzados luck"],
  ['1f440', "ojos mirar eyes"],
  ['2764_fe0f', "corazón heart love"],
  ['1f494', "corazón roto broken heart"],
  ['1f525', "fuego fire"],
  ['2728', "brillos sparkles"],
  ['1f389', "fiesta confeti party popper"],
  ['1f38a', "confeti confetti"],
  ['1f381', "regalo gift"],
  ['1f388', "globo balloon"],
  ['1f680', "cohete rocket"],
  ['1f4a1', "idea bombilla idea bulb"],
  ['1f4af', "cien 100"],
  ['2705', "correcto check"],
  ['274c', "error cruz cross"],
  ['26a1', "rayo energía lightning"],
  ['1f31f', "estrella star"],
  ['1f308', "arcoíris rainbow"],
  ['1f327_fe0f', "lluvia rain"],
  ['2744_fe0f', "nieve snow"],
  ['1f30d', "mundo tierra earth world"],
  ['1f431', "gato cat"],
  ['1f98a', "zorro fox"],
  ['1f984', "unicornio unicorn"],
  ['1f422', "tortuga turtle"],
  ['1f98b', "mariposa butterfly"],
  ['1f41d', "abeja bee"],
  ['1f340', "trébol clover"],
  ['1f355', "pizza"],
  ['1f37f', "palomitas popcorn"],
  ['2615', "café coffee"],
  ['1f382', "tarta cumpleaños cake birthday"],
  ['1f3c6', "trofeo ganador trophy"],
  ['26bd', "fútbol soccer"],
  ['1f4da', "libros books"],
  ['1f4c8', "gráfico sube chart up"],
  ['23f0', "despertador alarm clock"],
  ['231b', "reloj de arena hourglass"],
  ['1f6a8', "alarma sirena siren"],
  ['1f4a5', "explosión boom"],
  ['1f3af', "diana objetivo target"],
  ['1f9e0', "cerebro brain"],
  ['1f393', "graduación graduation"],
  ['1f4f8', "foto cámara camera"],
];
export const stickerURL = (code, size = 512) => `https://fonts.gstatic.com/s/e/notoemoji/latest/${code}/${size}.gif`;
export const STICKER_CREDIT = 'Noto Emoji animado — Google (CC BY 4.0)';
