// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Quarterly results for the board","Dark blue and gold: large animated KPIs with sound, waterfall, funnel, stacked bars and a table with formulas against budget"],
"biz_climate":["Workplace climate survey","Violet and interactive: countdown, 100 % bars, 1 to 5 rating, word cloud, multiple choice and audience questions"],
"biz_investment":["Investor pitch","Black and gold: a 3D product that spins and travels with Transform, giant figures, market in circles, traction, use of funds and team"],
"biz_marketing":["Campaign marketing plan","Warm style: text in a circle, target audience, funnel, channel mix, calendar table, budget with a formula and a poll"],
"biz_onboarding":["Welcome for new employees","Friendly style: a 3D robot that waves and walks through the week, org chart one by one, values with icons and a matching activity"],
"biz_proposal":["Sales proposal to a client","Paper style: seal, process one by one, mock-ups on a laptop and a phone, pricing, budget with VAT in formulas, timeline and guarantees"],
"biz_roadmap":["Project roadmap","Dark technical style: chevrons one by one, animated Gantt chart, timeline, a 3D car that moves forward with Transform and a status table"],
"biz_sales":["Sales and annual forecast","Minimalist grey: combined bars and lines, scenarios, forecast formula, table with formulas, stacked and horizontal bars"],
"biz_startup_agrotech":["Agritech pitch: sensor irrigation","Aerial view of plots with a moisture map, NASA 3D satellite, phone, chained drops with sound, table with formulas and treemap"],
"biz_startup_edtech":["Edtech pitch: maths tutor","Squared notebook: chained sticky notes, handwriting, step-by-step equations, phone, live quiz, cycle and charts"],
"biz_startup_energy":["Energy pitch: solar community","Rooftops from dawn to night: a sun that rises and crosses the sky along an arc, radial diagram, hourly areas, equation and table with formulas"],
"biz_startup_fashion":["Circular fashion pitch: Retal","Clothes tag that travels with Morph, dashed stitching, a garment’s life in a chain, cycle, doughnut, radar and multiple-choice poll"],
"biz_startup_insurance":["Insurance pitch: cover by the day","Grey rain and a yellow umbrella: chained pictogram, app with a switch, price equation, table with formulas, timeline and poll"],
"biz_startup_kitchen":["Kitchen robotics pitch: Fogón","Professional kitchen: tickets on the rail, fire Text Art, 3D robot that walks in and waves, recipe as code, countdown and funnel"],
"biz_startup_lastmile":["Logistics pitch: last mile","Metro map style: lines that draw themselves, 3D truck and bikes that travel the map, table with formulas, area and waterfall"],
"biz_startup_mental":["Mental health pitch: Remanso","Calm night: breathing rings, a one-minute breathing countdown, phone app, steps, rating and table with formulas"],
"biz_startup_pets":["Pet pitch: fresh food","Sticker style with paw prints that appear in a chain, 3D fox that walks across, portion formula in a table, doughnut and quiz"],
"biz_startup_rural":["Rural tourism pitch: Alpende","Mountains at dusk and postcards: 3D lantern, postmark with curved text, map with a 3D car along the route, bars, pie and word cloud"],
"biz_strategy":["Strategic plan and OKRs","Clean white style: figures that enter in sequence, pyramid, priorities with icons, OKR table, progress bars, radar and chevrons"],
"biz_swot":["SWOT and competitor analysis","Graphite background: SWOT in quadrants, strategy matrix, positioning map, grouped bars, Venn, pie chart and a multiple-choice poll"],
"creative_bauhaus":["Bauhaus: form and function","Bauhaus geometric art: primary shapes that spin and bounce, a timeline, a grid that morphs and a matching activity"],
"creative_brutalism":["Brutalism: a web manifesto","Brutalist style: giant type, black blocks, vertical text, hard shadows, animated strikethrough, table and poll"],
"creative_comic":["Comic: animal superpowers","Comic style: panels, speech and thought bubbles, bouncing Text Art sound effects, a 3D fox, a chart and a quiz"],
"creative_fashion":["Fashion magazine: slow autumn","Magazine style: serif masthead, a 3D watch on the cover, columns with a drop cap, a big quote, the season's palette and a chart"],
"creative_glass":["Glassmorphism: a finance app","See-through cards over coloured lights, the app on a phone, a doughnut chart, a card that morphs and a rating poll"],
"creative_pixel":["Pixel art: your first video game","Retro video game style: pixel sprites, a score bar, 3D characters that walk and jump, step-by-step code, a quiz and a countdown"],
"creative_space":["Galaxy: looking into the past","Space style: stars, glowing nebulae, NASA 3D models, a probe that tours the planets, curved text and a quiz"],
"creative_swiss_blood":["Campaign: give blood","Public poster in white and red: a drop that fills the screen with Morph, process, yes or wait, doughnut, bars, phone and quiz"],
"creative_swiss_chairs":["Exhibition: the modern chair","Swiss poster in grey and lime: a 3D chair that turns and travels with Morph, chained timeline, doughnut, 3D armchair, table with formulas and ordering"],
"creative_swiss_designconf":["Design conference: Grid 27","Graphite and cyan: the grid builds itself and changes with Morph, outline numeral, formula, timeline, CSS code, word cloud and break"],
"creative_swiss_film":["Film festival: the programme","Swiss in black and red: a giant number that becomes a band with Morph, sections on a grid, table, bars, poll and countdown"],
"creative_swiss_foundation":["A foundation's annual report","Swiss in white and cobalt blue: giant year, full-bleed letter, chained figures, equation, doughnut, area, chevrons and accounts with formulas"],
"creative_swiss_games":["School games: the visual identity","White and magenta, custom palette: SVG pictograms, a 3D figure crossing the city, lines, medal table with formulas, steps and quiz"],
"creative_swiss_museum":["Natural history museum guide","Swiss signage in black and yellow: a custom floor plan with an animated route, a walking 3D fox, columns, table, labelling and pictograms"],
"creative_swiss_orchestra":["Symphony orchestra: 26/27 season","Night blue and amber: turning arcs, curved text, figures on a stave, cycles, table, equation, bars, poll and applause"],
"creative_swiss_publisher":["A publisher's autumn catalogue","Cream paper and petrol green: a shelf of vertical spines, SVG covers, tablet, pie, order form with formulas, calendar and gaps"],
"creative_swiss_typeface":["Specimen of a new typeface","Specimen in white and violet: letters that travel with Morph, measured anatomy, scale with formula, glyphs, radar and licences"],
"creative_synthwave":["Synthwave: Neón 86 festival","Retro 80s style: gradient sun, a grid that draws itself, glowing neon, Morph, a dancing 3D robot and a word cloud"],
"creative_watercolor":["Watercolour: a balcony garden","Watercolour and paper style: radial gradient blots, hand-drawn shapes, handwriting, a drawing that traces itself and 3D"],
"creative_zen":["Japanese minimalism: tea","Japanese minimalism: lots of white, a red sun that morphs, vertical text, an ensō that paints itself and a countdown"],
"data_ab_test":["A/B experiment","Equations, two-series scatter, labelled columns, conversion table with formulas and significance figures"],
"data_energy":["Energy and consumption","Hourly stacked areas, three-series lines, treemap, labelled columns and calculated rate table"],
"data_exec_panel":["Monthly executive dashboard","KPIs with traffic lights and sparklines, combo chart against budget, small multiples, doughnut and poll"],
"data_home_finance":["Personal finances","Waterfall from salary to savings, pie chart, lines and area, tables with SUM, AVERAGE, MAX and MIN"],
"data_market_study":["Market study","Big figures, treemap, bubbles, scatter plot, two-series horizontal bars and 2 × 2 matrix"],
"data_population":["Population and demographics","Population pyramid, histogram, horizontal bars, crossing lines and indicator table with formulas"],
"data_sales_regions":["Sales by region","Grouped, stacked and 100 % bars, combo chart with target, table with formula totals and animated KPIs"],
"data_satisfaction":["Satisfaction survey","Doughnut with legend, compared radars, labelled columns, NPS, live rating and word cloud"],
"data_season_stats":["The season in numbers","Giant figures with sound, league table with formulas, negative bars, lines, stacked bars and team radar"],
"data_web_metrics":["Web and marketing metrics","KPIs with sparklines, four-series lines, areas, conversion funnel, combo chart and table with formulas"],
"edu_body":["The human body","Lab style: 3D figure with Morph, character walking along a path, bar chart, label the body and quiz"],
"edu_cell":["The cell","Cell drawn with shapes, parts one by one, Morph to zoom in, matching pairs, diagram, 3D plant and rating"],
"edu_english":["English for beginners","Classroom mode: flip cards with sound, 3D robot that walks and waves, 3D fox, three questions with points, leaderboard and applause"],
"edu_fractions":["Fractions","Neon style: drawn pizzas, step-by-step equations, addition with Morph, fill in the gaps, quiz and countdown challenge"],
"edu_hist_alandalus":["Al-Andalus: science and gardens","Horseshoe arch, timeline one by one, horizontal bars, a turning astrolabe, a star made with Morph, matching pairs and poll"],
"edu_hist_castle":["Castles and feudalism","A castle at night and a 3D knight crossing the bridge, a feudal pyramid that rises, labelling, a sun crossing the day, treemap and shields"],
"edu_hist_egypt":["Egypt, Gift of the Nile","Lapis lazuli and gold: sun rising behind the pyramids, animated flood, area chart, equation, Morph, hieroglyph cartouche and ordering"],
"edu_hist_greece":["Athens: democracy is born","Black-figure vase style: meander, curved text, Morph, doughnut, a temple that rises, ostraka with sound, poll and table"],
"edu_hist_maya":["The Maya: time and stars","Jungle and jade: dot-and-bar numbers, Morph into base 20, equation, turning calendar wheels, serpent of light and cacao"],
"edu_hist_mesopotamia":["Mesopotamia: writing is born","A clay tablet that writes itself, map with rivers drawn live, a growing ziggurat, base 60 with formulas, fill in the gaps and radial"],
"edu_hist_printing":["The printing press: books multiply","Incunabulum page: red initial letter, mirrored type composed with Morph, a press that comes down with sound, figures, bars and gaps"],
"edu_hist_rome":["Rome, engineers of the empire","Marble and imperial red: Morph, triumphal arch, a road in layers with a marching 3D soldier, aqueduct, equation, formulas and quiz"],
"edu_hist_silkroad":["The Silk Road","Silk and saffron: a moving caravan, map with a route drawn live, price waterfall, table with formulas, 3D lantern, equation and ordering"],
"edu_hist_vikings":["Vikings, seafarers of the north","Fjord under the aurora: a rocking ship, runes, myths struck out with a stamp, animated voyage, figures with sound, 3D warrior, radar and matching"],
"edu_math_coordinates":["Coordinates: the treasure map","Treasure map: compass rose with curved text, points that pop up, a 3D pirate following clues, a boat that draws itself and labelling"],
"edu_math_integers":["Integers: sea and mountain","From the sea bed to the summit: number line with jumps, ice Text Art, sub-zero temperatures, a submarine that rises and dives, ordering and quiz"],
"edu_math_primes":["Prime numbers","Green terminal: custom neon, sieve of Eratosthenes click by click with 100 cells, factor tree, step-by-step code, quiz and challenge"],
"edu_math_probability":["Probability: measuring luck","Burgundy and gold gaming table: dice rolling with a drumroll, curved text, Laplace's rule, tree one by one, bars, lines and quiz"],
"edu_math_proportion":["Proportionality at the supermarket","Shopping receipt: bouncing stamp, proportionality table with formulas, rule of three step by step, calculated discounts, lines and gaps"],
"edu_math_pythagoras":["The Pythagorean theorem","Chalkboard: a figure that draws itself, proof without words with Morph, triples with formulas, a 3D shortcut and a quiz"],
"edu_math_sequences":["Sequences and patterns","Botanical book: a Fibonacci spiral that draws itself, chained pebbles, matchsticks with formulas, code, 3D plant and the golden ratio"],
"edu_math_stats":["Statistics: mean, median and mode","Squared notebook: cascading sticky notes, frequencies with formulas, bars, doughnut with degrees, histogram and live poll"],
"edu_math_symmetry":["Symmetry and tilings","Nasrid tiles: a spinning star, a butterfly that mirrors itself, animated translation, rotation and reflection, angle table and honeycomb"],
"edu_math_volumes":["Areas and volumes","Blue technical drawing: title block as a table, flat net, measured 3D bottle, volumes with formulas, bars, filling cones and matching"],
"edu_quixote":["Don Quixote","Ink and paper style: windmill turning with sound, curved text, animated quotes, Morph, timeline, fill in the gaps and quiz"],
"edu_renewables":["Renewable energy","Spinning wind turbine, cards, area, doughnut and grouped bar charts, live word cloud, poll and countdown"],
"edu_revolution":["The French Revolution","Old paper style: text in a circle, Morph, social pyramid, animated timeline with sound, put events in order and poll"],
"edu_spain":["Geography of Spain","Atlas style: compass rose, relief as a target diagram, rivers table with formulas, peaks and rainfall charts, matching pairs and quiz"],
"edu_volcanoes":["Volcanoes","Fire style: animated eruption with sound, volcano parts to label, table, timed quiz and countdown"],
"edu_water":["The water cycle","Cycle diagram one by one, landscape with rising drops and animated rain with sound, doughnut charts, matching pairs and 3D satellite"],
"life_bookclub":["Book club","A hand-drawn bookshelf, a cover made of shapes, quotes that transform, a radial diagram, a rating and a vote on the next book"],
"life_cv":["Visual CV","Text in a circle, key figures, a step-by-step timeline, animated skill bars, a radar chart, screens in devices and contact details"],
"life_fitness":["Training plan: 5 km","A 3D runner, fire Text Art, phases with gradients, a week with formulas, progress charts, a pyramid, a countdown and a word cloud"],
"life_garden":["Urban vegetable garden","A 3D plant with Transform, a sowing calendar as a colour-coded table, cycle, Venn, watering and growth charts, a labelling activity"],
"life_graduation":["Graduation and end of year","Gold Text Art, mortarboards made of shapes, polaroids that flip in, figures with a drum roll, thanks, a word cloud and applause"],
"life_italy":["Trip around Italy","Text in a circle, a route with connectors and an animated path, timeline, budget with formulas, charts and a matching activity"],
"life_kids_party":["Children's birthday party","Bright colours: a dancing 3D robot, cheering characters, hand-drawn balloons, a points quiz and a countdown"],
"life_moving":["Moving house and new home","A hand-drawn house of shapes, timeline, a checklist that strikes out, 3D furniture that moves onto the floor plan with Transform, budget and an ordering activity"],
"life_recipe":["Recipe: guacamole","A 3D avocado that travels between slides (Transform), ingredients with formulas, steps one by one, a countdown and a rating"],
"life_travel_eu_amsterdam":["Amsterdam: canals and bikes","Canal house façades that build in sequence, canals as a target, bike crossing with sound, table with formulas, lines and pie poll"],
"life_travel_eu_camino":["Camino de Santiago: from Sarria","Credential filling with stamps with sound, kilometre waterfall, 3D walker, backpack equation, doughnut and ordering stages"],
"life_travel_eu_croatia":["Sailing Croatia’s Dalmatia","Nautical chart, compass rose that turns and travels with Morph, flags, matching, miles with formulas, quiz and countdown"],
"life_travel_eu_danube":["The Danube by bike","Cycling computer style: route on a phone, step-by-step GPX file, stacked bars, 3D bottle with Morph, formulas and treemap"],
"life_travel_eu_fjords":["Norwegian fjords by water","Layered landscape with reflections, sailing ship, fjord cross-section that draws itself, bars, radar, step-by-step route and multiple-choice poll"],
"life_travel_eu_greece":["Greek islands by ferry","White village of shapes, Greek key, route that draws itself, timetable with formulas, bubbles, 3D sunglasses with Morph and sunset"],
"life_travel_eu_iceland":["Iceland: the Ring Road by car","Gradient auroras, map with a sounding path, 3D car, figures with drumroll, wind-chill equation, walking fox and quiz"],
"life_travel_eu_lisbon":["Lisbon: hills and trams","SVG tiles, a tram climbing the hills along a path with sound, height profile, flipping cards, table with formulas and gaps"],
"life_travel_eu_prague":["Prague, city of a hundred spires","Astronomical clock made of shapes that turns and travels with Morph, parade with chime, countdown, map to label and table"],
"life_travel_eu_scotland":["Scotland: the Highlands by car","Tartan woven from shapes, road that draws itself, cars giving way, turning castles, 3D lantern, bars and audience questions"],
"life_wedding":["Wedding invitation","Classic type and gold: Text Art, curved text, the couple's timeline, a map with an animated route, a poll and a countdown"],
"prod_app_bank":["Cartilla: banking for older people","Leather and gold savings book: gold Text Art, Morph to zoom into the phone, table with SUM, waterfall, stamp and anti-fraud quiz"],
"prod_app_gym":["Serie: bookings at your gym","LED scoreboard: 3D fighter who cheers and walks to class, two countdowns, occupancy by hour, fares with formulas and quiz"],
"prod_app_health":["Turno: health centre appointments","Clinical: self-drawing heartbeat, before and after, cycle one by one, walking 3D patient, schedule on a monitor, bars and Q&A"],
"prod_app_language":["Vocablo: language learning app","Airmail postcard: stamps, speech bubbles that pop with sound, flipping cards, Morph, forgetting equation, chart and matching"],
"prod_app_market":["Plaza: the local market at home","Awning and chalkboards: 3D van that drives the map, stalls in a radial, phone, treemap, fees with formulas and poll"],
"prod_app_meditation":["Marea: meditation and sleep app","Night sea: moon with curved text, phone Morph, guided breathing with chained rings, countdown, chart and 3D lantern"],
"prod_app_music":["Garaje: local live music","Vinyl and neon: record that travels with Morph, spinning curved text, equaliser with drumroll, laptop, radar, pie and word cloud"],
"prod_app_photo":["Grano: film photography","Darkroom: film strip, photo that develops with Morph, counter with drumroll, histogram, tablet, table and labelling"],
"prod_app_recipes":["Sobras: recipes from what you have","Fridge with sticky notes: 3D avocado with Morph, phone that recognises ingredients, steps, doughnut, recipe with formulas and countdown"],
"prod_app_transit":["Andén: city transit","Metro signage: departures board with countdown, self-drawing map, animated trip, phone, stacked bars and fares"],
"product_app":["Mobile app presentation","App on phone, tablet and laptop, Morph, user journey as chevrons, key figures, retention chart and word cloud"],
"product_car":["Presentation: electric car","Uncropped 3D car that circles round on arrival, Morph, key figures, area and bar charts, table and vote"],
"product_eco":["Product sustainability","Eco green: 3D plant with Morph, life cycle, footprint waterfall, materials bar chart, lines with a target and fill in the gaps"],
"product_furniture":["Furniture collection","Editorial style: 3D sofas and chairs, Morph with different views, swing and orbit, colour swatches, tablet and budget"],
"product_keynote":["Hardware keynote","Premium white style: iridescent lamp and 3D bottle, Morph with labels, float and zoom in, key figures, table and prices"],
"product_roadmap":["Product roadmap","Self-drawing road, pyramid, timeline one by one, now and next, matrix, stacked bars, multiple-choice vote and ordering"],
"product_robot":["Industrial assistant robot","Industrial style: 3D robot that waves, walks a path, chains animations and dances; org chart, cycle, chart and quiz"],
"product_saas":["SaaS platform demo","Dashboard in a browser window with numbered call-outs, radial, funnel, KPIs, stacked bars, step-by-step code and Q&A"],
"product_security":["Product security","Green neon: layered target, flow with connectors appearing step by step, highlighted code, chart, steps and a matching activity"],
"product_watch":["Launch: smartwatch","Black and gold: a 3D watch travels across three slides with Morph and different arrivals, gold Text Art, radar and prices"],
"sci_ai":["Artificial intelligence","Violet neon: 3D robot that waves and travels with Morph, timeline, org chart, neural network that lights up, chart and word cloud"],
"sci_brain":["Neuroscience: the brain","Dark style with glows: drawn neuron with an animated impulse, walking 3D figure, radial diagram, org chart, bars and label a picture"],
"sci_chem":["Chemistry: the periodic table","Clean lab look: periodic table that builds itself in a cascade, molecules made of shapes, 3D brazier, equations, doughnut and matching"],
"sci_climate":["Climate change in data","Warming stripes, line, area and treemap charts, greenhouse effect that draws itself, 3D satellite, cycle and multiple-choice vote"],
"sci_mars":["Mission to Mars","Rusty space style: NASA 3D rover with Morph, floating astronaut, animated orbit, equation and quiz"],
"sci_med_case":["Clinical case: fever and cough","Medical record style: folder, stamp, X-ray on a light box with a circle that draws itself, CURB-65 with a formula, poll and questions"],
"sci_med_ecg":["Cardiology: reading an ECG","ECG paper: traces that draw themselves, an impulse travelling through the heart, table with formulas, equation, quiz and countdown"],
"sci_med_glucose":["Endocrinology: glucose and insulin","Glucose sensor app style: phone with the screen, cycle one by one, curves, doughnut, table with formulas, equation, 3D avocado and poll"],
"sci_med_immune":["Immunology: the immune response","Fluorescence microscope: cells that light up, a drawn antibody, phagocytosis with Morph, org chart and matching"],
"sci_med_kidney":["Renal physiology: the nephron","Blueprint: a nephron that draws itself, a drop travelling it with sound, dimensions, waterfall, equation, table with formulas, 3D bottle and cycle"],
"sci_med_knee":["Anatomy: the knee","Antique anatomical plate style: curved text, sepia engraving, Morph to the menisci, matrix, table, walking 3D figure and labelling"],
"sci_med_micro":["Microbiology: antibiotic resistance","Petri dishes: colonies that pop up with sound, exponential growth, selection told with Morph, antibiogram, radial diagram and word cloud"],
"sci_med_pk":["Pharmacokinetics: the half-life","Medicine box style: a blister that fills up, LADME one by one, two-series curves, equations, table with formulas, code and fill in the gaps"],
"sci_med_stroke":["Neurology: stroke code","Emergency race against the clock: siren lights, giant number with a drumroll, chained BE-FAST, doughnut, chevrons, ordering steps and countdown"],
"sci_med_trial":["Clinical trial: reading the results","Scientific journal style: CONSORT with connectors, survival curves, table with formulas, NNT, chained forest plot and quiz"],
"sci_newton":["Physics: Newton's laws","Physics notebook: equations, moving 3D car, projectile path that draws itself, table with formulas and fill in the gaps"],
"sci_python":["Programming in Python","Dark code-editor style: terminal that types itself, code with highlight steps, animated output, line ordering and a countdown challenge"],
"sci_solar":["The solar system","Planets to scale appearing in a chain, three 3D probes with different views and movements, table, radial diagram and matching"],
"sci_stats":["Statistics and probability","Editorial style: bell curve that draws itself, formulas, histogram, scatter, area, bar and bubble charts, and a scored question"],
"sci_thesis":["Bachelor's thesis defence","Sober academic look: institutional cover, contents, method with an equation, table with totals, results in charts, references and Q&A"],
"showcase_3d":["Catalogue: 3D in depth","3D models with all their options: views, moves on entry, spin, edges, margin, clips, walking and arrival with Morph"],
"showcase_animations":["Catalogue: animations","Every object animation: entrance, emphasis, exit, motion paths, draw, chained, sounds and several on one object"],
"showcase_charts":["Catalogue: charts","The 15 chart types, two per slide, with series, combo, grid, labels and axis titles, plus the table of options"],
"showcase_diagrams":["Catalogue: diagrams","The 15 diagram layouts written as an outline, the 4 colour schemes and appearing one by one when presenting"],
"showcase_morph":["Catalogue: Morph","Morph step by step: text that changes size and place, shapes, growing bars, a picture, 3D and letters that rearrange"],
"showcase_objects":["Catalogue: media and objects","Code with steps, equations, icons, five devices, tables with styles and formulas, slide zoom and connectors"],
"showcase_polls":["Catalogue: polls and activities","The 11 kinds of poll and activity from phones, the countdown in its three styles, leaderboard and classroom mode"],
"showcase_shapes":["Catalogue: shapes","Every shape by category with its name, lines and dashes, gradients, opacity, hand-drawn look, shadows, text inside and rotation"],
"showcase_text":["Catalogue: Text Art and typography","The 10 Text Art styles, curved text, columns, five bullet levels, the 8 font pairs, alignment and spacing"],
"showcase_transitions":["Catalogue: transitions","All 22 slide transitions, one by one: entrance, a different exit, directions, speed and auto-advance"]};
