// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Quarterly results for the board","Dark blue and gold: large animated KPIs with sound, waterfall, funnel, stacked bars and a table with formulas against budget"],
"biz_climate":["Workplace climate survey","Violet and interactive: countdown, 100 % bars, 1 to 5 rating, word cloud, multiple choice and audience questions"],
"biz_investment":["Investor pitch","Black and gold: a 3D product that spins and travels with Transform, giant figures, market in circles, traction, use of funds and team"],
"biz_marketing":["Campaign marketing plan","Warm style: text in a circle, target audience, funnel, channel mix, calendar table, budget with a formula and a poll"],
"biz_onboarding":["Welcome for new employees","Friendly style: a 3D robot that waves and walks through the week, org chart one by one, values with icons and a matching activity"],
"biz_proposal":["Sales proposal to a client","Paper style: seal, process one by one, mock-ups on a laptop and a phone, pricing, budget with VAT in formulas, timeline and guarantees"],
"biz_retail_basket":["Basket analysis: what a receipt tells","A till receipt that prints itself, average ticket equation, waterfall, scatter plot, product network, table, SQL query, doughnut and quiz"],
"biz_retail_blackfriday":["Black Friday campaign","Black and neon: price tags, figures with sound, struck-through prices, hourly lines, funnel, table with formulas, quiz and countdown"],
"biz_retail_cx":["Customer experience: Marta's journey","Drawn persona, an emotion curve that draws itself with chained faces, quotes, NPS with an equation, matrix, Morph and rating"],
"biz_retail_inventory":["Stock: no shortages, no excess","Drawn warehouse with racks and labels, comparison, Pareto as a combo chart, equation, table with formulas, code, 3D lamp and ordering"],
"biz_retail_loyalty":["Loyalty: the bakery club","A stamp card that fills up in a chain with sound and applause, customer value equation, pyramid of tiers, table with formulas and app"],
"biz_retail_market":["Municipal market: a plan to revive it","Iron façade with a curved name, chalk boards in a chain, treemap, hourly areas, seasonal calendar in a table, 3D avocado and word cloud"],
"biz_retail_omni":["Omnichannel: buy online, pick up in store","A drawn app in a phone and website in a browser, a route that draws itself, a 3D van driving down the street, table with a formula, code and 100 % stacked bars"],
"biz_retail_opening":["Opening a bookshop café","Drawn shopfront with an awning, neighbourhood map with chained points, Venn, 3D armchair, timeline, table with formulas and countdown"],
"biz_retail_supermarket":["Supermarket: a new layout","Floor plan made of shapes, a trolley that tours the shop, heat map, sections that move with Morph, shelf display and table"],
"biz_retail_window":["Window dressing: the autumn window","Editorial in black and ivory: 3D sunglasses with Morph, text in a circle, colour swatches, a drawn shop window with a triangle and focal points"],
"biz_roadmap":["Project roadmap","Dark technical style: chevrons one by one, animated Gantt chart, timeline, a 3D car that moves forward with Transform and a status table"],
"biz_sales":["Sales and annual forecast","Minimalist grey: combined bars and lines, scenarios, forecast formula, table with formulas, stacked and horizontal bars"],
"biz_startup_agrotech":["Agritech pitch: sensor irrigation","Aerial view of plots with a moisture map, NASA 3D satellite, phone, chained drops with sound, table with formulas and treemap"],
"biz_startup_edtech":["Edtech pitch: maths tutor","Squared notebook: chained sticky notes, handwriting, step-by-step equations, phone, live quiz, cycle and charts"],
"biz_startup_energy":["Energy pitch: solar community","Rooftops from dawn to night: a sun that rises and crosses the sky along an arc, radial diagram, hourly areas, equation and table with formulas"],
"biz_startup_fashion":["Circular fashion pitch: Retal","Clothes tag that travels with Morph, dashed stitching, a garment’s life in a chain, cycle, doughnut, radar and multiple-choice poll"],
"biz_startup_insurance":["Insurance pitch: cover by the day","Grey rain and a yellow umbrella: chained pictogram, app with a switch, price equation, table with formulas, timeline and poll"],
"biz_startup_kitchen":["Kitchen robotics pitch: Fogón","Professional kitchen: tickets on the rail, fire Text Art, 3D robot that walks in and waves, recipe as code, countdown and funnel"],
"biz_startup_lastmile":["Logistics pitch: last mile","Metro map style: lines that draw themselves, 3D truck and bikes that travel the map, table with formulas, area and waterfall"],
"biz_startup_mental":["Mental health pitch: Remanso","Calm night: breathing rings, a one-minute breathing countdown, phone app, steps, rating and table with formulas"],
"biz_startup_pets":["Pet pitch: fresh food","Sticker style with paw prints that appear in a chain, 3D fox that walks across, portion formula in a table, doughnut and quiz"],
"biz_startup_rural":["Rural tourism pitch: Alpende","Mountains at dusk and postcards: 3D lantern, postmark with curved text, map with a 3D car along the route, bars, pie and word cloud"],
"biz_strategy":["Strategic plan and OKRs","Clean white style: figures that enter in sequence, pyramid, priorities with icons, OKR table, progress bars, radar and chevrons"],
"biz_swot":["SWOT and competitor analysis","Graphite background: SWOT in quadrants, strategy matrix, positioning map, grouped bars, Venn, pie chart and a multiple-choice poll"],
"creative_bauhaus":["Bauhaus: form and function","Bauhaus geometric art: primary shapes that spin and bounce, a timeline, a grid that morphs and a matching activity"],
"creative_brutalism":["Brutalism: a web manifesto","Brutalist style: giant type, black blocks, vertical text, hard shadows, animated strikethrough, table and poll"],
"creative_comic":["Comic: animal superpowers","Comic style: panels, speech and thought bubbles, bouncing Text Art sound effects, a 3D fox, a chart and a quiz"],
"creative_fashion":["Fashion magazine: slow autumn","Magazine style: serif masthead, a 3D watch on the cover, columns with a drop cap, a big quote, the season's palette and a chart"],
"creative_glass":["Glassmorphism: a finance app","See-through cards over coloured lights, the app on a phone, a doughnut chart, a card that morphs and a rating poll"],
"creative_pixel":["Pixel art: your first video game","Retro video game style: pixel sprites, a score bar, 3D characters that walk and jump, step-by-step code, a quiz and a countdown"],
"creative_retro_atomic":["Retrofuturism: the future of 1962","Atomic age: a morphing saucer house, chained hits and misses, walking 3D robot, radar, matrix, countdown and word cloud"],
"creative_retro_deco":["Art deco: the Grand Hotel turns 100","Art deco in gold and black: a morphing fan, golden Text Art, a lift as a timeline, 3D sofa, table with formulas and quiz"],
"creative_retro_desktop90":["The 90s: backups","90s desktop: grey windows, cascading errors, progress bar, equation, table with formulas, step-by-step code and quiz"],
"creative_retro_diner":["The 50s: the diner reopens","50s diner: neon sign, checkerboard floor, awning, 3D truck along the road, menu with formulas, doughnut, spinning seal and poll"],
"creative_retro_letterpress":["Letterpress poster: the neighbourhood festival","Wood type poster: misregistered ink, letters that drop with sound, programme, stacked bars, waterfall, proclamation, poll and countdown"],
"creative_retro_sepia":["Sepia album: find your grandparents","Sepia album: photo corners, handwriting, ancestors equation, a growing tree, map with a drawn journey, pie, matching and Morph"],
"creative_retro_teletext":["Teletext: the neighbourhood league","Teletext pages: lines that load by themselves, scoreboard and standings with formulas, bars, columns, quiz and countdown"],
"creative_retro_typewriter":["Typewriter: a short story workshop","Paper and typewriter: lines typed with sound, strike-through and handwritten correction, an arc that draws itself, bars, gaps and countdown"],
"creative_retro_vapor":["Vaporwave: the music in shops","Pastel vaporwave: a morphing moon, SVG palm trees, glitch titles, scatter, 3D lamp, table with average and rating"],
"creative_retro_vinyl":["The 70s: the vinyl club","Seventies style: striped rainbows, drawn records that spin, giant figure, lines, bars, 3D sofa, ordering activity and sticker"],
"creative_space":["Galaxy: looking into the past","Space style: stars, glowing nebulae, NASA 3D models, a probe that tours the planets, curved text and a quiz"],
"creative_swiss_blood":["Campaign: give blood","Public poster in white and red: a drop that fills the screen with Morph, process, yes or wait, doughnut, bars, phone and quiz"],
"creative_swiss_chairs":["Exhibition: the modern chair","Swiss poster in grey and lime: a 3D chair that turns and travels with Morph, chained timeline, doughnut, 3D armchair, table with formulas and ordering"],
"creative_swiss_designconf":["Design conference: Grid 27","Graphite and cyan: the grid builds itself and changes with Morph, outline numeral, formula, timeline, CSS code, word cloud and break"],
"creative_swiss_film":["Film festival: the programme","Swiss in black and red: a giant number that becomes a band with Morph, sections on a grid, table, bars, poll and countdown"],
"creative_swiss_foundation":["A foundation's annual report","Swiss in white and cobalt blue: giant year, full-bleed letter, chained figures, equation, doughnut, area, chevrons and accounts with formulas"],
"creative_swiss_games":["School games: the visual identity","White and magenta, custom palette: SVG pictograms, a 3D figure crossing the city, lines, medal table with formulas, steps and quiz"],
"creative_swiss_museum":["Natural history museum guide","Swiss signage in black and yellow: a custom floor plan with an animated route, a walking 3D fox, columns, table, labelling and pictograms"],
"creative_swiss_orchestra":["Symphony orchestra: 26/27 season","Night blue and amber: turning arcs, curved text, figures on a stave, cycles, table, equation, bars, poll and applause"],
"creative_swiss_publisher":["A publisher's autumn catalogue","Cream paper and petrol green: a shelf of vertical spines, SVG covers, tablet, pie, order form with formulas, calendar and gaps"],
"creative_swiss_typeface":["Specimen of a new typeface","Specimen in white and violet: letters that travel with Morph, measured anatomy, scale with formula, glyphs, radar and licences"],
"creative_synthwave":["Synthwave: Neón 86 festival","Retro 80s style: gradient sun, a grid that draws itself, glowing neon, Morph, a dancing 3D robot and a word cloud"],
"creative_watercolor":["Watercolour: a balcony garden","Watercolour and paper style: radial gradient blots, hand-drawn shapes, handwriting, a drawing that traces itself and 3D"],
"creative_zen":["Japanese minimalism: tea","Japanese minimalism: lots of white, a red sun that morphs, vertical text, an ensō that paints itself and a countdown"],
"data_ab_test":["A/B experiment","Equations, two-series scatter, labelled columns, conversion table with formulas and significance figures"],
"data_city_air":["Air quality in Brisamar","A sky that clears with Morph, a needle gauge, equation, lines with gaps, radar, table with formulas and a rating"],
"data_city_bikes":["Pedalia: a year of bike sharing","Metro-style map, a bike that rides a line, figures with sound, lines, stacked bars, app on a phone, table and code"],
"data_city_budget":["Participatory budget","Civic poster: ballot box with falling ballots, doughnut, chevrons, combo chart, results with a drumroll, table with formulas"],
"data_city_housing":["Housing: the price of staying","Architect's drawing: SVG floor plan, areas to scale, combo chart, equation, table with formulas, scatter and a 3D sofa"],
"data_city_noise":["The noise of Sotoverde","A wave that rises by itself, decibel ruler with sounds, equation, noise map, stacked bars, quiz and countdown"],
"data_city_tourism":["Tourism on Isla Marena","Travel poster: sun with curved text, pictogram, area chart, treemap, 100 % bars, 3D walker, table and postcard"],
"data_city_traffic":["Rush-hour traffic","Night control room: map with traced jams, a traffic light that lights up, heat table, Webster's formula, code and a 3D truck"],
"data_city_trees":["Urban tree inventory","Herbarium sheet: drawn tree, 3D plant with Morph, treemap, histogram, equation, table and matching"],
"data_city_waste":["What we throw away in Villa Cardo","Bins that bounce with sound, giant figure, waterfall, stacked bars, colour-coded pie, funnel, matching and table"],
"data_city_water":["The water of Fuentelinda","A reservoir that empties with Morph, lines, doughnut, bars, tariff with equation and formulas, shower countdown"],
"data_energy":["Energy and consumption","Hourly stacked areas, three-series lines, treemap, labelled columns and calculated rate table"],
"data_exec_panel":["Monthly executive dashboard","KPIs with traffic lights and sparklines, combo chart against budget, small multiples, doughnut and poll"],
"data_home_finance":["Personal finances","Waterfall from salary to savings, pie chart, lines and area, tables with SUM, AVERAGE, MAX and MIN"],
"data_market_study":["Market study","Big figures, treemap, bubbles, scatter plot, two-series horizontal bars and 2 × 2 matrix"],
"data_population":["Population and demographics","Population pyramid, histogram, horizontal bars, crossing lines and indicator table with formulas"],
"data_sales_regions":["Sales by region","Grouped, stacked and 100 % bars, combo chart with target, table with formula totals and animated KPIs"],
"data_satisfaction":["Satisfaction survey","Doughnut with legend, compared radars, labelled columns, NPS, live rating and word cloud"],
"data_season_stats":["The season in numbers","Giant figures with sound, league table with formulas, negative bars, lines, stacked bars and team radar"],
"data_web_metrics":["Web and marketing metrics","KPIs with sparklines, four-series lines, areas, conversion funnel, combo chart and table with formulas"],
"edu_bio_digestion":["A sandwich's journey","Metro map: line D draws itself, a sandwich rides it, departures board as a table, enzymes, bars, ordering stops and Text Art"],
"edu_bio_dna":["DNA, the recipe for life","Neon lab: a helix that builds itself, Text Art, bases that pair up, step-by-step Python code, bars, a mutation and matching pairs"],
"edu_bio_ecosystem":["The forest: who eats whom","Kraft-paper field notebook: walking 3D fox, food chain, a web that draws itself, pyramid and 10 % table, lines and labelling"],
"edu_bio_evolution":["Adaptation: the finches' beaks","Night nautical chart: a ship sailing a route, drawn beaks, drought bars, scatter, cycle, Transform of the beak and quiz"],
"edu_bio_heart":["The heart, a tireless pump","Red and blue: a drawn heartbeat, giant figures, traced circuits, a drop through the heart, pulse with countdown and formulas, 3D and quiz"],
"edu_bio_mendel":["Mendel and the peas","Garden notebook: peas that pop up, generations with Transform, Punnett square, bars and doughnut, timeline and quiz"],
"edu_bio_microbes":["Microbes: the invisible world","Microscope eyepiece: curved text, Transform from 40 to 400 times, shapes of bacteria, yeast in lines, a poll and Text Art"],
"edu_bio_photosynthesis":["Photosynthesis: the green factory","Leaf in the sun: 3D plant, animated inputs and outputs, Transform into the chloroplast, equation, table with averages, countdown, lines and gaps"],
"edu_bio_pollination":["From flower to fruit","Spring meadow: a flying bee, parts of the flower, labelling, treemap, Transform from flower to fruit, 3D avocado, timeline and word cloud"],
"edu_bio_respiration":["Breathing: the journey of air","Open sky: breathing lungs, the path of air, Transform breathing in and out, two doughnuts, 3D bottle, countdown and quiz"],
"edu_body":["The human body","Lab style: 3D figure with Morph, character walking along a path, bar chart, label the body and quiz"],
"edu_cell":["The cell","Cell drawn with shapes, parts one by one, Morph to zoom in, matching pairs, diagram, 3D plant and rating"],
"edu_english":["English for beginners","Classroom mode: flip cards with sound, 3D robot that walks and waves, 3D fox, three questions with points, leaderboard and applause"],
"edu_fractions":["Fractions","Neon style: drawn pizzas, step-by-step equations, addition with Morph, fill in the gaps, quiz and countdown challenge"],
"edu_geo_cities":["The city: how it grows","A city at night from above: neon Text Art, area chart, drawn street plans, rings with Transform, radial diagram and a 3D car"],
"edu_geo_climograph":["Reading a climograph","Weather station: a rising thermometer, bars with a line, table with formulas, equations, 3D satellite, matching and a countdown challenge"],
"edu_geo_coasts":["Coasts and tides","Lighthouse with a turning beam, coastal shapes one by one, an eroding cliff, tides in a chart and a table with formulas, labelling"],
"edu_geo_continents":["Continents and oceans","Children's atlas: continents that pop in with a sound, treemap, ocean doughnut, a 3D robot crossing the world, matching and labelling"],
"edu_geo_deserts":["Deserts","Dunes at sunset: a moving caravan, gold Text Art, bar and line charts, 3D fox, a drawn oasis, myths struck out and a quiz"],
"edu_geo_mountains":["Mountains","Alpine poster: landform parts one by one, temperature equation and table, vegetation belts as a pyramid, a climbing 3D hiker and ordering"],
"edu_geo_pyramids":["Population pyramids","Census poster: a pyramid built bar by bar, three shapes with Transform, line chart, equations, ordering and a quiz"],
"edu_geo_river":["The journey of a river","Watercolour: a river drawn as a drop runs along it, zoom with Transform, flow with an equation, table with formulas and labelling"],
"edu_geo_timezones":["Time zones","Airport departures board with flipping rows, rotating Earth with an equation, the Sun crossing the zones, table with formulas, 3D watch and gaps"],
"edu_geo_topomap":["Reading a topographic map","Orienteering map: a course that draws itself, scale with an equation, table with formulas, contour lines with Transform and a 3D runner"],
"edu_hist_alandalus":["Al-Andalus: science and gardens","Horseshoe arch, timeline one by one, horizontal bars, a turning astrolabe, a star made with Morph, matching pairs and poll"],
"edu_hist_castle":["Castles and feudalism","A castle at night and a 3D knight crossing the bridge, a feudal pyramid that rises, labelling, a sun crossing the day, treemap and shields"],
"edu_hist_egypt":["Egypt, Gift of the Nile","Lapis lazuli and gold: sun rising behind the pyramids, animated flood, area chart, equation, Morph, hieroglyph cartouche and ordering"],
"edu_hist_greece":["Athens: democracy is born","Black-figure vase style: meander, curved text, Morph, doughnut, a temple that rises, ostraka with sound, poll and table"],
"edu_hist_maya":["The Maya: time and stars","Jungle and jade: dot-and-bar numbers, Morph into base 20, equation, turning calendar wheels, serpent of light and cacao"],
"edu_hist_mesopotamia":["Mesopotamia: writing is born","A clay tablet that writes itself, map with rivers drawn live, a growing ziggurat, base 60 with formulas, fill in the gaps and radial"],
"edu_hist_printing":["The printing press: books multiply","Incunabulum page: red initial letter, mirrored type composed with Morph, a press that comes down with sound, figures, bars and gaps"],
"edu_hist_rome":["Rome, engineers of the empire","Marble and imperial red: Morph, triumphal arch, a road in layers with a marching 3D soldier, aqueduct, equation, formulas and quiz"],
"edu_hist_silkroad":["The Silk Road","Silk and saffron: a moving caravan, map with a route drawn live, price waterfall, table with formulas, 3D lantern, equation and ordering"],
"edu_hist_vikings":["Vikings, seafarers of the north","Fjord under the aurora: a rocking ship, runes, myths struck out with a stamp, animated voyage, figures with sound, 3D warrior, radar and matching"],
"edu_kids_colors":["Colours","Painting table: a rainbow that draws itself, paint pots with sound, mixes with Morph, icons, matching, a poll and a countdown"],
"edu_kids_emotions":["How do I feel?","A drawn face that changes emotion with Morph, a garland of faces, a balloon to breathe with, a poll and matching"],
"edu_kids_farm":["Farm animals","A drawn farm with its own animals, lines that draw themselves, a table that adds up, a moving 3D truck, a walking 3D fox, a quiz and labelling"],
"edu_kids_numbers":["The number train","A drawn train that rolls in with sound, counting one by one, hidden numbers, a sum as an equation, a chart, ordering, a quiz and a countdown"],
"edu_kids_sea":["Under the sea","A sea bed in a gradient, drawn fish that swim, bubbles, big and small, a 3D bottle into the bin, matching and a word cloud"],
"edu_kids_seasons":["The four seasons","A tree that changes with Morph through four seasons, falling leaves and snow, a wheel of the year, a cycle, matching and a poll"],
"edu_kids_senses":["The five senses","Cut-out cardboard: a drawn face, a radial diagram, riddles, buttons with five sounds, cards that flip, labelling and a countdown"],
"edu_kids_shapes":["Shapes and blocks","Play rug: blocks with sound, shapes that draw themselves, a house that turns into a robot with Morph, a 3D robot and a pyramid"],
"edu_kids_space":["Trip to the Moon","Night sky: a rocket that takes off with sound, a countdown, the Moon going round the Earth, phases, a 3D astronaut and lunar module"],
"edu_kids_transport":["How do we travel?","Road playmat: a 3D toy car, vehicles that cross with sound, a changing traffic light, a chart, a 3D car, matching and a poll"],
"edu_lang2_advent":["German: Advent and Christmas","Snowy night: golden Text Art, 3D lantern, falling snowflakes, an Advent calendar that opens, timeline, labelling and a recipe with formulas"],
"edu_lang2_artikel":["German: der, die, das","Bauhaus poster: shapes that come in with sound, endings in a table, doughnut, Transform into the accusative, matching and quiz"],
"edu_lang2_cafe":["French: au café","Bistro blackboard under the awning: curved text, the bill worked out with table formulas, a price equation, dialogue, bars and gap filling"],
"edu_lang2_directions":["English: how do I get to…?","Made-up underground map: a train rides the route with a motion path, sentences along the way, dialogue, drawn street, ordering, quiz and countdown"],
"edu_lang2_falsefriends":["False friends in English","Detective's file: stamp with sound, 3D sunglasses, suspects that flip over, evidence table, bars, strike-throughs and a poll"],
"edu_lang2_ola":["Portuguese: Olá, Lisboa!","Tiles and a yellow tram that climbs the hill on a motion path, greetings that flip, table of sounds, a chat on a phone and a treemap"],
"edu_lang2_passato":["Italian: il passato prossimo","Riviera postcard: a 3D car drives along the coast on a motion path, equation, participles in a table, agreement, gap filling and quiz"],
"edu_lang2_phrasal":["Phrasal verbs: level up","Neon arcade: Text Art, Transform that joins verb and particle, a 3D knight who moves forward, bars, strike-through, matching and countdown"],
"edu_lang2_sons":["French: the sounds","Spinning vinyl with curved text, tracks with sound, liaisons drawn as arcs, table of rules, radar, quiz and countdown"],
"edu_lang2_tenses":["Present perfect or past simple","Watchmaker's: 3D watch with Transform, a timeline with an arc that draws itself, equations, table, 100% bars, tree and countdown"],
"edu_lang_accent":["Accent marks without fear","Squared exercise book and red pen: syllables that sound as they light up, table, decision tree, animated crossings-out, sticky notes and quiz"],
"edu_lang_becquer":["Bécquer and the Rimas","Romantic night: swallows crossing the moon, curved text, verses that appear by themselves, 3D lantern, timeline, metre in a table and gap fill"],
"edu_lang_calderon":["Life Is a Dream","Curtain that opens and closes with sound, playhouse plan, 3D throne with Morph, monologue line by line, radial, scales and quiz"],
"edu_lang_commentary":["How to analyse a text","Page with highlighters that draw themselves and margin notes, chevrons one by one, timeline, equation, countdown, rubric and radar"],
"edu_lang_fables":["Fables: the fox and the grapes","Storybook: a 3D fox that walks in, curved title, timeline, drawn vine, steps, table, ordering and word cloud"],
"edu_lang_figures":["Figures of speech in comics","Pop comic: panels, speech bubbles and bursts with sound, a 3D watch flying along a path, verses that change colour and quiz"],
"edu_lang_genres":["Literary genres","Library at night: books that rise onto the shelf, index cards stamped with sound, Venn, hierarchy, doughnut, poll, matching and 3D armchair"],
"edu_lang_lazarillo":["Lazarillo de Tormes","Parchment and sealing wax: a 3D rogue walking the map from master to master, cards, table of masters, hunger line, quiz and ordering"],
"edu_lang_meter":["The music of verse: metre","Sound studio: a wave that draws itself, syllables that tick like a metronome, equation with cases, synalepha, sonnet as tracks and quiz"],
"edu_lang_syntax":["Subject and predicate, as a blueprint","Technical blueprint: pieces that fall into place with Morph, brackets that draw themselves, syntax tree, table, label the image and quiz"],
"edu_math_coordinates":["Coordinates: the treasure map","Treasure map: compass rose with curved text, points that pop up, a 3D pirate following clues, a boat that draws itself and labelling"],
"edu_math_integers":["Integers: sea and mountain","From the sea bed to the summit: number line with jumps, ice Text Art, sub-zero temperatures, a submarine that rises and dives, ordering and quiz"],
"edu_math_primes":["Prime numbers","Green terminal: custom neon, sieve of Eratosthenes click by click with 100 cells, factor tree, step-by-step code, quiz and challenge"],
"edu_math_probability":["Probability: measuring luck","Burgundy and gold gaming table: dice rolling with a drumroll, curved text, Laplace's rule, tree one by one, bars, lines and quiz"],
"edu_math_proportion":["Proportionality at the supermarket","Shopping receipt: bouncing stamp, proportionality table with formulas, rule of three step by step, calculated discounts, lines and gaps"],
"edu_math_pythagoras":["The Pythagorean theorem","Chalkboard: a figure that draws itself, proof without words with Morph, triples with formulas, a 3D shortcut and a quiz"],
"edu_math_sequences":["Sequences and patterns","Botanical book: a Fibonacci spiral that draws itself, chained pebbles, matchsticks with formulas, code, 3D plant and the golden ratio"],
"edu_math_stats":["Statistics: mean, median and mode","Squared notebook: cascading sticky notes, frequencies with formulas, bars, doughnut with degrees, histogram and live poll"],
"edu_math_symmetry":["Symmetry and tilings","Nasrid tiles: a spinning star, a butterfly that mirrors itself, animated translation, rotation and reflection, angle table and honeycomb"],
"edu_math_volumes":["Areas and volumes","Blue technical drawing: title block as a table, flat net, measured 3D bottle, volumes with formulas, bars, filling cones and matching"],
"edu_pe_active":["60 minutes a day","Cork board: pinned notes, a 3D character that jumps, week with formulas, stacked bars, doughnut, code and idea wall"],
"edu_pe_athletics":["Athletics: run, jump, throw","Tartan track: 3D character, pictograms that flip, lanes equation and table, start with sounds, histogram, ordering and podium"],
"edu_pe_basketball":["Basketball: shot and lay-up","Coach's board: a ball that bounces with sound, dimensioned court, traced parabola, drawn play, table with formulas and labelling"],
"edu_pe_calm":["Cool-down: stretch and breathe","Calm dawn: 3D plant, box breathing with a motion path, a circle that grows and shrinks, stretches, target and word cloud"],
"edu_pe_heart":["The heart in motion","Heart monitor: an ECG that draws itself, pulse countdown, equation, zones with formulas, area chart, phone with app and quiz"],
"edu_pe_hydration":["Drink before you are thirsty","Water and bubbles: 3D bottle, a body that fills up, sweat bars, a glass with Morph, colour scale and fill in the gaps"],
"edu_pe_nutrition":["The athlete's plate","Gingham tablecloth: a plate served part by part, doughnut, 3D avocado, breakfasts with formulas, myths that flip, matching and word cloud"],
"edu_pe_posture":["A back for life","Sepia plate: a spine vertebra by vertebra, chained labels, backpack with formulas, wrong and right, 3D chair, countdown and labelling"],
"edu_pe_sleep":["Sleeping is training too","Night window: stars that light up, 3D lamp, hypnogram, cycle, radial, phone with messages, chained routine and rating"],
"edu_pe_warmup":["Warming up before playing","Sports hall parquet: a 3D robot that runs, temperature line, chevrons, joints with sound, countdown, ordering and quiz"],
"edu_quixote":["Don Quixote","Ink and paper style: windmill turning with sound, curved text, animated quotes, Morph, timeline, fill in the gaps and quiz"],
"edu_renewables":["Renewable energy","Spinning wind turbine, cards, area, doughnut and grouped bar charts, live word cloud, poll and countdown"],
"edu_revolution":["The French Revolution","Old paper style: text in a circle, Morph, social pyramid, animated timeline with sound, put events in order and poll"],
"edu_spain":["Geography of Spain","Atlas style: compass rose, relief as a target diagram, rivers table with formulas, peaks and rainfall charts, matching pairs and quiz"],
"edu_volcanoes":["Volcanoes","Fire style: animated eruption with sound, volcano parts to label, table, timed quiz and countdown"],
"edu_water":["The water cycle","Cycle diagram one by one, landscape with rising drops and animated rain with sound, doughnut charts, matching pairs and 3D satellite"],
"life_bookclub":["Book club","A hand-drawn bookshelf, a cover made of shapes, quotes that transform, a radial diagram, a rating and a vote on the next book"],
"life_cv":["Visual CV","Text in a circle, key figures, a step-by-step timeline, animated skill bars, a radar chart, screens in devices and contact details"],
"life_fitness":["Training plan: 5 km","A 3D runner, fire Text Art, phases with gradients, a week with formulas, progress charts, a pyramid, a countdown and a word cloud"],
"life_garden":["Urban vegetable garden","A 3D plant with Transform, a sowing calendar as a colour-coded table, cycle, Venn, watering and growth charts, a labelling activity"],
"life_graduation":["Graduation and end of year","Gold Text Art, mortarboards made of shapes, polaroids that flip in, figures with a drum roll, thanks, a word cloud and applause"],
"life_italy":["Trip around Italy","Text in a circle, a route with connectors and an animated path, timeline, budget with formulas, charts and a matching activity"],
"life_kids_party":["Children's birthday party","Bright colours: a dancing 3D robot, cheering characters, hand-drawn balloons, a points quiz and a countdown"],
"life_moving":["Moving house and new home","A hand-drawn house of shapes, timeline, a checklist that strikes out, 3D furniture that moves onto the floor plan with Transform, budget and an ordering activity"],
"life_recipe":["Recipe: guacamole","A 3D avocado that travels between slides (Transform), ingredients with formulas, steps one by one, a countdown and a rating"],
"life_travel_eu_amsterdam":["Amsterdam: canals and bikes","Canal house façades that build in sequence, canals as a target, bike crossing with sound, table with formulas, lines and pie poll"],
"life_travel_eu_camino":["Camino de Santiago: from Sarria","Credential filling with stamps with sound, kilometre waterfall, 3D walker, backpack equation, doughnut and ordering stages"],
"life_travel_eu_croatia":["Sailing Croatia’s Dalmatia","Nautical chart, compass rose that turns and travels with Morph, flags, matching, miles with formulas, quiz and countdown"],
"life_travel_eu_danube":["The Danube by bike","Cycling computer style: route on a phone, step-by-step GPX file, stacked bars, 3D bottle with Morph, formulas and treemap"],
"life_travel_eu_fjords":["Norwegian fjords by water","Layered landscape with reflections, sailing ship, fjord cross-section that draws itself, bars, radar, step-by-step route and multiple-choice poll"],
"life_travel_eu_greece":["Greek islands by ferry","White village of shapes, Greek key, route that draws itself, timetable with formulas, bubbles, 3D sunglasses with Morph and sunset"],
"life_travel_eu_iceland":["Iceland: the Ring Road by car","Gradient auroras, map with a sounding path, 3D car, figures with drumroll, wind-chill equation, walking fox and quiz"],
"life_travel_eu_lisbon":["Lisbon: hills and trams","SVG tiles, a tram climbing the hills along a path with sound, height profile, flipping cards, table with formulas and gaps"],
"life_travel_eu_prague":["Prague, city of a hundred spires","Astronomical clock made of shapes that turns and travels with Morph, parade with chime, countdown, map to label and table"],
"life_travel_eu_scotland":["Scotland: the Highlands by car","Tartan woven from shapes, road that draws itself, cars giving way, turning castles, 3D lantern, bars and audience questions"],
"life_wedding":["Wedding invitation","Classic type and gold: Text Art, curved text, the couple's timeline, a map with an animated route, a poll and a countdown"],
"prod_app_bank":["Cartilla: banking for older people","Leather and gold savings book: gold Text Art, Morph to zoom into the phone, table with SUM, waterfall, stamp and anti-fraud quiz"],
"prod_app_gym":["Serie: bookings at your gym","LED scoreboard: 3D fighter who cheers and walks to class, two countdowns, occupancy by hour, fares with formulas and quiz"],
"prod_app_health":["Turno: health centre appointments","Clinical: self-drawing heartbeat, before and after, cycle one by one, walking 3D patient, schedule on a monitor, bars and Q&A"],
"prod_app_language":["Vocablo: language learning app","Airmail postcard: stamps, speech bubbles that pop with sound, flipping cards, Morph, forgetting equation, chart and matching"],
"prod_app_market":["Plaza: the local market at home","Awning and chalkboards: 3D van that drives the map, stalls in a radial, phone, treemap, fees with formulas and poll"],
"prod_app_meditation":["Marea: meditation and sleep app","Night sea: moon with curved text, phone Morph, guided breathing with chained rings, countdown, chart and 3D lantern"],
"prod_app_music":["Garaje: local live music","Vinyl and neon: record that travels with Morph, spinning curved text, equaliser with drumroll, laptop, radar, pie and word cloud"],
"prod_app_photo":["Grano: film photography","Darkroom: film strip, photo that develops with Morph, counter with drumroll, histogram, tablet, table and labelling"],
"prod_app_recipes":["Sobras: recipes from what you have","Fridge with sticky notes: 3D avocado with Morph, phone that recognises ingredients, steps, doughnut, recipe with formulas and countdown"],
"prod_app_transit":["Andén: city transit","Metro signage: departures board with countdown, self-drawing map, animated trip, phone, stacked bars and fares"],
"prod_hw_drone":["Cernícalo: mountain rescue drone","Topographic map: a flight path that draws itself as the drone follows it, NASA's 3D helicopter, thermal view, countdown, formulas and a quiz"],
"prod_hw_ereader":["Folio: e-ink reader","A book with page turns: drop cap, drawn reader, microcapsules that appear, key figure and bars, quote, table with formulas and fill in the gaps"],
"prod_hw_glasses":["Horizonte: smart glasses for cyclists","The road through the lens: 3D glasses with Morph, numbered parts with sound, bars, step-by-step YAML code, radial diagram and a poll"],
"prod_hw_headphones":["Silencio: noise-cancelling headphones","Anechoic chamber: waves that draw themselves and cancel out, equation, step-by-step process, frequency curve, table with formulas and a poll"],
"prod_hw_keyboard":["Tecla: modular mechanical keyboard","Keys that pop in with a click sound, force curves, layer-by-layer exploded view, keymap in code, budget with formulas and ordering"],
"prod_hw_lamp":["Alba: sunrise alarm lamp","Gradient sunrise: the sun rises with Morph, a 3D lamp that travels, timeline, light curve with equation, Kelvin scale and a rating"],
"prod_hw_thermostat":["Templa: smart thermostat","Thermostat dial and a house in cross-section with temperatures that appear, savings waterfall, equations, 24-hour lines, matrix and a poll"],
"prod_hw_toycar":["Chispa: a car for learning to code","Play mat: 3D car with Morph, cards that pop in with sound, a board the car travels across, code, quiz, steps and a doughnut chart"],
"prod_hw_tracker":["Miga: a tracker so you never lose a thing","Treasure map: crumbs that appear one by one up to the X, a hand-drawn circle that draws itself, doughnut, target, a trail through town and a word cloud"],
"prod_hw_trailcam":["Vigía: wildlife trail camera","Infrared viewfinder: a 3D fox that walks past and sets off the camera, drawn sensor range, key figures, area chart by hour, SUM table and matching"],
"product_app":["Mobile app presentation","App on phone, tablet and laptop, Morph, user journey as chevrons, key figures, retention chart and word cloud"],
"product_car":["Presentation: electric car","Uncropped 3D car that circles round on arrival, Morph, key figures, area and bar charts, table and vote"],
"product_eco":["Product sustainability","Eco green: 3D plant with Morph, life cycle, footprint waterfall, materials bar chart, lines with a target and fill in the gaps"],
"product_furniture":["Furniture collection","Editorial style: 3D sofas and chairs, Morph with different views, swing and orbit, colour swatches, tablet and budget"],
"product_keynote":["Hardware keynote","Premium white style: iridescent lamp and 3D bottle, Morph with labels, float and zoom in, key figures, table and prices"],
"product_roadmap":["Product roadmap","Self-drawing road, pyramid, timeline one by one, now and next, matrix, stacked bars, multiple-choice vote and ordering"],
"product_robot":["Industrial assistant robot","Industrial style: 3D robot that waves, walks a path, chains animations and dances; org chart, cycle, chart and quiz"],
"product_saas":["SaaS platform demo","Dashboard in a browser window with numbered call-outs, radial, funnel, KPIs, stacked bars, step-by-step code and Q&A"],
"product_security":["Product security","Green neon: layered target, flow with connectors appearing step by step, highlighted code, chart, steps and a matching activity"],
"product_watch":["Launch: smartwatch","Black and gold: a 3D watch travels across three slides with Morph and different arrivals, gold Text Art, radar and prices"],
"sci_ai":["Artificial intelligence","Violet neon: 3D robot that waves and travels with Morph, timeline, org chart, neural network that lights up, chart and word cloud"],
"sci_astro_blackholes":["Black holes","Pure black: a horizon that travels with Morph, curved text, a giant figure, table with formulas, a 3D astronaut spiralling in and a quiz"],
"sci_astro_cosmology":["From the Big Bang to today","A universe that cools down: a thermometer with Morph, a chained timeline, the cosmic background, scatter, doughnut and a calendar with formulas"],
"sci_astro_defense":["Planetary defence: a drill","Crisis room: hazard stripes, a 3D asteroid, the Torino scale in a chain, an animated deflection with sound, a countdown and a team vote"],
"sci_astro_exoplanets":["Other worlds wanted","Retro travel posters: a transit with its light curve drawn, Python code, the wobble with motion paths, area chart, a 3D satellite and a poll"],
"sci_astro_moon":["Selenography: the Moon","Old sepia atlas: an engraved SVG Moon, chained phases, synchronous rotation, tides, a 3D lunar module with Morph and matching"],
"sci_astro_pulsars":["Pulsars: the lighthouses of the cosmos","Oscilloscope screen: a signal that traces itself, a spinning lighthouse, pulses you can hear, a 3D radio telescope and nebula, table and a quiz"],
"sci_astro_skywatch":["A guide to stargazing","Red-light mode: a planisphere with curved text, a countdown, constellations that trace themselves, magnitudes, bars, table and a poll"],
"sci_astro_stars":["The life and death of stars","Stellar spectrum: chained classes, balance with arrows, a custom H-R diagram, a fork by mass, table with formulas and a 3D supernova"],
"sci_astro_sun":["The Sun, a star up close","Crimson solar filter: chained layers, fusion with an equation, a photon's journey, the sunspot cycle, a 3D probe with Morph and a quiz"],
"sci_astro_telescopes":["Telescopes: the blueprint","Technical blueprint style: rays that draw themselves, a 3D Webb with Morph across the spectrum, a hexagonal mirror in a chain, a trip to L2 and labelling"],
"sci_brain":["Neuroscience: the brain","Dark style with glows: drawn neuron with an animated impulse, walking 3D figure, radial diagram, org chart, bars and label a picture"],
"sci_chem":["Chemistry: the periodic table","Clean lab look: periodic table that builds itself in a cascade, molecules made of shapes, 3D brazier, equations, doughnut and matching"],
"sci_climate":["Climate change in data","Warming stripes, line, area and treemap charts, greenhouse effect that draws itself, 3D satellite, cycle and multiple-choice vote"],
"sci_mars":["Mission to Mars","Rusty space style: NASA 3D rover with Morph, floating astronaut, animated orbit, equation and quiz"],
"sci_med_case":["Clinical case: fever and cough","Medical record style: folder, stamp, X-ray on a light box with a circle that draws itself, CURB-65 with a formula, poll and questions"],
"sci_med_ecg":["Cardiology: reading an ECG","ECG paper: traces that draw themselves, an impulse travelling through the heart, table with formulas, equation, quiz and countdown"],
"sci_med_glucose":["Endocrinology: glucose and insulin","Glucose sensor app style: phone with the screen, cycle one by one, curves, doughnut, table with formulas, equation, 3D avocado and poll"],
"sci_med_immune":["Immunology: the immune response","Fluorescence microscope: cells that light up, a drawn antibody, phagocytosis with Morph, org chart and matching"],
"sci_med_kidney":["Renal physiology: the nephron","Blueprint: a nephron that draws itself, a drop travelling it with sound, dimensions, waterfall, equation, table with formulas, 3D bottle and cycle"],
"sci_med_knee":["Anatomy: the knee","Antique anatomical plate style: curved text, sepia engraving, Morph to the menisci, matrix, table, walking 3D figure and labelling"],
"sci_med_micro":["Microbiology: antibiotic resistance","Petri dishes: colonies that pop up with sound, exponential growth, selection told with Morph, antibiogram, radial diagram and word cloud"],
"sci_med_pk":["Pharmacokinetics: the half-life","Medicine box style: a blister that fills up, LADME one by one, two-series curves, equations, table with formulas, code and fill in the gaps"],
"sci_med_stroke":["Neurology: stroke code","Emergency race against the clock: siren lights, giant number with a drumroll, chained BE-FAST, doughnut, chevrons, ordering steps and countdown"],
"sci_med_trial":["Clinical trial: reading the results","Scientific journal style: CONSORT with connectors, survival curves, table with formulas, NNT, chained forest plot and quiz"],
"sci_newton":["Physics: Newton's laws","Physics notebook: equations, moving 3D car, projectile path that draws itself, table with formulas and fill in the gaps"],
"sci_nurse_cpr":["Basic CPR: life support","Green emergency signage: hands that compress in rhythm, AED pads that fly with sound, two series, countdown and ordering"],
"sci_nurse_drip":["IV fluids: calculating the drip rate","Drawn IV set with drops falling with sound, step-by-step formula, worked example, a table that calculates, pump and countdown"],
"sci_nurse_falls":["Falls in older people: the safe home","A home at night with a 3D lamp: floor plan with hazards fixed with Morph, walking test with a 3D figure, Venn, doughnut and countdown"],
"sci_nurse_hands":["Hand hygiene: the 5 moments","Tiles and bubbles: rising soap bubbles, the 5 moments on a floor plan, a UV lamp with sound, a 30 s countdown, bars and a quiz"],
"sci_nurse_heat":["Heat wave: health plan","Alert colours: a rising thermometer, Text Art, a drawn warning map, scatter chart, phone with the SMS, 3D bottle, table and quiz"],
"sci_nurse_herd":["Vaccines: herd immunity","Vaccination card with stamps and curved text, chain contagion cut off with Morph, equation, table with formulas, crossed-out myths"],
"sci_nurse_outbreak":["Investigating a food-borne outbreak","Corkboard: pinned notes and red string that draws itself, epidemic curve, table with formulas, relative risk, code and a poll"],
"sci_nurse_pressure":["Pressure ulcers: prevention","Thermal pressure map: spots that light up and fade, Braden with formulas, a spinning repositioning clock, skin layers and labelling"],
"sci_nurse_sbar":["Shift handover with SBAR","Ward whiteboard: a marker that underlines on its own, magnets and notes that stick with sound, chained dialogue, a score with a formula and matching"],
"sci_nurse_smoking":["Quitting smoking: what your body gains","From smoke to clean air: rising smoke, a cigarette as a timeline, lungs that change with Morph, savings table and breathing"],
"sci_python":["Programming in Python","Dark code-editor style: terminal that types itself, code with highlight steps, animated output, line ordering and a countdown challenge"],
"sci_solar":["The solar system","Planets to scale appearing in a chain, three 3D probes with different views and movements, table, radial diagram and matching"],
"sci_stats":["Statistics and probability","Editorial style: bell curve that draws itself, formulas, histogram, scatter, area, bar and bubble charts, and a scored question"],
"sci_thesis":["Bachelor's thesis defence","Sober academic look: institutional cover, contents, method with an equation, table with totals, results in charts, references and Q&A"],
"show_anim_bike":["Bike gears, demystified","Synchronised motion: gears that turn at their real ratio, wheels that roll their exact distance, two lanes at once and a table"],
"show_anim_blueprint":["Flat renovation: the floor plan","A plan that draws itself: walls in a chain, dimensions, a demolished wall that disappears, Morph to the new layout, services and schedule"],
"show_anim_ferries":["Island ferries: summer routes","Motion paths on a map: boats that turn with the route, routes drawn as they pass, three lines at once, a stopover and timetables"],
"show_anim_firefly":["Story: the firefly without a light","A story told with entrances and exits: narration visible only on its step, dialogue that comes and goes, flights and a light that returns"],
"show_anim_foosball":["Office table football tournament","Chained animations with sounds like a game: passes with clicks, a shot, a goal with applause, a bracket that advances, a table and a sweepstake"],
"show_anim_guitar":["Anatomy of the Spanish guitar","Triggers: click each part of the guitar to see its card and each string to make it vibrate; a spinning rosette"],
"show_anim_haiku":["Haiku workshop: word by word","Animation by word and paragraph: lines word by word, a prompt phrase by phrase, counted syllables and Morph"],
"show_anim_rpg":["Tabletop role-playing: your first game","3D characters with their animations: attack, block, cast spells and fall; walk up to the rival, a rolling die and health that drops"],
"show_anim_speech":["Speech: let's save the library","Emphasis in step with a speech: the sentence in focus and the rest dimmed, strike-through, highlight, hand-drawn underline and circle, countdown"],
"show_anim_tshirt":["Infographic: the journey of a T-shirt","An infographic that reveals itself: a route drawn with its stops on time, a pictogram of drops that fills, waterfall, figures and formula"],
"showcase_3d":["Catalogue: 3D in depth","3D models with all their options: views, moves on entry, spin, edges, margin, clips, walking and arrival with Morph"],
"showcase_animations":["Catalogue: animations","Every object animation: entrance, emphasis, exit, motion paths, draw, chained, sounds and several on one object"],
"showcase_charts":["Catalogue: charts","The 15 chart types, two per slide, with series, combo, grid, labels and axis titles, plus the table of options"],
"showcase_diagrams":["Catalogue: diagrams","The 15 diagram layouts written as an outline, the 4 colour schemes and appearing one by one when presenting"],
"showcase_morph":["Catalogue: Morph","Morph step by step: text that changes size and place, shapes, growing bars, a picture, 3D and letters that rearrange"],
"showcase_objects":["Catalogue: media and objects","Code with steps, equations, icons, five devices, tables with styles and formulas, slide zoom and connectors"],
"showcase_polls":["Catalogue: polls and activities","The 11 kinds of poll and activity from phones, the countdown in its three styles, leaderboard and classroom mode"],
"showcase_shapes":["Catalogue: shapes","Every shape by category with its name, lines and dashes, gradients, opacity, hand-drawn look, shadows, text inside and rotation"],
"showcase_text":["Catalogue: Text Art and typography","The 10 Text Art styles, curved text, columns, five bullet levels, the 8 font pairs, alignment and spacing"],
"showcase_transitions":["Catalogue: transitions","All 22 slide transitions, one by one: entrance, a different exit, directions, speed and auto-advance"]};
