// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Quarterly results for the board","Dark blue and gold: large animated KPIs with sound, waterfall, funnel, stacked bars and a table with formulas against budget"],
"biz_climate":["Workplace climate survey","Violet and interactive: countdown, 100 % bars, 1 to 5 rating, word cloud, multiple choice and audience questions"],
"biz_investment":["Investor pitch","Black and gold: a 3D product that spins and travels with Transform, giant figures, market in circles, traction, use of funds and team"],
"biz_marketing":["Campaign marketing plan","Warm style: text in a circle, target audience, funnel, channel mix, calendar table, budget with a formula and a poll"],
"biz_onboarding":["Welcome for new employees","Friendly style: a 3D robot that waves and walks through the week, org chart one by one, values with icons and a matching activity"],
"biz_proposal":["Sales proposal to a client","Paper style: seal, process one by one, mock-ups on a laptop and a phone, pricing, budget with VAT in formulas, timeline and guarantees"],
"biz_roadmap":["Project roadmap","Dark technical style: chevrons one by one, animated Gantt chart, timeline, a 3D car that moves forward with Transform and a status table"],
"biz_sales":["Sales and annual forecast","Minimalist grey: combined bars and lines, scenarios, forecast formula, table with formulas, stacked and horizontal bars"],
"biz_strategy":["Strategic plan and OKRs","Clean white style: figures that enter in sequence, pyramid, priorities with icons, OKR table, progress bars, radar and chevrons"],
"biz_swot":["SWOT and competitor analysis","Graphite background: SWOT in quadrants, strategy matrix, positioning map, grouped bars, Venn, pie chart and a multiple-choice poll"],
"creative_bauhaus":["Bauhaus: form and function","Bauhaus geometric art: primary shapes that spin and bounce, a timeline, a grid that morphs and a matching activity"],
"creative_brutalism":["Brutalism: a web manifesto","Brutalist style: giant type, black blocks, vertical text, hard shadows, animated strikethrough, table and poll"],
"creative_comic":["Comic: animal superpowers","Comic style: panels, speech and thought bubbles, bouncing Text Art sound effects, a 3D fox, a chart and a quiz"],
"creative_fashion":["Fashion magazine: slow autumn","Magazine style: serif masthead, a 3D watch on the cover, columns with a drop cap, a big quote, the season's palette and a chart"],
"creative_glass":["Glassmorphism: a finance app","See-through cards over coloured lights, the app on a phone, a doughnut chart, a card that morphs and a rating poll"],
"creative_pixel":["Pixel art: your first video game","Retro video game style: pixel sprites, a score bar, 3D characters that walk and jump, step-by-step code, a quiz and a countdown"],
"creative_space":["Galaxy: looking into the past","Space style: stars, glowing nebulae, NASA 3D models, a probe that tours the planets, curved text and a quiz"],
"creative_synthwave":["Synthwave: Neón 86 festival","Retro 80s style: gradient sun, a grid that draws itself, glowing neon, Morph, a dancing 3D robot and a word cloud"],
"creative_watercolor":["Watercolour: a balcony garden","Watercolour and paper style: radial gradient blots, hand-drawn shapes, handwriting, a drawing that traces itself and 3D"],
"creative_zen":["Japanese minimalism: tea","Japanese minimalism: lots of white, a red sun that morphs, vertical text, an ensō that paints itself and a countdown"],
"data_ab_test":["A/B experiment","Equations, two-series scatter, labelled columns, conversion table with formulas and significance figures"],
"data_energy":["Energy and consumption","Hourly stacked areas, three-series lines, treemap, labelled columns and calculated rate table"],
"data_exec_panel":["Monthly executive dashboard","KPIs with traffic lights and sparklines, combo chart against budget, small multiples, doughnut and poll"],
"data_home_finance":["Personal finances","Waterfall from salary to savings, pie chart, lines and area, tables with SUM, AVERAGE, MAX and MIN"],
"data_market_study":["Market study","Big figures, treemap, bubbles, scatter plot, two-series horizontal bars and 2 × 2 matrix"],
"data_population":["Population and demographics","Population pyramid, histogram, horizontal bars, crossing lines and indicator table with formulas"],
"data_sales_regions":["Sales by region","Grouped, stacked and 100 % bars, combo chart with target, table with formula totals and animated KPIs"],
"data_satisfaction":["Satisfaction survey","Doughnut with legend, compared radars, labelled columns, NPS, live rating and word cloud"],
"data_season_stats":["The season in numbers","Giant figures with sound, league table with formulas, negative bars, lines, stacked bars and team radar"],
"data_web_metrics":["Web and marketing metrics","KPIs with sparklines, four-series lines, areas, conversion funnel, combo chart and table with formulas"],
"edu_body":["The human body","Lab style: 3D figure with Morph, character walking along a path, bar chart, label the body and quiz"],
"edu_cell":["The cell","Cell drawn with shapes, parts one by one, Morph to zoom in, matching pairs, diagram, 3D plant and rating"],
"edu_english":["English for beginners","Classroom mode: flip cards with sound, 3D robot that walks and waves, 3D fox, three questions with points, leaderboard and applause"],
"edu_fractions":["Fractions","Neon style: drawn pizzas, step-by-step equations, addition with Morph, fill in the gaps, quiz and countdown challenge"],
"edu_quixote":["Don Quixote","Ink and paper style: windmill turning with sound, curved text, animated quotes, Morph, timeline, fill in the gaps and quiz"],
"edu_renewables":["Renewable energy","Spinning wind turbine, cards, area, doughnut and grouped bar charts, live word cloud, poll and countdown"],
"edu_revolution":["The French Revolution","Old paper style: text in a circle, Morph, social pyramid, animated timeline with sound, put events in order and poll"],
"edu_spain":["Geography of Spain","Atlas style: compass rose, relief as a target diagram, rivers table with formulas, peaks and rainfall charts, matching pairs and quiz"],
"edu_volcanoes":["Volcanoes","Fire style: animated eruption with sound, volcano parts to label, table, timed quiz and countdown"],
"edu_water":["The water cycle","Cycle diagram one by one, landscape with rising drops and animated rain with sound, doughnut charts, matching pairs and 3D satellite"],
"life_bookclub":["Book club","A hand-drawn bookshelf, a cover made of shapes, quotes that transform, a radial diagram, a rating and a vote on the next book"],
"life_cv":["Visual CV","Text in a circle, key figures, a step-by-step timeline, animated skill bars, a radar chart, screens in devices and contact details"],
"life_fitness":["Training plan: 5 km","A 3D runner, fire Text Art, phases with gradients, a week with formulas, progress charts, a pyramid, a countdown and a word cloud"],
"life_garden":["Urban vegetable garden","A 3D plant with Transform, a sowing calendar as a colour-coded table, cycle, Venn, watering and growth charts, a labelling activity"],
"life_graduation":["Graduation and end of year","Gold Text Art, mortarboards made of shapes, polaroids that flip in, figures with a drum roll, thanks, a word cloud and applause"],
"life_italy":["Trip around Italy","Text in a circle, a route with connectors and an animated path, timeline, budget with formulas, charts and a matching activity"],
"life_kids_party":["Children's birthday party","Bright colours: a dancing 3D robot, cheering characters, hand-drawn balloons, a points quiz and a countdown"],
"life_moving":["Moving house and new home","A hand-drawn house of shapes, timeline, a checklist that strikes out, 3D furniture that moves onto the floor plan with Transform, budget and an ordering activity"],
"life_recipe":["Recipe: guacamole","A 3D avocado that travels between slides (Transform), ingredients with formulas, steps one by one, a countdown and a rating"],
"life_wedding":["Wedding invitation","Classic type and gold: Text Art, curved text, the couple's timeline, a map with an animated route, a poll and a countdown"],
"product_app":["Mobile app presentation","App on phone, tablet and laptop, Morph, user journey as chevrons, key figures, retention chart and word cloud"],
"product_car":["Presentation: electric car","Uncropped 3D car that circles round on arrival, Morph, key figures, area and bar charts, table and vote"],
"product_eco":["Product sustainability","Eco green: 3D plant with Morph, life cycle, footprint waterfall, materials bar chart, lines with a target and fill in the gaps"],
"product_furniture":["Furniture collection","Editorial style: 3D sofas and chairs, Morph with different views, swing and orbit, colour swatches, tablet and budget"],
"product_keynote":["Hardware keynote","Premium white style: iridescent lamp and 3D bottle, Morph with labels, float and zoom in, key figures, table and prices"],
"product_roadmap":["Product roadmap","Self-drawing road, pyramid, timeline one by one, now and next, matrix, stacked bars, multiple-choice vote and ordering"],
"product_robot":["Industrial assistant robot","Industrial style: 3D robot that waves, walks a path, chains animations and dances; org chart, cycle, chart and quiz"],
"product_saas":["SaaS platform demo","Dashboard in a browser window with numbered call-outs, radial, funnel, KPIs, stacked bars, step-by-step code and Q&A"],
"product_security":["Product security","Green neon: layered target, flow with connectors appearing step by step, highlighted code, chart, steps and a matching activity"],
"product_watch":["Launch: smartwatch","Black and gold: a 3D watch travels across three slides with Morph and different arrivals, gold Text Art, radar and prices"],
"sci_ai":["Artificial intelligence","Violet neon: 3D robot that waves and travels with Morph, timeline, org chart, neural network that lights up, chart and word cloud"],
"sci_brain":["Neuroscience: the brain","Dark style with glows: drawn neuron with an animated impulse, walking 3D figure, radial diagram, org chart, bars and label a picture"],
"sci_chem":["Chemistry: the periodic table","Clean lab look: periodic table that builds itself in a cascade, molecules made of shapes, 3D brazier, equations, doughnut and matching"],
"sci_climate":["Climate change in data","Warming stripes, line, area and treemap charts, greenhouse effect that draws itself, 3D satellite, cycle and multiple-choice vote"],
"sci_mars":["Mission to Mars","Rusty space style: NASA 3D rover with Morph, floating astronaut, animated orbit, equation and quiz"],
"sci_newton":["Physics: Newton's laws","Physics notebook: equations, moving 3D car, projectile path that draws itself, table with formulas and fill in the gaps"],
"sci_python":["Programming in Python","Dark code-editor style: terminal that types itself, code with highlight steps, animated output, line ordering and a countdown challenge"],
"sci_solar":["The solar system","Planets to scale appearing in a chain, three 3D probes with different views and movements, table, radial diagram and matching"],
"sci_stats":["Statistics and probability","Editorial style: bell curve that draws itself, formulas, histogram, scatter, area, bar and bubble charts, and a scored question"],
"sci_thesis":["Bachelor's thesis defence","Sober academic look: institutional cover, contents, method with an equation, table with totals, results in charts, references and Q&A"],
"showcase_3d":["Catalogue: 3D in depth","3D models with all their options: views, moves on entry, spin, edges, margin, clips, walking and arrival with Morph"],
"showcase_animations":["Catalogue: animations","Every object animation: entrance, emphasis, exit, motion paths, draw, chained, sounds and several on one object"],
"showcase_charts":["Catalogue: charts","The 15 chart types, two per slide, with series, combo, grid, labels and axis titles, plus the table of options"],
"showcase_diagrams":["Catalogue: diagrams","The 15 diagram layouts written as an outline, the 4 colour schemes and appearing one by one when presenting"],
"showcase_morph":["Catalogue: Morph","Morph step by step: text that changes size and place, shapes, growing bars, a picture, 3D and letters that rearrange"],
"showcase_objects":["Catalogue: media and objects","Code with steps, equations, icons, five devices, tables with styles and formulas, slide zoom and connectors"],
"showcase_polls":["Catalogue: polls and activities","The 11 kinds of poll and activity from phones, the countdown in its three styles, leaderboard and classroom mode"],
"showcase_shapes":["Catalogue: shapes","Every shape by category with its name, lines and dashes, gradients, opacity, hand-drawn look, shadows, text inside and rotation"],
"showcase_text":["Catalogue: Text Art and typography","The 10 Text Art styles, curved text, columns, five bullet levels, the 8 font pairs, alignment and spacing"],
"showcase_transitions":["Catalogue: transitions","All 22 slide transitions, one by one: entrance, a different exit, directions, speed and auto-advance"]};
