// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Hiruhileko emaitzak kontseiluari","Urdin iluna eta urrea: soinudun adierazle handi animatuak, ur-jauzia, inbutua, barra metatuak eta aurrekontuarekin alderatzeko formuladun taula"],
"biz_climate":["Lan-giroari buruzko inkesta","Morea eta parte-hartzailea: atzerako kontaketa, % 100eko barrak, 1etik 5erako balorazioa, hitz-hodeia, aukera anitzekoa eta publikoaren galderak"],
"biz_investment":["Inbertitzaileentzako aurkezpena","Beltza eta urrea: biratu eta Eraldatu erabiliz bidaiatzen duen 3D produktua, zifra erraldoiak, merkatua zirkuluetan, trakzioa, funtsen erabilera eta taldea"],
"biz_marketing":["Kanpainaren marketin plana","Estilo beroa: testua zirkuluan, xede-publikoa, inbutua, kanalen nahasketa, egutegia taulan, aurrekontua formularekin eta bozketa"],
"biz_onboarding":["Langile berriei ongietorria","Estilo atsegina: agurtu eta astean zehar oinez dabilen 3D robota, organigrama banan-banan, balioak ikonoekin eta parekatze-jarduera"],
"biz_proposal":["Bezero baterako proposamen komertziala","Paper estiloa: zigilua, prozesua banan-banan, maketak eramangarrian eta mugikorrean, prezioak, BEZa formuletan duen aurrekontua, kronologia eta bermeak"],
"biz_retail_basket":["Saskiaren analisia: tiket batek kontatzen duena","Bere kabuz inprimatzen den kutxako tiketa, batez besteko tiketaren ekuazioa, ur-jauzia, sakabanatzea, produktu-sarea, taula, SQL kontsulta, donuta eta lehiaketa"],
"biz_retail_blackfriday":["Ostiral Beltzeko kanpaina","Beltza eta neoia: prezio-etiketak, soinudun zifrak, marratutako prezioak, orduko lerroak, inbutua, formuladun taula, lehiaketa eta atzerako kontaketa"],
"biz_retail_cx":["Bezeroaren esperientzia: Martaren bidaia","Persona marraztua, bere kabuz marrazten den emozio-kurba aurpegi kateatuekin, aipuak, NPS ekuazioarekin, matrizea, Eraldatu eta balorazioa"],
"biz_retail_inventory":["Inbentarioa: ez hausturarik ez soberakinik","Apalategi eta etiketadun biltegi marraztua, konparazioa, Pareto grafiko konbinatuan, ekuazioa, formuladun taula, kodea, 3D lanpara eta ordenatzea"],
"biz_retail_loyalty":["Fidelizazioa: okindegiko kluba","Soinuz eta txaloz katean betetzen den zigilu-txartela, bezeroaren balioaren ekuazioa, mailen piramidea, formuladun taula eta aplikazioa"],
"biz_retail_market":["Udal azoka: berpizteko plana","Izen kurbatua duen burdinazko fatxada, klarion-arbelak katean, treemap-a, orduko azalerak, sasoiko egutegia taulan, 3D ahuakatea eta hodeia"],
"biz_retail_omni":["Kanal anitzeko salmenta: erosi sarean, jaso dendan","Mugikorreko aplikazioa eta nabigatzaileko webgunea marraztuta, bere kabuz marrazten den ibilbidea, kalea zeharkatzen duen 3D furgoneta, formuladun taula, kodea eta % 100ean pilatutako barrak"],
"biz_retail_opening":["Liburu-denda eta kafetegi baten irekiera","Toldodun fatxada marraztua, kateatutako puntuak dituen auzoko mapa, Venn, 3D besaulkia, kronologia, formuladun taula eta atzerako kontaketa"],
"biz_retail_supermarket":["Supermerkatua: banaketa berria","Formaz egindako oinplanoa, denda zeharkatzen duen orgatxoa, bero-mapa, Eraldatu-rekin berrantolatzen diren sailak, apala eta taula"],
"biz_retail_window":["Erakusleihoak: udazkeneko erakusleihoa","Beltz eta boli koloreko editoriala: 3D betaurrekoak Eraldatu-rekin, zirkuluko testua, kolore-laginak, triangelua eta foku-puntuak dituen erakusleiho marraztua"],
"biz_roadmap":["Proiektu baten ibilbide-orria","Estilo tekniko iluna: galoiak banan-banan, Gantt diagrama animatua, kronologia, Eraldatu erabiliz aurrera egiten duen 3D autoa eta egoera-taula"],
"biz_sales":["Salmentak eta urteko aurreikuspena","Gris minimalista: barra eta lerro konbinatuak, agertokiak, aurreikuspen-formula, formuladun taula, barra metatuak eta horizontalak"],
"biz_startup_agrotech":["Agrotech pitch-a: sentsoreekin ureztatzea","Lursailen aireko ikuspegia hezetasun-maparekin, NASAren 3D satelitea, mugikorra, soinudun tanta kateatuak, formuladun taula eta treemap-a"],
"biz_startup_edtech":["Edtech pitch-a: matematika-tutorea","Koadernoa laukietan: post-it kateatuak, eskuz idatzitako letra, ekuazioak urratsez urrats, mugikorra, zuzeneko galdetegia, zikloa eta grafikoak"],
"biz_startup_energy":["Energiaren pitch-a: eguzki-komunitatea","Teilatuak egunsentitik gauera: igo eta zerua arkuan zeharkatzen duen eguzkia, diagrama erradiala, orduko areak, ekuazioa eta formuladun taula"],
"biz_startup_fashion":["Moda zirkularraren pitch-a: Retal","Arropa-etiketa Eraldatu-rekin bidaiatzen duena, josturak puntuz, jantzi baten bizitza katean, zikloa, eraztuna, radarra eta aukera anitzeko bozketa"],
"biz_startup_insurance":["Aseguruen pitch-a: egunkako estaldura","Euri grisa eta aterki horia: piktograma katean, etengailudun aplikazioa, prezioaren ekuazioa, formuladun taula, kronologia eta bozketa"],
"biz_startup_kitchen":["Sukaldeko robotikaren pitch-a: Fogón","Sukalde profesionala: komandak errailean, suzko Text Art, oinez sartu eta agurtzen duen 3D robota, errezeta kode gisa, atzerako kontaketa eta inbutua"],
"biz_startup_lastmile":["Logistika pitch-a: azken miliakoa","Metro-plano estiloa: beren kabuz marrazten diren lerroak, mapa zeharkatzen duten 3D kamioia eta bizikletak, formuladun taula, area eta ur-jauzia"],
"biz_startup_mental":["Osasun mentalaren pitch-a: Remanso","Gau lasaia: arnasten duten eraztunak, arnasketa-minutua atzerako kontaketarekin, aplikazioa mugikorrean, eskailera, balorazioa eta formuladun taula"],
"biz_startup_pets":["Maskoten pitch-a: janari freskoa","Pegatina estiloa katean agertzen diren hatz-markekin, oinez zeharkatzen duen 3D azeria, errazioaren formula taula batean, eraztuna eta lehiaketa"],
"biz_startup_rural":["Landa-turismoaren pitch-a: Alpende","Mendiak ilunabarrean eta postalak: 3D farola, testu kurbatuko zigilua, ibilbidean 3D autoa duen mapa, barrak, tarta eta hitz-hodeia"],
"biz_strategy":["Plan estrategikoa eta OKRak","Estilo garbia zuriz: katean sartzen diren zifrak, piramidea, lehentasunak ikonoekin, OKR taula, aurrerapen-barrak, radarra eta galoiak"],
"biz_swot":["AMIA analisia eta lehiakideak","Grafito-hondoa: AMIA koadranteka, estrategien matrizea, posizionamendu-mapa, barra taldekatuak, Venn, tarta eta aukera anitzeko bozketa"],
"creative_bauhaus":["Bauhaus: forma eta funtzioa","Bauhaus arte geometrikoa: biratu eta errebotatzen duten oinarrizko formak, kronologia, Eraldatu sareta bat eta parekatze-jarduera"],
"creative_brutalism":["Brutalismoa: web manifestua","Estilo brutalista: tipografia erraldoia, bloke beltzak, testu bertikala, itzal gogorrak, marratu animatua, taula eta bozketa"],
"creative_comic":["Komikia: animalien superbotereak","Komiki estiloa: binetak, elkarrizketa eta pentsamendu bunbuiloak, errebotatzen duten Text Art onomatopeiak, 3D azeria, grafikoa eta lehiaketa"],
"creative_fashion":["Moda aldizkaria: udazken geldoa","Aldizkari estiloa: serif goiburua, 3D erlojua azalean, zutabeak hasierako letra handiarekin, aipu handia, denboraldiko paleta eta grafikoa"],
"creative_glass":["Glassmorphism: finantza aplikazioa","Txartel zeharrargiak kolore-distiren gainean, aplikazioa mugikorrean, eraztun-grafikoa, Eraldatu txartel bat eta balorazio-bozketa"],
"creative_pixel":["Pixel art: zure lehen bideojokoa","Bideojoko retro estiloa: pixel spriteak, markagailua, ibili eta salto egiten duten 3D pertsonaiak, urratsez urratseko kodea, lehiaketa eta atzerako kontaketa"],
"creative_retro_atomic":["Retrofuturismoa: 1962ko etorkizuna","Aro atomikoa: eraldatzen den plater-etxea, asmatzeak eta hutsak katean, ibiltzen den 3D robota, radarra, matrizea, atzerako kontaketa eta hitz-hodeia"],
"creative_retro_deco":["Art déco: Hotel Handiak 100 urte","Art déco urre eta beltzez: eraldatzen den haizemailea, Text Art urrekara, igogailua denbora-lerro gisa, 3D sofa, formuladun taula eta lehiaketa"],
"creative_retro_desktop90":["90eko hamarkada: segurtasun-kopiak","90eko mahaigaina: leiho grisak, errore-jauziak, aurrerapen-barra, ekuazioa, formuladun taula, urratsez urratseko kodea eta lehiaketa"],
"creative_retro_diner":["50eko hamarkada: kafetegia berriz irekitzen da","50eko kafetegia: neoizko errotulua, xake-zorua, toldoa, errepidean doan 3D kamioia, formuladun karta, eraztuna, biraka dabilen zigilua eta bozketa"],
"creative_retro_letterpress":["Inprenta-kartela: auzoko jaiak","Egurrezko letren kartela: desplazatutako tinta, soinuz erortzen diren letrak, egitaraua, barra pilatuak, ur-jauzia, bandoa, bozketa eta atzerako kontaketa"],
"creative_retro_sepia":["Sepia albuma: bilatu zure aitona-amonak","Sepia albuma: argazki-ertzak, eskuzko letra, arbasoen ekuazioa, hazten den zuhaitza, bidaia marraztua duen mapa, tarta, erlazionatu eta Eraldatu"],
"creative_retro_teletext":["Teletestua: auzoko liga","Teletestu-orriak: berez kargatzen diren lerroak, markagailua eta sailkapena formulekin, barrak, zutabeak, lehiaketa eta atzerako kontaketa"],
"creative_retro_typewriter":["Idazmakina: ipuin-tailerra","Orria eta idazmakina: soinuz idatzitako lerroak, marratua eta eskuzko zuzenketa, marrazten den arkua, barrak, hutsuneak eta atzerako kontaketa"],
"creative_retro_vapor":["Vaporwave: denden musika","Vaporwave pastela: eraldatzen den ilargia, SVG palmondoak, glitch izenburuak, sakabanatze-diagrama, 3D lanpara, batezbestekodun taula eta balorazioa"],
"creative_retro_vinyl":["70eko hamarkada: binilo kluba","Hirurogeita hamarreko estiloa: marradun ostadarrak, biraka dabiltzan disko marraztuak, zifra erraldoia, lerroak, barrak, 3D sofa, ordenatzeko jarduera eta pegatina"],
"creative_space":["Galaxia: iraganera begiratzea","Espazio estiloa: izarrak, nebulosa distiratsuak, NASAren 3D ereduak, planetak zeharkatzen dituen zunda, testu kurbatua eta lehiaketa"],
"creative_swiss_blood":["Kanpaina: eman odola","Kartel publikoa zuri eta gorriz: pantaila betetzen duen tanta Eraldatu-rekin, prozesua, bai ala itxaron, eraztuna, barrak, mugikorra eta lehiaketa"],
"creative_swiss_chairs":["Erakusketa: aulki modernoa","Kartel suitzarra gris eta lima: 3D aulkia biraka eta bidaian Eraldatu-rekin, kronologia, eraztuna, 3D besaulkia, taula formulekin eta ordenatu"],
"creative_swiss_designconf":["Diseinu biltzarra: Sareta 27","Grafitoa eta ziana: sareta bakarrik eraikitzen da eta Eraldatu-rekin aldatzen, ingerada-zifra, formula, kronologia, CSS kodea, hodeia eta atsedena"],
"creative_swiss_film":["Zinemaldia: egitaraua","Suitzarra beltz eta gorriz: zenbaki erraldoia banda bihurtzen da Eraldatu-rekin, sareta, taula, barrak, bozketa eta atzerako kontaketa"],
"creative_swiss_foundation":["Fundazio baten urteko txostena","Suitzarra zuri eta kobalto urdinez: urte erraldoia, gutun osoa koloretan, zifrak katean, ekuazioa, eraztuna, azalera, geziak eta kontuak formulekin"],
"creative_swiss_games":["Eskola jokoak: nortasun bisuala","Zuria eta magenta, paleta propioa: SVG piktogramak, hiria zeharkatzen duen 3D irudia, lerroak, domina-taula formulekin, mailak eta lehiaketa"],
"creative_swiss_museum":["Natur zientzien museoaren gida","Seinaleztapen suitzarra beltz eta horiz: plano propioa ibilbide animatuarekin, ibiltzen den 3D azeria, zutabeak, taula, etiketatu eta piktogramak"],
"creative_swiss_orchestra":["Orkestra sinfonikoa: 26/27 denboraldia","Gau urdina eta anbarra: biraka dabiltzan arkuak, testu kurbatua, zifrak pentagraman, zikloak, taula, ekuazioa, barrak, bozketa eta txaloak"],
"creative_swiss_publisher":["Argitaletxe baten udazkeneko katalogoa","Krema paperea eta petrolio berdea: bizkar bertikalen apala, SVG azalak, tableta, tarta, eskaera formulekin, egutegia eta hutsuneak"],
"creative_swiss_typeface":["Letra-tipo berri baten erakustegia","Erakustegia zuri eta morez: Eraldatu-rekin bidaiatzen duten letrak, neurtutako anatomia, eskala formularekin, glifoak, radarra eta lizentziak"],
"creative_synthwave":["Synthwave: Neón 86 jaialdia","80ko hamarkadako estilo retroa: eguzki gradientea, bere kabuz marrazten den sareta, neoi distiratsua, Eraldatu, dantzan dabilen 3D robota eta hitz-hodeia"],
"creative_watercolor":["Akuarela: baratzea balkoian","Akuarela eta paper estiloa: gradiente erradialeko orbanak, eskuz egindako formak, eskuzko letra, bere kabuz marrazten den marrazkia eta 3D"],
"creative_zen":["Japoniar minimalismoa: tea","Japoniar minimalismoa: zuri asko, eraldatzen den eguzki gorria, testu bertikala, bere kabuz margotzen den ensōa eta atzerako kontaketa"],
"data_ab_test":["A/B esperimentua","Ekuazioak, bi serieko sakabanatzea, etiketadun zutabeak, formuladun bihurketa-taula eta esangura-zifrak"],
"data_city_air":["Airearen kalitatea Brisamarren","Eraldatu-rekin argitzen den zerua, orratzdun indizea, ekuazioa, hutsuneak dituzten lerroak, radarra, formuladun taula eta balorazioa"],
"data_city_bikes":["Pedalia: urtebete bizikleta partekatuan","Metro erako planoa, lerro bat egiten duen bizikleta, soinudun zifrak, lerroak, pilatuak, mugikorreko aplikazioa, taula eta kodea"],
"data_city_budget":["Aurrekontu parte-hartzaileak","Kartel zibikoa: txartelak erortzen diren hautetsontzia, eraztuna, galoiak, konbinatua, emaitzak danborradarekin, formuladun taula"],
"data_city_housing":["Etxebizitza: geratzearen prezioa","Arkitekto-planoa: SVG oinplanoa, eskalako azalerak, konbinatua, ekuazioa, formuladun taula, sakabanatzea eta 3D sofa"],
"data_city_noise":["Sotoverdeko zarata","Bere kabuz altxatzen den uhina, dezibel-erregela soinuekin, ekuazioa, zarata-mapa, barra pilatuak, lehiaketa eta atzerako kontaketa"],
"data_city_tourism":["Turismoa Isla Marenan","Bidaia-kartela: testu kurbatua duen eguzkia, piktograma, azalerak, laukizuzenak, % 100eko barrak, 3D oinezkoa, taula eta postala"],
"data_city_traffic":["Trafikoa puntako orduan","Gaueko kontrol gela: auto-ilarak marraztutako mapa, pizten den semaforoa, bero-taula, Websterren formula, kodea eta 3D kamioia"],
"data_city_trees":["Hiriko zuhaitzen inbentarioa","Herbario-orria: marraztutako zuhaitza, 3D landarea Eraldatu-rekin, laukizuzenak, histograma, ekuazioa, taula eta parekatzea"],
"data_city_waste":["Villa Cardon botatzen duguna","Soinuarekin jauzi egiten duten edukiontziak, zifra erraldoia, ur-jauzia, pilatuak, koloreko tarta, inbutua, parekatzea eta taula"],
"data_city_water":["Fuentelindako ura","Eraldatu-rekin hustutzen den urtegia, lerroak, eraztuna, barrak, tarifa ekuazio eta formulekin, dutxa atzerako kontaketarekin"],
"data_energy":["Energia eta kontsumoa","Orduko azalera metatuak, hiru serieko lerroak, laukizuzenak, etiketadun zutabeak eta tarifa-taula kalkulatua"],
"data_exec_panel":["Hileko zuzendaritza-panela","Semaforo eta minigrafikodun KPIak, aurrekontuaren aurkako konbinatua, multiplo txikiak, eraztuna eta bozketa"],
"data_home_finance":["Finantza pertsonalak","Soldatatik aurrezkira doan ur-jauzia, grafiko zirkularra, lerroak eta azalera, BATURA, BATEZBESTEKOA, MAX eta MIN dituzten taulak"],
"data_market_study":["Merkatu-azterketa","Zifra handiak, laukizuzen-grafikoa, burbuilak, sakabanatzea, bi serieko barra horizontalak eta 2 × 2 matrizea"],
"data_population":["Biztanleria eta demografia","Biztanleria-piramidea, histograma, barra horizontalak, gurutzatzen diren lerroak eta formuladun adierazle-taula"],
"data_sales_regions":["Salmentak eskualdeka","Barra taldekatuak, metatuak eta % 100ekoak, helburudun grafiko konbinatua, formula bidezko guztizkoak dituen taula eta KPI animatuak"],
"data_satisfaction":["Gogobetetze-inkesta","Legendadun eraztuna, radar konparatuak, etiketadun zutabeak, NPS, balorazioa eta hitz-hodeia zuzenean"],
"data_season_stats":["Denboraldia zenbakitan","Soinudun zifra erraldoiak, formuladun sailkapena, barra negatiboak, lerroak, metatuak eta taldearen radarra"],
"data_sport_climb":["Etapa erregina: Alto de Peñaroja","Ibilbide-liburua: txirrindulari batek igotzen duen profil koloreztatua, mendateen taula formulekin, potentziaren ekuazioa, sakabanatzea, eraztuna eta 3D betaurrekoak"],
"data_sport_elo":["Elo: indarra nola neurtzen den","Gaueko taula: 3D zalduna, ekuazioak, espero den kurba, urratsez urratseko adibidea, histograma, formuladun taula, kodea eta lehiaketa"],
"data_sport_load":["Entrenamendu-karga eta lesioak","Fisioterapia-partea: gorputzaren mapa, aurrera doan markatzailea duen ACWR ekuazioa, lerroak, pilatuak, kodea, formuladun taula, zikloa eta 3D irudia"],
"data_sport_marathon":["Maratoia: helmugaratzeek kontatzen dutena","Dortsala azalean, soinudun zifrak, helmugaratzeen histograma, 30. km-ko horma, korrika doan 3D robot-erritmo-emailea, formuladun taula eta domina"],
"data_sport_serve":["Sake baten anatomia","Buztin gorria: errebotatzen duen pilota, sakeak pistan eta koadrorako zooma Eraldatu-rekin, radarra, % 100eko barrak, ekuazioa eta bozketa"],
"data_sport_shots":["Nondik irabazten den: jaurtiketa-mapa","Egurrezko parketa: jaurtiketa marraztua, eFG ekuazioa, zelai-erdia eraginkortasunaren araberako guneekin, % 100eko barrak, gurutzatzen diren lerroak eta lehiaketa"],
"data_sport_sprint":["100 metro 9,94 segundotan","Estadioa gauez: neoizko marka, faseak galoietan, abiadura 10 m-ro, formuladun taula, foto finisha, 3D erlojua eta atzerako kontaketa"],
"data_sport_stadium":["Estadioa betetzea","Partidako sarrera: harmailak okupazioaren arabera, azalerak, bi serieko sakabanatzea, laukizuzenak, inbutua, formuladun taula, bozketa eta 3D eserlekua"],
"data_sport_swim":["Besokadaz besokada: 200 m libre","Igerilekua goitik: lau luzera egiten dituen igerilaria, ekuazioa, multiplo txikiak, zutabe pilatuak, formuladun taula eta hodeia"],
"data_sport_xg":["Espero diren golak (xG)","Arbela belaren gainean: jaurtiketa marraztuak, markagailua xG-ren aurrean, jaurtiketen mapa banan-banan, ekuazio logistikoa, kodea, taula eta lehiaketa"],
"data_web_metrics":["Web eta marketin metrikak","Minigrafikodun KPIak, lau serieko lerroak, azalerak, bihurketa-inbutua, konbinatua eta formuladun taula"],
"edu_bio_digestion":["Ogitarteko baten bidaia","Metro-planoa: D linea marrazten da, ogitarteko batek egiten du, irteeren panela taulan, entzimak, barrak, geltokiak ordenatu eta Text Art"],
"edu_bio_dna":["DNA, bizitzaren errezeta","Neoizko laborategia: bere kabuz muntatzen den helizea, Text Art, parekatzen diren baseak, Python kodea urratsez urrats, barrak, mutazioa eta bikoteak lotu"],
"edu_bio_ecosystem":["Basoa: nork jaten du nor","Kraft paperezko landa-koadernoa: ibiltzen den 3D azeria, elikadura-katea, marrazten den sarea, piramidea eta % 10eko taula, lerroak eta etiketatu"],
"edu_bio_evolution":["Egokitzapena: txontaren mokoa","Gaueko itsas karta: ibilbide bat nabigatzen duen itsasontzia, marraztutako mokoak, lehorteko barrak, sakabanatzea, zikloa, mokoaren Eraldatu eta lehiaketa"],
"edu_bio_heart":["Bihotza, ponpa nekaezina","Gorria eta urdina: marraztutako taupada, zifra erraldoiak, zirkuitu marraztuak, tanta bihotzean zehar, pultsua atzerako kontaketarekin eta formulekin, 3D eta lehiaketa"],
"edu_bio_mendel":["Mendel eta ilarrak","Baratze-koadernoa: agertzen diren ilarrak, belaunaldiak Eraldatu bidez, Punnett karratua, barrak eta eraztuna, denbora-lerroa eta lehiaketa"],
"edu_bio_microbes":["Mikrobioak: mundu ikusezina","Mikroskopioaren okularra: testu kurbatua, Eraldatu 40tik 400 handipenera, bakterio-formak, legamia lerroetan, bozketa eta Text Art"],
"edu_bio_photosynthesis":["Fotosintesia: fabrika berdea","Hostoa eguzkitan: 3D landarea, sarrera eta irteera animatuak, Eraldatu kloroplastora, ekuazioa, batez bestekoen taula, atzerako kontaketa, lerroak eta hutsuneak"],
"edu_bio_pollination":["Loretik fruitura","Udaberriko larrea: hegan doan erlea, lorearen atalak, etiketatu, treemap, Eraldatu loretik fruitura, 3D ahuakatea, kronologia eta hodeia"],
"edu_bio_respiration":["Arnasa hartu: airearen bidaia","Zeru irekia: arnasa hartzen duten birikak, airearen bidea, Eraldatu arnasa hartzean eta botatzean, bi eraztun, 3D botila, atzerako kontaketa eta lehiaketa"],
"edu_body":["Giza gorputza","Laborategi estiloa: 3D irudia Eraldatu-rekin, ibilbide batean dabilen pertsonaia, barra-grafikoa, gorputza etiketatu eta galdetegia"],
"edu_cell":["Zelula","Formekin marraztutako zelula, zatiak banan-banan, Eraldatu hurbiltzeko, bikoteak lotu, diagrama, 3D landarea eta balorazioa"],
"edu_english":["Ingelesa hasiberrientzat","Ikasgela modua: soinuarekin biratzen diren txartelak, ibili eta agurtzen duen 3D robota, 3D azeria, hiru galdera puntuekin, sailkapena eta txaloak"],
"edu_fractions":["Zatikiak","Neon estiloa: marraztutako pizzak, ekuazioak urratsez urrats, batuketa Eraldatu-rekin, hutsuneak bete, galdetegia eta erronka atzerako kontaketarekin"],
"edu_geo_cities":["Hiria: nola hazten den","Gaueko hiria goitik: neoizko Text Art, area-grafikoa, marraztutako planoak, eraztunak Eraldatu-rekin, diagrama erradiala eta 3D autoa"],
"edu_geo_climograph":["Klimograma bat irakurtzea","Estazio meteorologikoa: igotzen den termometroa, barrak lerroarekin, formuladun taula, ekuazioak, 3D satelitea, lotu eta atzerako kontaketadun erronka"],
"edu_geo_coasts":["Kostaldeak eta itsasaldiak","Argi-sorta biratzen duen itsasargia, kostaldeko formak banan-banan, higatzen den itsaslabarra, itsasaldiak grafikoan eta formuladun taulan, etiketatzea"],
"edu_geo_continents":["Kontinenteak eta ozeanoak","Haurrentzako atlasa: soinuarekin agertzen diren kontinenteak, zuhaitz-mapa, ozeanoen donuta, mundua zeharkatzen duen 3D robota, lotu eta etiketatu"],
"edu_geo_deserts":["Basamortuak","Dunak ilunabarrean: aurrera doan karabana, urrezko Text Art, barra- eta lerro-grafikoak, 3D azeria, marraztutako oasia, marratutako mitoak eta lehiaketa"],
"edu_geo_mountains":["Mendiak","Alpeetako kartela: erliebearen atalak banan-banan, tenperaturaren ekuazioa eta taula, landaredi-solairuak piramidean, igotzen den 3D mendizalea eta ordenatu"],
"edu_geo_pyramids":["Biztanleria-piramideak","Errolda-kartela: barraz barra eraikitzen den piramidea, hiru forma Eraldatu-rekin, lerro-grafikoa, ekuazioak, ordenatu eta lehiaketa"],
"edu_geo_river":["Ibai baten bidaia","Akuarela: tanta batek zeharkatzen duen bitartean marrazten den ibaia, zooma Eraldatu-rekin, emaria ekuazioarekin, formuladun taula eta etiketatzea"],
"edu_geo_timezones":["Ordu-eremuak","Aireportuko panela errenkada biragarriekin, ekuazioarekin biratzen den Lurra, ordu-eremuak zeharkatzen dituen Eguzkia, formuladun taula, 3D erlojua eta hutsuneak"],
"edu_geo_topomap":["Mapa topografiko bat irakurtzea","Orientazio-mapa: marrazten den ibilbidea, eskala ekuazioarekin, formuladun taula, sestra-kurbak Eraldatu-rekin eta 3D korrikalaria"],
"edu_hist_alandalus":["Al-Andalus: zientzia eta lorategiak","Ferra-arkua, kronologia banan-banan, barra horizontalak, biratzen den astrolabioa, izarra Eraldatu bidez, bikoteak lotu eta bozketa"],
"edu_hist_castle":["Gazteluak eta feudalismoa","Gaueko gaztelua eta zubia zeharkatzen duen 3D zalduna, altxatzen den piramide feudala, etiketatu, eguna zeharkatzen duen eguzkia, treemap eta armarriak"],
"edu_hist_egypt":["Egipto, Niloren oparia","Lapitzuli eta urrea: piramideen atzetik ateratzen den eguzkia, uholde animatua, azalera-grafikoa, ekuazioa, Eraldatu, kartutxo hieroglifikoa eta ordenatu"],
"edu_hist_greece":["Atenas: demokrazia jaio da","Irudi beltzeko ontzi estiloa: meandroa, testu kurbatua, Eraldatu, eraztuna, altxatzen den tenplua, soinudun ostrakak, bozketa eta taula"],
"edu_hist_maya":["Maiak: denbora eta izarrak","Oihana eta jadea: puntu eta marrazko zenbakiak, Eraldatu 20 oinarrira, ekuazioa, biratzen diren egutegi-gurpilak, argizko sugea eta kakaoa"],
"edu_hist_mesopotamia":["Mesopotamia: idazkera jaio da","Bere kabuz idazten den buztinezko taula, ibaiak marrazten dituen mapa, hazten den zigurata, 60 oinarria formulekin, hutsuneak bete eta erradiala"],
"edu_hist_printing":["Inprenta: liburua ugaltzen da","Inkunable-orria: hasierako letra gorria, alderantzizko tipoak Eraldatu bidez konposatuak, soinuz jaisten den prentsa, zifrak, barrak eta hutsuneak"],
"edu_hist_rome":["Erroma, inperioko ingeniariak","Marmola eta gorri inperiala: Eraldatu, garaipen-arkua, geruzaz geruzako galtzada martxan doan 3D soldaduarekin, akueduktua, ekuazioa, formulak eta lehiaketa"],
"edu_hist_silkroad":["Zetaren Bidea","Zeta eta azafraia: martxan doan karabana, ibilbidea marrazten den mapa, prezioaren ur-jauzia, formuladun taula, 3D farola, ekuazioa eta ordenatu"],
"edu_hist_vikings":["Bikingoak, iparraldeko nabigatzaileak","Fiordoa aurora azpian: kulunkatzen den ontzia, errunak, zigiluz ezabatutako mitoak, zeharkaldi animatua, soinudun zifrak, 3D gudaria, radarra eta lotu"],
"edu_kids_colors":["Koloreak","Margo-mahaia: bere kabuz marrazten den ostadarra, soinudun potoak, nahasketak Eraldatu-rekin, ikonoak, lotu, bozketa eta atzerako kontaketa"],
"edu_kids_emotions":["Nola sentitzen naiz?","Eraldatu-rekin emozioz aldatzen den aurpegi marraztua, aurpegien girlanda, arnasteko puxika, bozketa eta lotu"],
"edu_kids_farm":["Baserriko animaliak","Baserri marraztua bere animaliekin, marrazten diren lerroak, batuketadun taula, martxan dagoen 3D kamioia, ibiltzen den 3D azeria, lehiaketa eta etiketatu"],
"edu_kids_numbers":["Zenbakien trena","Soinuarekin sartzen den tren marraztua, banan-banan zenbatu, ezkutuko zenbakiak, batuketa ekuazioan, grafikoa, ordenatu, lehiaketa eta atzerako kontaketa"],
"edu_kids_sea":["Itsaspean","Itsas hondoa gradientean, igerian dabiltzan arrain marraztuak, burbuilak, handia eta txikia, 3D botila edukiontzira, lotu eta hitz-hodeia"],
"edu_kids_seasons":["Lau urtaroak","Eraldatu-rekin lau urtaroetan aldatzen den zuhaitza, erortzen diren hostoak eta elurra, urtearen gurpila, zikloa, lotu eta bozketa"],
"edu_kids_senses":["Bost zentzumenak","Kartoi moztua: aurpegi marraztua, diagrama erradiala, asmakizunak, bost soinuko botoiak, biratzen diren txartelak, etiketatu eta atzerako kontaketa"],
"edu_kids_shapes":["Formak eta blokeak","Jolas-alfonbra: soinudun blokeak, bere kabuz marrazten diren formak, Eraldatu-rekin robot bihurtzen den etxea, 3D robota eta piramidea"],
"edu_kids_space":["Ilargirako bidaia","Gaueko zerua: soinuarekin aireratzen den suziria, atzerako kontaketa, Lurraren inguruan biratzen duen Ilargia, faseak, 3D astronauta eta ilargi-modulua"],
"edu_kids_transport":["Nola bidaiatzen dugu?","Errepide-alfonbra: 3D jostailu-autoa, soinuarekin igarotzen diren ibilgailuak, aldatzen den semaforoa, grafikoa, 3D autoa, lotu eta bozketa"],
"edu_lang2_advent":["Alemana: Abendualdia eta Eguberriak","Gau elurtsua: urrezko Text Art, 3D farola, erortzen diren malutak, irekitzen den Abendualdiko egutegia, kronologia, etiketatzea eta formuladun errezeta"],
"edu_lang2_artikel":["Alemana: der, die, das","Bauhaus kartela: soinuarekin sartzen diren formak, amaierak taulan, donuta, Eraldatu akusatibora, bikoteak lotu eta lehiaketa"],
"edu_lang2_cafe":["Frantsesa: au café","Bistro-arbela toldoaren azpian: testu kurbatua, kontua taulako formulekin, prezioen ekuazioa, elkarrizketa, barrak eta hutsuneak"],
"edu_lang2_directions":["Ingelesa: nola iritsi…ra","Asmatutako metro-mapa: tren batek ibilbidea egiten du Ibilbidearekin, bidean esaldiak, elkarrizketa, marraztutako kalea, ordenatzea, lehiaketa eta atzerako kontaketa"],
"edu_lang2_falsefriends":["Lagun faltsuak ingelesez","Detektibe-espedientea: soinudun zigilua, 3D eguzkitako betaurrekoak, biratzen diren susmagarriak, frogen taula, barrak, marratuak eta bozketa"],
"edu_lang2_ola":["Portugesa: Olá, Lisboa!","Azulejoak eta muinoa Ibilbidearekin igotzen duen tranbia horia, biratzen diren agurrak, soinuen taula, mugikorreko txata eta zuhaitz-mapa"],
"edu_lang2_passato":["Italiera: il passato prossimo","Rivierako postala: 3D autoa kostaldean barrena Ibilbidearekin, ekuazioa, partizipioak taulan, komunztadura, hutsuneak eta lehiaketa"],
"edu_lang2_phrasal":["Phrasal verbs: level up","Neoizko arcadea: Text Art, aditza eta partikula batzen dituen Eraldatu, aurrera doan 3D zalduna, barrak, marratua, lotu eta atzerako kontaketa"],
"edu_lang2_sons":["Frantsesa: soinuak","Biraka dabilen biniloa testu kurbatuarekin, soinudun pistak, arku gisa marrazten diren loturak, arauen taula, radarra, lehiaketa eta atzerako kontaketa"],
"edu_lang2_tenses":["Present perfect ala past simple","Erlojugintza: 3D erlojua Eraldatu-rekin, bere kabuz marrazten den arkudun denbora-lerroa, ekuazioak, taula, % 100eko barrak, zuhaitza eta atzerako kontaketa"],
"edu_lang_accent":["Azentu grafikoa beldurrik gabe","Koadernoa eta boligrafo gorria: argitzean soinua duten silabak, taula, erabaki-zuhaitza, marratu animatuak, ohar itsaskorrak eta lehiaketa"],
"edu_lang_becquer":["Bécquer eta Rimak","Gau erromantikoa: ilargia zeharkatzen duten enarak, testu kurbatua, bakarrik agertzen diren bertsoak, 3D farola, kronologia, metrika taulan eta hutsuneak"],
"edu_lang_calderon":["Bizitza amets da","Soinuarekin irekitzen eta ixten den oihala, antzoki-korralaren planoa, 3D tronua Eraldatu-rekin, bakarrizketa bertsoz bertso, erradiala, balantza eta lehiaketa"],
"edu_lang_commentary":["Testu bat nola iruzkindu","Bere kabuz marrazten diren subrailatzaileak eta albo-oharrak dituen orria, galoiak banan-banan, kronologia, ekuazioa, atzerako kontaketa, errubrika eta radarra"],
"edu_lang_fables":["Alegiak: azeria eta mahatsak","Ipuin-liburua: oinez sartzen den 3D azeria, izenburu kurbatua, kronologia, marraztutako parra, mailak, taula, ordenatu eta hitz-hodeia"],
"edu_lang_figures":["Figura erretorikoak komikian","Pop komikia: binetak, bunbuiloak eta leherketak soinuarekin, ibilbide batean hegan doan 3D erlojua, koloreztatzen diren bertsoak eta lehiaketa"],
"edu_lang_genres":["Genero literarioak","Liburutegia gauez: apalera igotzen diren liburuak, soinuarekin zigilatutako fitxak, Venn, hierarkia, eraztuna, bozketa, lotu eta 3D besaulkia"],
"edu_lang_lazarillo":["Lazarillo de Tormes","Pergaminoa eta zigilu-argizaria: nagusiz nagusi mapa zeharkatzen duen 3D pikaroa, txartelak, nagusien taula, gosearen lerroa, lehiaketa eta ordenatu"],
"edu_lang_meter":["Bertsoaren musika: metrika","Soinu-estudioa: bere kabuz marrazten den uhina, metronomo baten moduan jotzen duten silabak, kasuko ekuazioa, sinalefa, sonetoa pistaka eta lehiaketa"],
"edu_lang_syntax":["Subjektua eta predikatua, planoan","Plano teknikoa: Eraldatu-rekin ordenatzen diren piezak, marrazten diren kortxeteak, zuhaitz sintaktikoa, taula, irudia etiketatu eta lehiaketa"],
"edu_math_coordinates":["Koordenatuak: altxorraren mapa","Altxorraren mapa: haize-arrosa testu kurbatuarekin, agertzen diren puntuak, pistei jarraitzen dien 3D pirata, marrazten den itsasontzia eta etiketatzea"],
"edu_math_integers":["Zenbaki osoak: itsasoa eta mendia","Itsas hondotik gailurrera: jauziak dituen zuzena, izotz Text Art, zero azpiko tenperaturak, igo eta jaisten den itsaspekoa, ordenatzea eta lehiaketa"],
"edu_math_primes":["Zenbaki lehenak","Terminal berdea: neoi propioa, Eratostenesen bahea klikez kliko 100 laukirekin, faktore-zuhaitza, kodea urratsez urrats, lehiaketa eta erronka"],
"edu_math_probability":["Probabilitatea: zortea neurtzea","Joko-mahai burdeos eta urrea: danbor-hotsarekin biraka dauden daduak, testu kurbatua, Laplaceren erregela, zuhaitza banan-banan, barrak, lerroak eta lehiaketa"],
"edu_math_proportion":["Proportzionaltasuna supermerkatuan","Erosketa-tiketa: errebotatzen duen zigilua, proportzionaltasun-taula formulekin, hiruko erregela urratsez urrats, kalkulatutako beherapenak, lerroak eta hutsuneak"],
"edu_math_pythagoras":["Pitagorasen teorema","Klarion-arbela: bere kabuz marrazten den irudia, hitzik gabeko frogapena Eraldatu-rekin, hirukoteak formulekin, 3D lasterbidea eta lehiaketa"],
"edu_math_sequences":["Segidak eta ereduak","Botanika-liburua: bere kabuz marrazten den Fibonacciren espirala, kateko harriak, txotxak formulekin, kodea, 3D landarea eta urrezko zenbakia"],
"edu_math_stats":["Estatistika: batezbestekoa, mediana eta moda","Koadrikulatutako koadernoa: ur-jauzian agertzen diren ohar itsaskorrak, maiztasunak formulekin, barrak, eraztuna graduekin, histograma eta zuzeneko bozketa"],
"edu_math_symmetry":["Simetria eta mosaikoak","Nazari azulejuak: biratzen den izarra, islatzen den tximeleta, translazioa, biraketa eta simetria animatuak, angelu-taula eta abaraska"],
"edu_math_volumes":["Azalerak eta bolumenak","Plano tekniko urdina: koadroa taulan, garapen laua, neurtutako 3D botila, bolumenak formulekin, barrak, betetzen duten konoak eta lotzea"],
"edu_pe_active":["60 minutu egunean","Kortxozko taula: txintxetadun oharrak, salto egiten duen 3D pertsonaia, astea formulekin, barra pilatuak, eraztuna, kodea eta ideia-horma"],
"edu_pe_athletics":["Atletismoa: korrika, jauzi, jaurti","Tartanezko pista: 3D pertsonaia, biratzen diren piktogramak, kaleen ekuazioa eta taula, irteera soinuekin, histograma, ordenatu eta podiuma"],
"edu_pe_basketball":["Saskibaloia: jaurtiketa eta erretiluan","Entrenatzailearen arbela: soinuarekin errebotatzen duen baloia, neurriak dituen pista, marraztutako parabola, jokaldia, taula formulekin eta etiketatu"],
"edu_pe_calm":["Lasaitasunera itzuli: luzatu eta arnastu","Egunsenti lasaia: 3D landarea, kutxa-arnasketa ibilbidearekin, hazi eta txikitzen den zirkulua, luzaketak, itua eta hitz-hodeia"],
"edu_pe_heart":["Bihotza martxan","Bihotz-monitorea: bere kabuz marrazten den elektroa, pultsuaren atzerako kontaketa, ekuazioa, zonak formulekin, azalera, mugikorra aplikazioarekin eta lehiaketa"],
"edu_pe_hydration":["Edan egarria izan aurretik","Ura eta burbuilak: 3D botila, betetzen den gorputza, izerdiaren barrak, edalontzia Eraldatu-rekin, kolore-eskala eta hutsuneak bete"],
"edu_pe_nutrition":["Kirolariaren platera","Koadrodun mahai-zapia: zatika zerbitzatzen den platera, eraztuna, 3D ahuakatea, gosariak formulekin, buelta ematen duten mitoak, lotu eta hitz-hodeia"],
"edu_pe_posture":["Bizitza osorako bizkarra","Sepia xafla: bizkarrezurra ornoz orno, katean doazen errotuluak, motxila formulekin, horrela ez eta horrela bai, 3D aulkia, atzerako kontaketa eta etiketatu"],
"edu_pe_sleep":["Lo egitea ere entrenatzea da","Gaueko leihoa: pizten diren izarrak, 3D lanpara, hipnograma, zikloa, erradiala, mugikorra mezuekin, katean doan errutina eta balorazioa"],
"edu_pe_warmup":["Jolastu aurretik berotu","Kiroldegiko parketa: korrika doan 3D robota, tenperatura-lerroa, galoiak, artikulazioak soinuarekin, atzerako kontaketa, ordenatu eta lehiaketa"],
"edu_quixote":["Don Kixote","Tinta eta paper estiloa: soinuarekin biratzen den errota, testu kurbatua, aipu animatuak, Eraldatu, kronologia, hutsuneak bete eta galdetegia"],
"edu_renewables":["Energia berriztagarriak","Biratzen den aerosorgailua, txartelak, azalera-, eraztun- eta barra taldekatuen grafikoak, zuzeneko hitz-hodeia, bozketa eta atzerako kontaketa"],
"edu_revolution":["Frantziako Iraultza","Paper zaharraren estiloa: testua zirkuluan, Eraldatu, gizarte-piramidea, kronologia animatua soinuarekin, gertaerak ordenatu eta bozketa"],
"edu_spain":["Espainiako geografia","Atlas estiloa: haize-arrosa, erliebea itu moduan, ibaien taula formulekin, gailur eta euri grafikoak, bikoteak lotu eta galdetegia"],
"edu_volcanoes":["Sumendiak","Su estiloa: erupzio animatua soinuarekin, sumendiaren zatiak etiketatzeko, taula, denboradun galdetegia eta atzerako kontaketa"],
"edu_water":["Uraren zikloa","Ziklo-diagrama banan-banan, igotzen diren tantak eta euri animatua soinuarekin dituen paisaia, eraztun-grafikoak, bikoteak lotu eta 3D satelitea"],
"learn_revela_ai":["Revelaren AA","Txat bat aurora azpian: aurkezpen bat sortzea, testuak berridaztea (Eraldatu hitzez hitz erabiliz), irudiak, laguntzailea eta laguntza gehiago"],
"learn_revela_anim":["Animazioak urratsez urrats","Antzoki bat: sarrera, enfasia, irteera eta ibilbideak, aurrekoarekin edo ondoren hastea, animazio-panela, efektu gehiago eta soinuak"],
"learn_revela_collab":["Elkarlanean aritu eta partekatu","Kortxozko taula bat: aldi berean elkarlanean, partekatzeko baimenak, benetako iruzkinak eta zereginak, estekak, bertsioak eta lotzeko jarduera bat"],
"learn_revela_design":["Diseinua: txantiloia, gaiak eta koloreak","Lagin-liburu bat: txantiloia eta diapositiben diseinuak, gaiak, paletak eta letra-tipoak, kalkulatutako kontrastea, Text Art, testu kurbatua eta diseinu-ideiak"],
"learn_revela_export":["Esportatu eta eraman","Irteeren panel bat: PDF, PowerPoint, bideoa, web-orria, SCORM, oharrekin inprimatzea eta teklatu-lasterbideak, azken bozketarekin"],
"learn_revela_first":["Zure lehen aurkezpena 5 minututan","Bost urratseko errezeta: adibideen galeria, diapositiben diseinuak, idaztea, irudi bat txertatzea eta aurkeztea, atzerako kontaketarekin"],
"learn_revela_live":["Zuzeneko bozketak eta jarduerak","Lehiaketa-plato bat: bozketa, hitz-hodeia, puntuzko galdetegia, atzerako kontaketa, sailkapena eta ordenatzeko jarduera, benetakoak"],
"learn_revela_morph":["Eraldatu: metamorfosia","Beldarretik tximeletara Eraldatu erabiliz: bikoiztu animatuz, objektuka, hitzez hitz eta karakterez karaktere, eraldatzen diren diapositiben bidez"],
"learn_revela_pptx":["PowerPoint bat inportatu eta jarraitu","Etxe-aldaketa bat: .pptx bat nola inportatu, zer gordetzen den (txantiloia, animazioak, Eraldatu, oharrak) eta nola esportatu berriro"],
"learn_revela_present":["Profesional baten moduan aurkeztu","Hegazkin-kabina bat: moderatzailearen ikuspegia, oharrak, mugikorra urruneko kontrol gisa, laser-erakuslea eta tinta, arbela, atzerako kontaketa eta lasterbideak"],
"life_bookclub":["Irakurketa kluba","Eskuz marraztutako apalategia, formekin egindako azala, eraldatzen diren aipuak, diagrama erradiala, balorazioa eta hurrengo liburuaren bozketa"],
"life_cv":["Curriculum bisuala","Testua zirkuluan, zifrak, kronologia urratsez urrats, trebetasun-barra animatuak, radarra, pantailak gailuetan eta kontaktua"],
"life_fitness":["Entrenamendu-plana: 5 km","3D korrikalaria, su-Text Art, gradientedun faseak, formuladun astea, aurrerapen-grafikoak, piramidea, atzerako kontaketa eta hitz-hodeia"],
"life_garden":["Hiri-baratzea","3D landarea Eraldatu-rekin, ereintza-egutegia koloretako taulan, zikloa, Venn, ureztatze- eta hazkunde-grafikoak, etiketatzeko jarduera"],
"life_graduation":["Graduazioa eta ikasturte-amaiera","Urre-Text Art, formekin egindako birreteak, sartzean biratzen diren polaroidak, danbor-hotsa duten zifrak, eskerrak, hitz-hodeia eta txaloak"],
"life_italy":["Bidaia Italian zehar","Testua zirkuluan, lotuneak eta ibilbide animatua dituen bidea, kronologia, formulak dituen aurrekontua, grafikoak eta parekatzeko jarduera"],
"life_kids_party":["Haur-urtebetetzea","Kolore biziak: dantzan ari den 3D robota, ospatzen duten pertsonaiak, eskuz marraztutako puxikak, puntuzko lehiaketa eta atzerako kontaketa"],
"life_moving":["Etxe-aldaketa eta etxe berria","Eskuzko formekin egindako etxea, kronologia, marratzen den zerrenda, Eraldatu bidez planora pasatzen diren 3D altzariak, aurrekontua eta ordenatzeko jarduera"],
"life_recipe":["Errezeta: guacamolea","Diapositiben artean bidaiatzen duen 3D ahuakatea (Eraldatu), formuladun osagaiak, urratsak banan-banan, atzerako kontaketa eta balorazioa"],
"life_travel_eu_amsterdam":["Amsterdam: ubideak eta bizikletak","Katean muntatzen diren ubide-fatxadak, ubideak jomuga gisa, soinuz gurutzatzen duen bizikleta, formuladun taula, lerroak eta tarta-bozketa"],
"life_travel_eu_camino":["Done Jakue Bidea: Sarriatik","Soinudun zigiluz betetzen den kredentziala, kilometro-ur-jauzia, 3D oinezkoa, motxilaren ekuazioa, donuta eta etapak ordenatzea"],
"life_travel_eu_croatia":["Kroazia belaontziz Dalmazian","Itsas karta, biratu eta Eraldatu-rekin bidaiatzen duen haize-arrosa, banderak, parekatu, formuladun miliak, lehiaketa eta atzerako kontaketa"],
"life_travel_eu_danube":["Danubio bizikletaz","Txirrindulari-ordenagailu estiloa: ibilbidea mugikorrean, GPX fitxategia urratsez urrats, pilatutako barrak, 3D botila Eraldatu-rekin, formulak eta laukizuzenak"],
"life_travel_eu_fjords":["Norvegiako fiordoak uretatik","Geruzatutako paisaia islekin, nabigatzen duen itsasontzia, bere kabuz marrazten den fiordo-ebakidura, barrak, radarra, urratsak eta aukera anitzeko bozketa"],
"life_travel_eu_greece":["Greziako uharteak ferryz","Formaz egindako herri zuria, greka, bere kabuz marrazten den ibilbidea, formuladun ordutegiak, burbuilak, 3D betaurrekoak Eraldatu-rekin eta ilunabarra"],
"life_travel_eu_iceland":["Islandia: Ring Road autoz","Gradientedun aurorak, soinudun ibilbidea mapan, 3D autoa, danborrada duten zifrak, hotzaren ekuazioa, oinez doan azeria eta lehiaketa"],
"life_travel_eu_lisbon":["Lisboa: muinoak eta tranbiak","SVG azulejoak, muinoak igotzen dituen tranbia soinuarekin, altuera-profila, biratzen diren txartelak, formuladun taula eta hutsuneak"],
"life_travel_eu_prague":["Praga, ehun dorreen hiria","Formaz egindako erloju astronomikoa, biratu eta Eraldatu-rekin bidaiatzen duena, kanpaitxodun desfilea, atzerako kontaketa, etiketatzeko mapa eta taula"],
"life_travel_eu_scotland":["Eskozia: Highlandak autoz","Formaz ehundutako tartana, marrazten den errepidea, bidea uzten duten autoak, biratzen diren gazteluak, 3D farola, barrak eta galderak"],
"life_wedding":["Ezteiko gonbidapena","Tipografia klasikoa eta urrea: Text Art, testu kurbatua, bikotearen kronologia, ibilbide animatua duen mapa, bozketa eta atzerako kontaketa"],
"prod_app_bank":["Cartilla: adinekoentzako banka","Larruzko eta urrezko aurrezki-liburuxka: urrezko Text Art, mugikorra hurbiltzeko Eraldaketa, BATURA duen taula, ur-jauzia, zigilua eta iruzurraren aurkako lehiaketa"],
"prod_app_gym":["Serie: erreserbak zure gimnasioan","LED markagailua: ospatzen duen eta bere klaseraino oinez doan 3D borrokalaria, bi atzerako kontaketa, orduko okupazioa, formuladun tarifak eta lehiaketa"],
"prod_app_health":["Turno: hitzorduak osasun-zentroan","Klinikoa: marrazten den taupada, aurretik eta ondoren, zikloa banan-banan, oinez dabilen 3D gaixoa, agenda monitorean, barrak eta galderak"],
"prod_app_language":["Vocablo: hizkuntzak ikasteko aplikazioa","Aire-posta txartela: zigiluak, soinuarekin jauzi egiten duten bunbuiloak, biratzen diren txartelak, Eraldaketa, ahanzturaren ekuazioa, grafikoa eta lotu"],
"prod_app_market":["Plaza: auzoko merkatua etxera","Toldoa eta klarion-arbelak: planoa zeharkatzen duen 3D furgoneta, postuak erradialean, mugikorra, laukizuzenak, formuladun komisioak eta bozketa"],
"prod_app_meditation":["Marea: meditazio eta lo aplikazioa","Gaueko itsasoa: ilargia testu kurbatuarekin, mugikorraren Eraldaketa, kateatutako eraztunekin arnasketa gidatua, atzerako kontaketa, grafikoa eta 3D farola"],
"prod_app_music":["Garaje: auzoko zuzeneko musika","Biniloa eta neoia: Eraldaketarekin bidaiatzen duen diskoa, biratzen duen testu kurbatua, danbor-hotsdun ekualizadorea, eramangarria, radarra, tarta eta hitz-hodeia"],
"prod_app_photo":["Grano: filmeko argazkigintza","Gela iluna: film-zerrenda, Eraldaketarekin errebelatzen den argazkia, danbor-hotsdun kontagailua, histograma, tableta, taula eta etiketatu"],
"prod_app_recipes":["Sobras: dagoenarekin errezetak","Hozkailua postitekin: 3D ahuakatea Eraldaketarekin, osagaiak ezagutzen dituen mugikorra, urratsak, eraztuna, formuladun errezeta eta atzerako kontaketa"],
"prod_app_transit":["Andén: hiri-garraioa","Metroko seinaleztapena: irteeren panela atzerako kontaketarekin, bere kabuz marrazten den planoa, bidaia animatua, mugikorra, barra metatuak eta tarifak"],
"prod_hw_drone":["Cernícalo: mendiko erreskaterako dronea","Mapa topografikoa: dronea ibili ahala marrazten den hegaldia, NASAren 3D helikopteroa, ikuspegi termikoa, atzerako kontaketa, formulak eta lehiaketa"],
"prod_hw_ereader":["Folio: tinta elektronikoko irakurgailua","Orri-pasea duen liburua: hasierako letra handia, marraztutako irakurgailua, agertzen diren mikrokapsulak, zifra eta barrak, aipua, formuladun taula eta hutsuneak"],
"prod_hw_glasses":["Horizonte: txirrindularientzako datudun betaurrekoak","Errepidea lentetik: 3D betaurrekoak Eraldatu-rekin, soinudun zati zenbatuak, barrak, YAML kodea urratsez urrats, erradiala eta bozketa"],
"prod_hw_headphones":["Silencio: zarata ezabatzeko entzungailuak","Ganbera anekoikoa: beren kabuz marrazten eta ezeztatzen diren uhinak, ekuazioa, urratsez urratseko prozesua, maiztasun-kurba, formuladun taula eta bozketa"],
"prod_hw_keyboard":["Tecla: teklatu mekaniko modularra","Klik-soinuarekin jauzi egiten duten teklak, indar-kurbak, geruzakako zatiketa, teklen mapa kodean, formuladun aurrekontua eta ordenatu"],
"prod_hw_lamp":["Alba: lanpara iratzargailua","Egunsentia gradientean: eguzkia Eraldatu-rekin igotzen da, bidaiatzen duen 3D lanpara, kronologia, argi-kurba ekuazioarekin, Kelvin eskala eta balorazioa"],
"prod_hw_thermostat":["Templa: termostato adimenduna","Termostatoaren esfera eta ebakidurako etxea agertzen diren tenperaturekin, aurrezki-ur-jauzia, ekuazioak, 24 orduko lerroak, matrizea eta bozketa"],
"prod_hw_toycar":["Chispa: programatzen ikasteko autoa","Jolas-alfonbra: 3D autoa Eraldatu-rekin, soinuarekin jauzi egiten duten kartak, ibiltzen den taula, kodea, lehiaketa, eskailera eta donuta"],
"prod_hw_tracker":["Miga: ezer ez galtzeko kokagailua","Altxorraren mapa: X-raino banan-banan agertzen diren apurrak, eskuz marrazten den zirkulua, donuta, itua, auzoko arrastoa eta hitz-hodeia"],
"prod_hw_trailcam":["Vigía: argazki-tranpa kamera","Bisore infragorria: igarotzean kamera abiarazten duen 3D azeria, sentsorearen irismen marraztua, zifrak, orduko azalerak, BATURA duen taula eta lotu"],
"product_app":["Mugikorreko aplikazioaren aurkezpena","Aplikazioa mugikorrean, tabletan eta eramangarrian, Eraldatu, ibilbidea galoietan, zifrak, atxikipen-grafikoa eta hitz-hodeia"],
"product_car":["Aurkezpena: auto elektrikoa","Ertzetan moztu gabeko 3D autoa, sartzean bira ematen duena, Eraldatu, zifrak, azalera- eta barra-grafikoak, taula eta bozketa"],
"product_eco":["Produktuaren iraunkortasuna","Berde ekologikoa: 3D landarea Eraldatu-rekin, bizi-zikloa, aztarnaren ur-jauzia, materialen barrak, helburudun lerroak eta hutsuneak bete"],
"product_furniture":["Altzari-bilduma","Estilo editoriala: 3D sofak eta aulkiak, Eraldatu ikuspegi desberdinekin, kulunka eta bira, kolore-laginak, tableta eta aurrekontua"],
"product_keynote":["Hardware keynotea","Estilo zuri premium: lanpara irisatua eta 3D botila, Eraldatu etiketekin, flotatu eta hurbildu, zifrak, taula eta prezioak"],
"product_roadmap":["Produktuaren bide-orria","Bere kabuz marrazten den bidea, piramidea, kronologia banan-banan, orain eta gero, matrizea, barra pilatuak, aukera anitzeko bozketa eta ordenatzekoa"],
"product_robot":["Industria-robot laguntzailea","Estilo industriala: agurtzen duen 3D robota, ibilbide batean dabilena, animazioak kateatzen dituena eta dantzatzen duena; organigrama, zikloa, grafikoa eta lehiaketa"],
"product_saas":["SaaS plataformaren demoa","Panela nabigatzaile-leihoan dei zenbakidunekin, erradiala, inbutua, adierazleak, barra pilatuak, kodea urratsez urrats eta galderak"],
"product_security":["Produktuaren segurtasuna","Neoi berdea: geruzetako itua, urratsez urrats agertzen den fluxua lotzaileekin, kode nabarmendua, grafikoa, eskailera eta parekatzeko jarduera"],
"product_watch":["Aurkezpena: erloju adimenduna","Beltza eta urrea: 3D erlojua hiru diapositibatan zehar Eraldatu eta iritsiera desberdinekin, urrezko Text Art, radarra eta prezioak"],
"sci_ai":["Adimen artifiziala","Neoi morea: agurtu eta Eraldatu-rekin bidaiatzen duen 3D robota, kronologia, organigrama, pizten den sare neuronala, grafikoa eta hitz-hodeia"],
"sci_astro_blackholes":["Zulo beltzak","Beltz-beltza: Eraldatu-rekin bidaiatzen duen horizontea, testu kurbatua, zifra erraldoia, formuladun taula, 3D astronauta espiralean eta lehiaketa"],
"sci_astro_cosmology":["Big Bangetik gaur arte","Hozten ari den unibertsoa: termometroa Eraldatu-rekin, kronologia katean, hondo kosmikoa, sakabanatzea, donuta eta formuladun egutegia"],
"sci_astro_defense":["Planeta-defentsa: simulakroa","Krisi-gela: arrisku-marrak, 3D asteroidea, Torinoko eskala katean, soinudun desbideratze animatua, atzerako kontaketa eta taldeen bozketa"],
"sci_astro_exoplanets":["Beste mundu batzuen bila","Bidaia-kartel retroak: argi-kurba marraztua duen iragaitza, Python kodea, kulunka ibilbideekin, area, 3D satelitea eta bozketa"],
"sci_astro_moon":["Selenografia: Ilargia","Atlas zaharra sepian: SVGn grabatutako Ilargia, faseak katean, biraketa sinkronoa, itsasaldiak, 3D ilargi-modulua Eraldatu-rekin eta parekatu"],
"sci_astro_pulsars":["Pulsarrak: kosmosaren itsasargiak","Osziloskopio-pantaila: bere kabuz marrazten den seinalea, biraka dabilen itsasargia, entzuten diren pultsuak, 3D irrati-teleskopioa eta nebulosa, taula eta lehiaketa"],
"sci_astro_skywatch":["Zerua behatzeko gida","Argi gorriko modua: planisferioa testu kurbatuarekin, atzerako kontaketa, beren kabuz marrazten diren konstelazioak, magnitudeak, barrak, taula eta bozketa"],
"sci_astro_stars":["Izarren bizitza eta heriotza","Izar-espektroa: klaseak katean, oreka geziekin, H-R diagrama propioa, masaren araberako bidegurutzea, formuladun taula eta 3D supernoba"],
"sci_astro_sun":["Eguzkia, izar bat hurbiletik","Eguzki-iragazki karmina: geruzak katean, fusioa ekuazioarekin, fotoi baten bidaia, orbanen zikloa, 3D zunda Eraldatu-rekin eta lehiaketa"],
"sci_astro_telescopes":["Teleskopioak: planoa","Plano teknikoaren estiloa: marrazten diren izpiak, 3D Webb Eraldatu-rekin espektroan zehar, ispilu hexagonala katean, L2rako bidaia eta etiketatu"],
"sci_brain":["Neurozientzia: garuna","Estilo iluna distiraz: bultzada animatua duen neurona marraztua, oinez dabilen 3D irudia, erradiala, organigrama, barrak eta irudi bat etiketatu"],
"sci_chem":["Kimika: taula periodikoa","Laborategi garbia: urjauzian eraikitzen den taula periodikoa, formazko molekulak, 3D braseroa, ekuazioak, eraztuna eta parekatzea"],
"sci_climate":["Klima-aldaketa datuetan","Berotze-bandak, lerro, azalera eta laukizuzen grafikoak, bere burua marrazten duen berotegi-efektua, 3D satelitea, zikloa eta aukera anitzeko bozketa"],
"sci_mars":["Marterako misioa","Espazio-estilo herdoila: NASAren 3D rover-a Eraldatu-rekin, astronauta flotatzen, orbita animatua, ekuazioa eta lehiaketa"],
"sci_med_case":["Kasu klinikoa: sukarra eta eztula","Historia kliniko estiloa: karpeta, zigilua, erradiografia negatoskopioan marrazten den zirkuluarekin, CURB-65 formularekin, bozketa eta galderak"],
"sci_med_ecg":["Kardiologia: EKG bat irakurtzea","EKG papera: bakarrik marrazten diren trazuak, bihotza zeharkatzen duen bulkada, formuladun taula, ekuazioa, lehiaketa eta atzerako kontaketa"],
"sci_med_glucose":["Endokrinologia: glukosa eta intsulina","Glukosa-sentsorearen aplikazio estiloa: mugikorra pantailarekin, zikloa banan-banan, kurbak, eraztuna, formuladun taula, ekuazioa, 3D ahuakatea eta bozketa"],
"sci_med_immune":["Immunologia: erantzun immunea","Fluoreszentzia-mikroskopioa: pizten diren zelulak, marraztutako antigorputza, fagozitosia Eraldatu-rekin, organigrama eta lotzea"],
"sci_med_kidney":["Giltzurrunaren fisiologia: nefrona","Plano teknikoa: marrazten den nefrona, soinuarekin zeharkatzen duen tanta, kotak, ur-jauzia, ekuazioa, formuladun taula, 3D botila eta zikloa"],
"sci_med_knee":["Anatomia: belauna","Antzinako xafla anatomikoaren estiloa: testu kurbatua, sepia grabatua, Eraldatu meniskoetara, matrizea, taula, ibiltzen den 3D irudia eta etiketatzea"],
"sci_med_micro":["Mikrobiologia: antibiotikoen erresistentzia","Petri plakak: soinuarekin agertzen diren koloniak, hazkunde esponentziala, Eraldatu-rekin kontatutako hautaketa, antibiograma, erradiala eta hitz-hodeia"],
"sci_med_pk":["Farmakozinetika: erdibizitza","Botika-kutxa estiloa: betetzen den blisterra, LADME banan-banan, bi serieko kurbak, ekuazioak, formuladun taula, kodea eta hutsuneak"],
"sci_med_stroke":["Neurologia: ictus kodea","Larrialdietako erlojupekoa: sirena-argiak, danbor-hotsarekin zifra erraldoia, BE-FAST katean, eraztuna, galoiak, urratsak ordenatzea eta atzerako kontaketa"],
"sci_med_trial":["Saiakuntza klinikoa: emaitzak irakurtzea","Aldizkari zientifikoaren estiloa: CONSORT loturekin, biziraupen-kurbak, formuladun taula, NNT, kateatutako forest plot-a eta lehiaketa"],
"sci_newton":["Fisika: Newtonen legeak","Fisika-koadernoa: ekuazioak, mugitzen den 3D autoa, bere burua marrazten duen jaurtiketa parabolikoa, formuladun taula eta hutsuneak bete"],
"sci_nurse_cpr":["Oinarrizko BBB: bizi-euskarria","Larrialdietako seinaleztapen berdea: erritmoan sakatzen duten eskuak, soinuarekin hegan doazen DEAren adabakiak, bi serie, atzera-kontaketa eta ordenatu"],
"sci_nurse_drip":["Fluidoterapia: tantakatzea kalkulatu","Marraztutako serum-ekipoa soinuarekin erortzen diren tantekin, formula urratsez urrats, ebatzitako adibidea, kalkulatzen duen taula, ponpa eta atzera-kontaketa"],
"sci_nurse_falls":["Adinekoen erorketak: etxe segurua","Etxea gauez 3D lanpararekin: Eraldatu bidez konpontzen diren arriskuak dituen planoa, ibiltze-proba 3D irudiarekin, Venn, donuta eta atzera-kontaketa"],
"sci_nurse_hands":["Eskuen higienea: 5 uneak","Baldosak eta burbuilak: gora doazen xaboi-burbuilak, 5 uneak plano batean, UV lanpara soinuarekin, 30 s-ko atzera-kontaketa, barrak eta lehiaketa"],
"sci_nurse_heat":["Bero-boladak: osasun-plana","Alerta-koloreak: igotzen den termometroa, Text Art, marraztutako abisu-mapa, sakabanatze-diagrama, SMSa duen mugikorra, 3D botila, taula eta lehiaketa"],
"sci_nurse_herd":["Txertoak: talde-immunitatea","Txerto-txartela zigiluekin eta testu kurbatuarekin, katean kutsatzea Eraldatu bidez etenda, ekuazioa, formuladun taula, mito marratuak"],
"sci_nurse_outbreak":["Elikagai bidezko agerraldi bat ikertu","Kortxozko taula: txintxetadun oharrak eta bere kabuz marrazten den hari gorria, kurba epidemikoa, formuladun taula, arrisku erlatiboa, kodea eta bozketa"],
"sci_nurse_pressure":["Presio-ultzerak: prebenitu","Presio-mapa termikoa: piztu eta itzaltzen diren orbanak, Braden formulekin, biratzen duen jarrera-aldaketen erlojua, larruazal-geruzak eta etiketatu"],
"sci_nurse_sbar":["Txanda-aldaketa SBAR bidez","Solairuko arbel zuria: bere kabuz azpimarratzen duen errotuladorea, soinuarekin itsasten diren imanak eta oharrak, kateko elkarrizketa, formuladun eskala eta lotu"],
"sci_nurse_smoking":["Erretzeari utzi: zure gorputzak irabazten duena","Ketetik aire garbira: gora doan kea, denbora-lerro den zigarroa, Eraldatu bidez aldatzen diren birikak, aurrezki-taula eta arnasketa"],
"sci_python":["Python programazioa","Editore ilunaren estiloa: bere kabuz idazten den terminala, nabarmentze-urratsak dituen kodea, irteera animatua, lerroak ordenatu eta atzerako kontaketa duen erronka"],
"sci_solar":["Eguzki-sistema","Eskalan dauden planetak katean agertzen, hiru 3D zunda ikuspegi eta mugimendu desberdinekin, taula, diagrama erradiala eta parekatzea"],
"sci_stats":["Estatistika eta probabilitatea","Estilo editoriala: bere burua marrazten duen kanpaia, formulak, histograma, sakabanatzea, azalera, barrak eta burbuilak, eta puntudun galdera"],
"sci_thesis":["GrALaren defentsa","Akademiko soila: azal instituzionala, aurkibidea, ekuazioa duen metodologia, guztizkoak dituen taula, emaitzak grafikoetan, bibliografia eta galderak"],
"show_anim_bike":["Bizikletaren aldagailuak, misteriorik gabe","Mugimendu sinkronizatuak: benetako erlazioan biratzen diren engranajeak, beren distantzia egiten duten gurpilak, bi errei batera eta taula"],
"show_anim_blueprint":["Etxebizitza baten berrikuntza: planoa","Bere kabuz marrazten den planoa: hormak katean, kotak, desagertzen den eraisketa, Eraldatu banaketa berrira, instalazioak eta obra"],
"show_anim_ferries":["Ferryak uharteen artean: udako ibilbideak","Ibilbideak mapa batean: bidearekin biratzen diren itsasontziak, igarotzean marrazten diren ibilbideak, hiru linea batera, geldialdia eta ordutegiak"],
"show_anim_firefly":["Ipuina: argirik gabeko ipurtargia","Sarrera eta irteeraz egindako ipuina: kontakizuna bere urratsean soilik ikusgai, agertu eta joaten diren elkarrizketak, hegaldiak eta itzultzen den argia"],
"show_anim_foosball":["Bulegoko futbolin txapelketa","Soinuekin kateatutako animazioak joko batean bezala: klik egindako paseak, jaurtiketa, txaloekin gola, aurrera doan taula, sailkapena eta porra"],
"show_anim_guitar":["Gitarra espainiarraren anatomia","Abiarazleak: klik gitarraren atal bakoitzean bere fitxa ikusteko eta soka bakoitzean dardaraz dadin; biraka doan errosetoia"],
"show_anim_haiku":["Haiku tailerra: hitzez hitz","Hitz eta paragrafoen araberako animazioa: bertsoak hitzez hitz, agindua esaldiz esaldi, silaba zenbatuak eta Eraldatu"],
"show_anim_rpg":["Mahai-rola: zure lehen partida","3D pertsonaiak beren animazioekin: eraso, blokeatu, sorginkeriak bota eta erori; aurkariarengana oinez joan, biraka doan dadoa eta jaisten den bizitza"],
"show_anim_speech":["Hitzaldia: salba dezagun liburutegia","Hitzaldi baten erritmoko enfasia: esaldia fokuan eta gainerakoa itzalita, marratu, nabarmendu, eskuz egindako azpimarra eta zirkulua, atzerako kontaketa"],
"show_anim_tshirt":["Infografia: kamiseta baten bidaia","Bere burua erakusten duen infografia: geltokiak garaiz dituen ibilbide marraztua, betetzen den tanta-piktograma, ur-jauzia, zifrak eta formula"],
"showcase_3d":["Katalogoa: 3D sakonean","3D ereduak aukera guztiekin: ikuspegiak, sartzean mugimenduak, biraketa, ertzak, marjina, klipak, ibiltzea eta Eraldatu bidezko iristea"],
"showcase_animations":["Katalogoa: animazioak","Objektuen animazio guztiak: sarrera, enfasia, irteera, ibilbideak, marraztu, kateatuak, soinuak eta hainbat objektu bakarrean"],
"showcase_charts":["Katalogoa: grafikoak","15 grafiko motak, bi diapositiba bakoitzeko, serieekin, konbinatuarekin, saretarekin, etiketekin eta ardatzen izenburuekin, eta aukeren taula"],
"showcase_diagrams":["Katalogoa: diagramak","Eskema gisa idatzitako 15 diagrama-diseinuak, 4 kolore-eskemak eta aurkeztean banan-banan agertzea"],
"showcase_morph":["Katalogoa: Eraldatu","Eraldatu urratsez urrats: tamaina eta lekua aldatzen dituen testua, formak, hazten diren barrak, irudia, 3D eta berrantolatzen diren letrak"],
"showcase_objects":["Katalogoa: multimedia eta objektuak","Kodea urratsekin, ekuazioak, ikonoak, bost gailu, estilo eta formuladun taulak, diapositiba-zooma eta konektoreak"],
"showcase_polls":["Katalogoa: bozketak eta jarduerak","Mugikorretik egiteko 11 bozketa eta jarduera mota, atzerako kontaketa bere hiru estiloetan, sailkapena eta ikasgela modua"],
"showcase_shapes":["Katalogoa: formak","Forma guztiak kategoriaka bere izenarekin, lerroak eta marrak, gradienteak, opakutasuna, eskuzko trazua, itzalak, barruko testua eta biraketa"],
"showcase_text":["Katalogoa: Text Art eta tipografia","Text Art-en 10 estiloak, testu kurbatua, zutabeak, bost buleta-maila, 8 letra-bikoteak, lerrokatzea eta tartea"],
"showcase_transitions":["Katalogoa: trantsizioak","22 diapositiba-trantsizioak, banan-banan: sarrera, irteera desberdina, norabideak, abiadura eta aurrerapen automatikoa"]};
