// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Hiruhileko emaitzak kontseiluari","Urdin iluna eta urrea: soinudun adierazle handi animatuak, ur-jauzia, inbutua, barra metatuak eta aurrekontuarekin alderatzeko formuladun taula"],
"biz_climate":["Lan-giroari buruzko inkesta","Morea eta parte-hartzailea: atzerako kontaketa, % 100eko barrak, 1etik 5erako balorazioa, hitz-hodeia, aukera anitzekoa eta publikoaren galderak"],
"biz_investment":["Inbertitzaileentzako aurkezpena","Beltza eta urrea: biratu eta Eraldatu erabiliz bidaiatzen duen 3D produktua, zifra erraldoiak, merkatua zirkuluetan, trakzioa, funtsen erabilera eta taldea"],
"biz_marketing":["Kanpainaren marketin plana","Estilo beroa: testua zirkuluan, xede-publikoa, inbutua, kanalen nahasketa, egutegia taulan, aurrekontua formularekin eta bozketa"],
"biz_onboarding":["Langile berriei ongietorria","Estilo atsegina: agurtu eta astean zehar oinez dabilen 3D robota, organigrama banan-banan, balioak ikonoekin eta parekatze-jarduera"],
"biz_proposal":["Bezero baterako proposamen komertziala","Paper estiloa: zigilua, prozesua banan-banan, maketak eramangarrian eta mugikorrean, prezioak, BEZa formuletan duen aurrekontua, kronologia eta bermeak"],
"biz_roadmap":["Proiektu baten ibilbide-orria","Estilo tekniko iluna: galoiak banan-banan, Gantt diagrama animatua, kronologia, Eraldatu erabiliz aurrera egiten duen 3D autoa eta egoera-taula"],
"biz_sales":["Salmentak eta urteko aurreikuspena","Gris minimalista: barra eta lerro konbinatuak, agertokiak, aurreikuspen-formula, formuladun taula, barra metatuak eta horizontalak"],
"biz_strategy":["Plan estrategikoa eta OKRak","Estilo garbia zuriz: katean sartzen diren zifrak, piramidea, lehentasunak ikonoekin, OKR taula, aurrerapen-barrak, radarra eta galoiak"],
"biz_swot":["AMIA analisia eta lehiakideak","Grafito-hondoa: AMIA koadranteka, estrategien matrizea, posizionamendu-mapa, barra taldekatuak, Venn, tarta eta aukera anitzeko bozketa"],
"creative_bauhaus":["Bauhaus: forma eta funtzioa","Bauhaus arte geometrikoa: biratu eta errebotatzen duten oinarrizko formak, kronologia, Eraldatu sareta bat eta parekatze-jarduera"],
"creative_brutalism":["Brutalismoa: web manifestua","Estilo brutalista: tipografia erraldoia, bloke beltzak, testu bertikala, itzal gogorrak, marratu animatua, taula eta bozketa"],
"creative_comic":["Komikia: animalien superbotereak","Komiki estiloa: binetak, elkarrizketa eta pentsamendu bunbuiloak, errebotatzen duten Text Art onomatopeiak, 3D azeria, grafikoa eta lehiaketa"],
"creative_fashion":["Moda aldizkaria: udazken geldoa","Aldizkari estiloa: serif goiburua, 3D erlojua azalean, zutabeak hasierako letra handiarekin, aipu handia, denboraldiko paleta eta grafikoa"],
"creative_glass":["Glassmorphism: finantza aplikazioa","Txartel zeharrargiak kolore-distiren gainean, aplikazioa mugikorrean, eraztun-grafikoa, Eraldatu txartel bat eta balorazio-bozketa"],
"creative_pixel":["Pixel art: zure lehen bideojokoa","Bideojoko retro estiloa: pixel spriteak, markagailua, ibili eta salto egiten duten 3D pertsonaiak, urratsez urratseko kodea, lehiaketa eta atzerako kontaketa"],
"creative_space":["Galaxia: iraganera begiratzea","Espazio estiloa: izarrak, nebulosa distiratsuak, NASAren 3D ereduak, planetak zeharkatzen dituen zunda, testu kurbatua eta lehiaketa"],
"creative_synthwave":["Synthwave: Neón 86 jaialdia","80ko hamarkadako estilo retroa: eguzki gradientea, bere kabuz marrazten den sareta, neoi distiratsua, Eraldatu, dantzan dabilen 3D robota eta hitz-hodeia"],
"creative_watercolor":["Akuarela: baratzea balkoian","Akuarela eta paper estiloa: gradiente erradialeko orbanak, eskuz egindako formak, eskuzko letra, bere kabuz marrazten den marrazkia eta 3D"],
"creative_zen":["Japoniar minimalismoa: tea","Japoniar minimalismoa: zuri asko, eraldatzen den eguzki gorria, testu bertikala, bere kabuz margotzen den ensōa eta atzerako kontaketa"],
"data_ab_test":["A/B esperimentua","Ekuazioak, bi serieko sakabanatzea, etiketadun zutabeak, formuladun bihurketa-taula eta esangura-zifrak"],
"data_energy":["Energia eta kontsumoa","Orduko azalera metatuak, hiru serieko lerroak, laukizuzenak, etiketadun zutabeak eta tarifa-taula kalkulatua"],
"data_exec_panel":["Hileko zuzendaritza-panela","Semaforo eta minigrafikodun KPIak, aurrekontuaren aurkako konbinatua, multiplo txikiak, eraztuna eta bozketa"],
"data_home_finance":["Finantza pertsonalak","Soldatatik aurrezkira doan ur-jauzia, grafiko zirkularra, lerroak eta azalera, BATURA, BATEZBESTEKOA, MAX eta MIN dituzten taulak"],
"data_market_study":["Merkatu-azterketa","Zifra handiak, laukizuzen-grafikoa, burbuilak, sakabanatzea, bi serieko barra horizontalak eta 2 × 2 matrizea"],
"data_population":["Biztanleria eta demografia","Biztanleria-piramidea, histograma, barra horizontalak, gurutzatzen diren lerroak eta formuladun adierazle-taula"],
"data_sales_regions":["Salmentak eskualdeka","Barra taldekatuak, metatuak eta % 100ekoak, helburudun grafiko konbinatua, formula bidezko guztizkoak dituen taula eta KPI animatuak"],
"data_satisfaction":["Gogobetetze-inkesta","Legendadun eraztuna, radar konparatuak, etiketadun zutabeak, NPS, balorazioa eta hitz-hodeia zuzenean"],
"data_season_stats":["Denboraldia zenbakitan","Soinudun zifra erraldoiak, formuladun sailkapena, barra negatiboak, lerroak, metatuak eta taldearen radarra"],
"data_web_metrics":["Web eta marketin metrikak","Minigrafikodun KPIak, lau serieko lerroak, azalerak, bihurketa-inbutua, konbinatua eta formuladun taula"],
"edu_body":["Giza gorputza","Laborategi estiloa: 3D irudia Eraldatu-rekin, ibilbide batean dabilen pertsonaia, barra-grafikoa, gorputza etiketatu eta galdetegia"],
"edu_cell":["Zelula","Formekin marraztutako zelula, zatiak banan-banan, Eraldatu hurbiltzeko, bikoteak lotu, diagrama, 3D landarea eta balorazioa"],
"edu_english":["Ingelesa hasiberrientzat","Ikasgela modua: soinuarekin biratzen diren txartelak, ibili eta agurtzen duen 3D robota, 3D azeria, hiru galdera puntuekin, sailkapena eta txaloak"],
"edu_fractions":["Zatikiak","Neon estiloa: marraztutako pizzak, ekuazioak urratsez urrats, batuketa Eraldatu-rekin, hutsuneak bete, galdetegia eta erronka atzerako kontaketarekin"],
"edu_quixote":["Don Kixote","Tinta eta paper estiloa: soinuarekin biratzen den errota, testu kurbatua, aipu animatuak, Eraldatu, kronologia, hutsuneak bete eta galdetegia"],
"edu_renewables":["Energia berriztagarriak","Biratzen den aerosorgailua, txartelak, azalera-, eraztun- eta barra taldekatuen grafikoak, zuzeneko hitz-hodeia, bozketa eta atzerako kontaketa"],
"edu_revolution":["Frantziako Iraultza","Paper zaharraren estiloa: testua zirkuluan, Eraldatu, gizarte-piramidea, kronologia animatua soinuarekin, gertaerak ordenatu eta bozketa"],
"edu_spain":["Espainiako geografia","Atlas estiloa: haize-arrosa, erliebea itu moduan, ibaien taula formulekin, gailur eta euri grafikoak, bikoteak lotu eta galdetegia"],
"edu_volcanoes":["Sumendiak","Su estiloa: erupzio animatua soinuarekin, sumendiaren zatiak etiketatzeko, taula, denboradun galdetegia eta atzerako kontaketa"],
"edu_water":["Uraren zikloa","Ziklo-diagrama banan-banan, igotzen diren tantak eta euri animatua soinuarekin dituen paisaia, eraztun-grafikoak, bikoteak lotu eta 3D satelitea"],
"life_bookclub":["Irakurketa kluba","Eskuz marraztutako apalategia, formekin egindako azala, eraldatzen diren aipuak, diagrama erradiala, balorazioa eta hurrengo liburuaren bozketa"],
"life_cv":["Curriculum bisuala","Testua zirkuluan, zifrak, kronologia urratsez urrats, trebetasun-barra animatuak, radarra, pantailak gailuetan eta kontaktua"],
"life_fitness":["Entrenamendu-plana: 5 km","3D korrikalaria, su-Text Art, gradientedun faseak, formuladun astea, aurrerapen-grafikoak, piramidea, atzerako kontaketa eta hitz-hodeia"],
"life_garden":["Hiri-baratzea","3D landarea Eraldatu-rekin, ereintza-egutegia koloretako taulan, zikloa, Venn, ureztatze- eta hazkunde-grafikoak, etiketatzeko jarduera"],
"life_graduation":["Graduazioa eta ikasturte-amaiera","Urre-Text Art, formekin egindako birreteak, sartzean biratzen diren polaroidak, danbor-hotsa duten zifrak, eskerrak, hitz-hodeia eta txaloak"],
"life_italy":["Bidaia Italian zehar","Testua zirkuluan, lotuneak eta ibilbide animatua dituen bidea, kronologia, formulak dituen aurrekontua, grafikoak eta parekatzeko jarduera"],
"life_kids_party":["Haur-urtebetetzea","Kolore biziak: dantzan ari den 3D robota, ospatzen duten pertsonaiak, eskuz marraztutako puxikak, puntuzko lehiaketa eta atzerako kontaketa"],
"life_moving":["Etxe-aldaketa eta etxe berria","Eskuzko formekin egindako etxea, kronologia, marratzen den zerrenda, Eraldatu bidez planora pasatzen diren 3D altzariak, aurrekontua eta ordenatzeko jarduera"],
"life_recipe":["Errezeta: guacamolea","Diapositiben artean bidaiatzen duen 3D ahuakatea (Eraldatu), formuladun osagaiak, urratsak banan-banan, atzerako kontaketa eta balorazioa"],
"life_wedding":["Ezteiko gonbidapena","Tipografia klasikoa eta urrea: Text Art, testu kurbatua, bikotearen kronologia, ibilbide animatua duen mapa, bozketa eta atzerako kontaketa"],
"product_app":["Mugikorreko aplikazioaren aurkezpena","Aplikazioa mugikorrean, tabletan eta eramangarrian, Eraldatu, ibilbidea galoietan, zifrak, atxikipen-grafikoa eta hitz-hodeia"],
"product_car":["Aurkezpena: auto elektrikoa","Ertzetan moztu gabeko 3D autoa, sartzean bira ematen duena, Eraldatu, zifrak, azalera- eta barra-grafikoak, taula eta bozketa"],
"product_eco":["Produktuaren iraunkortasuna","Berde ekologikoa: 3D landarea Eraldatu-rekin, bizi-zikloa, aztarnaren ur-jauzia, materialen barrak, helburudun lerroak eta hutsuneak bete"],
"product_furniture":["Altzari-bilduma","Estilo editoriala: 3D sofak eta aulkiak, Eraldatu ikuspegi desberdinekin, kulunka eta bira, kolore-laginak, tableta eta aurrekontua"],
"product_keynote":["Hardware keynotea","Estilo zuri premium: lanpara irisatua eta 3D botila, Eraldatu etiketekin, flotatu eta hurbildu, zifrak, taula eta prezioak"],
"product_roadmap":["Produktuaren bide-orria","Bere kabuz marrazten den bidea, piramidea, kronologia banan-banan, orain eta gero, matrizea, barra pilatuak, aukera anitzeko bozketa eta ordenatzekoa"],
"product_robot":["Industria-robot laguntzailea","Estilo industriala: agurtzen duen 3D robota, ibilbide batean dabilena, animazioak kateatzen dituena eta dantzatzen duena; organigrama, zikloa, grafikoa eta lehiaketa"],
"product_saas":["SaaS plataformaren demoa","Panela nabigatzaile-leihoan dei zenbakidunekin, erradiala, inbutua, adierazleak, barra pilatuak, kodea urratsez urrats eta galderak"],
"product_security":["Produktuaren segurtasuna","Neoi berdea: geruzetako itua, urratsez urrats agertzen den fluxua lotzaileekin, kode nabarmendua, grafikoa, eskailera eta parekatzeko jarduera"],
"product_watch":["Aurkezpena: erloju adimenduna","Beltza eta urrea: 3D erlojua hiru diapositibatan zehar Eraldatu eta iritsiera desberdinekin, urrezko Text Art, radarra eta prezioak"],
"sci_ai":["Adimen artifiziala","Neoi morea: agurtu eta Eraldatu-rekin bidaiatzen duen 3D robota, kronologia, organigrama, pizten den sare neuronala, grafikoa eta hitz-hodeia"],
"sci_brain":["Neurozientzia: garuna","Estilo iluna distiraz: bultzada animatua duen neurona marraztua, oinez dabilen 3D irudia, erradiala, organigrama, barrak eta irudi bat etiketatu"],
"sci_chem":["Kimika: taula periodikoa","Laborategi garbia: urjauzian eraikitzen den taula periodikoa, formazko molekulak, 3D braseroa, ekuazioak, eraztuna eta parekatzea"],
"sci_climate":["Klima-aldaketa datuetan","Berotze-bandak, lerro, azalera eta laukizuzen grafikoak, bere burua marrazten duen berotegi-efektua, 3D satelitea, zikloa eta aukera anitzeko bozketa"],
"sci_mars":["Marterako misioa","Espazio-estilo herdoila: NASAren 3D rover-a Eraldatu-rekin, astronauta flotatzen, orbita animatua, ekuazioa eta lehiaketa"],
"sci_newton":["Fisika: Newtonen legeak","Fisika-koadernoa: ekuazioak, mugitzen den 3D autoa, bere burua marrazten duen jaurtiketa parabolikoa, formuladun taula eta hutsuneak bete"],
"sci_python":["Python programazioa","Editore ilunaren estiloa: bere kabuz idazten den terminala, nabarmentze-urratsak dituen kodea, irteera animatua, lerroak ordenatu eta atzerako kontaketa duen erronka"],
"sci_solar":["Eguzki-sistema","Eskalan dauden planetak katean agertzen, hiru 3D zunda ikuspegi eta mugimendu desberdinekin, taula, diagrama erradiala eta parekatzea"],
"sci_stats":["Estatistika eta probabilitatea","Estilo editoriala: bere burua marrazten duen kanpaia, formulak, histograma, sakabanatzea, azalera, barrak eta burbuilak, eta puntudun galdera"],
"sci_thesis":["GrALaren defentsa","Akademiko soila: azal instituzionala, aurkibidea, ekuazioa duen metodologia, guztizkoak dituen taula, emaitzak grafikoetan, bibliografia eta galderak"]};
