// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Hiruhileko emaitzak kontseiluari","Urdin iluna eta urrea: soinudun adierazle handi animatuak, ur-jauzia, inbutua, barra metatuak eta aurrekontuarekin alderatzeko formuladun taula"],
"biz_climate":["Lan-giroari buruzko inkesta","Morea eta parte-hartzailea: atzerako kontaketa, % 100eko barrak, 1etik 5erako balorazioa, hitz-hodeia, aukera anitzekoa eta publikoaren galderak"],
"biz_investment":["Inbertitzaileentzako aurkezpena","Beltza eta urrea: biratu eta Eraldatu erabiliz bidaiatzen duen 3D produktua, zifra erraldoiak, merkatua zirkuluetan, trakzioa, funtsen erabilera eta taldea"],
"biz_marketing":["Kanpainaren marketin plana","Estilo beroa: testua zirkuluan, xede-publikoa, inbutua, kanalen nahasketa, egutegia taulan, aurrekontua formularekin eta bozketa"],
"biz_onboarding":["Langile berriei ongietorria","Estilo atsegina: agurtu eta astean zehar oinez dabilen 3D robota, organigrama banan-banan, balioak ikonoekin eta parekatze-jarduera"],
"biz_proposal":["Bezero baterako proposamen komertziala","Paper estiloa: zigilua, prozesua banan-banan, maketak eramangarrian eta mugikorrean, prezioak, BEZa formuletan duen aurrekontua, kronologia eta bermeak"],
"biz_roadmap":["Proiektu baten ibilbide-orria","Estilo tekniko iluna: galoiak banan-banan, Gantt diagrama animatua, kronologia, Eraldatu erabiliz aurrera egiten duen 3D autoa eta egoera-taula"],
"biz_sales":["Salmentak eta urteko aurreikuspena","Gris minimalista: barra eta lerro konbinatuak, agertokiak, aurreikuspen-formula, formuladun taula, barra metatuak eta horizontalak"],
"biz_startup_agrotech":["Agrotech pitch-a: sentsoreekin ureztatzea","Lursailen aireko ikuspegia hezetasun-maparekin, NASAren 3D satelitea, mugikorra, soinudun tanta kateatuak, formuladun taula eta treemap-a"],
"biz_startup_edtech":["Edtech pitch-a: matematika-tutorea","Koadernoa laukietan: post-it kateatuak, eskuz idatzitako letra, ekuazioak urratsez urrats, mugikorra, zuzeneko galdetegia, zikloa eta grafikoak"],
"biz_startup_energy":["Energiaren pitch-a: eguzki-komunitatea","Teilatuak egunsentitik gauera: igo eta zerua arkuan zeharkatzen duen eguzkia, diagrama erradiala, orduko areak, ekuazioa eta formuladun taula"],
"biz_startup_fashion":["Moda zirkularraren pitch-a: Retal","Arropa-etiketa Eraldatu-rekin bidaiatzen duena, josturak puntuz, jantzi baten bizitza katean, zikloa, eraztuna, radarra eta aukera anitzeko bozketa"],
"biz_startup_insurance":["Aseguruen pitch-a: egunkako estaldura","Euri grisa eta aterki horia: piktograma katean, etengailudun aplikazioa, prezioaren ekuazioa, formuladun taula, kronologia eta bozketa"],
"biz_startup_kitchen":["Sukaldeko robotikaren pitch-a: Fogón","Sukalde profesionala: komandak errailean, suzko Text Art, oinez sartu eta agurtzen duen 3D robota, errezeta kode gisa, atzerako kontaketa eta inbutua"],
"biz_startup_lastmile":["Logistika pitch-a: azken miliakoa","Metro-plano estiloa: beren kabuz marrazten diren lerroak, mapa zeharkatzen duten 3D kamioia eta bizikletak, formuladun taula, area eta ur-jauzia"],
"biz_startup_mental":["Osasun mentalaren pitch-a: Remanso","Gau lasaia: arnasten duten eraztunak, arnasketa-minutua atzerako kontaketarekin, aplikazioa mugikorrean, eskailera, balorazioa eta formuladun taula"],
"biz_startup_pets":["Maskoten pitch-a: janari freskoa","Pegatina estiloa katean agertzen diren hatz-markekin, oinez zeharkatzen duen 3D azeria, errazioaren formula taula batean, eraztuna eta lehiaketa"],
"biz_startup_rural":["Landa-turismoaren pitch-a: Alpende","Mendiak ilunabarrean eta postalak: 3D farola, testu kurbatuko zigilua, ibilbidean 3D autoa duen mapa, barrak, tarta eta hitz-hodeia"],
"biz_strategy":["Plan estrategikoa eta OKRak","Estilo garbia zuriz: katean sartzen diren zifrak, piramidea, lehentasunak ikonoekin, OKR taula, aurrerapen-barrak, radarra eta galoiak"],
"biz_swot":["AMIA analisia eta lehiakideak","Grafito-hondoa: AMIA koadranteka, estrategien matrizea, posizionamendu-mapa, barra taldekatuak, Venn, tarta eta aukera anitzeko bozketa"],
"creative_bauhaus":["Bauhaus: forma eta funtzioa","Bauhaus arte geometrikoa: biratu eta errebotatzen duten oinarrizko formak, kronologia, Eraldatu sareta bat eta parekatze-jarduera"],
"creative_brutalism":["Brutalismoa: web manifestua","Estilo brutalista: tipografia erraldoia, bloke beltzak, testu bertikala, itzal gogorrak, marratu animatua, taula eta bozketa"],
"creative_comic":["Komikia: animalien superbotereak","Komiki estiloa: binetak, elkarrizketa eta pentsamendu bunbuiloak, errebotatzen duten Text Art onomatopeiak, 3D azeria, grafikoa eta lehiaketa"],
"creative_fashion":["Moda aldizkaria: udazken geldoa","Aldizkari estiloa: serif goiburua, 3D erlojua azalean, zutabeak hasierako letra handiarekin, aipu handia, denboraldiko paleta eta grafikoa"],
"creative_glass":["Glassmorphism: finantza aplikazioa","Txartel zeharrargiak kolore-distiren gainean, aplikazioa mugikorrean, eraztun-grafikoa, Eraldatu txartel bat eta balorazio-bozketa"],
"creative_pixel":["Pixel art: zure lehen bideojokoa","Bideojoko retro estiloa: pixel spriteak, markagailua, ibili eta salto egiten duten 3D pertsonaiak, urratsez urratseko kodea, lehiaketa eta atzerako kontaketa"],
"creative_space":["Galaxia: iraganera begiratzea","Espazio estiloa: izarrak, nebulosa distiratsuak, NASAren 3D ereduak, planetak zeharkatzen dituen zunda, testu kurbatua eta lehiaketa"],
"creative_swiss_blood":["Kanpaina: eman odola","Kartel publikoa zuri eta gorriz: pantaila betetzen duen tanta Eraldatu-rekin, prozesua, bai ala itxaron, eraztuna, barrak, mugikorra eta lehiaketa"],
"creative_swiss_chairs":["Erakusketa: aulki modernoa","Kartel suitzarra gris eta lima: 3D aulkia biraka eta bidaian Eraldatu-rekin, kronologia, eraztuna, 3D besaulkia, taula formulekin eta ordenatu"],
"creative_swiss_designconf":["Diseinu biltzarra: Sareta 27","Grafitoa eta ziana: sareta bakarrik eraikitzen da eta Eraldatu-rekin aldatzen, ingerada-zifra, formula, kronologia, CSS kodea, hodeia eta atsedena"],
"creative_swiss_film":["Zinemaldia: egitaraua","Suitzarra beltz eta gorriz: zenbaki erraldoia banda bihurtzen da Eraldatu-rekin, sareta, taula, barrak, bozketa eta atzerako kontaketa"],
"creative_swiss_foundation":["Fundazio baten urteko txostena","Suitzarra zuri eta kobalto urdinez: urte erraldoia, gutun osoa koloretan, zifrak katean, ekuazioa, eraztuna, azalera, geziak eta kontuak formulekin"],
"creative_swiss_games":["Eskola jokoak: nortasun bisuala","Zuria eta magenta, paleta propioa: SVG piktogramak, hiria zeharkatzen duen 3D irudia, lerroak, domina-taula formulekin, mailak eta lehiaketa"],
"creative_swiss_museum":["Natur zientzien museoaren gida","Seinaleztapen suitzarra beltz eta horiz: plano propioa ibilbide animatuarekin, ibiltzen den 3D azeria, zutabeak, taula, etiketatu eta piktogramak"],
"creative_swiss_orchestra":["Orkestra sinfonikoa: 26/27 denboraldia","Gau urdina eta anbarra: biraka dabiltzan arkuak, testu kurbatua, zifrak pentagraman, zikloak, taula, ekuazioa, barrak, bozketa eta txaloak"],
"creative_swiss_publisher":["Argitaletxe baten udazkeneko katalogoa","Krema paperea eta petrolio berdea: bizkar bertikalen apala, SVG azalak, tableta, tarta, eskaera formulekin, egutegia eta hutsuneak"],
"creative_swiss_typeface":["Letra-tipo berri baten erakustegia","Erakustegia zuri eta morez: Eraldatu-rekin bidaiatzen duten letrak, neurtutako anatomia, eskala formularekin, glifoak, radarra eta lizentziak"],
"creative_synthwave":["Synthwave: Neón 86 jaialdia","80ko hamarkadako estilo retroa: eguzki gradientea, bere kabuz marrazten den sareta, neoi distiratsua, Eraldatu, dantzan dabilen 3D robota eta hitz-hodeia"],
"creative_watercolor":["Akuarela: baratzea balkoian","Akuarela eta paper estiloa: gradiente erradialeko orbanak, eskuz egindako formak, eskuzko letra, bere kabuz marrazten den marrazkia eta 3D"],
"creative_zen":["Japoniar minimalismoa: tea","Japoniar minimalismoa: zuri asko, eraldatzen den eguzki gorria, testu bertikala, bere kabuz margotzen den ensōa eta atzerako kontaketa"],
"data_ab_test":["A/B esperimentua","Ekuazioak, bi serieko sakabanatzea, etiketadun zutabeak, formuladun bihurketa-taula eta esangura-zifrak"],
"data_energy":["Energia eta kontsumoa","Orduko azalera metatuak, hiru serieko lerroak, laukizuzenak, etiketadun zutabeak eta tarifa-taula kalkulatua"],
"data_exec_panel":["Hileko zuzendaritza-panela","Semaforo eta minigrafikodun KPIak, aurrekontuaren aurkako konbinatua, multiplo txikiak, eraztuna eta bozketa"],
"data_home_finance":["Finantza pertsonalak","Soldatatik aurrezkira doan ur-jauzia, grafiko zirkularra, lerroak eta azalera, BATURA, BATEZBESTEKOA, MAX eta MIN dituzten taulak"],
"data_market_study":["Merkatu-azterketa","Zifra handiak, laukizuzen-grafikoa, burbuilak, sakabanatzea, bi serieko barra horizontalak eta 2 × 2 matrizea"],
"data_population":["Biztanleria eta demografia","Biztanleria-piramidea, histograma, barra horizontalak, gurutzatzen diren lerroak eta formuladun adierazle-taula"],
"data_sales_regions":["Salmentak eskualdeka","Barra taldekatuak, metatuak eta % 100ekoak, helburudun grafiko konbinatua, formula bidezko guztizkoak dituen taula eta KPI animatuak"],
"data_satisfaction":["Gogobetetze-inkesta","Legendadun eraztuna, radar konparatuak, etiketadun zutabeak, NPS, balorazioa eta hitz-hodeia zuzenean"],
"data_season_stats":["Denboraldia zenbakitan","Soinudun zifra erraldoiak, formuladun sailkapena, barra negatiboak, lerroak, metatuak eta taldearen radarra"],
"data_web_metrics":["Web eta marketin metrikak","Minigrafikodun KPIak, lau serieko lerroak, azalerak, bihurketa-inbutua, konbinatua eta formuladun taula"],
"edu_body":["Giza gorputza","Laborategi estiloa: 3D irudia Eraldatu-rekin, ibilbide batean dabilen pertsonaia, barra-grafikoa, gorputza etiketatu eta galdetegia"],
"edu_cell":["Zelula","Formekin marraztutako zelula, zatiak banan-banan, Eraldatu hurbiltzeko, bikoteak lotu, diagrama, 3D landarea eta balorazioa"],
"edu_english":["Ingelesa hasiberrientzat","Ikasgela modua: soinuarekin biratzen diren txartelak, ibili eta agurtzen duen 3D robota, 3D azeria, hiru galdera puntuekin, sailkapena eta txaloak"],
"edu_fractions":["Zatikiak","Neon estiloa: marraztutako pizzak, ekuazioak urratsez urrats, batuketa Eraldatu-rekin, hutsuneak bete, galdetegia eta erronka atzerako kontaketarekin"],
"edu_hist_alandalus":["Al-Andalus: zientzia eta lorategiak","Ferra-arkua, kronologia banan-banan, barra horizontalak, biratzen den astrolabioa, izarra Eraldatu bidez, bikoteak lotu eta bozketa"],
"edu_hist_castle":["Gazteluak eta feudalismoa","Gaueko gaztelua eta zubia zeharkatzen duen 3D zalduna, altxatzen den piramide feudala, etiketatu, eguna zeharkatzen duen eguzkia, treemap eta armarriak"],
"edu_hist_egypt":["Egipto, Niloren oparia","Lapitzuli eta urrea: piramideen atzetik ateratzen den eguzkia, uholde animatua, azalera-grafikoa, ekuazioa, Eraldatu, kartutxo hieroglifikoa eta ordenatu"],
"edu_hist_greece":["Atenas: demokrazia jaio da","Irudi beltzeko ontzi estiloa: meandroa, testu kurbatua, Eraldatu, eraztuna, altxatzen den tenplua, soinudun ostrakak, bozketa eta taula"],
"edu_hist_maya":["Maiak: denbora eta izarrak","Oihana eta jadea: puntu eta marrazko zenbakiak, Eraldatu 20 oinarrira, ekuazioa, biratzen diren egutegi-gurpilak, argizko sugea eta kakaoa"],
"edu_hist_mesopotamia":["Mesopotamia: idazkera jaio da","Bere kabuz idazten den buztinezko taula, ibaiak marrazten dituen mapa, hazten den zigurata, 60 oinarria formulekin, hutsuneak bete eta erradiala"],
"edu_hist_printing":["Inprenta: liburua ugaltzen da","Inkunable-orria: hasierako letra gorria, alderantzizko tipoak Eraldatu bidez konposatuak, soinuz jaisten den prentsa, zifrak, barrak eta hutsuneak"],
"edu_hist_rome":["Erroma, inperioko ingeniariak","Marmola eta gorri inperiala: Eraldatu, garaipen-arkua, geruzaz geruzako galtzada martxan doan 3D soldaduarekin, akueduktua, ekuazioa, formulak eta lehiaketa"],
"edu_hist_silkroad":["Zetaren Bidea","Zeta eta azafraia: martxan doan karabana, ibilbidea marrazten den mapa, prezioaren ur-jauzia, formuladun taula, 3D farola, ekuazioa eta ordenatu"],
"edu_hist_vikings":["Bikingoak, iparraldeko nabigatzaileak","Fiordoa aurora azpian: kulunkatzen den ontzia, errunak, zigiluz ezabatutako mitoak, zeharkaldi animatua, soinudun zifrak, 3D gudaria, radarra eta lotu"],
"edu_math_coordinates":["Koordenatuak: altxorraren mapa","Altxorraren mapa: haize-arrosa testu kurbatuarekin, agertzen diren puntuak, pistei jarraitzen dien 3D pirata, marrazten den itsasontzia eta etiketatzea"],
"edu_math_integers":["Zenbaki osoak: itsasoa eta mendia","Itsas hondotik gailurrera: jauziak dituen zuzena, izotz Text Art, zero azpiko tenperaturak, igo eta jaisten den itsaspekoa, ordenatzea eta lehiaketa"],
"edu_math_primes":["Zenbaki lehenak","Terminal berdea: neoi propioa, Eratostenesen bahea klikez kliko 100 laukirekin, faktore-zuhaitza, kodea urratsez urrats, lehiaketa eta erronka"],
"edu_math_probability":["Probabilitatea: zortea neurtzea","Joko-mahai burdeos eta urrea: danbor-hotsarekin biraka dauden daduak, testu kurbatua, Laplaceren erregela, zuhaitza banan-banan, barrak, lerroak eta lehiaketa"],
"edu_math_proportion":["Proportzionaltasuna supermerkatuan","Erosketa-tiketa: errebotatzen duen zigilua, proportzionaltasun-taula formulekin, hiruko erregela urratsez urrats, kalkulatutako beherapenak, lerroak eta hutsuneak"],
"edu_math_pythagoras":["Pitagorasen teorema","Klarion-arbela: bere kabuz marrazten den irudia, hitzik gabeko frogapena Eraldatu-rekin, hirukoteak formulekin, 3D lasterbidea eta lehiaketa"],
"edu_math_sequences":["Segidak eta ereduak","Botanika-liburua: bere kabuz marrazten den Fibonacciren espirala, kateko harriak, txotxak formulekin, kodea, 3D landarea eta urrezko zenbakia"],
"edu_math_stats":["Estatistika: batezbestekoa, mediana eta moda","Koadrikulatutako koadernoa: ur-jauzian agertzen diren ohar itsaskorrak, maiztasunak formulekin, barrak, eraztuna graduekin, histograma eta zuzeneko bozketa"],
"edu_math_symmetry":["Simetria eta mosaikoak","Nazari azulejuak: biratzen den izarra, islatzen den tximeleta, translazioa, biraketa eta simetria animatuak, angelu-taula eta abaraska"],
"edu_math_volumes":["Azalerak eta bolumenak","Plano tekniko urdina: koadroa taulan, garapen laua, neurtutako 3D botila, bolumenak formulekin, barrak, betetzen duten konoak eta lotzea"],
"edu_quixote":["Don Kixote","Tinta eta paper estiloa: soinuarekin biratzen den errota, testu kurbatua, aipu animatuak, Eraldatu, kronologia, hutsuneak bete eta galdetegia"],
"edu_renewables":["Energia berriztagarriak","Biratzen den aerosorgailua, txartelak, azalera-, eraztun- eta barra taldekatuen grafikoak, zuzeneko hitz-hodeia, bozketa eta atzerako kontaketa"],
"edu_revolution":["Frantziako Iraultza","Paper zaharraren estiloa: testua zirkuluan, Eraldatu, gizarte-piramidea, kronologia animatua soinuarekin, gertaerak ordenatu eta bozketa"],
"edu_spain":["Espainiako geografia","Atlas estiloa: haize-arrosa, erliebea itu moduan, ibaien taula formulekin, gailur eta euri grafikoak, bikoteak lotu eta galdetegia"],
"edu_volcanoes":["Sumendiak","Su estiloa: erupzio animatua soinuarekin, sumendiaren zatiak etiketatzeko, taula, denboradun galdetegia eta atzerako kontaketa"],
"edu_water":["Uraren zikloa","Ziklo-diagrama banan-banan, igotzen diren tantak eta euri animatua soinuarekin dituen paisaia, eraztun-grafikoak, bikoteak lotu eta 3D satelitea"],
"life_bookclub":["Irakurketa kluba","Eskuz marraztutako apalategia, formekin egindako azala, eraldatzen diren aipuak, diagrama erradiala, balorazioa eta hurrengo liburuaren bozketa"],
"life_cv":["Curriculum bisuala","Testua zirkuluan, zifrak, kronologia urratsez urrats, trebetasun-barra animatuak, radarra, pantailak gailuetan eta kontaktua"],
"life_fitness":["Entrenamendu-plana: 5 km","3D korrikalaria, su-Text Art, gradientedun faseak, formuladun astea, aurrerapen-grafikoak, piramidea, atzerako kontaketa eta hitz-hodeia"],
"life_garden":["Hiri-baratzea","3D landarea Eraldatu-rekin, ereintza-egutegia koloretako taulan, zikloa, Venn, ureztatze- eta hazkunde-grafikoak, etiketatzeko jarduera"],
"life_graduation":["Graduazioa eta ikasturte-amaiera","Urre-Text Art, formekin egindako birreteak, sartzean biratzen diren polaroidak, danbor-hotsa duten zifrak, eskerrak, hitz-hodeia eta txaloak"],
"life_italy":["Bidaia Italian zehar","Testua zirkuluan, lotuneak eta ibilbide animatua dituen bidea, kronologia, formulak dituen aurrekontua, grafikoak eta parekatzeko jarduera"],
"life_kids_party":["Haur-urtebetetzea","Kolore biziak: dantzan ari den 3D robota, ospatzen duten pertsonaiak, eskuz marraztutako puxikak, puntuzko lehiaketa eta atzerako kontaketa"],
"life_moving":["Etxe-aldaketa eta etxe berria","Eskuzko formekin egindako etxea, kronologia, marratzen den zerrenda, Eraldatu bidez planora pasatzen diren 3D altzariak, aurrekontua eta ordenatzeko jarduera"],
"life_recipe":["Errezeta: guacamolea","Diapositiben artean bidaiatzen duen 3D ahuakatea (Eraldatu), formuladun osagaiak, urratsak banan-banan, atzerako kontaketa eta balorazioa"],
"life_travel_eu_amsterdam":["Amsterdam: ubideak eta bizikletak","Katean muntatzen diren ubide-fatxadak, ubideak jomuga gisa, soinuz gurutzatzen duen bizikleta, formuladun taula, lerroak eta tarta-bozketa"],
"life_travel_eu_camino":["Done Jakue Bidea: Sarriatik","Soinudun zigiluz betetzen den kredentziala, kilometro-ur-jauzia, 3D oinezkoa, motxilaren ekuazioa, donuta eta etapak ordenatzea"],
"life_travel_eu_croatia":["Kroazia belaontziz Dalmazian","Itsas karta, biratu eta Eraldatu-rekin bidaiatzen duen haize-arrosa, banderak, parekatu, formuladun miliak, lehiaketa eta atzerako kontaketa"],
"life_travel_eu_danube":["Danubio bizikletaz","Txirrindulari-ordenagailu estiloa: ibilbidea mugikorrean, GPX fitxategia urratsez urrats, pilatutako barrak, 3D botila Eraldatu-rekin, formulak eta laukizuzenak"],
"life_travel_eu_fjords":["Norvegiako fiordoak uretatik","Geruzatutako paisaia islekin, nabigatzen duen itsasontzia, bere kabuz marrazten den fiordo-ebakidura, barrak, radarra, urratsak eta aukera anitzeko bozketa"],
"life_travel_eu_greece":["Greziako uharteak ferryz","Formaz egindako herri zuria, greka, bere kabuz marrazten den ibilbidea, formuladun ordutegiak, burbuilak, 3D betaurrekoak Eraldatu-rekin eta ilunabarra"],
"life_travel_eu_iceland":["Islandia: Ring Road autoz","Gradientedun aurorak, soinudun ibilbidea mapan, 3D autoa, danborrada duten zifrak, hotzaren ekuazioa, oinez doan azeria eta lehiaketa"],
"life_travel_eu_lisbon":["Lisboa: muinoak eta tranbiak","SVG azulejoak, muinoak igotzen dituen tranbia soinuarekin, altuera-profila, biratzen diren txartelak, formuladun taula eta hutsuneak"],
"life_travel_eu_prague":["Praga, ehun dorreen hiria","Formaz egindako erloju astronomikoa, biratu eta Eraldatu-rekin bidaiatzen duena, kanpaitxodun desfilea, atzerako kontaketa, etiketatzeko mapa eta taula"],
"life_travel_eu_scotland":["Eskozia: Highlandak autoz","Formaz ehundutako tartana, marrazten den errepidea, bidea uzten duten autoak, biratzen diren gazteluak, 3D farola, barrak eta galderak"],
"life_wedding":["Ezteiko gonbidapena","Tipografia klasikoa eta urrea: Text Art, testu kurbatua, bikotearen kronologia, ibilbide animatua duen mapa, bozketa eta atzerako kontaketa"],
"prod_app_bank":["Cartilla: adinekoentzako banka","Larruzko eta urrezko aurrezki-liburuxka: urrezko Text Art, mugikorra hurbiltzeko Eraldaketa, BATURA duen taula, ur-jauzia, zigilua eta iruzurraren aurkako lehiaketa"],
"prod_app_gym":["Serie: erreserbak zure gimnasioan","LED markagailua: ospatzen duen eta bere klaseraino oinez doan 3D borrokalaria, bi atzerako kontaketa, orduko okupazioa, formuladun tarifak eta lehiaketa"],
"prod_app_health":["Turno: hitzorduak osasun-zentroan","Klinikoa: marrazten den taupada, aurretik eta ondoren, zikloa banan-banan, oinez dabilen 3D gaixoa, agenda monitorean, barrak eta galderak"],
"prod_app_language":["Vocablo: hizkuntzak ikasteko aplikazioa","Aire-posta txartela: zigiluak, soinuarekin jauzi egiten duten bunbuiloak, biratzen diren txartelak, Eraldaketa, ahanzturaren ekuazioa, grafikoa eta lotu"],
"prod_app_market":["Plaza: auzoko merkatua etxera","Toldoa eta klarion-arbelak: planoa zeharkatzen duen 3D furgoneta, postuak erradialean, mugikorra, laukizuzenak, formuladun komisioak eta bozketa"],
"prod_app_meditation":["Marea: meditazio eta lo aplikazioa","Gaueko itsasoa: ilargia testu kurbatuarekin, mugikorraren Eraldaketa, kateatutako eraztunekin arnasketa gidatua, atzerako kontaketa, grafikoa eta 3D farola"],
"prod_app_music":["Garaje: auzoko zuzeneko musika","Biniloa eta neoia: Eraldaketarekin bidaiatzen duen diskoa, biratzen duen testu kurbatua, danbor-hotsdun ekualizadorea, eramangarria, radarra, tarta eta hitz-hodeia"],
"prod_app_photo":["Grano: filmeko argazkigintza","Gela iluna: film-zerrenda, Eraldaketarekin errebelatzen den argazkia, danbor-hotsdun kontagailua, histograma, tableta, taula eta etiketatu"],
"prod_app_recipes":["Sobras: dagoenarekin errezetak","Hozkailua postitekin: 3D ahuakatea Eraldaketarekin, osagaiak ezagutzen dituen mugikorra, urratsak, eraztuna, formuladun errezeta eta atzerako kontaketa"],
"prod_app_transit":["Andén: hiri-garraioa","Metroko seinaleztapena: irteeren panela atzerako kontaketarekin, bere kabuz marrazten den planoa, bidaia animatua, mugikorra, barra metatuak eta tarifak"],
"product_app":["Mugikorreko aplikazioaren aurkezpena","Aplikazioa mugikorrean, tabletan eta eramangarrian, Eraldatu, ibilbidea galoietan, zifrak, atxikipen-grafikoa eta hitz-hodeia"],
"product_car":["Aurkezpena: auto elektrikoa","Ertzetan moztu gabeko 3D autoa, sartzean bira ematen duena, Eraldatu, zifrak, azalera- eta barra-grafikoak, taula eta bozketa"],
"product_eco":["Produktuaren iraunkortasuna","Berde ekologikoa: 3D landarea Eraldatu-rekin, bizi-zikloa, aztarnaren ur-jauzia, materialen barrak, helburudun lerroak eta hutsuneak bete"],
"product_furniture":["Altzari-bilduma","Estilo editoriala: 3D sofak eta aulkiak, Eraldatu ikuspegi desberdinekin, kulunka eta bira, kolore-laginak, tableta eta aurrekontua"],
"product_keynote":["Hardware keynotea","Estilo zuri premium: lanpara irisatua eta 3D botila, Eraldatu etiketekin, flotatu eta hurbildu, zifrak, taula eta prezioak"],
"product_roadmap":["Produktuaren bide-orria","Bere kabuz marrazten den bidea, piramidea, kronologia banan-banan, orain eta gero, matrizea, barra pilatuak, aukera anitzeko bozketa eta ordenatzekoa"],
"product_robot":["Industria-robot laguntzailea","Estilo industriala: agurtzen duen 3D robota, ibilbide batean dabilena, animazioak kateatzen dituena eta dantzatzen duena; organigrama, zikloa, grafikoa eta lehiaketa"],
"product_saas":["SaaS plataformaren demoa","Panela nabigatzaile-leihoan dei zenbakidunekin, erradiala, inbutua, adierazleak, barra pilatuak, kodea urratsez urrats eta galderak"],
"product_security":["Produktuaren segurtasuna","Neoi berdea: geruzetako itua, urratsez urrats agertzen den fluxua lotzaileekin, kode nabarmendua, grafikoa, eskailera eta parekatzeko jarduera"],
"product_watch":["Aurkezpena: erloju adimenduna","Beltza eta urrea: 3D erlojua hiru diapositibatan zehar Eraldatu eta iritsiera desberdinekin, urrezko Text Art, radarra eta prezioak"],
"sci_ai":["Adimen artifiziala","Neoi morea: agurtu eta Eraldatu-rekin bidaiatzen duen 3D robota, kronologia, organigrama, pizten den sare neuronala, grafikoa eta hitz-hodeia"],
"sci_brain":["Neurozientzia: garuna","Estilo iluna distiraz: bultzada animatua duen neurona marraztua, oinez dabilen 3D irudia, erradiala, organigrama, barrak eta irudi bat etiketatu"],
"sci_chem":["Kimika: taula periodikoa","Laborategi garbia: urjauzian eraikitzen den taula periodikoa, formazko molekulak, 3D braseroa, ekuazioak, eraztuna eta parekatzea"],
"sci_climate":["Klima-aldaketa datuetan","Berotze-bandak, lerro, azalera eta laukizuzen grafikoak, bere burua marrazten duen berotegi-efektua, 3D satelitea, zikloa eta aukera anitzeko bozketa"],
"sci_mars":["Marterako misioa","Espazio-estilo herdoila: NASAren 3D rover-a Eraldatu-rekin, astronauta flotatzen, orbita animatua, ekuazioa eta lehiaketa"],
"sci_med_case":["Kasu klinikoa: sukarra eta eztula","Historia kliniko estiloa: karpeta, zigilua, erradiografia negatoskopioan marrazten den zirkuluarekin, CURB-65 formularekin, bozketa eta galderak"],
"sci_med_ecg":["Kardiologia: EKG bat irakurtzea","EKG papera: bakarrik marrazten diren trazuak, bihotza zeharkatzen duen bulkada, formuladun taula, ekuazioa, lehiaketa eta atzerako kontaketa"],
"sci_med_glucose":["Endokrinologia: glukosa eta intsulina","Glukosa-sentsorearen aplikazio estiloa: mugikorra pantailarekin, zikloa banan-banan, kurbak, eraztuna, formuladun taula, ekuazioa, 3D ahuakatea eta bozketa"],
"sci_med_immune":["Immunologia: erantzun immunea","Fluoreszentzia-mikroskopioa: pizten diren zelulak, marraztutako antigorputza, fagozitosia Eraldatu-rekin, organigrama eta lotzea"],
"sci_med_kidney":["Giltzurrunaren fisiologia: nefrona","Plano teknikoa: marrazten den nefrona, soinuarekin zeharkatzen duen tanta, kotak, ur-jauzia, ekuazioa, formuladun taula, 3D botila eta zikloa"],
"sci_med_knee":["Anatomia: belauna","Antzinako xafla anatomikoaren estiloa: testu kurbatua, sepia grabatua, Eraldatu meniskoetara, matrizea, taula, ibiltzen den 3D irudia eta etiketatzea"],
"sci_med_micro":["Mikrobiologia: antibiotikoen erresistentzia","Petri plakak: soinuarekin agertzen diren koloniak, hazkunde esponentziala, Eraldatu-rekin kontatutako hautaketa, antibiograma, erradiala eta hitz-hodeia"],
"sci_med_pk":["Farmakozinetika: erdibizitza","Botika-kutxa estiloa: betetzen den blisterra, LADME banan-banan, bi serieko kurbak, ekuazioak, formuladun taula, kodea eta hutsuneak"],
"sci_med_stroke":["Neurologia: ictus kodea","Larrialdietako erlojupekoa: sirena-argiak, danbor-hotsarekin zifra erraldoia, BE-FAST katean, eraztuna, galoiak, urratsak ordenatzea eta atzerako kontaketa"],
"sci_med_trial":["Saiakuntza klinikoa: emaitzak irakurtzea","Aldizkari zientifikoaren estiloa: CONSORT loturekin, biziraupen-kurbak, formuladun taula, NNT, kateatutako forest plot-a eta lehiaketa"],
"sci_newton":["Fisika: Newtonen legeak","Fisika-koadernoa: ekuazioak, mugitzen den 3D autoa, bere burua marrazten duen jaurtiketa parabolikoa, formuladun taula eta hutsuneak bete"],
"sci_python":["Python programazioa","Editore ilunaren estiloa: bere kabuz idazten den terminala, nabarmentze-urratsak dituen kodea, irteera animatua, lerroak ordenatu eta atzerako kontaketa duen erronka"],
"sci_solar":["Eguzki-sistema","Eskalan dauden planetak katean agertzen, hiru 3D zunda ikuspegi eta mugimendu desberdinekin, taula, diagrama erradiala eta parekatzea"],
"sci_stats":["Estatistika eta probabilitatea","Estilo editoriala: bere burua marrazten duen kanpaia, formulak, histograma, sakabanatzea, azalera, barrak eta burbuilak, eta puntudun galdera"],
"sci_thesis":["GrALaren defentsa","Akademiko soila: azal instituzionala, aurkibidea, ekuazioa duen metodologia, guztizkoak dituen taula, emaitzak grafikoetan, bibliografia eta galderak"],
"showcase_3d":["Katalogoa: 3D sakonean","3D ereduak aukera guztiekin: ikuspegiak, sartzean mugimenduak, biraketa, ertzak, marjina, klipak, ibiltzea eta Eraldatu bidezko iristea"],
"showcase_animations":["Katalogoa: animazioak","Objektuen animazio guztiak: sarrera, enfasia, irteera, ibilbideak, marraztu, kateatuak, soinuak eta hainbat objektu bakarrean"],
"showcase_charts":["Katalogoa: grafikoak","15 grafiko motak, bi diapositiba bakoitzeko, serieekin, konbinatuarekin, saretarekin, etiketekin eta ardatzen izenburuekin, eta aukeren taula"],
"showcase_diagrams":["Katalogoa: diagramak","Eskema gisa idatzitako 15 diagrama-diseinuak, 4 kolore-eskemak eta aurkeztean banan-banan agertzea"],
"showcase_morph":["Katalogoa: Eraldatu","Eraldatu urratsez urrats: tamaina eta lekua aldatzen dituen testua, formak, hazten diren barrak, irudia, 3D eta berrantolatzen diren letrak"],
"showcase_objects":["Katalogoa: multimedia eta objektuak","Kodea urratsekin, ekuazioak, ikonoak, bost gailu, estilo eta formuladun taulak, diapositiba-zooma eta konektoreak"],
"showcase_polls":["Katalogoa: bozketak eta jarduerak","Mugikorretik egiteko 11 bozketa eta jarduera mota, atzerako kontaketa bere hiru estiloetan, sailkapena eta ikasgela modua"],
"showcase_shapes":["Katalogoa: formak","Forma guztiak kategoriaka bere izenarekin, lerroak eta marrak, gradienteak, opakutasuna, eskuzko trazua, itzalak, barruko testua eta biraketa"],
"showcase_text":["Katalogoa: Text Art eta tipografia","Text Art-en 10 estiloak, testu kurbatua, zutabeak, bost buleta-maila, 8 letra-bikoteak, lerrokatzea eta tartea"],
"showcase_transitions":["Katalogoa: trantsizioak","22 diapositiba-trantsizioak, banan-banan: sarrera, irteera desberdina, norabideak, abiadura eta aurrerapen automatikoa"]};
