// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Résultats trimestriels au conseil","Bleu foncé et or : grands indicateurs animés avec son, cascade, entonnoir, barres empilées et tableau avec formules face au budget"],
"biz_climate":["Enquête sur le climat social","Violet et participatif : compte à rebours, barres à 100 %, note de 1 à 5, nuage de mots, choix multiple et questions du public"],
"biz_investment":["Présentation pour investisseurs","Noir et or : produit 3D qui tourne et voyage avec Transformer, chiffres géants, marché en cercles, traction, utilisation des fonds et équipe"],
"biz_marketing":["Plan marketing de campagne","Style chaleureux : texte en cercle, public cible, entonnoir, mix de canaux, calendrier en tableau, budget avec formule et vote"],
"biz_onboarding":["Accueil des nouveaux employés","Style convivial : robot 3D qui salue et parcourt la semaine à pied, organigramme un par un, valeurs avec icônes et activité d'association"],
"biz_proposal":["Proposition commerciale à un client","Style papier : sceau, processus un par un, maquettes sur ordinateur portable et mobile, tarifs, budget avec TVA en formules, chronologie et garanties"],
"biz_roadmap":["Feuille de route d'un projet","Style technique sombre : chevrons un par un, diagramme de Gantt animé, chronologie, voiture 3D qui avance avec Transformer et tableau d'état"],
"biz_sales":["Ventes et prévisions annuelles","Minimaliste en gris : barres et lignes combinées, scénarios, formule de prévision, tableau avec formules, barres empilées et horizontales"],
"biz_startup_agrotech":["Pitch agritech : irrigation par capteurs","Vue aérienne de parcelles avec carte d’humidité, satellite 3D de la NASA, mobile, gouttes en chaîne sonores, tableau à formules et treemap"],
"biz_startup_edtech":["Pitch edtech : tuteur de maths","Cahier à carreaux : post-it en chaîne, écriture manuscrite, équations pas à pas, mobile, quiz en direct, cycle et graphiques"],
"biz_startup_energy":["Pitch énergie : communauté solaire","Toits de l’aube à la nuit : soleil qui se lève et traverse le ciel en arc, diagramme radial, aires par heure, équation et tableau à formules"],
"biz_startup_fashion":["Pitch mode circulaire : Retal","Étiquette de vêtement qui voyage avec Morphose, coutures pointillées, vie d’un vêtement en chaîne, cycle, anneau, radar et vote multiple"],
"biz_startup_insurance":["Pitch assurance : couverture à la journée","Pluie grise et parapluie jaune : pictogramme en chaîne, appli avec interrupteur, équation du prix, tableau à formules, chronologie et vote"],
"biz_startup_kitchen":["Pitch robotique de cuisine : Fogón","Cuisine pro : bons sur le rail, Text Art de feu, robot 3D qui entre en marchant et salue, recette en code, compte à rebours et entonnoir"],
"biz_startup_lastmile":["Pitch logistique : dernier kilomètre","Style plan de métro : lignes qui se tracent seules, camion 3D et vélos qui parcourent la carte, tableau à formules, aires et cascade"],
"biz_startup_mental":["Pitch santé mentale : Remanso","Nuit calme : anneaux qui respirent, minute de respiration avec compte à rebours, appli sur mobile, escalier, notation et tableau à formules"],
"biz_startup_pets":["Pitch animaux : nourriture fraîche","Style autocollant avec empreintes en chaîne, renard 3D qui traverse en marchant, formule de la ration dans un tableau, anneau et quiz"],
"biz_startup_rural":["Pitch tourisme rural : Alpende","Montagnes au crépuscule et cartes postales : lanterne 3D, cachet au texte courbe, carte avec voiture 3D sur la route, barres, secteurs et nuage de mots"],
"biz_strategy":["Plan stratégique et OKR","Style blanc épuré : chiffres qui entrent en chaîne, pyramide, priorités avec icônes, tableau d'OKR, barres d'avancement, radar et chevrons"],
"biz_swot":["Analyse SWOT et concurrence","Fond graphite : SWOT par quadrants, matrice des stratégies, carte de positionnement, barres groupées, Venn, camembert et vote à choix multiple"],
"creative_bauhaus":["Bauhaus : forme et fonction","Art géométrique Bauhaus : formes primaires qui tournent et rebondissent, chronologie, grille en Morphose et activité d'association"],
"creative_brutalism":["Brutalisme : manifeste web","Style brutaliste : typographie géante, blocs noirs, texte vertical, ombres dures, barré animé, tableau et sondage"],
"creative_comic":["BD : super-pouvoirs des animaux","Style BD : cases, bulles de dialogue et de pensée, onomatopées en Text Art qui rebondissent, renard 3D, graphique et quiz"],
"creative_fashion":["Magazine de mode : automne lent","Style magazine : titre en serif, montre 3D en couverture, colonnes avec lettrine, grande citation, palette de saison et graphique"],
"creative_glass":["Glassmorphism : appli de finances","Cartes translucides sur des lueurs colorées, appli dans un mobile, graphique en anneau, carte en Morphose et vote de notation"],
"creative_pixel":["Pixel art : ton premier jeu vidéo","Style jeu vidéo rétro : sprites en pixels, tableau des scores, personnages 3D qui marchent et sautent, code pas à pas, quiz et compte à rebours"],
"creative_space":["Galaxie : regarder le passé","Style spatial : étoiles, nébuleuses lumineuses, modèles 3D de la NASA, sonde qui parcourt les planètes, texte courbé et quiz"],
"creative_swiss_blood":["Campagne : donnez votre sang","Affiche publique blanc et rouge : goutte qui remplit l'écran avec Morphose, processus, oui ou attends, anneau, barres, mobile et quiz"],
"creative_swiss_chairs":["Exposition : la chaise moderne","Affiche suisse gris et citron vert : chaise 3D qui tourne et voyage avec Morphose, chronologie, anneau, fauteuil 3D, tableau avec formules et ordonner"],
"creative_swiss_designconf":["Congrès de design : Grille 27","Graphite et cyan : la grille se construit seule et se transforme avec Morphose, chiffre en contour, formule, chronologie, code CSS, nuage et pause"],
"creative_swiss_film":["Festival de cinéma : le programme","Suisse en noir et rouge : chiffre géant qui devient bandeau avec Morphose, sections en grille, tableau, barres, sondage et compte à rebours"],
"creative_swiss_foundation":["Rapport annuel d'une fondation","Suisse en blanc et bleu cobalt : année géante, lettre pleine page, chiffres en chaîne, équation, anneau, aire, chevrons et comptes avec formules"],
"creative_swiss_games":["Jeux scolaires : l'identité visuelle","Blanc et magenta, palette propre : pictogrammes SVG, figure 3D qui traverse la ville, lignes, tableau des médailles avec formules, étapes et quiz"],
"creative_swiss_museum":["Guide du musée d'histoire naturelle","Signalétique suisse noir et jaune : plan maison avec parcours animé, renard 3D qui marche, colonnes, tableau, étiquetage et pictogrammes"],
"creative_swiss_orchestra":["Orchestre symphonique : saison 26/27","Bleu nuit et ambre : arcs qui tournent, texte courbe, chiffres sur une portée, cycles, tableau, équation, barres, sondage et applaudissements"],
"creative_swiss_publisher":["Catalogue d'automne d'une maison d'édition","Papier crème et vert pétrole : étagère de dos verticaux, couvertures SVG, tablette, camembert, commande avec formules, calendrier et trous"],
"creative_swiss_typeface":["Spécimen d'une nouvelle police","Spécimen blanc et violet : lettres qui voyagent avec Morphose, anatomie mesurée, échelle avec formule, glyphes, radar et licences"],
"creative_synthwave":["Synthwave : festival Neón 86","Style rétro années 80 : soleil en dégradé, grille qui se dessine, néon lumineux, Morphose, robot 3D qui danse et nuage de mots"],
"creative_watercolor":["Aquarelle : potager sur le balcon","Style aquarelle et papier : taches en dégradé radial, formes à main levée, écriture manuscrite, dessin qui se trace seul et 3D"],
"creative_zen":["Minimalisme japonais : le thé","Minimalisme japonais : beaucoup de blanc, soleil rouge en Morphose, texte vertical, ensō qui se peint seul et compte à rebours"],
"data_ab_test":["Expérience A/B","Équations, nuage de points à deux séries, colonnes étiquetées, tableau de conversion à formules et chiffres de significativité"],
"data_energy":["Énergie et consommation","Aires empilées par heure, lignes à trois séries, compartimentage, colonnes étiquetées et tableau de tarifs calculé"],
"data_exec_panel":["Tableau de bord mensuel de direction","KPI avec feux tricolores et mini-graphiques, combiné face au budget, petits multiples, anneau et vote"],
"data_home_finance":["Finances personnelles","Cascade du salaire à l'épargne, graphique circulaire, lignes et aires, tableaux avec SOMME, MOYENNE, MAX et MIN"],
"data_market_study":["Étude de marché","Grands chiffres, compartimentage, bulles, nuage de points, barres horizontales à deux séries et matrice 2 × 2"],
"data_population":["Population et démographie","Pyramide des âges, histogramme, barres horizontales, lignes qui se croisent et tableau d'indicateurs à formules"],
"data_sales_regions":["Ventes par région","Barres groupées, empilées et à 100 %, graphique combiné avec objectif, tableau aux totaux par formule et KPI animés"],
"data_satisfaction":["Enquête de satisfaction","Anneau avec légende, radars comparés, colonnes étiquetées, NPS, notation et nuage de mots en direct"],
"data_season_stats":["La saison en chiffres","Chiffres géants sonores, classement à formules, barres négatives, lignes, barres empilées et radar de l'équipe"],
"data_web_metrics":["Mesures web et marketing","KPI avec mini-graphiques, lignes à quatre séries, aires, entonnoir de conversion, graphique combiné et tableau à formules"],
"edu_body":["Le corps humain","Style laboratoire : figure 3D avec Morphose, personnage qui marche sur un parcours, graphique en barres, légender le corps et quiz"],
"edu_cell":["La cellule","Cellule dessinée avec des formes, parties une à une, Morphose pour zoomer, associer des paires, diagramme, plante 3D et note"],
"edu_english":["Anglais pour débutants","Mode classe : cartes qui se retournent avec son, robot 3D qui marche et salue, renard 3D, trois questions à points, classement et applaudissements"],
"edu_fractions":["Les fractions","Style néon : pizzas dessinées, équations pas à pas, addition avec Morphose, texte à trous, quiz et défi avec compte à rebours"],
"edu_hist_alandalus":["Al-Andalus : science et jardins","Arc outrepassé, chronologie pas à pas, barres horizontales, astrolabe qui tourne, étoile par Morphose, associer des paires et vote"],
"edu_hist_castle":["Châteaux et féodalité","Château nocturne et chevalier 3D qui traverse le pont, pyramide féodale qui s’élève, étiqueter, soleil qui parcourt la journée, treemap et blasons"],
"edu_hist_egypt":["L’Égypte, don du Nil","Lapis-lazuli et or : soleil qui se lève derrière les pyramides, crue animée, graphique en aires, équation, Morphose, cartouche hiéroglyphique et mise en ordre"],
"edu_hist_greece":["Athènes : naissance de la démocratie","Style vase à figures noires : méandre, texte courbé, Morphose, anneau, temple qui s’élève, ostraka sonores, vote et tableau"],
"edu_hist_maya":["Les Mayas : le temps et les étoiles","Jungle et jade : nombres en points et barres, Morphose en base 20, équation, roues de calendrier qui tournent, serpent de lumière et cacao"],
"edu_hist_mesopotamia":["Mésopotamie : naissance de l’écriture","Tablette d’argile qui s’écrit seule, carte aux fleuves tracés, ziggourat qui grandit, base 60 avec formules, texte à trous et radial"],
"edu_hist_printing":["L’imprimerie : le livre se multiplie","Page d’incunable : lettrine rouge, caractères inversés composés par Morphose, presse qui descend avec son, chiffres, barres et texte à trous"],
"edu_hist_rome":["Rome, ingénieurs de l’empire","Marbre et rouge impérial : Morphose, arc de triomphe, voie en couches avec soldat 3D qui marche, aqueduc, équation, formules et quiz"],
"edu_hist_silkroad":["La route de la soie","Soie et safran : caravane en marche, carte avec route tracée, cascade du prix, tableau avec formules, lanterne 3D, équation et mise en ordre"],
"edu_hist_vikings":["Les Vikings, navigateurs du Nord","Fjord sous l’aurore : bateau qui se balance, runes, mythes barrés avec tampon, traversée animée, chiffres sonores, guerrier 3D, radar et associer"],
"edu_math_coordinates":["Coordonnées : la carte au trésor","Carte au trésor : rose des vents avec texte courbe, points qui apparaissent, pirate 3D qui suit des indices, bateau qui se dessine et étiquetage"],
"edu_math_integers":["Nombres entiers : mer et montagne","Du fond de la mer au sommet : droite avec sauts, Text Art glace, températures négatives, sous-marin qui monte et descend, classement et quiz"],
"edu_math_primes":["Nombres premiers","Terminal vert : néon personnalisé, crible d'Ératosthène clic après clic avec 100 cases, arbre de facteurs, code pas à pas, quiz et défi"],
"edu_math_probability":["Probabilités : mesurer la chance","Table de jeu bordeaux et or : dés qui roulent avec roulement de tambour, texte courbe, règle de Laplace, arbre un par un, barres, courbes et quiz"],
"edu_math_proportion":["La proportionnalité au supermarché","Ticket de caisse : tampon qui rebondit, tableau de proportionnalité avec formules, règle de trois pas à pas, soldes calculés, courbes et textes à trous"],
"edu_math_pythagoras":["Le théorème de Pythagore","Tableau noir : figure qui se dessine seule, démonstration sans mots avec Morphose, triplets avec formules, raccourci en 3D et quiz"],
"edu_math_sequences":["Suites et motifs","Livre de botanique : spirale de Fibonacci qui se trace seule, cailloux en chaîne, allumettes avec formules, code, plante 3D et nombre d'or"],
"edu_math_stats":["Statistiques : moyenne, médiane et mode","Cahier quadrillé : notes adhésives en cascade, fréquences avec formules, barres, anneau avec degrés, histogramme et vote en direct"],
"edu_math_symmetry":["Symétrie et pavages","Azulejos nasrides : étoile qui tourne, papillon qui se reflète, translation, rotation et symétrie animées, tableau d'angles et nid d'abeilles"],
"edu_math_volumes":["Aires et volumes","Plan technique bleu : cartouche en tableau, patron, bouteille 3D mesurée, volumes avec formules, barres, cônes qui remplissent et association"],
"edu_quixote":["Don Quichotte","Style encre et papier : moulin qui tourne avec son, texte courbe, citations animées, Morphose, chronologie, texte à trous et quiz"],
"edu_renewables":["Énergies renouvelables","Éolienne qui tourne, cartes, graphiques en aires, en anneau et en barres groupées, nuage de mots en direct, sondage et compte à rebours"],
"edu_revolution":["La Révolution française","Style papier ancien : texte en cercle, Morphose, pyramide sociale, chronologie animée avec son, remettre les faits en ordre et sondage"],
"edu_spain":["Géographie de l'Espagne","Style atlas : rose des vents, relief en cible, tableau des fleuves avec formules, graphiques des sommets et des pluies, associer des paires et quiz"],
"edu_volcanoes":["Les volcans","Style feu : éruption animée avec son, parties du volcan à légender, tableau, quiz chronométré et compte à rebours"],
"edu_water":["Le cycle de l'eau","Diagramme de cycle un à un, paysage avec gouttes qui montent et pluie animée avec son, graphiques en anneau, associer des paires et satellite 3D"],
"life_bookclub":["Club de lecture","Étagère à main levée, couverture faite de formes, citations qui se transforment, diagramme radial, note et vote du prochain livre"],
"life_cv":["CV visuel","Texte en cercle, chiffres clés, chronologie pas à pas, barres de compétences animées, radar, écrans dans des appareils et contact"],
"life_fitness":["Plan d'entraînement : 5 km","Coureur 3D, Text Art feu, phases en dégradé, semaine avec formules, graphiques de progression, pyramide, compte à rebours et nuage de mots"],
"life_garden":["Potager urbain","Plante 3D avec Transformer, calendrier des semis en tableau coloré, cycle, Venn, graphiques d'arrosage et de croissance, activité d'étiquetage"],
"life_graduation":["Remise des diplômes et fin d'année","Text Art or, mortiers faits de formes, polaroïds qui pivotent à l'entrée, chiffres avec roulement de tambour, remerciements, nuage de mots et applaudissements"],
"life_italy":["Voyage en Italie","Texte en cercle, itinéraire avec connecteurs et trajet animé, chronologie, budget avec formules, graphiques et activité d'association"],
"life_kids_party":["Anniversaire d'enfant","Couleurs vives : robot 3D qui danse, personnages qui fêtent, ballons à main levée, quiz à points et compte à rebours"],
"life_moving":["Déménagement et nouveau foyer","Maison en formes à main levée, chronologie, liste qui se barre, meubles 3D qui passent sur le plan avec Transformer, budget et activité de classement"],
"life_recipe":["Recette : guacamole","Avocat 3D qui voyage entre les diapositives (Transformer), ingrédients avec formules, étapes une à une, compte à rebours et note"],
"life_travel_eu_amsterdam":["Amsterdam : canaux et vélos","Façades de canal qui se montent en chaîne, canaux en cible, vélo qui traverse avec son, tableau à formules, lignes et vote en camembert"],
"life_travel_eu_camino":["Chemin de Compostelle : depuis Sarria","Crédenciale qui se remplit de tampons sonores, cascade de kilomètres, marcheur 3D, équation du sac, anneau et étapes à ordonner"],
"life_travel_eu_croatia":["Croatie : la Dalmatie à la voile","Carte marine, rose des vents qui tourne et voyage avec Morphose, pavillons, associer, milles à formules, quiz et compte à rebours"],
"life_travel_eu_danube":["Le Danube à vélo","Style compteur vélo : trajet sur mobile, fichier GPX pas à pas, barres empilées, gourde 3D avec Morphose, formules et rectangles"],
"life_travel_eu_fjords":["Fjords norvégiens par l’eau","Paysage en couches avec reflets, bateau qui navigue, coupe du fjord qui se dessine, barres, radar, étapes une à une et vote multiple"],
"life_travel_eu_greece":["Îles grecques en ferry","Village blanc en formes, grecque, route qui se dessine, horaires à formules, bulles, lunettes 3D avec Morphose et coucher de soleil"],
"life_travel_eu_iceland":["Islande : la Ring Road en voiture","Aurores en dégradé, carte avec trajet sonore, voiture 3D, chiffres avec roulement, équation du froid, renard qui marche et quiz"],
"life_travel_eu_lisbon":["Lisbonne : collines et tramways","Azulejos en SVG, tramway qui gravit les collines sur un trajet sonore, profil d’altitude, cartes qui tournent, tableau à formules et trous"],
"life_travel_eu_prague":["Prague, la ville aux cent clochers","Horloge astronomique en formes qui tourne et voyage avec Morphose, défilé avec carillon, compte à rebours, carte à légender et tableau"],
"life_travel_eu_scotland":["Écosse : les Highlands en voiture","Tartan tissé de formes, route qui se dessine, voitures qui se cèdent le passage, châteaux qui tournent, lanterne 3D, barres et questions"],
"life_wedding":["Faire-part de mariage","Typographie classique et or : Text Art, texte courbé, chronologie du couple, carte avec trajet animé, sondage et compte à rebours"],
"prod_app_bank":["Cartilla : la banque pour les seniors","Livret d'épargne cuir et or : Text Art or, Morphose pour zoomer sur le mobile, tableau avec SOMME, cascade, tampon et quiz anti-fraude"],
"prod_app_gym":["Serie : réservations dans ta salle de sport","Tableau LED : guerrier 3D qui célèbre et marche jusqu'au cours, deux comptes à rebours, affluence par heure, tarifs avec formules et quiz"],
"prod_app_health":["Turno : rendez-vous au centre de santé","Clinique : battement qui se dessine, avant et après, cycle un par un, patient 3D qui marche, agenda sur écran, barres et questions"],
"prod_app_language":["Vocablo : appli pour apprendre les langues","Carte par avion : timbres, bulles qui sautent avec du son, cartes qui se retournent, Morphose, équation de l'oubli, graphique et association"],
"prod_app_market":["Plaza : le marché du quartier à domicile","Auvent et ardoises : camionnette 3D qui parcourt le plan, étals en radial, mobile, rectangles, commissions avec formules et vote"],
"prod_app_meditation":["Marea : appli de méditation et de sommeil","Mer de nuit : lune avec texte courbe, Morphose du mobile, respiration guidée par anneaux enchaînés, compte à rebours, graphique et lanterne 3D"],
"prod_app_music":["Garaje : musique live du quartier","Vinyle et néon : disque qui voyage avec Morphose, texte courbe qui tourne, égaliseur avec roulement, portable, radar, camembert et nuage de mots"],
"prod_app_photo":["Grano : photographie argentique","Chambre noire : bande de film, photo qui se révèle avec Morphose, compteur avec roulement, histogramme, tablette, tableau et étiquetage"],
"prod_app_recipes":["Sobras : recettes avec ce qu'on a","Frigo à post-it : avocat 3D avec Morphose, mobile qui reconnaît les ingrédients, étapes, anneau, recette avec formules et compte à rebours"],
"prod_app_transit":["Andén : transports urbains","Signalétique de métro : tableau des départs avec compte à rebours, plan qui se dessine seul, trajet animé, mobile, barres empilées et tarifs"],
"product_app":["Présentation d’application mobile","Application sur mobile, tablette et portable, Morphose, parcours en chevrons, chiffres, graphique de rétention et nuage de mots"],
"product_car":["Présentation : voiture électrique","Voiture 3D sans bords coupés qui fait le tour en entrant, Morphose, chiffres, graphiques en aires et barres, tableau et vote"],
"product_eco":["Durabilité du produit","Vert éco : plante 3D avec Morphose, cycle de vie, cascade d’empreinte, barres des matériaux, courbes avec objectif et texte à trous"],
"product_furniture":["Collection de meubles","Style éditorial : canapés et chaises 3D, Morphose avec vues différentes, balancement et tour, nuancier, tablette et budget"],
"product_keynote":["Keynote matériel","Style blanc premium : lampe irisée et bouteille 3D, Morphose avec étiquettes, flotter et zoomer, chiffres, tableau et prix"],
"product_roadmap":["Feuille de route produit","Chemin qui se dessine seul, pyramide, chronologie un par un, maintenant et ensuite, matrice, barres empilées, vote multiple et à ordonner"],
"product_robot":["Robot assistant industriel","Style industriel : robot 3D qui salue, suit un parcours, enchaîne les animations et danse ; organigramme, cycle, graphique et quiz"],
"product_saas":["Démo de plateforme SaaS","Tableau de bord dans une fenêtre de navigateur avec repères numérotés, radial, entonnoir, indicateurs, barres empilées, code par étapes et questions"],
"product_security":["Sécurité du produit","Néon vert : cible en couches, flux avec connecteurs qui apparaît pas à pas, code surligné, graphique, escalier et activité d’association"],
"product_watch":["Lancement : montre connectée","Noir et or : montre 3D qui traverse trois diapositives avec Morphose et arrivées différentes, Text Art or, radar et prix"],
"sci_ai":["Intelligence artificielle","Néon violet : robot 3D qui salue et voyage avec Morphose, chronologie, organigramme, réseau de neurones qui s'allume, graphique et nuage de mots"],
"sci_brain":["Neurosciences : le cerveau","Style sombre lumineux : neurone dessiné avec influx animé, personnage 3D qui marche, radial, organigramme, barres et légender une image"],
"sci_chem":["Chimie : le tableau périodique","Laboratoire épuré : tableau périodique qui se construit en cascade, molécules en formes, brasero 3D, équations, anneau et association"],
"sci_climate":["Le changement climatique en données","Bandes de réchauffement, graphiques en courbes, aires et rectangles, effet de serre qui se dessine, satellite 3D, cycle et vote à choix multiple"],
"sci_mars":["Mission vers Mars","Style spatial rouille : rover 3D de la NASA avec Morphose, astronaute flottant, orbite animée, équation et quiz"],
"sci_med_case":["Cas clinique : fièvre et toux","Style dossier médical : chemise, tampon, radio sur négatoscope avec cercle qui se dessine, CURB-65 avec formule, vote et questions"],
"sci_med_ecg":["Cardiologie : lire un ECG","Papier d'ECG : tracés qui se dessinent seuls, influx qui parcourt le cœur, tableau avec formules, équation, quiz et compte à rebours"],
"sci_med_glucose":["Endocrinologie : glucose et insuline","Style appli de capteur de glucose : téléphone avec l'écran, cycle un par un, courbes, anneau, tableau avec formules, équation, avocat 3D et vote"],
"sci_med_immune":["Immunologie : la réponse immunitaire","Microscope à fluorescence : cellules qui s'allument, anticorps dessiné, phagocytose avec Morphose, organigramme et associations"],
"sci_med_kidney":["Physiologie rénale : le néphron","Plan technique : néphron qui se dessine, goutte qui le parcourt avec son, cotes, cascade, équation, tableau avec formules, bouteille 3D et cycle"],
"sci_med_knee":["Anatomie : le genou","Style planche anatomique ancienne : texte courbe, gravure sépia, Morphose vers les ménisques, matrice, tableau, figure 3D qui marche et étiquetage"],
"sci_med_micro":["Microbiologie : résistance aux antibiotiques","Boîtes de Petri : colonies qui apparaissent avec son, croissance exponentielle, sélection racontée avec Morphose, antibiogramme, radial et nuage de mots"],
"sci_med_pk":["Pharmacocinétique : la demi-vie","Style boîte de médicament : blister qui se remplit, LADME un par un, courbes à deux séries, équations, tableau avec formules, code et textes à trous"],
"sci_med_stroke":["Neurologie : alerte AVC","Course contre la montre aux urgences : gyrophares, chiffre géant avec roulement de tambour, BE-FAST enchaîné, anneau, chevrons, ordonner les étapes et compte à rebours"],
"sci_med_trial":["Essai clinique : lire les résultats","Style revue scientifique : CONSORT avec connecteurs, courbes de survie, tableau avec formules, NNT, forest plot enchaîné et quiz"],
"sci_newton":["Physique : les lois de Newton","Cahier de physique : équations, voiture 3D en mouvement, tir parabolique qui se dessine, tableau avec formules et texte à trous"],
"sci_python":["Programmer en Python","Style éditeur sombre : terminal qui s'écrit tout seul, code avec étapes de surlignage, sortie animée, lignes à ordonner et défi chronométré"],
"sci_solar":["Le système solaire","Planètes à l'échelle qui apparaissent en chaîne, trois sondes 3D aux vues et mouvements différents, tableau, diagramme radial et association"],
"sci_stats":["Statistiques et probabilités","Style éditorial : courbe en cloche qui se dessine, formules, histogramme, nuage de points, aires, barres et bulles, et question à points"],
"sci_thesis":["Soutenance de mémoire de licence","Académique sobre : couverture institutionnelle, sommaire, méthodologie avec équation, tableau avec totaux, résultats en graphiques, bibliographie et Q&R"],
"showcase_3d":["Catalogue : la 3D en détail","Modèles 3D avec toutes leurs options : vues, mouvements à l’entrée, rotation, bords, marge, clips, marche et arrivée avec Morphose"],
"showcase_animations":["Catalogue : animations","Toutes les animations d’objet : entrée, emphase, sortie, trajectoires, dessin, enchaînées, sons et plusieurs sur un objet"],
"showcase_charts":["Catalogue : graphiques","Les 15 types de graphique, deux par diapositive, avec séries, combiné, grille, étiquettes et titres d’axes, et le tableau des options"],
"showcase_diagrams":["Catalogue : diagrammes","Les 15 dispositions de diagramme écrites comme un plan, les 4 jeux de couleurs et l’apparition un à un en présentation"],
"showcase_morph":["Catalogue : Morphose","Morphose pas à pas : texte qui change de taille et de place, formes, barres qui grandissent, image, 3D et lettres qui se réordonnent"],
"showcase_objects":["Catalogue : multimédia et objets","Code par étapes, équations, icônes, cinq appareils, tableaux avec styles et formules, zoom de diapositive et connecteurs"],
"showcase_polls":["Catalogue : sondages et activités","Les 11 types de sondage et d’activité depuis le mobile, compte à rebours dans ses trois styles, classement et mode classe"],
"showcase_shapes":["Catalogue : formes","Toutes les formes par catégorie avec leur nom, lignes et tirets, dégradés, opacité, tracé à main levée, ombres, texte à l’intérieur et rotation"],
"showcase_text":["Catalogue : Text Art et typographie","Les 10 styles de Text Art, texte courbé, colonnes, cinq niveaux de puces, les 8 paires de polices, alignement et espacement"],
"showcase_transitions":["Catalogue : transitions","Les 22 transitions de diapositive, une à une : entrée, sortie différente, directions, vitesse et avance automatique"]};
