// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Résultats trimestriels au conseil","Bleu foncé et or : grands indicateurs animés avec son, cascade, entonnoir, barres empilées et tableau avec formules face au budget"],
"biz_climate":["Enquête sur le climat social","Violet et participatif : compte à rebours, barres à 100 %, note de 1 à 5, nuage de mots, choix multiple et questions du public"],
"biz_investment":["Présentation pour investisseurs","Noir et or : produit 3D qui tourne et voyage avec Transformer, chiffres géants, marché en cercles, traction, utilisation des fonds et équipe"],
"biz_marketing":["Plan marketing de campagne","Style chaleureux : texte en cercle, public cible, entonnoir, mix de canaux, calendrier en tableau, budget avec formule et vote"],
"biz_onboarding":["Accueil des nouveaux employés","Style convivial : robot 3D qui salue et parcourt la semaine à pied, organigramme un par un, valeurs avec icônes et activité d'association"],
"biz_proposal":["Proposition commerciale à un client","Style papier : sceau, processus un par un, maquettes sur ordinateur portable et mobile, tarifs, budget avec TVA en formules, chronologie et garanties"],
"biz_roadmap":["Feuille de route d'un projet","Style technique sombre : chevrons un par un, diagramme de Gantt animé, chronologie, voiture 3D qui avance avec Transformer et tableau d'état"],
"biz_sales":["Ventes et prévisions annuelles","Minimaliste en gris : barres et lignes combinées, scénarios, formule de prévision, tableau avec formules, barres empilées et horizontales"],
"biz_strategy":["Plan stratégique et OKR","Style blanc épuré : chiffres qui entrent en chaîne, pyramide, priorités avec icônes, tableau d'OKR, barres d'avancement, radar et chevrons"],
"biz_swot":["Analyse SWOT et concurrence","Fond graphite : SWOT par quadrants, matrice des stratégies, carte de positionnement, barres groupées, Venn, camembert et vote à choix multiple"],
"creative_bauhaus":["Bauhaus : forme et fonction","Art géométrique Bauhaus : formes primaires qui tournent et rebondissent, chronologie, grille en Morphose et activité d'association"],
"creative_brutalism":["Brutalisme : manifeste web","Style brutaliste : typographie géante, blocs noirs, texte vertical, ombres dures, barré animé, tableau et sondage"],
"creative_comic":["BD : super-pouvoirs des animaux","Style BD : cases, bulles de dialogue et de pensée, onomatopées en Text Art qui rebondissent, renard 3D, graphique et quiz"],
"creative_fashion":["Magazine de mode : automne lent","Style magazine : titre en serif, montre 3D en couverture, colonnes avec lettrine, grande citation, palette de saison et graphique"],
"creative_glass":["Glassmorphism : appli de finances","Cartes translucides sur des lueurs colorées, appli dans un mobile, graphique en anneau, carte en Morphose et vote de notation"],
"creative_pixel":["Pixel art : ton premier jeu vidéo","Style jeu vidéo rétro : sprites en pixels, tableau des scores, personnages 3D qui marchent et sautent, code pas à pas, quiz et compte à rebours"],
"creative_space":["Galaxie : regarder le passé","Style spatial : étoiles, nébuleuses lumineuses, modèles 3D de la NASA, sonde qui parcourt les planètes, texte courbé et quiz"],
"creative_synthwave":["Synthwave : festival Neón 86","Style rétro années 80 : soleil en dégradé, grille qui se dessine, néon lumineux, Morphose, robot 3D qui danse et nuage de mots"],
"creative_watercolor":["Aquarelle : potager sur le balcon","Style aquarelle et papier : taches en dégradé radial, formes à main levée, écriture manuscrite, dessin qui se trace seul et 3D"],
"creative_zen":["Minimalisme japonais : le thé","Minimalisme japonais : beaucoup de blanc, soleil rouge en Morphose, texte vertical, ensō qui se peint seul et compte à rebours"],
"data_ab_test":["Expérience A/B","Équations, nuage de points à deux séries, colonnes étiquetées, tableau de conversion à formules et chiffres de significativité"],
"data_energy":["Énergie et consommation","Aires empilées par heure, lignes à trois séries, compartimentage, colonnes étiquetées et tableau de tarifs calculé"],
"data_exec_panel":["Tableau de bord mensuel de direction","KPI avec feux tricolores et mini-graphiques, combiné face au budget, petits multiples, anneau et vote"],
"data_home_finance":["Finances personnelles","Cascade du salaire à l'épargne, graphique circulaire, lignes et aires, tableaux avec SOMME, MOYENNE, MAX et MIN"],
"data_market_study":["Étude de marché","Grands chiffres, compartimentage, bulles, nuage de points, barres horizontales à deux séries et matrice 2 × 2"],
"data_population":["Population et démographie","Pyramide des âges, histogramme, barres horizontales, lignes qui se croisent et tableau d'indicateurs à formules"],
"data_sales_regions":["Ventes par région","Barres groupées, empilées et à 100 %, graphique combiné avec objectif, tableau aux totaux par formule et KPI animés"],
"data_satisfaction":["Enquête de satisfaction","Anneau avec légende, radars comparés, colonnes étiquetées, NPS, notation et nuage de mots en direct"],
"data_season_stats":["La saison en chiffres","Chiffres géants sonores, classement à formules, barres négatives, lignes, barres empilées et radar de l'équipe"],
"data_web_metrics":["Mesures web et marketing","KPI avec mini-graphiques, lignes à quatre séries, aires, entonnoir de conversion, graphique combiné et tableau à formules"],
"edu_body":["Le corps humain","Style laboratoire : figure 3D avec Morphose, personnage qui marche sur un parcours, graphique en barres, légender le corps et quiz"],
"edu_cell":["La cellule","Cellule dessinée avec des formes, parties une à une, Morphose pour zoomer, associer des paires, diagramme, plante 3D et note"],
"edu_english":["Anglais pour débutants","Mode classe : cartes qui se retournent avec son, robot 3D qui marche et salue, renard 3D, trois questions à points, classement et applaudissements"],
"edu_fractions":["Les fractions","Style néon : pizzas dessinées, équations pas à pas, addition avec Morphose, texte à trous, quiz et défi avec compte à rebours"],
"edu_quixote":["Don Quichotte","Style encre et papier : moulin qui tourne avec son, texte courbe, citations animées, Morphose, chronologie, texte à trous et quiz"],
"edu_renewables":["Énergies renouvelables","Éolienne qui tourne, cartes, graphiques en aires, en anneau et en barres groupées, nuage de mots en direct, sondage et compte à rebours"],
"edu_revolution":["La Révolution française","Style papier ancien : texte en cercle, Morphose, pyramide sociale, chronologie animée avec son, remettre les faits en ordre et sondage"],
"edu_spain":["Géographie de l'Espagne","Style atlas : rose des vents, relief en cible, tableau des fleuves avec formules, graphiques des sommets et des pluies, associer des paires et quiz"],
"edu_volcanoes":["Les volcans","Style feu : éruption animée avec son, parties du volcan à légender, tableau, quiz chronométré et compte à rebours"],
"edu_water":["Le cycle de l'eau","Diagramme de cycle un à un, paysage avec gouttes qui montent et pluie animée avec son, graphiques en anneau, associer des paires et satellite 3D"],
"life_bookclub":["Club de lecture","Étagère à main levée, couverture faite de formes, citations qui se transforment, diagramme radial, note et vote du prochain livre"],
"life_cv":["CV visuel","Texte en cercle, chiffres clés, chronologie pas à pas, barres de compétences animées, radar, écrans dans des appareils et contact"],
"life_fitness":["Plan d'entraînement : 5 km","Coureur 3D, Text Art feu, phases en dégradé, semaine avec formules, graphiques de progression, pyramide, compte à rebours et nuage de mots"],
"life_garden":["Potager urbain","Plante 3D avec Transformer, calendrier des semis en tableau coloré, cycle, Venn, graphiques d'arrosage et de croissance, activité d'étiquetage"],
"life_graduation":["Remise des diplômes et fin d'année","Text Art or, mortiers faits de formes, polaroïds qui pivotent à l'entrée, chiffres avec roulement de tambour, remerciements, nuage de mots et applaudissements"],
"life_italy":["Voyage en Italie","Texte en cercle, itinéraire avec connecteurs et trajet animé, chronologie, budget avec formules, graphiques et activité d'association"],
"life_kids_party":["Anniversaire d'enfant","Couleurs vives : robot 3D qui danse, personnages qui fêtent, ballons à main levée, quiz à points et compte à rebours"],
"life_moving":["Déménagement et nouveau foyer","Maison en formes à main levée, chronologie, liste qui se barre, meubles 3D qui passent sur le plan avec Transformer, budget et activité de classement"],
"life_recipe":["Recette : guacamole","Avocat 3D qui voyage entre les diapositives (Transformer), ingrédients avec formules, étapes une à une, compte à rebours et note"],
"life_wedding":["Faire-part de mariage","Typographie classique et or : Text Art, texte courbé, chronologie du couple, carte avec trajet animé, sondage et compte à rebours"],
"product_app":["Présentation d’application mobile","Application sur mobile, tablette et portable, Morphose, parcours en chevrons, chiffres, graphique de rétention et nuage de mots"],
"product_car":["Présentation : voiture électrique","Voiture 3D sans bords coupés qui fait le tour en entrant, Morphose, chiffres, graphiques en aires et barres, tableau et vote"],
"product_eco":["Durabilité du produit","Vert éco : plante 3D avec Morphose, cycle de vie, cascade d’empreinte, barres des matériaux, courbes avec objectif et texte à trous"],
"product_furniture":["Collection de meubles","Style éditorial : canapés et chaises 3D, Morphose avec vues différentes, balancement et tour, nuancier, tablette et budget"],
"product_keynote":["Keynote matériel","Style blanc premium : lampe irisée et bouteille 3D, Morphose avec étiquettes, flotter et zoomer, chiffres, tableau et prix"],
"product_roadmap":["Feuille de route produit","Chemin qui se dessine seul, pyramide, chronologie un par un, maintenant et ensuite, matrice, barres empilées, vote multiple et à ordonner"],
"product_robot":["Robot assistant industriel","Style industriel : robot 3D qui salue, suit un parcours, enchaîne les animations et danse ; organigramme, cycle, graphique et quiz"],
"product_saas":["Démo de plateforme SaaS","Tableau de bord dans une fenêtre de navigateur avec repères numérotés, radial, entonnoir, indicateurs, barres empilées, code par étapes et questions"],
"product_security":["Sécurité du produit","Néon vert : cible en couches, flux avec connecteurs qui apparaît pas à pas, code surligné, graphique, escalier et activité d’association"],
"product_watch":["Lancement : montre connectée","Noir et or : montre 3D qui traverse trois diapositives avec Morphose et arrivées différentes, Text Art or, radar et prix"],
"sci_ai":["Intelligence artificielle","Néon violet : robot 3D qui salue et voyage avec Morphose, chronologie, organigramme, réseau de neurones qui s'allume, graphique et nuage de mots"],
"sci_brain":["Neurosciences : le cerveau","Style sombre lumineux : neurone dessiné avec influx animé, personnage 3D qui marche, radial, organigramme, barres et légender une image"],
"sci_chem":["Chimie : le tableau périodique","Laboratoire épuré : tableau périodique qui se construit en cascade, molécules en formes, brasero 3D, équations, anneau et association"],
"sci_climate":["Le changement climatique en données","Bandes de réchauffement, graphiques en courbes, aires et rectangles, effet de serre qui se dessine, satellite 3D, cycle et vote à choix multiple"],
"sci_mars":["Mission vers Mars","Style spatial rouille : rover 3D de la NASA avec Morphose, astronaute flottant, orbite animée, équation et quiz"],
"sci_newton":["Physique : les lois de Newton","Cahier de physique : équations, voiture 3D en mouvement, tir parabolique qui se dessine, tableau avec formules et texte à trous"],
"sci_python":["Programmer en Python","Style éditeur sombre : terminal qui s'écrit tout seul, code avec étapes de surlignage, sortie animée, lignes à ordonner et défi chronométré"],
"sci_solar":["Le système solaire","Planètes à l'échelle qui apparaissent en chaîne, trois sondes 3D aux vues et mouvements différents, tableau, diagramme radial et association"],
"sci_stats":["Statistiques et probabilités","Style éditorial : courbe en cloche qui se dessine, formules, histogramme, nuage de points, aires, barres et bulles, et question à points"],
"sci_thesis":["Soutenance de mémoire de licence","Académique sobre : couverture institutionnelle, sommaire, méthodologie avec équation, tableau avec totaux, résultats en graphiques, bibliographie et Q&R"],
"showcase_3d":["Catalogue : la 3D en détail","Modèles 3D avec toutes leurs options : vues, mouvements à l’entrée, rotation, bords, marge, clips, marche et arrivée avec Morphose"],
"showcase_animations":["Catalogue : animations","Toutes les animations d’objet : entrée, emphase, sortie, trajectoires, dessin, enchaînées, sons et plusieurs sur un objet"],
"showcase_charts":["Catalogue : graphiques","Les 15 types de graphique, deux par diapositive, avec séries, combiné, grille, étiquettes et titres d’axes, et le tableau des options"],
"showcase_diagrams":["Catalogue : diagrammes","Les 15 dispositions de diagramme écrites comme un plan, les 4 jeux de couleurs et l’apparition un à un en présentation"],
"showcase_morph":["Catalogue : Morphose","Morphose pas à pas : texte qui change de taille et de place, formes, barres qui grandissent, image, 3D et lettres qui se réordonnent"],
"showcase_objects":["Catalogue : multimédia et objets","Code par étapes, équations, icônes, cinq appareils, tableaux avec styles et formules, zoom de diapositive et connecteurs"],
"showcase_polls":["Catalogue : sondages et activités","Les 11 types de sondage et d’activité depuis le mobile, compte à rebours dans ses trois styles, classement et mode classe"],
"showcase_shapes":["Catalogue : formes","Toutes les formes par catégorie avec leur nom, lignes et tirets, dégradés, opacité, tracé à main levée, ombres, texte à l’intérieur et rotation"],
"showcase_text":["Catalogue : Text Art et typographie","Les 10 styles de Text Art, texte courbé, colonnes, cinq niveaux de puces, les 8 paires de polices, alignement et espacement"],
"showcase_transitions":["Catalogue : transitions","Les 22 transitions de diapositive, une à une : entrée, sortie différente, directions, vitesse et avance automatique"]};
