// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Resultados trimestrais ao consello","Azul escuro e dourado: indicadores grandes animados con son, fervenza, funil, barras apiladas e táboa con fórmulas fronte ao orzamento"],
"biz_climate":["Enquisa de clima laboral","Violeta e participativo: conta atrás, barras ao 100 %, valoración de 1 a 5, nube de palabras, elección múltiple e preguntas do público"],
"biz_investment":["Presentación para investidores","Negro e ouro: produto 3D que xira e viaxa con Transformar, cifras xigantes, mercado en círculos, tracción, uso dos fondos e equipo"],
"biz_marketing":["Plan de márketing de campaña","Estilo cálido: texto en círculo, público obxectivo, funil, combinación de canles, calendario en táboa, orzamento con fórmula e votación"],
"biz_onboarding":["Benvida ás novas persoas empregadas","Estilo amable: robot 3D que saúda e percorre a semana camiñando, organigrama un a un, valores con iconas e actividade de emparellar"],
"biz_proposal":["Proposta comercial a un cliente","Estilo papel: selo, proceso un a un, maquetas en portátil e móbil, prezos, orzamento con IVE en fórmulas, cronoloxía e garantías"],
"biz_retail_basket":["Análise de cesta: o que conta un tíquet","Tíquet de caixa que se imprime, ecuación do tíquet medio, fervenza, dispersión, rede de produtos, táboa, consulta SQL, dónut e concurso"],
"biz_retail_blackfriday":["Campaña do Venres Negro","Negro e neon: etiquetas de prezo, cifras con son, prezos riscados, liñas por horas, funil, táboa con fórmulas, concurso e conta atrás"],
"biz_retail_cx":["Experiencia de cliente: a viaxe de Marta","Persoa debuxada, curva de emocións que se traza soa con caras en cadea, citas, NPS con ecuación, matriz, Transformar e valoración"],
"biz_retail_inventory":["Inventario: nin roturas nin excesos","Almacén debuxado con estantes e etiquetas, comparativa, Pareto en combinado, ecuación, táboa con fórmulas, código, lámpada 3D e ordenar"],
"biz_retail_loyalty":["Fidelización: o club da panadaría","Tarxeta de selos que se enche en cadea con son e aplausos, ecuación do valor do cliente, pirámide de niveis, táboa con fórmulas e app"],
"biz_retail_market":["Mercado municipal: plan para revivilo","Fachada de ferro con nome curvo, lousas de xiz en cadea, treemap, áreas por horas, calendario de tempada en táboa, aguacate 3D e nube"],
"biz_retail_omni":["Omnicanle: compra en liña, recolle na tenda","App no móbil e web no navegador debuxadas, ruta que se traza soa, furgoneta 3D que percorre a rúa, táboa con fórmula, código e barras apiladas ao 100 %"],
"biz_retail_opening":["Apertura dunha libraría-café","Fachada debuxada con toldo, mapa do barrio con puntos en cadea, Venn, butaca 3D, cronoloxía, táboa con fórmulas e conta atrás"],
"biz_retail_supermarket":["Supermercado: nova distribución","Planta feita de formas, carro que percorre a tenda, mapa de calor, seccións que se recolocan con Transformar, lineal e táboa"],
"biz_retail_window":["Escaparatismo: o escaparate de outono","Editorial en negro e marfil: lentes 3D con Transformar, texto en círculo, mostras de cor, escaparate debuxado con triángulo e puntos focais"],
"biz_roadmap":["Folla de ruta dun proxecto","Estilo técnico escuro: galóns un a un, diagrama de Gantt animado, cronoloxía, coche 3D que avanza con Transformar e táboa de estado"],
"biz_sales":["Vendas e previsión anual","Minimalista en gris: barras e liñas combinadas, escenarios, fórmula de previsión, táboa con fórmulas, barras apiladas e horizontais"],
"biz_startup_agrotech":["Pitch agrotech: rega con sensores","Vista aérea de parcelas con mapa de humidade, satélite 3D da NASA, móbil, pingas en cadea con son, táboa con fórmulas e treemap"],
"biz_startup_edtech":["Pitch edtech: titor de matemáticas","Caderno cuadriculado: pósits en cadea, letra manuscrita, ecuacións paso a paso, móbil, cuestionario en directo, ciclo e gráficos"],
"biz_startup_energy":["Pitch enerxía: comunidade solar","Tellados da alba á noite: sol que sae e cruza o ceo en arco, diagrama radial, áreas por horas, ecuación e táboa con fórmulas"],
"biz_startup_fashion":["Pitch moda circular: Retal","Etiqueta de roupa que viaxa con Transformar, costuras punteadas, vida dunha peza en cadea, ciclo, anel, radar e votación múltiple"],
"biz_startup_insurance":["Pitch seguros: cobertura por días","Choiva gris e paraugas amarelo: pictograma en cadea, app con interruptor, ecuación do prezo, táboa con fórmulas, cronoloxía e votación"],
"biz_startup_kitchen":["Pitch robótica de cociña: Fogón","Cociña profesional: comandas no rail, Text Art de lume, robot 3D que entra camiñando e saúda, receita en código, conta atrás e funil"],
"biz_startup_lastmile":["Pitch loxística: última milla","Estilo plano de metro: liñas que se debuxan soas, camión 3D e bicis que percorren o mapa, táboa con fórmulas, área e fervenza"],
"biz_startup_mental":["Pitch saúde mental: Remanso","Noite en calma: aneis que respiran, minuto de respiración con conta atrás, app no móbil, escaleira, valoración e táboa con fórmulas"],
"biz_startup_pets":["Pitch mascotas: comida fresca","Estilo adhesivo con pegadas que aparecen en cadea, raposo 3D que cruza camiñando, fórmula da ración nunha táboa, anel e concurso"],
"biz_startup_rural":["Pitch turismo rural: Alpende","Montañas ao solpor e postais: farol 3D, mataselos con texto curvo, mapa con coche 3D pola ruta, barras, torta e nube de palabras"],
"biz_strategy":["Plan estratéxico e OKR","Estilo limpo en branco: cifras que entran en cadea, pirámide, prioridades con iconas, táboa de OKR, barras de avance, radar e galóns"],
"biz_swot":["Análise DAFO e competencia","Fondo grafito: DAFO por cuadrantes, matriz de estratexias, mapa de posicionamento, barras agrupadas, Venn, torta e votación múltiple"],
"creative_bauhaus":["Bauhaus: forma e función","Arte xeométrica Bauhaus: formas primarias que xiran e rebotan, cronoloxía, retícula con Transformar e actividade de emparellar"],
"creative_brutalism":["Brutalismo: manifesto web","Estilo brutalista: tipografía xigante, bloques negros, texto vertical, sombras duras, riscado animado, táboa e votación"],
"creative_comic":["Banda deseñada: superpoderes animais","Estilo banda deseñada: viñetas, globos de diálogo e pensamento, onomatopeas en Text Art que rebotan, raposo 3D, gráfico e concurso"],
"creative_fashion":["Revista de moda: outono lento","Estilo revista: cabeceira con serifa, reloxo 3D na portada, columnas con capitular, cita grande, paleta de tempada e gráfico"],
"creative_glass":["Glassmorphism: app de finanzas","Tarxetas translúcidas sobre brillos de cor, móbil coa app, gráfico de rosca, tarxeta con Transformar e votación de valoración"],
"creative_pixel":["Pixel art: o teu primeiro videoxogo","Estilo videoxogo retro: sprites de píxeles, marcador, personaxes 3D que andan e saltan, código paso a paso, concurso e conta atrás"],
"creative_retro_atomic":["Retrofuturismo: o futuro de 1962","Era atómica: casa prato voador que se transforma, acertos e fallos en cadea, robot 3D que anda, radar, matriz, conta atrás e nube de palabras"],
"creative_retro_deco":["Art déco: o Gran Hotel cumpre 100 anos","Art déco en ouro e negro: abano que se transforma, Text Art dourado, ascensor como liña do tempo, sofá 3D, táboa con fórmulas e concurso"],
"creative_retro_desktop90":["Anos 90: copias de seguridade","Escritorio dos 90: xanelas grises, erros en fervenza, barra de progreso, ecuación, táboa con fórmulas, código por pasos e concurso"],
"creative_retro_diner":["Anos 50: a cafetaría reabre","Cafetaría dos 50: rótulo de neon, chan axadrezado, toldo, camión 3D pola estrada, carta con fórmulas, anel, selo que xira e votación"],
"creative_retro_letterpress":["Cartel de imprenta: as festas do barrio","Cartel de tipos de madeira: tinta desprazada, letras que caen con son, programa, barras apiladas, fervenza, bando, votación e conta atrás"],
"creative_retro_sepia":["Álbum sepia: busca os teus avós","Álbum sepia: cantoneiras, letra a man, ecuación de antepasados, árbore que medra, mapa con viaxe debuxada, torta, relacionar e Transformar"],
"creative_retro_teletext":["Teletexto: a liga veciñal","Páxinas de teletexto: liñas que se cargan soas, marcador e clasificación con fórmulas, barras, columnas, concurso e conta atrás"],
"creative_retro_typewriter":["Máquina de escribir: obradoiro de relato","Folio e máquina de escribir: liñas tecleadas con son, riscado e corrección a man, arco que se debuxa, barras, ocos e conta atrás"],
"creative_retro_vapor":["Vaporwave: a música das tendas","Vaporwave pastel: lúa que se transforma, palmeiras en SVG, títulos glitch, dispersión, lámpada 3D, táboa con media e valoración"],
"creative_retro_vinyl":["Anos 70: o club do vinilo","Estilo setenteiro: arco da vella de franxas, discos debuxados que xiran, cifra xigante, liñas, barras, sofá 3D, actividade de ordenar e adhesivo"],
"creative_space":["Galaxia: mirar o pasado","Estilo espacial: estrelas, nebulosas brillantes, modelos 3D da NASA, sonda que percorre os planetas, texto curvo e concurso"],
"creative_swiss_blood":["Campaña: doa sangue","Cartel público en branco e vermello: pinga que enche a pantalla con Transformar, proceso, si ou agarda, anel, barras, móbil e concurso"],
"creative_swiss_chairs":["Exposición: a cadeira moderna","Cartel suízo gris e lima: cadeira 3D que xira e viaxa con Transformar, cronoloxía, anel, butaca 3D, táboa con fórmulas e ordenar"],
"creative_swiss_designconf":["Congreso de deseño: Grella 27","Grafito e cian: a grella móntase soa e transfórmase, cifra de contorno, fórmula, cronoloxía, código CSS, nube e descanso"],
"creative_swiss_film":["Festival de cine: o programa","Suízo en negro e vermello: número xigante que se volve banda con Transformar, seccións en grella, táboa, barras, votación e conta atrás"],
"creative_swiss_foundation":["Memoria anual dunha fundación","Suízo en branco e azul cobalto: ano xigante, carta a toda tinta, cifras encadeadas, ecuación, anel, área, galóns e contas con fórmulas"],
"creative_swiss_games":["Xogos escolares: a identidade","Branco e maxenta, paleta propia: pictogramas en SVG, figura 3D que percorre a cidade, liñas, medalleiro con fórmulas, pasos e concurso"],
"creative_swiss_museum":["Guía do museo de historia natural","Sinalética suíza en negro e amarelo: plano propio con percorrido animado, raposo 3D que anda, columnas, táboa, etiquetar e pictogramas"],
"creative_swiss_orchestra":["Orquestra sinfónica: tempada 26/27","Azul noite e ámbar: arcos que xiran, texto curvo, cifras sobre un pentagrama, ciclos, táboa, ecuación, barras, votación e aplausos"],
"creative_swiss_publisher":["Catálogo de outono dunha editorial","Papel crema e verde petróleo: andel de lombos verticais, portadas en SVG, tableta, torta, pedido con fórmulas, calendario e ocos"],
"creative_swiss_typeface":["Mostrario dunha tipografía nova","Mostrario en branco e violeta: letras que viaxan con Transformar, anatomía medida, escala con fórmula, glifos, radar e licenzas"],
"creative_synthwave":["Synthwave: festival Neón 86","Estilo retro anos 80: sol con degradado, grella que se debuxa, neón brillante, Transformar, robot 3D que baila e nube de palabras"],
"creative_watercolor":["Acuarela: horta no balcón","Estilo acuarela e papel: manchas con degradado radial, formas a man alzada, letra manuscrita, debuxo que se traza só e 3D"],
"creative_zen":["Minimalismo xaponés: o té","Minimalismo xaponés: moito branco, sol vermello que se transforma, texto vertical, ensō que se pinta só e conta atrás"],
"data_ab_test":["Experimento A/B","Ecuacións, dispersión de dúas series, columnas con etiquetas, táboa de conversión con fórmulas e cifras de significación"],
"data_city_air":["Calidade do aire en Brisamar","Ceo que se despexa con Transformar, índice con agulla, ecuación, liñas con ocos, radar, táboa con fórmulas e valoración"],
"data_city_bikes":["Pedalia: un ano de bici compartida","Plano tipo metro, bici que percorre unha liña, cifras con son, liñas, apiladas, app no móbil, táboa e código"],
"data_city_budget":["Orzamentos participativos","Cartel cívico: urna con papeletas que caen, anel, galóns, combinado, resultados con redobre, táboa con fórmulas"],
"data_city_housing":["Vivenda: o prezo de quedar","Plano de arquitecto: planta en SVG, superficies a escala, combinado, ecuación, táboa con fórmulas, dispersión e sofá 3D"],
"data_city_noise":["O ruído de Sotoverde","Onda que se ergue soa, regra de decibelios con sons, ecuación, mapa de ruído, barras apiladas, concurso e conta atrás"],
"data_city_tourism":["Turismo en Isla Marena","Cartel de viaxe: sol con texto curvo, pictograma, áreas, rectángulos, barras ao 100 %, paseante 3D, táboa e postal"],
"data_city_traffic":["Tráfico na hora punta","Sala de control nocturna: mapa con atascos trazados, semáforo que se acende, táboa de calor, fórmula de Webster, código e camión 3D"],
"data_city_trees":["Inventario do arborado urbano","Prego de herbario: árbore debuxada, planta 3D con Transformar, rectángulos, histograma, ecuación, táboa e emparellar"],
"data_city_waste":["O que tiramos en Villa Cardo","Colectores que saltan con son, cifra xigante, fervenza, apiladas, torta por cores, funil, emparellar e táboa"],
"data_city_water":["A auga de Fuentelinda","Encoro que se baleira con Transformar, liñas, anel, barras, tarifa con ecuación e fórmulas, ducha con conta atrás"],
"data_energy":["Enerxía e consumo","Áreas apiladas por hora, liñas de tres series, rectángulos, columnas con etiquetas e táboa de tarifas calculada"],
"data_exec_panel":["Panel executivo mensual","KPI con semáforos e minigráficos, combinado fronte ao orzamento, múltiplos pequenos, anel e votación"],
"data_home_finance":["Finanzas persoais","Fervenza do soldo ao aforro, gráfico circular, liñas e área, táboas con SUMA, MEDIA, MÁX e MÍN"],
"data_market_study":["Estudo de mercado","Cifras grandes, gráfico de rectángulos, burbullas, dispersión, barras horizontais de dúas series e matriz 2 × 2"],
"data_population":["Poboación e demografía","Pirámide de poboación, histograma, barras horizontais, liñas que se cruzan e táboa de indicadores con fórmulas"],
"data_sales_regions":["Vendas por rexión","Barras agrupadas, apiladas e ao 100 %, gráfico combinado con obxectivo, táboa con totais por fórmula e KPI animados"],
"data_satisfaction":["Enquisa de satisfacción","Anel con lenda, radares comparados, columnas con etiquetas, NPS, valoración e nube de palabras en directo"],
"data_season_stats":["A tempada en cifras","Cifras xigantes con son, clasificación con fórmulas, barras negativas, liñas, apiladas e radar do equipo"],
"data_web_metrics":["Métricas web e márketing","KPI con minigráficos, liñas de catro series, áreas, funil de conversión, combinado e táboa con fórmulas"],
"edu_bio_digestion":["A viaxe dun bocadillo","Plano de metro: a liña D debúxase, un bocadillo percórrea, panel de saídas en táboa, encimas, barras, ordenar paradas e Text Art"],
"edu_bio_dna":["O ADN, a receita da vida","Laboratorio de neon: hélice que se monta soa, Text Art, bases que se emparellan, código Python paso a paso, barras, mutación e unir parellas"],
"edu_bio_ecosystem":["O bosque: quen come a quen","Caderno de campo en papel kraft: raposo 3D que anda, cadea trófica, rede que se debuxa, pirámide e táboa do 10 %, liñas e etiquetar"],
"edu_bio_evolution":["Adaptación: o peteiro dos pimpíns","Carta náutica nocturna: barco que navega unha ruta, peteiros debuxados, barras da seca, dispersión, ciclo, Transformar do peteiro e concurso"],
"edu_bio_heart":["O corazón, unha bomba incansable","Vermello e azul: latexo debuxado, cifras xigantes, circuítos trazados, pinga polo corazón, pulso con conta atrás e fórmulas, 3D e concurso"],
"edu_bio_mendel":["Mendel e os chícharos","Caderno de horta: chícharos que aparecen, xeracións con Transformar, cadro de Punnett, barras e anel, liña do tempo e concurso"],
"edu_bio_microbes":["Microbios: o mundo invisible","Ocular de microscopio: texto curvo, Transformar de 40 a 400 aumentos, formas de bacterias, fermento en liñas, votación e Text Art"],
"edu_bio_photosynthesis":["Fotosíntese: a fábrica verde","Folla ao sol: planta 3D, entradas e saídas animadas, Transformar ao cloroplasto, ecuación, táboa con medias, conta atrás, liñas e ocos"],
"edu_bio_pollination":["Da flor ao froito","Prado de primavera: abella que voa, partes da flor, etiquetar, treemap, Transformar de flor a froito, aguacate 3D, cronoloxía e nube"],
"edu_bio_respiration":["Respirar: a viaxe do aire","Ceo aberto: pulmóns que respiran, camiño do aire, Transformar ao inspirar e expirar, dous aneis, botella 3D, conta atrás e concurso"],
"edu_body":["O corpo humano","Estilo laboratorio: figura 3D con Transformar, personaxe que camiña por un percorrido, gráfico de barras, etiquetar o corpo e cuestionario"],
"edu_cell":["A célula","Célula debuxada con formas, partes unha a unha, Transformar para achegarse, unir parellas, diagrama, planta 3D e valoración"],
"edu_english":["Inglés para principiantes","Modo aula: tarxetas que xiran con son, robot 3D que anda e saúda, raposo 3D, tres preguntas con puntos, clasificación e aplausos"],
"edu_fractions":["Fraccións","Estilo neón: pizzas debuxadas, ecuacións paso a paso, suma con Transformar, completar ocos, cuestionario e reto con conta atrás"],
"edu_geo_cities":["A cidade: como medra","Cidade nocturna desde arriba: Text Art neón, gráfico de área, planos debuxados, aneis con Transformar, diagrama radial e coche 3D"],
"edu_geo_climograph":["Ler un climograma","Estación meteorolóxica: termómetro que sobe, barras con liña, táboa con fórmulas, ecuacións, satélite 3D, unir e reto con conta atrás"],
"edu_geo_coasts":["Costas e mareas","Faro con feixe que xira, formas da costa unha a unha, cantil que se erosiona, mareas en gráfico e táboa con fórmulas, etiquetar"],
"edu_geo_continents":["Continentes e océanos","Atlas infantil: continentes que aparecen con son, mapa de árbore, rosca de océanos, robot 3D que cruza o mundo, unir e etiquetar"],
"edu_geo_deserts":["Os desertos","Dunas ao solpor: caravana que avanza, Text Art dourado, gráficos de barras e de liñas, raposo 3D, oasis debuxado, mitos riscados e concurso"],
"edu_geo_mountains":["As montañas","Cartel alpino: partes do relevo unha a unha, ecuación e táboa de temperatura, pisos en pirámide, excursionista 3D que sobe e ordenar"],
"edu_geo_pyramids":["Pirámides de poboación","Cartel de censo: pirámide que se constrúe barra a barra, tres formas con Transformar, gráfico de liñas, ecuacións, ordenar e concurso"],
"edu_geo_river":["A viaxe dun río","Acuarela: río que se debuxa cunha pinga que o percorre, zoom con Transformar, caudal con ecuación, táboa con fórmulas e etiquetar"],
"edu_geo_timezones":["Fusos horarios","Panel de aeroporto con filas que xiran, Terra que rota con ecuación, Sol que cruza os fusos, táboa con fórmulas, reloxo 3D e ocos"],
"edu_geo_topomap":["Ler un mapa topográfico","Mapa de orientación: percorrido que se debuxa, escala con ecuación, táboa con fórmulas, curvas de nivel con Transformar e corredora 3D"],
"edu_hist_alandalus":["Al-Andalus: ciencia e xardíns","Arco de ferradura, cronoloxía un a un, barras horizontais, astrolabio que xira, estrela con Transformar, unir parellas e votación"],
"edu_hist_castle":["Castelos e feudalismo","Castelo nocturno e cabaleiro 3D que cruza a ponte, pirámide feudal que se ergue, etiquetar, sol que percorre o día, treemap e escudos"],
"edu_hist_egypt":["Exipto, o agasallo do Nilo","Lapislázuli e ouro: sol que sae tras as pirámides, crecida animada, gráfico de áreas, ecuación, Transformar, cartucho xeroglífico e ordenar"],
"edu_hist_greece":["Atenas: nace a democracia","Estilo vaso de figuras negras: meandro, texto curvo, Transformar, anel, templo que se ergue, óstraka con son, votación e táboa"],
"edu_hist_maya":["Os maias: tempo e estrelas","Selva e xade: números de puntos e raias, Transformar a base 20, ecuación, rodas de calendario que xiran, serpe de luz e cacao"],
"edu_hist_mesopotamia":["Mesopotamia: nace a escrita","Táboa de arxila que se escribe soa, mapa con ríos que se debuxan, zigurat que medra, base 60 con fórmulas, completar ocos e radial"],
"edu_hist_printing":["A imprenta: o libro multiplícase","Páxina incunable: letra capital vermella, tipos do revés compostos con Transformar, prensa que baixa con son, cifras, barras e ocos"],
"edu_hist_rome":["Roma, enxeñeiros do imperio","Mármore e vermello imperial: Transformar, arco triunfal, calzada por capas con soldado 3D que marcha, acueduto, ecuación, fórmulas e concurso"],
"edu_hist_silkroad":["A Ruta da Seda","Seda e azafrán: caravana en marcha, mapa con ruta que se traza, fervenza do prezo, táboa con fórmulas, farol 3D, ecuación e ordenar"],
"edu_hist_vikings":["Viquingos, navegantes do norte","Fiorde baixo a aurora: barco que se abanea, runas, mitos riscados con selo, travesía animada, cifras con son, guerreiro 3D, radar e unir"],
"edu_kids_colors":["As cores","Mesa de pintar: arco da vella que se debuxa só, botes con son, mesturas con Transformar, iconas, emparellar, votación e conta atrás"],
"edu_kids_emotions":["Como me sinto?","Unha cara debuxada que cambia de emoción con Transformar, grilanda de caras, globo para respirar, votación e emparellar"],
"edu_kids_farm":["Os animais da granxa","Granxa debuxada con animais propios, liñas que se trazan, táboa con suma, camión 3D en marcha, raposo 3D que camiña, concurso e etiquetar"],
"edu_kids_numbers":["O tren dos números","Tren debuxado que entra con son, contar un a un, números agochados, suma en ecuación, gráfico, ordenar, concurso e conta atrás"],
"edu_kids_sea":["Baixo o mar","Fondo mariño en degradado, peixes debuxados que nadan, burbullas, grande e pequeno, botella 3D ao colector, emparellar e nube de palabras"],
"edu_kids_seasons":["As catro estacións","Unha árbore que cambia con Transformar nas catro estacións, follas e neve que caen, roda do ano, ciclo, emparellar e votación"],
"edu_kids_senses":["Os cinco sentidos","Cartolina recortada: cara debuxada, diagrama radial, adiviñas, botóns con cinco sons, tarxetas que xiran, etiquetar e conta atrás"],
"edu_kids_shapes":["Formas e bloques","Alfombra de xogos: bloques con son, formas que se debuxan soas, casa que se volve robot con Transformar, robot 3D e pirámide"],
"edu_kids_space":["Viaxe á Lúa","Ceo nocturno: foguete que despega con son, conta atrás, Lúa que xira arredor da Terra, fases, astronauta e módulo lunar 3D"],
"edu_kids_transport":["Como viaxamos?","Alfombra de estradas: coche de xoguete 3D, vehículos que cruzan con son, semáforo que cambia, gráfico, coche 3D, emparellar e votación"],
"edu_lang2_advent":["Alemán: Advento e Nadal","Noite nevada: Text Art dourado, farol 3D, folerpas que caen, calendario de Advento que se abre, cronoloxía, etiquetar e receita con fórmulas"],
"edu_lang2_artikel":["Alemán: der, die, das","Cartel Bauhaus: formas que entran con son, terminacións en táboa, rosca, Transformar ao acusativo, unir parellas e concurso"],
"edu_lang2_cafe":["Francés: au café","Lousa de bistró baixo o toldo: texto curvo, conta con fórmulas na táboa, ecuación de prezos, diálogo, barras e ocos"],
"edu_lang2_directions":["Inglés: como chegar a…","Plano de metro inventado: un tren percorre a ruta con Traxectoria, frases ao paso, diálogo, rúa debuxada, ordenar, concurso e conta atrás"],
"edu_lang2_falsefriends":["Falsos amigos en inglés","Expediente de detective: selo con son, lentes 3D, sospeitosos que xiran, táboa de probas, barras, riscados e votación"],
"edu_lang2_ola":["Portugués: Olá, Lisboa!","Azulexos e tranvía amarelo que sobe o outeiro con Traxectoria, saúdos que xiran, táboa de sons, chat nun móbil e mapa de árbore"],
"edu_lang2_passato":["Italiano: il passato prossimo","Postal da Riviera: coche 3D que percorre a costa con Traxectoria, ecuación, participios en táboa, concordancia, ocos e concurso"],
"edu_lang2_phrasal":["Phrasal verbs: level up","Arcade de neón: Text Art, Transformar que une verbo e partícula, cabaleiro 3D que avanza, barras, riscado, unir e conta atrás"],
"edu_lang2_sons":["Francés: os sons","Vinilo que xira con texto curvo, pistas con son, ligazóns debuxadas en arco, táboa de regras, radar, concurso e conta atrás"],
"edu_lang2_tenses":["Present perfect ou past simple","Reloxaría: reloxo 3D con Transformar, liña do tempo con arco que se debuxa, ecuacións, táboa, barras ao 100 %, árbore e conta atrás"],
"edu_lang_accent":["O til sen medo","Caderno cuadriculado e bolígrafo vermello: sílabas que soan ao iluminarse, táboa, árbore de decisión, riscos animados, pósits e concurso"],
"edu_lang_becquer":["Bécquer e as Rimas","Noite romántica: andoriñas que cruzan a lúa, texto curvo, versos que aparecen sós, farol 3D, cronoloxía, métrica en táboa e ocos"],
"edu_lang_calderon":["A vida é soño","Pano que se abre e se pecha con son, plano do curral, trono 3D con Transformar, monólogo verso a verso, radial, balanza e concurso"],
"edu_lang_commentary":["Como comentar un texto","Páxina con fluorescentes que se trazan sós e notas na marxe, galóns un a un, cronoloxía, ecuación, conta atrás, rúbrica e radar"],
"edu_lang_fables":["Fábulas: a raposa e as uvas","Libro de contos: raposo 3D que entra andando, título curvo, cronoloxía, parra debuxada, chanzos, táboa, ordenar e nube de palabras"],
"edu_lang_figures":["Figuras retóricas en cómic","Cómic pop: viñetas, globos e explosións con son, reloxo 3D que voa por unha traxectoria, versos que se colorean e concurso"],
"edu_lang_genres":["Os xéneros literarios","Biblioteca de noite: libros que soben ao andel, fichas seladas con son, Venn, xerarquía, rosca, votación, unir e butaca 3D"],
"edu_lang_lazarillo":["O Lazarillo de Tormes","Pergamiño e lacre: pícaro 3D que percorre o mapa de amo en amo, tarxetas, táboa de amos, liña da fame, concurso e ordenar"],
"edu_lang_meter":["A música do verso: métrica","Estudo de son: onda que se debuxa, sílabas que soan coma un metrónomo, ecuación con casos, sinalefa, soneto por pistas e concurso"],
"edu_lang_syntax":["Suxeito e predicado, en plano","Plano técnico: pezas que se ordenan con Transformar, corchetes que se trazan, árbore sintáctica, táboa, etiquetar imaxe e concurso"],
"edu_math_coordinates":["Coordenadas: o mapa do tesouro","Mapa do tesouro: rosa dos ventos con texto curvo, puntos que aparecen, pirata 3D que segue pistas, barco que se debuxa e etiquetar"],
"edu_math_integers":["Números enteiros: mar e montaña","Do fondo do mar ao cumio: recta con saltos, Text Art xeo, temperaturas baixo cero, submarino que sobe e baixa, ordenar e concurso"],
"edu_math_primes":["Números primos","Terminal verde: neon propio, crible de Eratóstenes clic a clic con 100 casas, árbore de factores, código paso a paso, concurso e reto"],
"edu_math_probability":["Probabilidade: medir a sorte","Mesa de xogo burdeos e ouro: dados que rodan con redobre, texto curvo, regra de Laplace, árbore un a un, barras, liñas e concurso"],
"edu_math_proportion":["Proporcionalidade no súper","Tícket de compra: selo que rebota, táboa de proporcionalidade con fórmulas, regra de tres paso a paso, rebaixas calculadas, liñas e ocos"],
"edu_math_pythagoras":["O teorema de Pitágoras","Encerado de giz: figura que se debuxa soa, demostración sen palabras con Transformar, ternas con fórmulas, atallo en 3D e concurso"],
"edu_math_sequences":["Sucesións e patróns","Libro de botánica: espiral de Fibonacci que se traza soa, pedras en cadea, palillos con fórmulas, código, planta 3D e número de ouro"],
"edu_math_stats":["Estatística: media, mediana e moda","Caderno cuadriculado: notas adhesivas en fervenza, frecuencias con fórmulas, barras, rosca con graos, histograma e votación en directo"],
"edu_math_symmetry":["Simetría e mosaicos","Azulexos nazarís: estrela que xira, bolboreta que se reflicte, translación, xiro e simetría animados, táboa de ángulos e panal"],
"edu_math_volumes":["Áreas e volumes","Plano técnico azul: caixetín en táboa, desenvolvemento plano, botella 3D medida, volumes con fórmulas, barras, conos que enchen e emparellar"],
"edu_pe_active":["60 minutos ao día","Taboleiro de cortiza: notas con chinchetas, personaxe 3D que salta, semana con fórmulas, barras apiladas, anel, código e muro de ideas"],
"edu_pe_athletics":["Atletismo: correr, saltar, lanzar","Pista de tartán: personaxe 3D, pictogramas que xiran, ecuación e táboa de rúas, saída con sons, histograma, ordenar e podio"],
"edu_pe_basketball":["Baloncesto: tiro e bandexa","Encerado de adestrador: balón que bota con son, pista acoutada, parábola trazada, xogada debuxada, táboa con fórmulas e etiquetar"],
"edu_pe_calm":["Volta á calma: estirar e respirar","Amencer en calma: planta 3D, respiración en caixa con traxectoria, círculo que medra e encolle, estiramentos, diana e nube de palabras"],
"edu_pe_heart":["O corazón en marcha","Monitor cardíaco: electro que se traza só, conta atrás do pulso, ecuación, zonas con fórmulas, área, móbil con app e concurso"],
"edu_pe_hydration":["Bebe antes de ter sede","Auga e burbullas: botella 3D, corpo que se enche, barras da suor, vaso con Transformar, escala de cor e encher ocos"],
"edu_pe_nutrition":["O prato do deportista","Mantel de cadros: prato que se serve por partes, anel, aguacate 3D, almorzos con fórmulas, mitos que xiran, unir e nube de palabras"],
"edu_pe_posture":["Unhas costas para toda a vida","Lámina en sepia: columna vértebra a vértebra, rótulos en cadea, mochila con fórmulas, así non e así si, cadeira 3D, conta atrás e etiquetar"],
"edu_pe_sleep":["Durmir tamén é adestrar","Ventá de noite: estrelas que se acenden, lámpada 3D, hipnograma, ciclo, radial, móbil con mensaxes, rutina en cadea e valoración"],
"edu_pe_warmup":["Quentar antes de xogar","Parqué de polideportivo: robot 3D que corre, liña de temperatura, galóns, articulacións con son, conta atrás, ordenar e concurso"],
"edu_quixote":["O Quixote","Estilo tinta e papel: muíño que xira con son, texto curvo, citas animadas, Transformar, cronoloxía, completar ocos e cuestionario"],
"edu_renewables":["Enerxías renovables","Aeroxerador que xira, tarxetas, gráficos de área, rosca e barras agrupadas, nube de palabras en directo, votación e conta atrás"],
"edu_revolution":["A Revolución Francesa","Estilo papel antigo: texto en círculo, Transformar, pirámide social, cronoloxía animada con son, ordenar feitos e votación"],
"edu_spain":["Xeografía de España","Estilo atlas: rosa dos ventos, relevo en diana, táboa de ríos con fórmulas, gráficos de picos e choivas, unir parellas e cuestionario"],
"edu_volcanoes":["Os volcáns","Estilo lume: erupción animada con son, partes do volcán para etiquetar, táboa, cuestionario con tempo e conta atrás"],
"edu_water":["O ciclo da auga","Diagrama de ciclo un a un, paisaxe con pingas que soben e choiva animada con son, gráficos de rosca, unir parellas e satélite 3D"],
"life_bookclub":["Clube de lectura","Andel a man alzada, portada con formas, citas que se transforman, diagrama radial, valoración e votación do próximo libro"],
"life_cv":["Currículo visual","Texto en círculo, cifras, cronoloxía paso a paso, barras de habilidades animadas, radar, pantallas en dispositivos e contacto"],
"life_fitness":["Plan de adestramento: 5 km","Corredor 3D, Text Art lume, fases con degradados, semana con fórmulas, gráficos de progreso, pirámide, conta atrás e nube de palabras"],
"life_garden":["Horta urbana","Planta 3D con Transformar, calendario de sementeira en táboa de cores, ciclo, Venn, gráficos de rega e crecemento, actividade de etiquetar"],
"life_graduation":["Graduación e fin de curso","Text Art ouro, birretes con formas, polaroids que xiran ao entrar, cifras con redobre, agradecementos, nube de palabras e aplausos"],
"life_italy":["Viaxe por Italia","Texto en círculo, ruta con conectores e percorrido animado, cronoloxía, orzamento con fórmulas, gráficos e actividade de emparellar"],
"life_kids_party":["Aniversario infantil","Cores vivas: robot 3D que baila, personaxes que celebran, globos a man alzada, concurso con puntos e conta atrás"],
"life_moving":["Mudanza e novo fogar","Casa con formas a man alzada, cronoloxía, lista que se risca, mobles 3D que pasan ao plano con Transformar, orzamento e actividade de ordenar"],
"life_recipe":["Receita: guacamole","Aguacate 3D que viaxa entre diapositivas (Transformar), ingredientes con fórmulas, pasos un a un, conta atrás e valoración"],
"life_travel_eu_amsterdam":["Ámsterdam: canles e bicis","Fachadas de canle que se montan en cadea, canles en diana, bici que cruza con son, táboa con fórmulas, liñas e votación en torta"],
"life_travel_eu_camino":["Camiño de Santiago: desde Sarria","Credencial que se enche de selos con son, fervenza de quilómetros, camiñante 3D, ecuación da mochila, rosca e ordenar etapas"],
"life_travel_eu_croatia":["Croacia a vela por Dalmacia","Carta náutica, rosa dos ventos que xira e viaxa con Transformar, bandeiras, emparellar, millas con fórmulas, concurso e conta atrás"],
"life_travel_eu_danube":["O Danubio en bici","Estilo ciclocomputador: ruta no móbil, ficheiro GPX paso a paso, barras apiladas, botella 3D con Transformar, fórmulas e rectángulos"],
"life_travel_eu_fjords":["Fiordes noruegueses por auga","Paisaxe por capas con reflexos, barco que navega, corte do fiorde que se debuxa, barras, radar, etapas unha a unha e votación múltiple"],
"life_travel_eu_greece":["Illas gregas en ferri","Aldea branca de formas, greca, ruta que se debuxa, horarios con fórmulas, burbullas, lentes 3D con Transformar e solpor"],
"life_travel_eu_iceland":["Islandia: a Ring Road en coche","Auroras con degradados, mapa con percorrido sonoro, coche 3D, cifras con redobre, ecuación do frío, raposo que camiña e concurso"],
"life_travel_eu_lisbon":["Lisboa: outeiros e tranvías","Azulexos en SVG, tranvía que sobe os outeiros por un percorrido con son, perfil de altura, cartas que xiran, táboa con fórmulas e ocos"],
"life_travel_eu_prague":["Praga, a cidade das cen torres","Reloxo astronómico de formas que xira e viaxa con Transformar, desfile con campaíña, conta atrás, mapa para etiquetar e táboa"],
"life_travel_eu_scotland":["Escocia: Highlands en coche","Tartán tecido con formas, estrada que se debuxa, coches que ceden o paso, castelos que xiran, farol 3D, barras e preguntas"],
"life_wedding":["Invitación de voda","Tipografía clásica e ouro: Text Art, texto curvo, cronoloxía da parella, mapa con percorrido animado, votación e conta atrás"],
"prod_app_bank":["Cartilla: banca para maiores","Libreta de aforro de pel e ouro: Text Art ouro, Transformar para achegar o móbil, táboa con SUMA, fervenza, selo e concurso contra a fraude"],
"prod_app_gym":["Serie: reservas no teu ximnasio","Marcador LED: loitador 3D que celebra e anda ata a súa clase, dúas contas atrás, ocupación por horas, tarifas con fórmulas e concurso"],
"prod_app_health":["Turno: citas no centro de saúde","Clínico: latexo que se debuxa, antes e despois, ciclo un a un, paciente 3D que anda, axenda en monitor, barras e preguntas"],
"prod_app_language":["Vocablo: app para aprender idiomas","Postal de correo aéreo: selos, bocadillos que saltan con son, tarxetas que xiran, Transformar, ecuación do esquecemento, gráfico e emparellar"],
"prod_app_market":["Plaza: o mercado do barrio na casa","Toldo e lousas de xiz: furgoneta 3D que percorre o plano, postos en radial, móbil, rectángulos, comisións con fórmulas e votación"],
"prod_app_meditation":["Marea: app de meditación e sono","Mar nocturno: lúa con texto curvo, Transformar do móbil, respiración guiada con aros encadeados, conta atrás, gráfico e farol 3D"],
"prod_app_music":["Garaje: música en directo do barrio","Vinilo e neon: disco que viaxa con Transformar, texto curvo que xira, ecualizador con redobre, portátil, radar, torta e nube de palabras"],
"prod_app_photo":["Grano: fotografía de carrete","Cuarto escuro: tira de película, foto que se revela con Transformar, contador con redobre, histograma, tableta, táboa e etiquetar"],
"prod_app_recipes":["Sobras: receitas co que hai","Neveira con pósits: aguacate 3D con Transformar, móbil que recoñece ingredientes, pasos, rosca, receita con fórmulas e conta atrás"],
"prod_app_transit":["Andén: transporte urbano","Sinalética de metro: panel de saídas con conta atrás, plano que se debuxa só, viaxe animada, móbil, barras apiladas e tarifas"],
"prod_hw_drone":["Cernícalo: dron de rescate en montaña","Mapa topográfico: voo que se debuxa co dron percorréndoo, helicóptero 3D da NASA, vista térmica, conta atrás, fórmulas e concurso"],
"prod_hw_ereader":["Folio: lector de tinta electrónica","Libro con paso de páxina: capitular, lector debuxado, microcápsulas que aparecen, cifra e barras, cita, táboa con fórmulas e ocos"],
"prod_hw_glasses":["Horizonte: lentes con datos para ciclistas","A estrada a través da lente: lentes 3D con Transformar, partes numeradas con son, barras, código YAML por pasos, radial e votación"],
"prod_hw_headphones":["Silencio: auriculares con cancelación de ruído","Cámara anecoica: ondas que se debuxan e se anulan, ecuación, proceso paso a paso, curva por frecuencias, táboa con fórmulas e votación"],
"prod_hw_keyboard":["Tecla: teclado mecánico modular","Teclas que saltan con son de clic, curvas de forza, despezamento por capas, mapa de teclas en código, orzamento con fórmulas e ordenar"],
"prod_hw_lamp":["Alba: lámpada espertador","Amencer en degradado: o sol sobe con Transformar, lámpada 3D que viaxa, cronoloxía, curva de luz con ecuación, escala Kelvin e valoración"],
"prod_hw_thermostat":["Templa: termóstato intelixente","Esfera de termóstato e casa en sección con temperaturas que aparecen, fervenza de aforro, ecuacións, liñas de 24 horas, matriz e votación"],
"prod_hw_toycar":["Chispa: coche para aprender a programar","Alfombra de xogo: coche 3D con Transformar, cartas que saltan con son, taboleiro que se percorre, código, concurso, escaleira e rosca"],
"prod_hw_tracker":["Miga: localizador para non perder nada","Mapa do tesouro: migallas que aparecen unha a unha ata o X, círculo a man que se debuxa, rosca, diana, rastro polo barrio e nube de palabras"],
"prod_hw_trailcam":["Vigía: cámara de fototrampeo","Visor infravermello: raposo 3D que cruza e dispara a cámara, alcance do sensor debuxado, cifras, áreas por horas, táboa con SUMA e emparellar"],
"product_app":["Presentación de app móbil","App en móbil, tableta e portátil, Transformar, percorrido en galóns, cifras, gráfico de retención e nube de palabras"],
"product_car":["Presentación: coche eléctrico","Coche 3D sen corte nos bordos que dá a volta ao entrar, Transformar, cifras, gráficos de área e barras, táboa e votación"],
"product_eco":["Sustentabilidade do produto","Verde eco: planta 3D con Transformar, ciclo de vida, fervenza de pegada, barras de materiais, liñas con obxectivo e encher ocos"],
"product_furniture":["Colección de mobles","Estilo editorial: sofás e cadeiras 3D, Transformar con vistas distintas, balanceo e volta, mostras de cor, tableta e orzamento"],
"product_keynote":["Keynote de hardware","Estilo branco premium: lámpada iridescente e botella 3D, Transformar con etiquetas, flotar e achegar, cifras, táboa e prezos"],
"product_roadmap":["Folla de ruta de produto","Camiño que se debuxa só, pirámide, cronoloxía un a un, agora e despois, matriz, barras apiladas, votación múltiple e de ordenar"],
"product_robot":["Robot asistente industrial","Estilo industrial: robot 3D que saúda, anda por un percorrido, encadea animacións e baila; organigrama, ciclo, gráfico e concurso"],
"product_saas":["Demo de plataforma SaaS","Panel en xanela de navegador con chamadas numeradas, radial, funil, indicadores, barras apiladas, código por pasos e preguntas"],
"product_security":["Seguridade do produto","Neón verde: diana de capas, fluxo con conectores que aparece paso a paso, código resaltado, gráfico, escaleira e actividade de emparellar"],
"product_watch":["Lanzamento: reloxo intelixente","Negro e ouro: reloxo 3D que viaxa por tres diapositivas con Transformar e chegadas distintas, Text Art ouro, radar e prezos"],
"sci_ai":["Intelixencia artificial","Neon violeta: robot 3D que saúda e viaxa con Transformar, cronoloxía, organigrama, rede neuronal que se acende, gráfico e nube de palabras"],
"sci_astro_blackholes":["Buracos negros","Negro absoluto: horizonte que viaxa con Transformar, texto curvo, cifra xigante, táboa con fórmulas, astronauta 3D en espiral e concurso"],
"sci_astro_cosmology":["Do Big Bang a hoxe","Un universo que arrefría: termómetro con Transformar, cronoloxía en cadea, fondo cósmico, dispersión, rosca e calendario con fórmulas"],
"sci_astro_defense":["Defensa planetaria: simulacro","Sala de crise: franxas de perigo, asteroide 3D, escala de Turín en cadea, desvío animado con son, conta atrás e votación de equipos"],
"sci_astro_exoplanets":["Búscanse outros mundos","Carteis de viaxe retro: tránsito coa curva de luz debuxada, código Python, bamboleo con traxectorias, área, satélite 3D e votación"],
"sci_astro_moon":["Selenografía: a Lúa","Atlas antigo en sepia: Lúa gravada en SVG, fases en cadea, xiro síncrono, mareas, módulo lunar 3D con Transformar e emparellar"],
"sci_astro_pulsars":["Púlsares: os faros do cosmos","Pantalla de osciloscopio: sinal que se traza soa, faro que xira, pulsos que soan, radiotelescopio e nebulosa 3D, táboa e concurso"],
"sci_astro_skywatch":["Guía para observar o ceo","Modo luz vermella: planisferio con texto curvo, conta atrás, constelacións que se trazan soas, magnitudes, barras, táboa e votación"],
"sci_astro_stars":["Vida e morte das estrelas","Espectro estelar: clases en cadea, equilibrio con frechas, diagrama H-R propio, bifurcación por masa, táboa con fórmulas e supernova 3D"],
"sci_astro_sun":["O Sol, unha estrela de preto","Filtro solar carmesí: capas en cadea, fusión con ecuación, a viaxe dun fotón, ciclo de manchas, sonda 3D con Transformar e concurso"],
"sci_astro_telescopes":["Telescopios: o plano","Estilo plano técnico: raios que se debuxan, Webb 3D con Transformar polo espectro, espello hexagonal en cadea, viaxe a L2 e etiquetar"],
"sci_brain":["Neurociencia: o cerebro","Estilo escuro con brillos: neurona debuxada con impulso animado, figura 3D que camiña, radial, organigrama, barras e etiquetar unha imaxe"],
"sci_chem":["Química: a táboa periódica","Laboratorio limpo: táboa periódica que se monta en fervenza, moléculas con formas, braseiro 3D, ecuacións, rosca e emparellar"],
"sci_climate":["O cambio climático en datos","Franxas de quecemento, gráficos de liñas, área e rectángulos, efecto invernadoiro que se debuxa, satélite 3D, ciclo e votación múltiple"],
"sci_mars":["Misión a Marte","Estilo espacial ferruxe: rover 3D da NASA con Transformar, astronauta flotando, órbita animada, ecuación e concurso"],
"sci_med_case":["Caso clínico: febre e tose","Estilo historia clínica: cartafol, selo, radiografía no negatoscopio con círculo que se debuxa, CURB-65 con fórmula, votación e preguntas"],
"sci_med_ecg":["Cardioloxía: ler un ECG","Papel de ECG: trazados que se debuxan sós, impulso que percorre o corazón, táboa con fórmulas, ecuación, concurso e conta atrás"],
"sci_med_glucose":["Endocrinoloxía: glicosa e insulina","Estilo app de sensor de glicosa: móbil coa pantalla, ciclo un a un, curvas, rosca, táboa con fórmulas, ecuación, aguacate 3D e votación"],
"sci_med_immune":["Inmunoloxía: a resposta inmune","Microscopio de fluorescencia: células que se acenden, anticorpo debuxado, fagocitose con Transformar, organigrama e emparellar"],
"sci_med_kidney":["Fisioloxía renal: a nefrona","Plano técnico: nefrona que se debuxa, pinga que a percorre con son, cotas, fervenza, ecuación, táboa con fórmulas, botella 3D e ciclo"],
"sci_med_knee":["Anatomía: o xeonllo","Estilo lámina anatómica antiga: texto curvo, gravado en sepia, Transformar cara aos meniscos, matriz, táboa, figura 3D que camiña e etiquetar"],
"sci_med_micro":["Microbioloxía: resistencia antibiótica","Placas de Petri: colonias que agromen con son, crecemento exponencial, selección contada con Transformar, antibiograma, radial e nube de palabras"],
"sci_med_pk":["Farmacocinética: a vida media","Estilo caixa de medicamento: blíster que se enche, LADME un a un, curvas de dúas series, ecuacións, táboa con fórmulas, código e ocos"],
"sci_med_stroke":["Neuroloxía: código ictus","Contrarreloxo de urxencias: luces de sirena, cifra xigante con redobre, BE-FAST encadeado, rosca, galóns, ordenar pasos e conta atrás"],
"sci_med_trial":["Ensaio clínico: ler os resultados","Estilo revista científica: CONSORT con conectores, curvas de supervivencia, táboa con fórmulas, NNT, forest plot encadeado e concurso"],
"sci_newton":["Física: as leis de Newton","Caderno de física: ecuacións, coche 3D en movemento, tiro parabólico que se debuxa, táboa con fórmulas e encher ocos"],
"sci_nurse_cpr":["RCP básica: soporte vital","Sinalética verde de emerxencia: mans que comprimen ao ritmo, parches do DEA que voan con son, dúas series, conta atrás e ordenar"],
"sci_nurse_drip":["Fluidoterapia: calcular o goteo","Equipo de soro debuxado con pingas que caen con son, fórmula paso a paso, exemplo resolto, táboa que calcula, bomba e conta atrás"],
"sci_nurse_falls":["Caídas en maiores: a casa segura","Casa de noite con lámpada 3D: plano con perigos que se arranxan con Transformar, proba de marcha con figura 3D, Venn, rosca e conta atrás"],
"sci_nurse_hands":["Hixiene de mans: os 5 momentos","Azulexos e burbullas: pompas que soben, os 5 momentos nun plano, lámpada UV con son, conta atrás de 30 s, barras e concurso"],
"sci_nurse_heat":["Vaga de calor: plan de saúde","Cores de alerta: termómetro que sobe, Text Art, mapa de avisos debuxado, dispersión, móbil co SMS, botella 3D, táboa e concurso"],
"sci_nurse_herd":["Vacinas: a inmunidade de grupo","Cartilla de vacinas con selos e texto curvo, contaxio en cadea cortado con Transformar, ecuación, táboa con fórmulas, mitos riscados"],
"sci_nurse_outbreak":["Investigar un gromo alimentario","Taboleiro de cortiza: notas con chinchetas e fío vermello que se debuxa, curva epidémica, táboa con fórmulas, risco relativo, código e votación"],
"sci_nurse_pressure":["Úlceras por presión: previr","Mapa de presión térmico: manchas que se acenden e se apagan, Braden con fórmulas, reloxo de cambios que xira, capas de pel e etiquetar"],
"sci_nurse_sbar":["O relevo de quenda con SBAR","Encerado branco de planta: rotulador que subliña só, imáns e notas que se pegan con son, diálogo en cadea, escala con fórmula e unir"],
"sci_nurse_smoking":["Deixar de fumar: o que gaña o teu corpo","Do fume ao aire limpo: fume que sobe, cigarro que é liña do tempo, pulmóns que cambian con Transformar, táboa de aforro e respiración"],
"sci_python":["Programación en Python","Estilo editor escuro: terminal que se escribe soa, código con pasos de resaltado, saída animada, ordenar liñas e reto con conta atrás"],
"sci_solar":["O sistema solar","Planetas a escala que aparecen en cadea, tres sondas 3D con vistas e movementos distintos, táboa, diagrama radial e emparellar"],
"sci_stats":["Estatística e probabilidade","Estilo editorial: campá que se debuxa, fórmulas, histograma, dispersión, área, barras e burbullas, e pregunta con puntos"],
"sci_thesis":["Defensa do TFG","Académico sobrio: portada institucional, índice, metodoloxía con ecuación, táboa con totais, resultados en gráficos, bibliografía e preguntas"],
"show_anim_bike":["As marchas da bici, sen misterio","Movementos sincronizados: engrenaxes que xiran á súa relación real, rodas que rodan a súa distancia, dous carrís á vez e táboa"],
"show_anim_blueprint":["Reforma dun piso: o plano","Plano que se debuxa só: muros en cadea, cotas, derriba que desaparece, Transformar a nova distribución, instalacións e obra"],
"show_anim_ferries":["Ferris entre illas: rutas de verán","Traxectorias sobre un mapa: barcos que xiran co camiño, rutas que se debuxan ao seu paso, tres liñas á vez, escala e horarios"],
"show_anim_firefly":["Conto: a vagalume sen luz","Un conto con entradas e saídas: narración visible só no seu paso, diálogos que aparecen e se van, voos e luz que volve"],
"show_anim_foosball":["Torneo de futbolín da oficina","Animacións encadeadas con sons coma un xogo: pases con clic, tiro, gol con aplausos, cadro que avanza, táboa e porra"],
"show_anim_guitar":["Anatomía da guitarra española","Desencadeadores: clic en cada parte da guitarra para ver a súa ficha e en cada corda para facela vibrar; roseta que xira"],
"show_anim_haiku":["Obradoiro de haiku: palabra a palabra","Animación por palabras e parágrafos: versos palabra a palabra, consigna frase a frase, sílabas contadas e Transformar"],
"show_anim_rpg":["Rol de mesa: a túa primeira partida","Personaxes 3D coas súas animacións: atacar, bloquear, lanzar feitizos e caer; camiñar ata o rival, dado que roda e vida que baixa"],
"show_anim_speech":["Discurso: salvemos a biblioteca","Énfase ao ritmo dun discurso: frase en foco e o resto atenuado, riscar, resaltar, subliñado e círculo a man, conta atrás"],
"show_anim_tshirt":["Infografía: a viaxe dunha camiseta","Infografía que se revela: ruta que se debuxa coas súas paradas a tempo, pictograma de pingas que se enche, fervenza, cifras e fórmula"],
"showcase_3d":["Catálogo: o 3D a fondo","Modelos 3D con todas as opcións: vistas, movementos ao entrar, xiro, bordos, marxe, clips, andar e chegada con Transformar"],
"showcase_animations":["Catálogo: animacións","Todas as animacións de obxecto: entrada, énfase, saída, traxectorias, debuxar, encadeadas, sons e varias nun obxecto"],
"showcase_charts":["Catálogo: gráficos","Os 15 tipos de gráfico, dous por diapositiva, con series, combinado, grade, etiquetas e títulos de eixos, e a táboa de opcións"],
"showcase_diagrams":["Catálogo: diagramas","Os 15 deseños de diagrama escritos como esquema, os 4 esquemas de cor e a aparición un a un ao presentar"],
"showcase_morph":["Catálogo: Transformar","Transformar paso a paso: texto que cambia de tamaño e sitio, formas, barras que medran, imaxe, 3D e letras que se reordenan"],
"showcase_objects":["Catálogo: multimedia e obxectos","Código con pasos, ecuacións, iconas, cinco dispositivos, táboas con estilos e fórmulas, zoom de diapositiva e conectores"],
"showcase_polls":["Catálogo: votacións e actividades","Os 11 tipos de votación e actividade desde o móbil, conta atrás nos seus tres estilos, clasificación e modo aula"],
"showcase_shapes":["Catálogo: formas","Todas as formas por categorías co seu nome, liñas e guións, degradados, opacidade, trazo a man, sombras, texto dentro e xiro"],
"showcase_text":["Catálogo: Text Art e tipografía","Os 10 estilos de Text Art, texto curvo, columnas, cinco niveis de viñetas, os 8 pares de letra, aliñamento e espazamento"],
"showcase_transitions":["Catálogo: transicións","As 22 transicións de diapositiva, unha a unha: entrada, saída distinta, direccións, velocidade e avance automático"]};
