// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Resultados trimestrais ao consello","Azul escuro e dourado: indicadores grandes animados con son, fervenza, funil, barras apiladas e táboa con fórmulas fronte ao orzamento"],
"biz_climate":["Enquisa de clima laboral","Violeta e participativo: conta atrás, barras ao 100 %, valoración de 1 a 5, nube de palabras, elección múltiple e preguntas do público"],
"biz_investment":["Presentación para investidores","Negro e ouro: produto 3D que xira e viaxa con Transformar, cifras xigantes, mercado en círculos, tracción, uso dos fondos e equipo"],
"biz_marketing":["Plan de márketing de campaña","Estilo cálido: texto en círculo, público obxectivo, funil, combinación de canles, calendario en táboa, orzamento con fórmula e votación"],
"biz_onboarding":["Benvida ás novas persoas empregadas","Estilo amable: robot 3D que saúda e percorre a semana camiñando, organigrama un a un, valores con iconas e actividade de emparellar"],
"biz_proposal":["Proposta comercial a un cliente","Estilo papel: selo, proceso un a un, maquetas en portátil e móbil, prezos, orzamento con IVE en fórmulas, cronoloxía e garantías"],
"biz_roadmap":["Folla de ruta dun proxecto","Estilo técnico escuro: galóns un a un, diagrama de Gantt animado, cronoloxía, coche 3D que avanza con Transformar e táboa de estado"],
"biz_sales":["Vendas e previsión anual","Minimalista en gris: barras e liñas combinadas, escenarios, fórmula de previsión, táboa con fórmulas, barras apiladas e horizontais"],
"biz_startup_agrotech":["Pitch agrotech: rega con sensores","Vista aérea de parcelas con mapa de humidade, satélite 3D da NASA, móbil, pingas en cadea con son, táboa con fórmulas e treemap"],
"biz_startup_edtech":["Pitch edtech: titor de matemáticas","Caderno cuadriculado: pósits en cadea, letra manuscrita, ecuacións paso a paso, móbil, cuestionario en directo, ciclo e gráficos"],
"biz_startup_energy":["Pitch enerxía: comunidade solar","Tellados da alba á noite: sol que sae e cruza o ceo en arco, diagrama radial, áreas por horas, ecuación e táboa con fórmulas"],
"biz_startup_fashion":["Pitch moda circular: Retal","Etiqueta de roupa que viaxa con Transformar, costuras punteadas, vida dunha peza en cadea, ciclo, anel, radar e votación múltiple"],
"biz_startup_insurance":["Pitch seguros: cobertura por días","Choiva gris e paraugas amarelo: pictograma en cadea, app con interruptor, ecuación do prezo, táboa con fórmulas, cronoloxía e votación"],
"biz_startup_kitchen":["Pitch robótica de cociña: Fogón","Cociña profesional: comandas no rail, Text Art de lume, robot 3D que entra camiñando e saúda, receita en código, conta atrás e funil"],
"biz_startup_lastmile":["Pitch loxística: última milla","Estilo plano de metro: liñas que se debuxan soas, camión 3D e bicis que percorren o mapa, táboa con fórmulas, área e fervenza"],
"biz_startup_mental":["Pitch saúde mental: Remanso","Noite en calma: aneis que respiran, minuto de respiración con conta atrás, app no móbil, escaleira, valoración e táboa con fórmulas"],
"biz_startup_pets":["Pitch mascotas: comida fresca","Estilo adhesivo con pegadas que aparecen en cadea, raposo 3D que cruza camiñando, fórmula da ración nunha táboa, anel e concurso"],
"biz_startup_rural":["Pitch turismo rural: Alpende","Montañas ao solpor e postais: farol 3D, mataselos con texto curvo, mapa con coche 3D pola ruta, barras, torta e nube de palabras"],
"biz_strategy":["Plan estratéxico e OKR","Estilo limpo en branco: cifras que entran en cadea, pirámide, prioridades con iconas, táboa de OKR, barras de avance, radar e galóns"],
"biz_swot":["Análise DAFO e competencia","Fondo grafito: DAFO por cuadrantes, matriz de estratexias, mapa de posicionamento, barras agrupadas, Venn, torta e votación múltiple"],
"creative_bauhaus":["Bauhaus: forma e función","Arte xeométrica Bauhaus: formas primarias que xiran e rebotan, cronoloxía, retícula con Transformar e actividade de emparellar"],
"creative_brutalism":["Brutalismo: manifesto web","Estilo brutalista: tipografía xigante, bloques negros, texto vertical, sombras duras, riscado animado, táboa e votación"],
"creative_comic":["Banda deseñada: superpoderes animais","Estilo banda deseñada: viñetas, globos de diálogo e pensamento, onomatopeas en Text Art que rebotan, raposo 3D, gráfico e concurso"],
"creative_fashion":["Revista de moda: outono lento","Estilo revista: cabeceira con serifa, reloxo 3D na portada, columnas con capitular, cita grande, paleta de tempada e gráfico"],
"creative_glass":["Glassmorphism: app de finanzas","Tarxetas translúcidas sobre brillos de cor, móbil coa app, gráfico de rosca, tarxeta con Transformar e votación de valoración"],
"creative_pixel":["Pixel art: o teu primeiro videoxogo","Estilo videoxogo retro: sprites de píxeles, marcador, personaxes 3D que andan e saltan, código paso a paso, concurso e conta atrás"],
"creative_space":["Galaxia: mirar o pasado","Estilo espacial: estrelas, nebulosas brillantes, modelos 3D da NASA, sonda que percorre os planetas, texto curvo e concurso"],
"creative_swiss_blood":["Campaña: doa sangue","Cartel público en branco e vermello: pinga que enche a pantalla con Transformar, proceso, si ou agarda, anel, barras, móbil e concurso"],
"creative_swiss_chairs":["Exposición: a cadeira moderna","Cartel suízo gris e lima: cadeira 3D que xira e viaxa con Transformar, cronoloxía, anel, butaca 3D, táboa con fórmulas e ordenar"],
"creative_swiss_designconf":["Congreso de deseño: Grella 27","Grafito e cian: a grella móntase soa e transfórmase, cifra de contorno, fórmula, cronoloxía, código CSS, nube e descanso"],
"creative_swiss_film":["Festival de cine: o programa","Suízo en negro e vermello: número xigante que se volve banda con Transformar, seccións en grella, táboa, barras, votación e conta atrás"],
"creative_swiss_foundation":["Memoria anual dunha fundación","Suízo en branco e azul cobalto: ano xigante, carta a toda tinta, cifras encadeadas, ecuación, anel, área, galóns e contas con fórmulas"],
"creative_swiss_games":["Xogos escolares: a identidade","Branco e maxenta, paleta propia: pictogramas en SVG, figura 3D que percorre a cidade, liñas, medalleiro con fórmulas, pasos e concurso"],
"creative_swiss_museum":["Guía do museo de historia natural","Sinalética suíza en negro e amarelo: plano propio con percorrido animado, raposo 3D que anda, columnas, táboa, etiquetar e pictogramas"],
"creative_swiss_orchestra":["Orquestra sinfónica: tempada 26/27","Azul noite e ámbar: arcos que xiran, texto curvo, cifras sobre un pentagrama, ciclos, táboa, ecuación, barras, votación e aplausos"],
"creative_swiss_publisher":["Catálogo de outono dunha editorial","Papel crema e verde petróleo: andel de lombos verticais, portadas en SVG, tableta, torta, pedido con fórmulas, calendario e ocos"],
"creative_swiss_typeface":["Mostrario dunha tipografía nova","Mostrario en branco e violeta: letras que viaxan con Transformar, anatomía medida, escala con fórmula, glifos, radar e licenzas"],
"creative_synthwave":["Synthwave: festival Neón 86","Estilo retro anos 80: sol con degradado, grella que se debuxa, neón brillante, Transformar, robot 3D que baila e nube de palabras"],
"creative_watercolor":["Acuarela: horta no balcón","Estilo acuarela e papel: manchas con degradado radial, formas a man alzada, letra manuscrita, debuxo que se traza só e 3D"],
"creative_zen":["Minimalismo xaponés: o té","Minimalismo xaponés: moito branco, sol vermello que se transforma, texto vertical, ensō que se pinta só e conta atrás"],
"data_ab_test":["Experimento A/B","Ecuacións, dispersión de dúas series, columnas con etiquetas, táboa de conversión con fórmulas e cifras de significación"],
"data_energy":["Enerxía e consumo","Áreas apiladas por hora, liñas de tres series, rectángulos, columnas con etiquetas e táboa de tarifas calculada"],
"data_exec_panel":["Panel executivo mensual","KPI con semáforos e minigráficos, combinado fronte ao orzamento, múltiplos pequenos, anel e votación"],
"data_home_finance":["Finanzas persoais","Fervenza do soldo ao aforro, gráfico circular, liñas e área, táboas con SUMA, MEDIA, MÁX e MÍN"],
"data_market_study":["Estudo de mercado","Cifras grandes, gráfico de rectángulos, burbullas, dispersión, barras horizontais de dúas series e matriz 2 × 2"],
"data_population":["Poboación e demografía","Pirámide de poboación, histograma, barras horizontais, liñas que se cruzan e táboa de indicadores con fórmulas"],
"data_sales_regions":["Vendas por rexión","Barras agrupadas, apiladas e ao 100 %, gráfico combinado con obxectivo, táboa con totais por fórmula e KPI animados"],
"data_satisfaction":["Enquisa de satisfacción","Anel con lenda, radares comparados, columnas con etiquetas, NPS, valoración e nube de palabras en directo"],
"data_season_stats":["A tempada en cifras","Cifras xigantes con son, clasificación con fórmulas, barras negativas, liñas, apiladas e radar do equipo"],
"data_web_metrics":["Métricas web e márketing","KPI con minigráficos, liñas de catro series, áreas, funil de conversión, combinado e táboa con fórmulas"],
"edu_body":["O corpo humano","Estilo laboratorio: figura 3D con Transformar, personaxe que camiña por un percorrido, gráfico de barras, etiquetar o corpo e cuestionario"],
"edu_cell":["A célula","Célula debuxada con formas, partes unha a unha, Transformar para achegarse, unir parellas, diagrama, planta 3D e valoración"],
"edu_english":["Inglés para principiantes","Modo aula: tarxetas que xiran con son, robot 3D que anda e saúda, raposo 3D, tres preguntas con puntos, clasificación e aplausos"],
"edu_fractions":["Fraccións","Estilo neón: pizzas debuxadas, ecuacións paso a paso, suma con Transformar, completar ocos, cuestionario e reto con conta atrás"],
"edu_hist_alandalus":["Al-Andalus: ciencia e xardíns","Arco de ferradura, cronoloxía un a un, barras horizontais, astrolabio que xira, estrela con Transformar, unir parellas e votación"],
"edu_hist_castle":["Castelos e feudalismo","Castelo nocturno e cabaleiro 3D que cruza a ponte, pirámide feudal que se ergue, etiquetar, sol que percorre o día, treemap e escudos"],
"edu_hist_egypt":["Exipto, o agasallo do Nilo","Lapislázuli e ouro: sol que sae tras as pirámides, crecida animada, gráfico de áreas, ecuación, Transformar, cartucho xeroglífico e ordenar"],
"edu_hist_greece":["Atenas: nace a democracia","Estilo vaso de figuras negras: meandro, texto curvo, Transformar, anel, templo que se ergue, óstraka con son, votación e táboa"],
"edu_hist_maya":["Os maias: tempo e estrelas","Selva e xade: números de puntos e raias, Transformar a base 20, ecuación, rodas de calendario que xiran, serpe de luz e cacao"],
"edu_hist_mesopotamia":["Mesopotamia: nace a escrita","Táboa de arxila que se escribe soa, mapa con ríos que se debuxan, zigurat que medra, base 60 con fórmulas, completar ocos e radial"],
"edu_hist_printing":["A imprenta: o libro multiplícase","Páxina incunable: letra capital vermella, tipos do revés compostos con Transformar, prensa que baixa con son, cifras, barras e ocos"],
"edu_hist_rome":["Roma, enxeñeiros do imperio","Mármore e vermello imperial: Transformar, arco triunfal, calzada por capas con soldado 3D que marcha, acueduto, ecuación, fórmulas e concurso"],
"edu_hist_silkroad":["A Ruta da Seda","Seda e azafrán: caravana en marcha, mapa con ruta que se traza, fervenza do prezo, táboa con fórmulas, farol 3D, ecuación e ordenar"],
"edu_hist_vikings":["Viquingos, navegantes do norte","Fiorde baixo a aurora: barco que se abanea, runas, mitos riscados con selo, travesía animada, cifras con son, guerreiro 3D, radar e unir"],
"edu_math_coordinates":["Coordenadas: o mapa do tesouro","Mapa do tesouro: rosa dos ventos con texto curvo, puntos que aparecen, pirata 3D que segue pistas, barco que se debuxa e etiquetar"],
"edu_math_integers":["Números enteiros: mar e montaña","Do fondo do mar ao cumio: recta con saltos, Text Art xeo, temperaturas baixo cero, submarino que sobe e baixa, ordenar e concurso"],
"edu_math_primes":["Números primos","Terminal verde: neon propio, crible de Eratóstenes clic a clic con 100 casas, árbore de factores, código paso a paso, concurso e reto"],
"edu_math_probability":["Probabilidade: medir a sorte","Mesa de xogo burdeos e ouro: dados que rodan con redobre, texto curvo, regra de Laplace, árbore un a un, barras, liñas e concurso"],
"edu_math_proportion":["Proporcionalidade no súper","Tícket de compra: selo que rebota, táboa de proporcionalidade con fórmulas, regra de tres paso a paso, rebaixas calculadas, liñas e ocos"],
"edu_math_pythagoras":["O teorema de Pitágoras","Encerado de giz: figura que se debuxa soa, demostración sen palabras con Transformar, ternas con fórmulas, atallo en 3D e concurso"],
"edu_math_sequences":["Sucesións e patróns","Libro de botánica: espiral de Fibonacci que se traza soa, pedras en cadea, palillos con fórmulas, código, planta 3D e número de ouro"],
"edu_math_stats":["Estatística: media, mediana e moda","Caderno cuadriculado: notas adhesivas en fervenza, frecuencias con fórmulas, barras, rosca con graos, histograma e votación en directo"],
"edu_math_symmetry":["Simetría e mosaicos","Azulexos nazarís: estrela que xira, bolboreta que se reflicte, translación, xiro e simetría animados, táboa de ángulos e panal"],
"edu_math_volumes":["Áreas e volumes","Plano técnico azul: caixetín en táboa, desenvolvemento plano, botella 3D medida, volumes con fórmulas, barras, conos que enchen e emparellar"],
"edu_quixote":["O Quixote","Estilo tinta e papel: muíño que xira con son, texto curvo, citas animadas, Transformar, cronoloxía, completar ocos e cuestionario"],
"edu_renewables":["Enerxías renovables","Aeroxerador que xira, tarxetas, gráficos de área, rosca e barras agrupadas, nube de palabras en directo, votación e conta atrás"],
"edu_revolution":["A Revolución Francesa","Estilo papel antigo: texto en círculo, Transformar, pirámide social, cronoloxía animada con son, ordenar feitos e votación"],
"edu_spain":["Xeografía de España","Estilo atlas: rosa dos ventos, relevo en diana, táboa de ríos con fórmulas, gráficos de picos e choivas, unir parellas e cuestionario"],
"edu_volcanoes":["Os volcáns","Estilo lume: erupción animada con son, partes do volcán para etiquetar, táboa, cuestionario con tempo e conta atrás"],
"edu_water":["O ciclo da auga","Diagrama de ciclo un a un, paisaxe con pingas que soben e choiva animada con son, gráficos de rosca, unir parellas e satélite 3D"],
"life_bookclub":["Clube de lectura","Andel a man alzada, portada con formas, citas que se transforman, diagrama radial, valoración e votación do próximo libro"],
"life_cv":["Currículo visual","Texto en círculo, cifras, cronoloxía paso a paso, barras de habilidades animadas, radar, pantallas en dispositivos e contacto"],
"life_fitness":["Plan de adestramento: 5 km","Corredor 3D, Text Art lume, fases con degradados, semana con fórmulas, gráficos de progreso, pirámide, conta atrás e nube de palabras"],
"life_garden":["Horta urbana","Planta 3D con Transformar, calendario de sementeira en táboa de cores, ciclo, Venn, gráficos de rega e crecemento, actividade de etiquetar"],
"life_graduation":["Graduación e fin de curso","Text Art ouro, birretes con formas, polaroids que xiran ao entrar, cifras con redobre, agradecementos, nube de palabras e aplausos"],
"life_italy":["Viaxe por Italia","Texto en círculo, ruta con conectores e percorrido animado, cronoloxía, orzamento con fórmulas, gráficos e actividade de emparellar"],
"life_kids_party":["Aniversario infantil","Cores vivas: robot 3D que baila, personaxes que celebran, globos a man alzada, concurso con puntos e conta atrás"],
"life_moving":["Mudanza e novo fogar","Casa con formas a man alzada, cronoloxía, lista que se risca, mobles 3D que pasan ao plano con Transformar, orzamento e actividade de ordenar"],
"life_recipe":["Receita: guacamole","Aguacate 3D que viaxa entre diapositivas (Transformar), ingredientes con fórmulas, pasos un a un, conta atrás e valoración"],
"life_travel_eu_amsterdam":["Ámsterdam: canles e bicis","Fachadas de canle que se montan en cadea, canles en diana, bici que cruza con son, táboa con fórmulas, liñas e votación en torta"],
"life_travel_eu_camino":["Camiño de Santiago: desde Sarria","Credencial que se enche de selos con son, fervenza de quilómetros, camiñante 3D, ecuación da mochila, rosca e ordenar etapas"],
"life_travel_eu_croatia":["Croacia a vela por Dalmacia","Carta náutica, rosa dos ventos que xira e viaxa con Transformar, bandeiras, emparellar, millas con fórmulas, concurso e conta atrás"],
"life_travel_eu_danube":["O Danubio en bici","Estilo ciclocomputador: ruta no móbil, ficheiro GPX paso a paso, barras apiladas, botella 3D con Transformar, fórmulas e rectángulos"],
"life_travel_eu_fjords":["Fiordes noruegueses por auga","Paisaxe por capas con reflexos, barco que navega, corte do fiorde que se debuxa, barras, radar, etapas unha a unha e votación múltiple"],
"life_travel_eu_greece":["Illas gregas en ferri","Aldea branca de formas, greca, ruta que se debuxa, horarios con fórmulas, burbullas, lentes 3D con Transformar e solpor"],
"life_travel_eu_iceland":["Islandia: a Ring Road en coche","Auroras con degradados, mapa con percorrido sonoro, coche 3D, cifras con redobre, ecuación do frío, raposo que camiña e concurso"],
"life_travel_eu_lisbon":["Lisboa: outeiros e tranvías","Azulexos en SVG, tranvía que sobe os outeiros por un percorrido con son, perfil de altura, cartas que xiran, táboa con fórmulas e ocos"],
"life_travel_eu_prague":["Praga, a cidade das cen torres","Reloxo astronómico de formas que xira e viaxa con Transformar, desfile con campaíña, conta atrás, mapa para etiquetar e táboa"],
"life_travel_eu_scotland":["Escocia: Highlands en coche","Tartán tecido con formas, estrada que se debuxa, coches que ceden o paso, castelos que xiran, farol 3D, barras e preguntas"],
"life_wedding":["Invitación de voda","Tipografía clásica e ouro: Text Art, texto curvo, cronoloxía da parella, mapa con percorrido animado, votación e conta atrás"],
"prod_app_bank":["Cartilla: banca para maiores","Libreta de aforro de pel e ouro: Text Art ouro, Transformar para achegar o móbil, táboa con SUMA, fervenza, selo e concurso contra a fraude"],
"prod_app_gym":["Serie: reservas no teu ximnasio","Marcador LED: loitador 3D que celebra e anda ata a súa clase, dúas contas atrás, ocupación por horas, tarifas con fórmulas e concurso"],
"prod_app_health":["Turno: citas no centro de saúde","Clínico: latexo que se debuxa, antes e despois, ciclo un a un, paciente 3D que anda, axenda en monitor, barras e preguntas"],
"prod_app_language":["Vocablo: app para aprender idiomas","Postal de correo aéreo: selos, bocadillos que saltan con son, tarxetas que xiran, Transformar, ecuación do esquecemento, gráfico e emparellar"],
"prod_app_market":["Plaza: o mercado do barrio na casa","Toldo e lousas de xiz: furgoneta 3D que percorre o plano, postos en radial, móbil, rectángulos, comisións con fórmulas e votación"],
"prod_app_meditation":["Marea: app de meditación e sono","Mar nocturno: lúa con texto curvo, Transformar do móbil, respiración guiada con aros encadeados, conta atrás, gráfico e farol 3D"],
"prod_app_music":["Garaje: música en directo do barrio","Vinilo e neon: disco que viaxa con Transformar, texto curvo que xira, ecualizador con redobre, portátil, radar, torta e nube de palabras"],
"prod_app_photo":["Grano: fotografía de carrete","Cuarto escuro: tira de película, foto que se revela con Transformar, contador con redobre, histograma, tableta, táboa e etiquetar"],
"prod_app_recipes":["Sobras: receitas co que hai","Neveira con pósits: aguacate 3D con Transformar, móbil que recoñece ingredientes, pasos, rosca, receita con fórmulas e conta atrás"],
"prod_app_transit":["Andén: transporte urbano","Sinalética de metro: panel de saídas con conta atrás, plano que se debuxa só, viaxe animada, móbil, barras apiladas e tarifas"],
"product_app":["Presentación de app móbil","App en móbil, tableta e portátil, Transformar, percorrido en galóns, cifras, gráfico de retención e nube de palabras"],
"product_car":["Presentación: coche eléctrico","Coche 3D sen corte nos bordos que dá a volta ao entrar, Transformar, cifras, gráficos de área e barras, táboa e votación"],
"product_eco":["Sustentabilidade do produto","Verde eco: planta 3D con Transformar, ciclo de vida, fervenza de pegada, barras de materiais, liñas con obxectivo e encher ocos"],
"product_furniture":["Colección de mobles","Estilo editorial: sofás e cadeiras 3D, Transformar con vistas distintas, balanceo e volta, mostras de cor, tableta e orzamento"],
"product_keynote":["Keynote de hardware","Estilo branco premium: lámpada iridescente e botella 3D, Transformar con etiquetas, flotar e achegar, cifras, táboa e prezos"],
"product_roadmap":["Folla de ruta de produto","Camiño que se debuxa só, pirámide, cronoloxía un a un, agora e despois, matriz, barras apiladas, votación múltiple e de ordenar"],
"product_robot":["Robot asistente industrial","Estilo industrial: robot 3D que saúda, anda por un percorrido, encadea animacións e baila; organigrama, ciclo, gráfico e concurso"],
"product_saas":["Demo de plataforma SaaS","Panel en xanela de navegador con chamadas numeradas, radial, funil, indicadores, barras apiladas, código por pasos e preguntas"],
"product_security":["Seguridade do produto","Neón verde: diana de capas, fluxo con conectores que aparece paso a paso, código resaltado, gráfico, escaleira e actividade de emparellar"],
"product_watch":["Lanzamento: reloxo intelixente","Negro e ouro: reloxo 3D que viaxa por tres diapositivas con Transformar e chegadas distintas, Text Art ouro, radar e prezos"],
"sci_ai":["Intelixencia artificial","Neon violeta: robot 3D que saúda e viaxa con Transformar, cronoloxía, organigrama, rede neuronal que se acende, gráfico e nube de palabras"],
"sci_brain":["Neurociencia: o cerebro","Estilo escuro con brillos: neurona debuxada con impulso animado, figura 3D que camiña, radial, organigrama, barras e etiquetar unha imaxe"],
"sci_chem":["Química: a táboa periódica","Laboratorio limpo: táboa periódica que se monta en fervenza, moléculas con formas, braseiro 3D, ecuacións, rosca e emparellar"],
"sci_climate":["O cambio climático en datos","Franxas de quecemento, gráficos de liñas, área e rectángulos, efecto invernadoiro que se debuxa, satélite 3D, ciclo e votación múltiple"],
"sci_mars":["Misión a Marte","Estilo espacial ferruxe: rover 3D da NASA con Transformar, astronauta flotando, órbita animada, ecuación e concurso"],
"sci_med_case":["Caso clínico: febre e tose","Estilo historia clínica: cartafol, selo, radiografía no negatoscopio con círculo que se debuxa, CURB-65 con fórmula, votación e preguntas"],
"sci_med_ecg":["Cardioloxía: ler un ECG","Papel de ECG: trazados que se debuxan sós, impulso que percorre o corazón, táboa con fórmulas, ecuación, concurso e conta atrás"],
"sci_med_glucose":["Endocrinoloxía: glicosa e insulina","Estilo app de sensor de glicosa: móbil coa pantalla, ciclo un a un, curvas, rosca, táboa con fórmulas, ecuación, aguacate 3D e votación"],
"sci_med_immune":["Inmunoloxía: a resposta inmune","Microscopio de fluorescencia: células que se acenden, anticorpo debuxado, fagocitose con Transformar, organigrama e emparellar"],
"sci_med_kidney":["Fisioloxía renal: a nefrona","Plano técnico: nefrona que se debuxa, pinga que a percorre con son, cotas, fervenza, ecuación, táboa con fórmulas, botella 3D e ciclo"],
"sci_med_knee":["Anatomía: o xeonllo","Estilo lámina anatómica antiga: texto curvo, gravado en sepia, Transformar cara aos meniscos, matriz, táboa, figura 3D que camiña e etiquetar"],
"sci_med_micro":["Microbioloxía: resistencia antibiótica","Placas de Petri: colonias que agromen con son, crecemento exponencial, selección contada con Transformar, antibiograma, radial e nube de palabras"],
"sci_med_pk":["Farmacocinética: a vida media","Estilo caixa de medicamento: blíster que se enche, LADME un a un, curvas de dúas series, ecuacións, táboa con fórmulas, código e ocos"],
"sci_med_stroke":["Neuroloxía: código ictus","Contrarreloxo de urxencias: luces de sirena, cifra xigante con redobre, BE-FAST encadeado, rosca, galóns, ordenar pasos e conta atrás"],
"sci_med_trial":["Ensaio clínico: ler os resultados","Estilo revista científica: CONSORT con conectores, curvas de supervivencia, táboa con fórmulas, NNT, forest plot encadeado e concurso"],
"sci_newton":["Física: as leis de Newton","Caderno de física: ecuacións, coche 3D en movemento, tiro parabólico que se debuxa, táboa con fórmulas e encher ocos"],
"sci_python":["Programación en Python","Estilo editor escuro: terminal que se escribe soa, código con pasos de resaltado, saída animada, ordenar liñas e reto con conta atrás"],
"sci_solar":["O sistema solar","Planetas a escala que aparecen en cadea, tres sondas 3D con vistas e movementos distintos, táboa, diagrama radial e emparellar"],
"sci_stats":["Estatística e probabilidade","Estilo editorial: campá que se debuxa, fórmulas, histograma, dispersión, área, barras e burbullas, e pregunta con puntos"],
"sci_thesis":["Defensa do TFG","Académico sobrio: portada institucional, índice, metodoloxía con ecuación, táboa con totais, resultados en gráficos, bibliografía e preguntas"],
"showcase_3d":["Catálogo: o 3D a fondo","Modelos 3D con todas as opcións: vistas, movementos ao entrar, xiro, bordos, marxe, clips, andar e chegada con Transformar"],
"showcase_animations":["Catálogo: animacións","Todas as animacións de obxecto: entrada, énfase, saída, traxectorias, debuxar, encadeadas, sons e varias nun obxecto"],
"showcase_charts":["Catálogo: gráficos","Os 15 tipos de gráfico, dous por diapositiva, con series, combinado, grade, etiquetas e títulos de eixos, e a táboa de opcións"],
"showcase_diagrams":["Catálogo: diagramas","Os 15 deseños de diagrama escritos como esquema, os 4 esquemas de cor e a aparición un a un ao presentar"],
"showcase_morph":["Catálogo: Transformar","Transformar paso a paso: texto que cambia de tamaño e sitio, formas, barras que medran, imaxe, 3D e letras que se reordenan"],
"showcase_objects":["Catálogo: multimedia e obxectos","Código con pasos, ecuacións, iconas, cinco dispositivos, táboas con estilos e fórmulas, zoom de diapositiva e conectores"],
"showcase_polls":["Catálogo: votacións e actividades","Os 11 tipos de votación e actividade desde o móbil, conta atrás nos seus tres estilos, clasificación e modo aula"],
"showcase_shapes":["Catálogo: formas","Todas as formas por categorías co seu nome, liñas e guións, degradados, opacidade, trazo a man, sombras, texto dentro e xiro"],
"showcase_text":["Catálogo: Text Art e tipografía","Os 10 estilos de Text Art, texto curvo, columnas, cinco niveis de viñetas, os 8 pares de letra, aliñamento e espazamento"],
"showcase_transitions":["Catálogo: transicións","As 22 transicións de diapositiva, unha a unha: entrada, saída distinta, direccións, velocidade e avance automático"]};
