// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Resultados trimestrais ao consello","Azul escuro e dourado: indicadores grandes animados con son, fervenza, funil, barras apiladas e táboa con fórmulas fronte ao orzamento"],
"biz_climate":["Enquisa de clima laboral","Violeta e participativo: conta atrás, barras ao 100 %, valoración de 1 a 5, nube de palabras, elección múltiple e preguntas do público"],
"biz_investment":["Presentación para investidores","Negro e ouro: produto 3D que xira e viaxa con Transformar, cifras xigantes, mercado en círculos, tracción, uso dos fondos e equipo"],
"biz_marketing":["Plan de márketing de campaña","Estilo cálido: texto en círculo, público obxectivo, funil, combinación de canles, calendario en táboa, orzamento con fórmula e votación"],
"biz_onboarding":["Benvida ás novas persoas empregadas","Estilo amable: robot 3D que saúda e percorre a semana camiñando, organigrama un a un, valores con iconas e actividade de emparellar"],
"biz_proposal":["Proposta comercial a un cliente","Estilo papel: selo, proceso un a un, maquetas en portátil e móbil, prezos, orzamento con IVE en fórmulas, cronoloxía e garantías"],
"biz_roadmap":["Folla de ruta dun proxecto","Estilo técnico escuro: galóns un a un, diagrama de Gantt animado, cronoloxía, coche 3D que avanza con Transformar e táboa de estado"],
"biz_sales":["Vendas e previsión anual","Minimalista en gris: barras e liñas combinadas, escenarios, fórmula de previsión, táboa con fórmulas, barras apiladas e horizontais"],
"biz_strategy":["Plan estratéxico e OKR","Estilo limpo en branco: cifras que entran en cadea, pirámide, prioridades con iconas, táboa de OKR, barras de avance, radar e galóns"],
"biz_swot":["Análise DAFO e competencia","Fondo grafito: DAFO por cuadrantes, matriz de estratexias, mapa de posicionamento, barras agrupadas, Venn, torta e votación múltiple"],
"creative_bauhaus":["Bauhaus: forma e función","Arte xeométrica Bauhaus: formas primarias que xiran e rebotan, cronoloxía, retícula con Transformar e actividade de emparellar"],
"creative_brutalism":["Brutalismo: manifesto web","Estilo brutalista: tipografía xigante, bloques negros, texto vertical, sombras duras, riscado animado, táboa e votación"],
"creative_comic":["Banda deseñada: superpoderes animais","Estilo banda deseñada: viñetas, globos de diálogo e pensamento, onomatopeas en Text Art que rebotan, raposo 3D, gráfico e concurso"],
"creative_fashion":["Revista de moda: outono lento","Estilo revista: cabeceira con serifa, reloxo 3D na portada, columnas con capitular, cita grande, paleta de tempada e gráfico"],
"creative_glass":["Glassmorphism: app de finanzas","Tarxetas translúcidas sobre brillos de cor, móbil coa app, gráfico de rosca, tarxeta con Transformar e votación de valoración"],
"creative_pixel":["Pixel art: o teu primeiro videoxogo","Estilo videoxogo retro: sprites de píxeles, marcador, personaxes 3D que andan e saltan, código paso a paso, concurso e conta atrás"],
"creative_space":["Galaxia: mirar o pasado","Estilo espacial: estrelas, nebulosas brillantes, modelos 3D da NASA, sonda que percorre os planetas, texto curvo e concurso"],
"creative_synthwave":["Synthwave: festival Neón 86","Estilo retro anos 80: sol con degradado, grella que se debuxa, neón brillante, Transformar, robot 3D que baila e nube de palabras"],
"creative_watercolor":["Acuarela: horta no balcón","Estilo acuarela e papel: manchas con degradado radial, formas a man alzada, letra manuscrita, debuxo que se traza só e 3D"],
"creative_zen":["Minimalismo xaponés: o té","Minimalismo xaponés: moito branco, sol vermello que se transforma, texto vertical, ensō que se pinta só e conta atrás"],
"data_ab_test":["Experimento A/B","Ecuacións, dispersión de dúas series, columnas con etiquetas, táboa de conversión con fórmulas e cifras de significación"],
"data_energy":["Enerxía e consumo","Áreas apiladas por hora, liñas de tres series, rectángulos, columnas con etiquetas e táboa de tarifas calculada"],
"data_exec_panel":["Panel executivo mensual","KPI con semáforos e minigráficos, combinado fronte ao orzamento, múltiplos pequenos, anel e votación"],
"data_home_finance":["Finanzas persoais","Fervenza do soldo ao aforro, gráfico circular, liñas e área, táboas con SUMA, MEDIA, MÁX e MÍN"],
"data_market_study":["Estudo de mercado","Cifras grandes, gráfico de rectángulos, burbullas, dispersión, barras horizontais de dúas series e matriz 2 × 2"],
"data_population":["Poboación e demografía","Pirámide de poboación, histograma, barras horizontais, liñas que se cruzan e táboa de indicadores con fórmulas"],
"data_sales_regions":["Vendas por rexión","Barras agrupadas, apiladas e ao 100 %, gráfico combinado con obxectivo, táboa con totais por fórmula e KPI animados"],
"data_satisfaction":["Enquisa de satisfacción","Anel con lenda, radares comparados, columnas con etiquetas, NPS, valoración e nube de palabras en directo"],
"data_season_stats":["A tempada en cifras","Cifras xigantes con son, clasificación con fórmulas, barras negativas, liñas, apiladas e radar do equipo"],
"data_web_metrics":["Métricas web e márketing","KPI con minigráficos, liñas de catro series, áreas, funil de conversión, combinado e táboa con fórmulas"],
"edu_body":["O corpo humano","Estilo laboratorio: figura 3D con Transformar, personaxe que camiña por un percorrido, gráfico de barras, etiquetar o corpo e cuestionario"],
"edu_cell":["A célula","Célula debuxada con formas, partes unha a unha, Transformar para achegarse, unir parellas, diagrama, planta 3D e valoración"],
"edu_english":["Inglés para principiantes","Modo aula: tarxetas que xiran con son, robot 3D que anda e saúda, raposo 3D, tres preguntas con puntos, clasificación e aplausos"],
"edu_fractions":["Fraccións","Estilo neón: pizzas debuxadas, ecuacións paso a paso, suma con Transformar, completar ocos, cuestionario e reto con conta atrás"],
"edu_quixote":["O Quixote","Estilo tinta e papel: muíño que xira con son, texto curvo, citas animadas, Transformar, cronoloxía, completar ocos e cuestionario"],
"edu_renewables":["Enerxías renovables","Aeroxerador que xira, tarxetas, gráficos de área, rosca e barras agrupadas, nube de palabras en directo, votación e conta atrás"],
"edu_revolution":["A Revolución Francesa","Estilo papel antigo: texto en círculo, Transformar, pirámide social, cronoloxía animada con son, ordenar feitos e votación"],
"edu_spain":["Xeografía de España","Estilo atlas: rosa dos ventos, relevo en diana, táboa de ríos con fórmulas, gráficos de picos e choivas, unir parellas e cuestionario"],
"edu_volcanoes":["Os volcáns","Estilo lume: erupción animada con son, partes do volcán para etiquetar, táboa, cuestionario con tempo e conta atrás"],
"edu_water":["O ciclo da auga","Diagrama de ciclo un a un, paisaxe con pingas que soben e choiva animada con son, gráficos de rosca, unir parellas e satélite 3D"],
"life_bookclub":["Clube de lectura","Andel a man alzada, portada con formas, citas que se transforman, diagrama radial, valoración e votación do próximo libro"],
"life_cv":["Currículo visual","Texto en círculo, cifras, cronoloxía paso a paso, barras de habilidades animadas, radar, pantallas en dispositivos e contacto"],
"life_fitness":["Plan de adestramento: 5 km","Corredor 3D, Text Art lume, fases con degradados, semana con fórmulas, gráficos de progreso, pirámide, conta atrás e nube de palabras"],
"life_garden":["Horta urbana","Planta 3D con Transformar, calendario de sementeira en táboa de cores, ciclo, Venn, gráficos de rega e crecemento, actividade de etiquetar"],
"life_graduation":["Graduación e fin de curso","Text Art ouro, birretes con formas, polaroids que xiran ao entrar, cifras con redobre, agradecementos, nube de palabras e aplausos"],
"life_italy":["Viaxe por Italia","Texto en círculo, ruta con conectores e percorrido animado, cronoloxía, orzamento con fórmulas, gráficos e actividade de emparellar"],
"life_kids_party":["Aniversario infantil","Cores vivas: robot 3D que baila, personaxes que celebran, globos a man alzada, concurso con puntos e conta atrás"],
"life_moving":["Mudanza e novo fogar","Casa con formas a man alzada, cronoloxía, lista que se risca, mobles 3D que pasan ao plano con Transformar, orzamento e actividade de ordenar"],
"life_recipe":["Receita: guacamole","Aguacate 3D que viaxa entre diapositivas (Transformar), ingredientes con fórmulas, pasos un a un, conta atrás e valoración"],
"life_wedding":["Invitación de voda","Tipografía clásica e ouro: Text Art, texto curvo, cronoloxía da parella, mapa con percorrido animado, votación e conta atrás"],
"product_app":["Presentación de app móbil","App en móbil, tableta e portátil, Transformar, percorrido en galóns, cifras, gráfico de retención e nube de palabras"],
"product_car":["Presentación: coche eléctrico","Coche 3D sen corte nos bordos que dá a volta ao entrar, Transformar, cifras, gráficos de área e barras, táboa e votación"],
"product_eco":["Sustentabilidade do produto","Verde eco: planta 3D con Transformar, ciclo de vida, fervenza de pegada, barras de materiais, liñas con obxectivo e encher ocos"],
"product_furniture":["Colección de mobles","Estilo editorial: sofás e cadeiras 3D, Transformar con vistas distintas, balanceo e volta, mostras de cor, tableta e orzamento"],
"product_keynote":["Keynote de hardware","Estilo branco premium: lámpada iridescente e botella 3D, Transformar con etiquetas, flotar e achegar, cifras, táboa e prezos"],
"product_roadmap":["Folla de ruta de produto","Camiño que se debuxa só, pirámide, cronoloxía un a un, agora e despois, matriz, barras apiladas, votación múltiple e de ordenar"],
"product_robot":["Robot asistente industrial","Estilo industrial: robot 3D que saúda, anda por un percorrido, encadea animacións e baila; organigrama, ciclo, gráfico e concurso"],
"product_saas":["Demo de plataforma SaaS","Panel en xanela de navegador con chamadas numeradas, radial, funil, indicadores, barras apiladas, código por pasos e preguntas"],
"product_security":["Seguridade do produto","Neón verde: diana de capas, fluxo con conectores que aparece paso a paso, código resaltado, gráfico, escaleira e actividade de emparellar"],
"product_watch":["Lanzamento: reloxo intelixente","Negro e ouro: reloxo 3D que viaxa por tres diapositivas con Transformar e chegadas distintas, Text Art ouro, radar e prezos"],
"sci_ai":["Intelixencia artificial","Neon violeta: robot 3D que saúda e viaxa con Transformar, cronoloxía, organigrama, rede neuronal que se acende, gráfico e nube de palabras"],
"sci_brain":["Neurociencia: o cerebro","Estilo escuro con brillos: neurona debuxada con impulso animado, figura 3D que camiña, radial, organigrama, barras e etiquetar unha imaxe"],
"sci_chem":["Química: a táboa periódica","Laboratorio limpo: táboa periódica que se monta en fervenza, moléculas con formas, braseiro 3D, ecuacións, rosca e emparellar"],
"sci_climate":["O cambio climático en datos","Franxas de quecemento, gráficos de liñas, área e rectángulos, efecto invernadoiro que se debuxa, satélite 3D, ciclo e votación múltiple"],
"sci_mars":["Misión a Marte","Estilo espacial ferruxe: rover 3D da NASA con Transformar, astronauta flotando, órbita animada, ecuación e concurso"],
"sci_newton":["Física: as leis de Newton","Caderno de física: ecuacións, coche 3D en movemento, tiro parabólico que se debuxa, táboa con fórmulas e encher ocos"],
"sci_python":["Programación en Python","Estilo editor escuro: terminal que se escribe soa, código con pasos de resaltado, saída animada, ordenar liñas e reto con conta atrás"],
"sci_solar":["O sistema solar","Planetas a escala que aparecen en cadea, tres sondas 3D con vistas e movementos distintos, táboa, diagrama radial e emparellar"],
"sci_stats":["Estatística e probabilidade","Estilo editorial: campá que se debuxa, fórmulas, histograma, dispersión, área, barras e burbullas, e pregunta con puntos"],
"sci_thesis":["Defensa do TFG","Académico sobrio: portada institucional, índice, metodoloxía con ecuación, táboa con totais, resultados en gráficos, bibliografía e preguntas"],
"showcase_3d":["Catálogo: o 3D a fondo","Modelos 3D con todas as opcións: vistas, movementos ao entrar, xiro, bordos, marxe, clips, andar e chegada con Transformar"],
"showcase_animations":["Catálogo: animacións","Todas as animacións de obxecto: entrada, énfase, saída, traxectorias, debuxar, encadeadas, sons e varias nun obxecto"],
"showcase_charts":["Catálogo: gráficos","Os 15 tipos de gráfico, dous por diapositiva, con series, combinado, grade, etiquetas e títulos de eixos, e a táboa de opcións"],
"showcase_diagrams":["Catálogo: diagramas","Os 15 deseños de diagrama escritos como esquema, os 4 esquemas de cor e a aparición un a un ao presentar"],
"showcase_morph":["Catálogo: Transformar","Transformar paso a paso: texto que cambia de tamaño e sitio, formas, barras que medran, imaxe, 3D e letras que se reordenan"],
"showcase_objects":["Catálogo: multimedia e obxectos","Código con pasos, ecuacións, iconas, cinco dispositivos, táboas con estilos e fórmulas, zoom de diapositiva e conectores"],
"showcase_polls":["Catálogo: votacións e actividades","Os 11 tipos de votación e actividade desde o móbil, conta atrás nos seus tres estilos, clasificación e modo aula"],
"showcase_shapes":["Catálogo: formas","Todas as formas por categorías co seu nome, liñas e guións, degradados, opacidade, trazo a man, sombras, texto dentro e xiro"],
"showcase_text":["Catálogo: Text Art e tipografía","Os 10 estilos de Text Art, texto curvo, columnas, cinco niveis de viñetas, os 8 pares de letra, aliñamento e espazamento"],
"showcase_transitions":["Catálogo: transicións","As 22 transicións de diapositiva, unha a unha: entrada, saída distinta, direccións, velocidade e avance automático"]};
