// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Risultati trimestrali al consiglio","Blu scuro e oro: grandi indicatori animati con suono, cascata, imbuto, barre impilate e tabella con formule rispetto al budget"],
"biz_climate":["Sondaggio sul clima aziendale","Viola e partecipativo: conto alla rovescia, barre al 100 %, valutazione da 1 a 5, nuvola di parole, scelta multipla e domande del pubblico"],
"biz_investment":["Presentazione per investitori","Nero e oro: prodotto 3D che ruota e viaggia con Trasforma, cifre giganti, mercato in cerchi, trazione, uso dei fondi e team"],
"biz_marketing":["Piano di marketing della campagna","Stile caldo: testo in cerchio, pubblico target, imbuto, mix di canali, calendario in tabella, budget con formula e votazione"],
"biz_onboarding":["Benvenuto ai nuovi dipendenti","Stile amichevole: robot 3D che saluta e percorre la settimana camminando, organigramma uno alla volta, valori con icone e attività di abbinamento"],
"biz_proposal":["Proposta commerciale a un cliente","Stile carta: sigillo, processo uno alla volta, mockup su portatile e cellulare, prezzi, preventivo con IVA in formule, cronologia e garanzie"],
"biz_retail_basket":["Analisi del carrello: cosa racconta uno scontrino","Scontrino che si stampa, equazione dello scontrino medio, cascata, dispersione, rete di prodotti, tabella, query SQL, ciambella e quiz"],
"biz_retail_blackfriday":["Campagna del Black Friday","Nero e neon: cartellini dei prezzi, cifre con suono, prezzi barrati, linee per ora, imbuto, tabella con formule, quiz e conto alla rovescia"],
"biz_retail_cx":["Esperienza del cliente: il viaggio di Marta","Persona disegnata, curva delle emozioni che si traccia da sola con volti in sequenza, citazioni, NPS con equazione, matrice, Trasformazione e valutazione"],
"biz_retail_inventory":["Inventario: né rotture né eccessi","Magazzino disegnato con scaffali ed etichette, confronto, Pareto in grafico combinato, equazione, tabella con formule, codice, lampada 3D e ordinamento"],
"biz_retail_loyalty":["Fidelizzazione: il club del forno","Tessera a timbri che si riempie in sequenza con suono e applausi, equazione del valore del cliente, piramide dei livelli, tabella con formule e app"],
"biz_retail_market":["Mercato comunale: un piano per rilanciarlo","Facciata in ferro con nome curvo, lavagne di gesso in sequenza, treemap, aree per ora, calendario di stagione in tabella, avocado 3D e nuvola di parole"],
"biz_retail_omni":["Omnicanale: compra online, ritira in negozio","App nel telefono e sito nel browser disegnati, percorso che si traccia da solo, furgone 3D che percorre la strada, tabella con formula, codice e barre in pila al 100 %"],
"biz_retail_opening":["Apertura di una libreria-caffè","Facciata disegnata con tenda, mappa del quartiere con punti in sequenza, Venn, poltrona 3D, cronologia, tabella con formule e conto alla rovescia"],
"biz_retail_supermarket":["Supermercato: nuova disposizione","Pianta fatta di forme, carrello che percorre il negozio, mappa di calore, reparti che si ricollocano con Trasformazione, scaffale e tabella"],
"biz_retail_window":["Vetrinistica: la vetrina d'autunno","Editoriale in nero e avorio: occhiali 3D con Trasformazione, testo in cerchio, campioni di colore, vetrina disegnata con triangolo e punti focali"],
"biz_roadmap":["Roadmap di un progetto","Stile tecnico scuro: frecce una alla volta, diagramma di Gantt animato, cronologia, auto 3D che avanza con Trasforma e tabella di stato"],
"biz_sales":["Vendite e previsione annuale","Minimalista in grigio: barre e linee combinate, scenari, formula di previsione, tabella con formule, barre impilate e orizzontali"],
"biz_startup_agrotech":["Pitch agritech: irrigazione con sensori","Vista aerea di campi con mappa dell’umidità, satellite 3D della NASA, telefono, gocce in sequenza con suono, tabella con formule e treemap"],
"biz_startup_edtech":["Pitch edtech: tutor di matematica","Quaderno a quadretti: post-it in sequenza, scrittura a mano, equazioni passo passo, telefono, quiz dal vivo, ciclo e grafici"],
"biz_startup_energy":["Pitch energia: comunità solare","Tetti dall’alba alla notte: sole che sorge e attraversa il cielo ad arco, diagramma radiale, aree orarie, equazione e tabella con formule"],
"biz_startup_fashion":["Pitch moda circolare: Retal","Etichetta d’abito che viaggia con Trasformazione, cuciture tratteggiate, vita di un capo in sequenza, ciclo, anello, radar e voto multiplo"],
"biz_startup_insurance":["Pitch assicurazioni: copertura a giornata","Pioggia grigia e ombrello giallo: pittogramma in sequenza, app con interruttore, equazione del prezzo, tabella con formule, cronologia e voto"],
"biz_startup_kitchen":["Pitch robotica da cucina: Fogón","Cucina professionale: comande sulla barra, Text Art di fuoco, robot 3D che entra camminando e saluta, ricetta in codice, conto alla rovescia e imbuto"],
"biz_startup_lastmile":["Pitch logistica: ultimo miglio","Stile mappa della metro: linee che si disegnano da sole, camion 3D e bici che percorrono la mappa, tabella con formule, area e cascata"],
"biz_startup_mental":["Pitch salute mentale: Remanso","Notte calma: anelli che respirano, minuto di respiro con conto alla rovescia, app sul telefono, scala, valutazione e tabella con formule"],
"biz_startup_pets":["Pitch animali: cibo fresco","Stile adesivo con impronte che appaiono in sequenza, volpe 3D che attraversa camminando, formula della razione in tabella, anello e quiz"],
"biz_startup_rural":["Pitch turismo rurale: Alpende","Montagne al tramonto e cartoline: lanterna 3D, timbro con testo curvo, mappa con auto 3D lungo il percorso, barre, torta e nuvola di parole"],
"biz_strategy":["Piano strategico e OKR","Stile bianco pulito: cifre che entrano in sequenza, piramide, priorità con icone, tabella degli OKR, barre di avanzamento, radar e frecce"],
"biz_swot":["Analisi SWOT e concorrenza","Sfondo grafite: SWOT per quadranti, matrice delle strategie, mappa di posizionamento, barre raggruppate, Venn, torta e votazione a scelta multipla"],
"creative_bauhaus":["Bauhaus: forma e funzione","Arte geometrica Bauhaus: forme primarie che girano e rimbalzano, cronologia, griglia con Trasforma e attività di abbinamento"],
"creative_brutalism":["Brutalismo: manifesto web","Stile brutalista: tipografia gigante, blocchi neri, testo verticale, ombre nette, barrato animato, tabella e sondaggio"],
"creative_comic":["Fumetto: superpoteri animali","Stile fumetto: vignette, nuvolette di dialogo e pensiero, onomatopee in Text Art che rimbalzano, volpe 3D, grafico e quiz"],
"creative_fashion":["Rivista di moda: autunno lento","Stile rivista: testata con grazie, orologio 3D in copertina, colonne con capolettera, citazione grande, palette di stagione e grafico"],
"creative_glass":["Glassmorphism: app di finanza","Schede traslucide su bagliori colorati, app nel cellulare, grafico ad anello, scheda con Trasforma e sondaggio di valutazione"],
"creative_pixel":["Pixel art: il tuo primo videogioco","Stile videogioco retrò: sprite in pixel, segnapunti, personaggi 3D che camminano e saltano, codice passo passo, quiz e conto alla rovescia"],
"creative_retro_atomic":["Retrofuturismo: il futuro del 1962","Era atomica: casa a disco volante che si trasforma, centri ed errori in sequenza, robot 3D che cammina, radar, matrice, conto alla rovescia e nuvola di parole"],
"creative_retro_deco":["Art déco: il Grand Hotel compie 100 anni","Art déco in oro e nero: ventaglio che si trasforma, Text Art dorato, ascensore come cronologia, divano 3D, tabella con formule e quiz"],
"creative_retro_desktop90":["Anni '90: i backup","Desktop anni '90: finestre grigie, errori a cascata, barra di avanzamento, equazione, tabella con formule, codice passo per passo e quiz"],
"creative_retro_diner":["Anni '50: la tavola calda riapre","Tavola calda anni '50: insegna al neon, pavimento a scacchi, tenda, camion 3D sulla strada, menù con formule, ciambella, sigillo che gira e sondaggio"],
"creative_retro_letterpress":["Manifesto tipografico: la festa del quartiere","Manifesto a caratteri in legno: inchiostro sfasato, lettere che cadono con suono, programma, barre impilate, cascata, bando, sondaggio e conto alla rovescia"],
"creative_retro_sepia":["Album seppia: cerca i tuoi nonni","Album seppia: angolini, scrittura a mano, equazione degli antenati, albero che cresce, mappa con viaggio disegnato, torta, abbinamenti e Trasforma"],
"creative_retro_teletext":["Televideo: il campionato di quartiere","Pagine di televideo: righe che si caricano da sole, punteggio e classifica con formule, barre, colonne, quiz e conto alla rovescia"],
"creative_retro_typewriter":["Macchina da scrivere: laboratorio di racconto","Foglio e macchina da scrivere: righe battute con suono, barrato e correzione a mano, arco che si disegna, barre, spazi vuoti e conto alla rovescia"],
"creative_retro_vapor":["Vaporwave: la musica dei negozi","Vaporwave pastello: luna che si trasforma, palme in SVG, titoli glitch, dispersione, lampada 3D, tabella con media e valutazione"],
"creative_retro_vinyl":["Anni '70: il club del vinile","Stile anni '70: arcobaleni a strisce, dischi disegnati che girano, cifra gigante, linee, barre, divano 3D, attività di ordinamento e adesivo"],
"creative_space":["Galassia: guardare il passato","Stile spaziale: stelle, nebulose luminose, modelli 3D della NASA, sonda che percorre i pianeti, testo curvo e quiz"],
"creative_swiss_blood":["Campagna: dona il sangue","Manifesto pubblico bianco e rosso: goccia che riempie lo schermo con Trasforma, processo, sì o aspetta, ciambella, barre, cellulare e quiz"],
"creative_swiss_chairs":["Mostra: la sedia moderna","Manifesto svizzero grigio e lime: sedia 3D che gira e viaggia con Trasforma, cronologia, ciambella, poltrona 3D, tabella con formule e ordinare"],
"creative_swiss_designconf":["Congresso di design: Griglia 27","Grafite e ciano: la griglia si monta da sola e cambia con Trasforma, cifra a contorno, formula, cronologia, codice CSS, nuvola e pausa"],
"creative_swiss_film":["Festival del cinema: il programma","Svizzero in nero e rosso: numero gigante che diventa fascia con Trasforma, sezioni a griglia, tabella, barre, sondaggio e conto alla rovescia"],
"creative_swiss_foundation":["Relazione annuale di una fondazione","Svizzero in bianco e blu cobalto: anno gigante, lettera a piena pagina, cifre a catena, equazione, ciambella, area, frecce e conti con formule"],
"creative_swiss_games":["Giochi scolastici: l'identità visiva","Bianco e magenta, tavolozza propria: pittogrammi SVG, figura 3D che attraversa la città, linee, medagliere con formule, gradini e quiz"],
"creative_swiss_museum":["Guida al museo di storia naturale","Segnaletica svizzera nero e giallo: pianta propria con percorso animato, volpe 3D che cammina, colonne, tabella, etichettare e pittogrammi"],
"creative_swiss_orchestra":["Orchestra sinfonica: stagione 26/27","Blu notte e ambra: archi che girano, testo curvo, cifre su un pentagramma, cicli, tabella, equazione, barre, sondaggio e applausi"],
"creative_swiss_publisher":["Catalogo d'autunno di una casa editrice","Carta crema e verde petrolio: scaffale di dorsi verticali, copertine SVG, tablet, torta, ordine con formule, calendario e lacune"],
"creative_swiss_typeface":["Campionario di un nuovo carattere","Campionario bianco e viola: lettere che viaggiano con Trasforma, anatomia misurata, scala con formula, glifi, radar e licenze"],
"creative_synthwave":["Synthwave: festival Neón 86","Stile retrò anni 80: sole sfumato, griglia che si disegna, neon luminoso, Trasforma, robot 3D che balla e nuvola di parole"],
"creative_watercolor":["Acquerello: orto sul balcone","Stile acquerello e carta: macchie con sfumatura radiale, forme a mano libera, scrittura a mano, disegno che si traccia da solo e 3D"],
"creative_zen":["Minimalismo giapponese: il tè","Minimalismo giapponese: tanto bianco, sole rosso che si trasforma, testo verticale, ensō che si dipinge da solo e conto alla rovescia"],
"data_ab_test":["Esperimento A/B","Equazioni, dispersione a due serie, colonne con etichette, tabella di conversione con formule e cifre di significatività"],
"data_city_air":["La qualità dell'aria a Brisamar","Cielo che si rasserena con Trasformazione, indice con lancetta, equazione, linee con vuoti, radar, tabella con formule e valutazione"],
"data_city_bikes":["Pedalia: un anno di bici condivisa","Mappa stile metro, bici che percorre una linea, cifre con suono, linee, barre in pila, app sul cellulare, tabella e codice"],
"data_city_budget":["Bilancio partecipativo","Manifesto civico: urna con schede che cadono, anello, chevron, grafico combinato, risultati con rullo di tamburi, tabella con formule"],
"data_city_housing":["Casa: il prezzo di restare","Disegno d'architetto: pianta in SVG, superfici in scala, grafico combinato, equazione, tabella con formule, dispersione e divano 3D"],
"data_city_noise":["Il rumore di Sotoverde","Onda che si alza da sola, righello dei decibel con suoni, equazione, mappa del rumore, barre in pila, quiz e conto alla rovescia"],
"data_city_tourism":["Turismo a Isla Marena","Manifesto di viaggio: sole con testo curvo, pittogramma, aree, rettangoli, barre al 100 %, passante 3D, tabella e cartolina"],
"data_city_traffic":["Il traffico nell'ora di punta","Sala di controllo notturna: mappa con code tracciate, semaforo che si accende, tabella di calore, formula di Webster, codice e camion 3D"],
"data_city_trees":["Censimento degli alberi urbani","Foglio d'erbario: albero disegnato, pianta 3D con Trasformazione, rettangoli, istogramma, equazione, tabella e abbinamento"],
"data_city_waste":["Quello che buttiamo a Villa Cardo","Bidoni che saltano con suono, cifra gigante, cascata, barre in pila, torta per colori, imbuto, abbinamento e tabella"],
"data_city_water":["L'acqua di Fuentelinda","Bacino che si svuota con Trasformazione, linee, anello, barre, tariffa con equazione e formule, doccia con conto alla rovescia"],
"data_energy":["Energia e consumi","Aree in pila per ora, linee a tre serie, treemap, colonne con etichette e tabella delle tariffe calcolata"],
"data_exec_panel":["Cruscotto direzionale mensile","KPI con semafori e minigrafici, combinato rispetto al budget, piccoli multipli, ciambella e sondaggio"],
"data_home_finance":["Finanze personali","Cascata dallo stipendio al risparmio, grafico a torta, linee e area, tabelle con SOMMA, MEDIA, MAX e MIN"],
"data_market_study":["Ricerca di mercato","Cifre grandi, treemap, bolle, dispersione, barre orizzontali a due serie e matrice 2 × 2"],
"data_population":["Popolazione e demografia","Piramide della popolazione, istogramma, barre orizzontali, linee che si incrociano e tabella di indicatori con formule"],
"data_sales_regions":["Vendite per regione","Barre raggruppate, in pila e al 100 %, grafico combinato con obiettivo, tabella con totali da formula e KPI animati"],
"data_satisfaction":["Sondaggio di soddisfazione","Ciambella con legenda, radar a confronto, colonne con etichette, NPS, valutazione e nuvola di parole dal vivo"],
"data_season_stats":["La stagione in cifre","Cifre giganti con suono, classifica con formule, barre negative, linee, barre in pila e radar della squadra"],
"data_sport_climb":["Tappa regina: l'Alto de Peñaroja","Libro di corsa: profilo colorato che un ciclista scala, tabella delle salite con formule, equazione della potenza, dispersione, anello e occhiali 3D"],
"data_sport_elo":["Elo: come si misura la forza","Scacchiera notturna: cavaliere 3D, equazioni, curva attesa, esempio passo passo, istogramma, tabella con formule, codice e quiz"],
"data_sport_load":["Carico di allenamento e infortuni","Referto di fisioterapia: mappa del corpo, equazione ACWR con indicatore che avanza, linee, barre in pila, codice, tabella con formule, ciclo e figura 3D"],
"data_sport_marathon":["Maratona: cosa raccontano gli arrivi","Pettorale in copertina, cifre con suono, istogramma degli arrivi, il muro del km 30, lepre robot 3D che corre, tabella con formule e medaglia"],
"data_sport_serve":["Anatomia di un servizio","Terra rossa: pallina che rimbalza, servizi sul campo e zoom sul riquadro con Trasforma, radar, barre al 100%, equazione e sondaggio"],
"data_sport_shots":["Da dove si vince: la mappa di tiro","Parquet di legno: tiro tracciato, equazione eFG, metà campo con zone per efficienza, barre al 100%, linee che si incrociano e quiz"],
"data_sport_sprint":["100 metri in 9,94 secondi","Stadio di notte: tempo al neon, fasi a frecce, velocità ogni 10 m, tabella con formule, fotofinish, orologio 3D e conto alla rovescia"],
"data_sport_stadium":["Riempire lo stadio","Biglietto della partita: tribune per occupazione, aree, dispersione a due serie, rettangoli, imbuto, tabella con formule, sondaggio e poltrona 3D"],
"data_sport_swim":["Bracciata dopo bracciata: 200 m stile libero","Piscina vista dall'alto: nuotatrice che fa quattro vasche, equazione, piccoli multipli, colonne in pila, tabella con formule e nuvola di parole"],
"data_sport_xg":["Gol attesi (xG)","Lavagna sul prato: tiri tracciati, punteggio contro xG, mappa dei tiri uno a uno, equazione logistica, codice, tabella e quiz"],
"data_web_metrics":["Metriche web e marketing","KPI con minigrafici, linee a quattro serie, aree, imbuto di conversione, grafico combinato e tabella con formule"],
"edu_bio_digestion":["Il viaggio di un panino","Mappa della metro: la linea D si disegna, un panino la percorre, tabellone delle partenze in tabella, enzimi, barre, ordinare le fermate e Text Art"],
"edu_bio_dna":["Il DNA, la ricetta della vita","Laboratorio al neon: elica che si monta da sola, Text Art, basi che si appaiano, codice Python passo passo, barre, mutazione e abbinamenti"],
"edu_bio_ecosystem":["Il bosco: chi mangia chi","Quaderno di campo in carta kraft: volpe 3D che cammina, catena alimentare, rete che si disegna, piramide e tabella del 10 %, linee ed etichette"],
"edu_bio_evolution":["Adattamento: il becco dei fringuelli","Carta nautica notturna: nave che segue una rotta, becchi disegnati, barre della siccità, dispersione, ciclo, Trasforma del becco e quiz"],
"edu_bio_heart":["Il cuore, una pompa instancabile","Rosso e blu: battito disegnato, cifre giganti, circuiti tracciati, goccia nel cuore, polso con conto alla rovescia e formule, 3D e quiz"],
"edu_bio_mendel":["Mendel e i piselli","Quaderno dell'orto: piselli che compaiono, generazioni con Trasforma, quadrato di Punnett, barre e ciambella, linea del tempo e quiz"],
"edu_bio_microbes":["Microbi: il mondo invisibile","Oculare del microscopio: testo curvo, Trasforma da 40 a 400 ingrandimenti, forme di batteri, lievito in linee, sondaggio e Text Art"],
"edu_bio_photosynthesis":["Fotosintesi: la fabbrica verde","Foglia al sole: pianta 3D, entrate e uscite animate, Trasforma verso il cloroplasto, equazione, tabella con medie, conto alla rovescia, linee e lacune"],
"edu_bio_pollination":["Dal fiore al frutto","Prato di primavera: ape che vola, parti del fiore, etichette, treemap, Trasforma dal fiore al frutto, avocado 3D, cronologia e nuvola"],
"edu_bio_respiration":["Respirare: il viaggio dell'aria","Cielo aperto: polmoni che respirano, percorso dell'aria, Trasforma tra inspirazione ed espirazione, due ciambelle, bottiglia 3D, conto alla rovescia e quiz"],
"edu_body":["Il corpo umano","Stile laboratorio: figura 3D con Trasforma, personaggio che cammina lungo un percorso, grafico a barre, etichettare il corpo e quiz"],
"edu_cell":["La cellula","Cellula disegnata con forme, parti una alla volta, Trasforma per avvicinarsi, abbinare coppie, diagramma, pianta 3D e valutazione"],
"edu_english":["Inglese per principianti","Modalità classe: schede che si girano con suono, robot 3D che cammina e saluta, volpe 3D, tre domande a punti, classifica e applausi"],
"edu_fractions":["Le frazioni","Stile neon: pizze disegnate, equazioni passo passo, somma con Trasforma, completare gli spazi, quiz e sfida con conto alla rovescia"],
"edu_geo_cities":["La città: come cresce","Città notturna dall'alto: Text Art al neon, grafico ad area, piante disegnate, anelli con Trasforma, diagramma radiale e auto 3D"],
"edu_geo_climograph":["Leggere un climogramma","Stazione meteo: termometro che sale, barre con linea, tabella con formule, equazioni, satellite 3D, abbinamenti e sfida con conto alla rovescia"],
"edu_geo_coasts":["Coste e maree","Faro con fascio che ruota, forme della costa una a una, scogliera che si erode, maree in grafico e tabella con formule, etichette"],
"edu_geo_continents":["Continenti e oceani","Atlante per bambini: continenti che compaiono con un suono, treemap, ciambella degli oceani, robot 3D che attraversa il mondo, abbinare ed etichettare"],
"edu_geo_deserts":["I deserti","Dune al tramonto: carovana che avanza, Text Art dorato, grafici a barre e a linee, volpe 3D, oasi disegnata, miti barrati e quiz"],
"edu_geo_mountains":["Le montagne","Manifesto alpino: parti del rilievo una a una, equazione e tabella della temperatura, fasce in piramide, escursionista 3D che sale e ordinare"],
"edu_geo_pyramids":["Piramidi della popolazione","Manifesto del censimento: piramide che si costruisce barra per barra, tre forme con Trasforma, grafico a linee, equazioni, ordinare e quiz"],
"edu_geo_river":["Il viaggio di un fiume","Acquerello: fiume che si disegna mentre una goccia lo percorre, zoom con Trasforma, portata con equazione, tabella con formule ed etichette"],
"edu_geo_timezones":["Fusi orari","Tabellone d'aeroporto con righe che girano, Terra che ruota con equazione, Sole che attraversa i fusi, tabella con formule, orologio 3D e completamento"],
"edu_geo_topomap":["Leggere una carta topografica","Carta da orienteering: percorso che si disegna, scala con equazione, tabella con formule, curve di livello con Trasforma e corritrice 3D"],
"edu_hist_alandalus":["Al-Andalus: scienza e giardini","Arco a ferro di cavallo, cronologia passo passo, barre orizzontali, astrolabio che gira, stella con Morph, abbinare coppie e votazione"],
"edu_hist_castle":["Castelli e feudalesimo","Castello notturno e cavaliere 3D che attraversa il ponte, piramide feudale che si alza, etichettare, sole che percorre il giorno, treemap e stemmi"],
"edu_hist_egypt":["Egitto, dono del Nilo","Lapislazzuli e oro: sole che sorge dietro le piramidi, piena animata, grafico ad aree, equazione, Morph, cartiglio geroglifico e ordinare"],
"edu_hist_greece":["Atene: nasce la democrazia","Stile vaso a figure nere: meandro, testo curvo, Morph, ciambella, tempio che si alza, ostraka con suono, votazione e tabella"],
"edu_hist_maya":["I Maya: tempo e stelle","Giungla e giada: numeri a punti e barre, Morph in base 20, equazione, ruote del calendario che girano, serpente di luce e cacao"],
"edu_hist_mesopotamia":["Mesopotamia: nasce la scrittura","Tavoletta d’argilla che si scrive da sola, mappa con fiumi disegnati, ziggurat che cresce, base 60 con formule, completare e radiale"],
"edu_hist_printing":["La stampa: il libro si moltiplica","Pagina di incunabolo: capolettera rosso, caratteri rovesciati composti con Morph, torchio che scende con suono, cifre, barre e lacune"],
"edu_hist_rome":["Roma, ingegneri dell’impero","Marmo e rosso imperiale: Morph, arco trionfale, strada a strati con soldato 3D che marcia, acquedotto, equazione, formule e quiz"],
"edu_hist_silkroad":["La Via della Seta","Seta e zafferano: carovana in marcia, mappa con rotta tracciata, cascata del prezzo, tabella con formule, lanterna 3D, equazione e ordinare"],
"edu_hist_vikings":["Vichinghi, navigatori del nord","Fiordo sotto l’aurora: nave che dondola, rune, miti barrati con timbro, traversata animata, cifre con suono, guerriero 3D, radar e abbinare"],
"edu_kids_colors":["I colori","Tavolo da pittura: arcobaleno che si disegna da solo, barattoli con suono, miscele con Trasformazione, icone, abbinare, sondaggio e conto alla rovescia"],
"edu_kids_emotions":["Come mi sento?","Un volto disegnato che cambia emozione con Trasformazione, ghirlanda di volti, palloncino per respirare, sondaggio e abbinare"],
"edu_kids_farm":["Gli animali della fattoria","Fattoria disegnata con animali propri, linee che si tracciano, tabella con somma, camion 3D in viaggio, volpe 3D che cammina, quiz ed etichette"],
"edu_kids_numbers":["Il treno dei numeri","Treno disegnato che entra con suono, contare uno a uno, numeri nascosti, somma in equazione, grafico, ordinare, quiz e conto alla rovescia"],
"edu_kids_sea":["Sotto il mare","Fondale in sfumatura, pesci disegnati che nuotano, bolle, grande e piccolo, bottiglia 3D nel bidone, abbinare e nuvola di parole"],
"edu_kids_seasons":["Le quattro stagioni","Un albero che cambia con Trasformazione nelle quattro stagioni, foglie e neve che cadono, ruota dell'anno, ciclo, abbinare e sondaggio"],
"edu_kids_senses":["I cinque sensi","Cartoncino ritagliato: volto disegnato, diagramma radiale, indovinelli, pulsanti con cinque suoni, carte che girano, etichette e conto alla rovescia"],
"edu_kids_shapes":["Forme e blocchi","Tappeto da gioco: blocchi con suono, forme che si disegnano da sole, casa che diventa robot con Trasformazione, robot 3D e piramide"],
"edu_kids_space":["Viaggio sulla Luna","Cielo notturno: razzo che decolla con suono, conto alla rovescia, Luna che gira intorno alla Terra, fasi, astronauta e modulo lunare 3D"],
"edu_kids_transport":["Come viaggiamo?","Tappeto stradale: auto giocattolo 3D, veicoli che passano con suono, semaforo che cambia, grafico, auto 3D, abbinare e sondaggio"],
"edu_lang2_advent":["Tedesco: Avvento e Natale","Notte innevata: Text Art dorato, lanterna 3D, fiocchi che cadono, calendario dell'Avvento che si apre, cronologia, etichettatura e ricetta con formule"],
"edu_lang2_artikel":["Tedesco: der, die, das","Manifesto Bauhaus: forme che entrano con suono, desinenze in tabella, ciambella, Trasforma verso l'accusativo, abbinamenti e quiz"],
"edu_lang2_cafe":["Francese: au café","Lavagna da bistrot sotto la tenda: testo curvo, conto con formule nella tabella, equazione dei prezzi, dialogo, barre e completamento"],
"edu_lang2_directions":["Inglese: come arrivare a…","Mappa della metro inventata: un treno percorre il tragitto con un percorso, frasi lungo la strada, dialogo, strada disegnata, riordino, quiz e conto alla rovescia"],
"edu_lang2_falsefriends":["I falsi amici in inglese","Fascicolo da detective: timbro con suono, occhiali 3D, sospettati che si girano, tabella delle prove, barre, cancellature e sondaggio"],
"edu_lang2_ola":["Portoghese: Olá, Lisboa!","Azulejos e tram giallo che sale la collina con un percorso, saluti che si girano, tabella dei suoni, chat su un telefono e mappa ad albero"],
"edu_lang2_passato":["Italiano: il passato prossimo","Cartolina della Riviera: auto 3D che percorre la costa con un percorso, equazione, participi in tabella, accordo, completamento e quiz"],
"edu_lang2_phrasal":["Phrasal verbs: level up","Sala giochi al neon: Text Art, Trasforma che unisce verbo e particella, cavaliere 3D che avanza, barre, barrato, abbinamenti e conto alla rovescia"],
"edu_lang2_sons":["Francese: i suoni","Vinile che gira con testo curvo, tracce con suono, legamenti disegnati ad arco, tabella delle regole, radar, quiz e conto alla rovescia"],
"edu_lang2_tenses":["Present perfect o past simple","Orologeria: orologio 3D con Trasforma, linea del tempo con un arco che si disegna, equazioni, tabella, barre al 100 %, albero e conto alla rovescia"],
"edu_lang_accent":["L'accento senza paura","Quaderno a quadretti e penna rossa: sillabe che suonano illuminandosi, tabella, albero decisionale, cancellature animate, post-it e quiz"],
"edu_lang_becquer":["Bécquer e le Rimas","Notte romantica: rondini che attraversano la luna, testo curvo, versi che appaiono da soli, lanterna 3D, cronologia, metrica in tabella e completamento"],
"edu_lang_calderon":["La vita è sogno","Sipario che si apre e si chiude con suono, pianta del corral, trono 3D con Trasforma, monologo verso per verso, radiale, bilancia e quiz"],
"edu_lang_commentary":["Come commentare un testo","Pagina con evidenziatori che si tracciano da soli e note a margine, frecce una a una, cronologia, equazione, conto alla rovescia, rubrica e radar"],
"edu_lang_fables":["Favole: la volpe e l'uva","Libro di fiabe: volpe 3D che entra camminando, titolo curvo, cronologia, pergolato disegnato, gradini, tabella, ordinamento e nuvola di parole"],
"edu_lang_figures":["Figure retoriche a fumetti","Fumetto pop: vignette, nuvolette ed esplosioni con suono, orologio 3D che vola lungo un percorso, versi che si colorano e quiz"],
"edu_lang_genres":["I generi letterari","Biblioteca di notte: libri che salgono sullo scaffale, schede timbrate con suono, Venn, gerarchia, anello, sondaggio, abbinamenti e poltrona 3D"],
"edu_lang_lazarillo":["Il Lazarillo de Tormes","Pergamena e ceralacca: furfante 3D che percorre la mappa di padrone in padrone, schede, tabella dei padroni, linea della fame, quiz e ordinamento"],
"edu_lang_meter":["La musica del verso: metrica","Studio di registrazione: onda che si disegna, sillabe che suonano come un metronomo, equazione per casi, sinalefe, sonetto per tracce e quiz"],
"edu_lang_syntax":["Soggetto e predicato, in progetto","Progetto tecnico: pezzi che si ordinano con Trasforma, parentesi che si tracciano, albero sintattico, tabella, etichettare un'immagine e quiz"],
"edu_math_coordinates":["Coordinate: la mappa del tesoro","Mappa del tesoro: rosa dei venti con testo curvo, punti che compaiono, pirata 3D che segue gli indizi, barca che si disegna ed etichettatura"],
"edu_math_integers":["Numeri interi: mare e montagna","Dal fondo del mare alla vetta: retta con salti, Text Art ghiaccio, temperature sotto zero, sottomarino che sale e scende, ordinare e quiz"],
"edu_math_primes":["Numeri primi","Terminale verde: neon personalizzato, crivello di Eratostene clic dopo clic con 100 caselle, albero dei fattori, codice passo a passo, quiz e sfida"],
"edu_math_probability":["Probabilità: misurare la fortuna","Tavolo da gioco bordeaux e oro: dadi che rotolano con rullo di tamburi, testo curvo, regola di Laplace, albero uno a uno, barre, linee e quiz"],
"edu_math_proportion":["La proporzionalità al supermercato","Scontrino: timbro che rimbalza, tabella di proporzionalità con formule, proporzione passo a passo, sconti calcolati, linee e completamento"],
"edu_math_pythagoras":["Il teorema di Pitagora","Lavagna: figura che si disegna da sola, dimostrazione senza parole con Trasforma, terne con formule, scorciatoia in 3D e quiz"],
"edu_math_sequences":["Successioni e schemi","Libro di botanica: spirale di Fibonacci che si traccia da sola, sassi in catena, fiammiferi con formule, codice, pianta 3D e numero aureo"],
"edu_math_stats":["Statistica: media, mediana e moda","Quaderno a quadretti: post-it a cascata, frequenze con formule, barre, ciambella con gradi, istogramma e sondaggio dal vivo"],
"edu_math_symmetry":["Simmetria e tassellature","Azulejos nasridi: stella che gira, farfalla che si riflette, traslazione, rotazione e simmetria animate, tabella degli angoli e alveare"],
"edu_math_volumes":["Aree e volumi","Disegno tecnico blu: cartiglio in tabella, sviluppo piano, bottiglia 3D misurata, volumi con formule, barre, coni che riempiono e abbinamento"],
"edu_pe_active":["60 minuti al giorno","Bacheca di sughero: note con puntine, personaggio 3D che salta, settimana con formule, barre in pila, ciambella, codice e muro di idee"],
"edu_pe_athletics":["Atletica: correre, saltare, lanciare","Pista in tartan: personaggio 3D, pittogrammi che girano, equazione e tabella delle corsie, partenza con suoni, istogramma, ordinare e podio"],
"edu_pe_basketball":["Basket: tiro e terzo tempo","Lavagna dell'allenatore: pallone che rimbalza con suono, campo quotato, parabola tracciata, schema disegnato, tabella con formule ed etichettare"],
"edu_pe_calm":["Defaticamento: allungarsi e respirare","Alba tranquilla: pianta 3D, respirazione quadrata con traiettoria, cerchio che cresce e si restringe, allungamenti, bersaglio e nuvola di parole"],
"edu_pe_heart":["Il cuore in movimento","Monitor cardiaco: elettro che si traccia da solo, conto alla rovescia del polso, equazione, zone con formule, area, telefono con app e quiz"],
"edu_pe_hydration":["Bevi prima di avere sete","Acqua e bolle: bottiglia 3D, corpo che si riempie, barre del sudore, bicchiere con Trasformazione, scala di colore e riempire i vuoti"],
"edu_pe_nutrition":["Il piatto dello sportivo","Tovaglia a quadri: piatto servito per parti, ciambella, avocado 3D, colazioni con formule, miti che si girano, abbinare e nuvola di parole"],
"edu_pe_posture":["Una schiena per tutta la vita","Tavola seppia: colonna vertebra per vertebra, didascalie a catena, zaino con formule, così no e così sì, sedia 3D, conto alla rovescia ed etichettare"],
"edu_pe_sleep":["Anche dormire è allenarsi","Finestra di notte: stelle che si accendono, lampada 3D, ipnogramma, ciclo, radiale, telefono con messaggi, routine a catena e valutazione"],
"edu_pe_warmup":["Riscaldarsi prima di giocare","Parquet della palestra: robot 3D che corre, linea della temperatura, frecce, articolazioni con suono, conto alla rovescia, ordinare e quiz"],
"edu_quixote":["Don Chisciotte","Stile inchiostro e carta: mulino che gira con suono, testo curvo, citazioni animate, Trasforma, cronologia, completare gli spazi e quiz"],
"edu_renewables":["Energie rinnovabili","Turbina eolica che gira, schede, grafici ad area, ad anello e a barre raggruppate, nuvola di parole in diretta, sondaggio e conto alla rovescia"],
"edu_revolution":["La Rivoluzione francese","Stile carta antica: testo in cerchio, Trasforma, piramide sociale, cronologia animata con suono, ordinare i fatti e sondaggio"],
"edu_spain":["Geografia della Spagna","Stile atlante: rosa dei venti, rilievo a bersaglio, tabella dei fiumi con formule, grafici di vette e piogge, abbinare coppie e quiz"],
"edu_volcanoes":["I vulcani","Stile fuoco: eruzione animata con suono, parti del vulcano da etichettare, tabella, quiz a tempo e conto alla rovescia"],
"edu_water":["Il ciclo dell'acqua","Diagramma a ciclo uno alla volta, paesaggio con gocce che salgono e pioggia animata con suono, grafici ad anello, abbinare coppie e satellite 3D"],
"learn_revela_ai":["L'IA di Revela","Una chat sotto l'aurora: creare una presentazione, riscrivere testi (con Trasforma per parole), immagini, l'assistente e altri aiuti"],
"learn_revela_anim":["Animazioni passo dopo passo","Un teatro: entrata, enfasi, uscita e percorsi, avvio con o dopo la precedente, riquadro animazione, altri effetti e suoni"],
"learn_revela_collab":["Collaborare e condividere","Una bacheca di sughero: collaborare insieme, permessi di condivisione, commenti e attività reali, link, versioni e un'attività di abbinamento"],
"learn_revela_design":["Design: schema, temi e colori","Una mazzetta di colori: schema e layout, temi, tavolozze e caratteri, contrasto calcolato, Text Art, testo curvo e idee di design"],
"learn_revela_export":["Esportare e portarla con te","Un tabellone delle partenze: PDF, PowerPoint, video, pagina web, SCORM, stampa con note e scorciatoie da tastiera, con votazione finale"],
"learn_revela_first":["La tua prima presentazione in 5 minuti","Una ricetta in cinque passi: galleria di esempi, layout delle diapositive, scrivere, inserire un'immagine e presentare, con conto alla rovescia"],
"learn_revela_live":["Sondaggi e attività dal vivo","Uno studio da quiz: votazione, nuvola di parole, quiz a punti, conto alla rovescia, classifica e attività di ordinamento, tutto funzionante"],
"learn_revela_morph":["Trasforma: la metamorfosi","Dal bruco alla farfalla con Trasforma: duplica per animare, per oggetti, per parole e per caratteri, in diapositive che si trasformano"],
"learn_revela_pptx":["Importare un PowerPoint e continuare","Un trasloco: come importare un .pptx, cosa si conserva (schema, animazioni, Trasforma, note) e come esportarlo di nuovo"],
"learn_revela_present":["Presentare come un professionista","Una cabina di pilotaggio: visualizzazione relatore, note, telecomando con il cellulare, puntatore laser e penna, lavagna, conto alla rovescia e scorciatoie"],
"life_bookclub":["Club del libro","Libreria a mano libera, copertina fatta di forme, citazioni che si trasformano, diagramma radiale, voto e scelta del prossimo libro"],
"life_cv":["Curriculum visivo","Testo in cerchio, cifre, cronologia passo passo, barre delle competenze animate, radar, schermate nei dispositivi e contatti"],
"life_fitness":["Piano di allenamento: 5 km","Corridore 3D, Text Art fuoco, fasi con sfumature, settimana con formule, grafici dei progressi, piramide, conto alla rovescia e nuvola di parole"],
"life_garden":["Orto urbano","Pianta 3D con Trasforma, calendario di semina in tabella a colori, ciclo, Venn, grafici di irrigazione e crescita, attività di etichettatura"],
"life_graduation":["Diploma e fine anno","Text Art oro, tocchi fatti di forme, polaroid che ruotano all'ingresso, cifre con rullo di tamburi, ringraziamenti, nuvola di parole e applausi"],
"life_italy":["Viaggio in Italia","Testo in cerchio, itinerario con connettori e percorso animato, cronologia, budget con formule, grafici e attività di abbinamento"],
"life_kids_party":["Compleanno per bambini","Colori vivaci: robot 3D che balla, personaggi che festeggiano, palloncini a mano libera, quiz a punti e conto alla rovescia"],
"life_moving":["Trasloco e nuova casa","Casa con forme a mano libera, cronologia, elenco che si barra, mobili 3D che passano alla pianta con Trasforma, budget e attività di ordinamento"],
"life_recipe":["Ricetta: guacamole","Avocado 3D che viaggia tra le diapositive (Trasforma), ingredienti con formule, passaggi uno alla volta, conto alla rovescia e voto"],
"life_travel_eu_amsterdam":["Amsterdam: canali e bici","Facciate sul canale che si montano in sequenza, canali a bersaglio, bici che passa con suono, tabella con formule, linee e voto a torta"],
"life_travel_eu_camino":["Cammino di Santiago: da Sarria","Credenziale che si riempie di timbri con suono, cascata di chilometri, camminatore 3D, equazione dello zaino, ciambella e tappe da ordinare"],
"life_travel_eu_croatia":["Croazia in barca a vela in Dalmazia","Carta nautica, rosa dei venti che gira e viaggia con Trasforma, bandiere, abbinare, miglia con formule, quiz e conto alla rovescia"],
"life_travel_eu_danube":["Il Danubio in bici","Stile ciclocomputer: percorso sul cellulare, file GPX passo a passo, barre impilate, borraccia 3D con Trasforma, formule e rettangoli"],
"life_travel_eu_fjords":["Fiordi norvegesi via acqua","Paesaggio a strati con riflessi, nave che naviga, sezione del fiordo che si disegna, barre, radar, tappe una a una e voto multiplo"],
"life_travel_eu_greece":["Isole greche in traghetto","Villaggio bianco di forme, greca, rotta che si disegna, orari con formule, bolle, occhiali 3D con Trasforma e tramonto"],
"life_travel_eu_iceland":["Islanda: la Ring Road in auto","Aurore in sfumatura, mappa con percorso sonoro, auto 3D, cifre con rullo, equazione del freddo, volpe che cammina e quiz"],
"life_travel_eu_lisbon":["Lisbona: colline e tram","Azulejos in SVG, tram che sale sulle colline lungo un percorso sonoro, profilo altimetrico, carte che girano, tabella con formule e lacune"],
"life_travel_eu_prague":["Praga, la città dalle cento torri","Orologio astronomico di forme che gira e viaggia con Trasforma, sfilata con campanello, conto alla rovescia, mappa da etichettare e tabella"],
"life_travel_eu_scotland":["Scozia: le Highlands in auto","Tartan tessuto di forme, strada che si disegna, auto che si danno la precedenza, castelli che girano, lanterna 3D, barre e domande"],
"life_wedding":["Invito di nozze","Tipografia classica e oro: Text Art, testo curvo, cronologia della coppia, mappa con percorso animato, sondaggio e conto alla rovescia"],
"prod_app_bank":["Cartilla: banca per anziani","Libretto di risparmio in pelle e oro: Text Art oro, Trasforma per avvicinare il telefono, tabella con SOMMA, cascata, timbro e quiz antifrode"],
"prod_app_gym":["Serie: prenotazioni nella tua palestra","Tabellone LED: guerriero 3D che esulta e cammina fino alla lezione, due conti alla rovescia, affluenza per ora, tariffe con formule e quiz"],
"prod_app_health":["Turno: appuntamenti al centro di salute","Clinico: battito che si disegna, prima e dopo, ciclo uno alla volta, paziente 3D che cammina, agenda su monitor, barre e domande"],
"prod_app_language":["Vocablo: app per imparare le lingue","Cartolina via aerea: francobolli, fumetti che saltano con suono, carte che girano, Trasforma, equazione dell'oblio, grafico e abbinamento"],
"prod_app_market":["Plaza: il mercato di quartiere a casa","Tendone e lavagne: furgone 3D che percorre la mappa, banchi in radiale, telefono, rettangoli, commissioni con formule e votazione"],
"prod_app_meditation":["Marea: app di meditazione e sonno","Mare notturno: luna con testo curvo, Trasforma del telefono, respirazione guidata ad anelli concatenati, conto alla rovescia, grafico e lanterna 3D"],
"prod_app_music":["Garaje: musica dal vivo del quartiere","Vinile e neon: disco che viaggia con Trasforma, testo curvo che gira, equalizzatore con rullo di tamburi, portatile, radar, torta e nuvola di parole"],
"prod_app_photo":["Grano: fotografia a pellicola","Camera oscura: striscia di pellicola, foto che si sviluppa con Trasforma, contatore con rullo, istogramma, tablet, tabella ed etichettare"],
"prod_app_recipes":["Sobras: ricette con quello che c'è","Frigo con post-it: avocado 3D con Trasforma, telefono che riconosce gli ingredienti, passi, ciambella, ricetta con formule e conto alla rovescia"],
"prod_app_transit":["Andén: trasporto urbano","Segnaletica della metro: tabellone partenze con conto alla rovescia, mappa che si disegna da sola, viaggio animato, telefono, barre impilate e tariffe"],
"prod_hw_drone":["Cernícalo: drone per il soccorso in montagna","Mappa topografica: volo che si disegna mentre il drone lo percorre, elicottero 3D della NASA, vista termica, conto alla rovescia, formule e quiz"],
"prod_hw_ereader":["Folio: lettore a inchiostro elettronico","Libro con voltapagina: capolettera, lettore disegnato, microcapsule che compaiono, cifra e barre, citazione, tabella con formule e completamento"],
"prod_hw_glasses":["Horizonte: occhiali con dati per ciclisti","La strada attraverso la lente: occhiali 3D con Trasformazione, parti numerate con suono, barre, codice YAML passo per passo, radiale e votazione"],
"prod_hw_headphones":["Silencio: cuffie con cancellazione del rumore","Camera anecoica: onde che si disegnano e si annullano, equazione, processo passo per passo, curva per frequenze, tabella con formule e votazione"],
"prod_hw_keyboard":["Tecla: tastiera meccanica modulare","Tasti che saltano con suono di clic, curve di forza, esploso a strati, mappa dei tasti in codice, preventivo con formule e ordinare"],
"prod_hw_lamp":["Alba: lampada sveglia","Alba in sfumatura: il sole sale con Trasformazione, lampada 3D che viaggia, cronologia, curva della luce con equazione, scala Kelvin e valutazione"],
"prod_hw_thermostat":["Templa: termostato intelligente","Quadrante del termostato e casa in sezione con temperature che compaiono, cascata del risparmio, equazioni, linee di 24 ore, matrice e votazione"],
"prod_hw_toycar":["Chispa: auto per imparare a programmare","Tappeto da gioco: auto 3D con Trasformazione, carte che saltano con suono, tabellone percorso, codice, quiz, scala e ciambella"],
"prod_hw_tracker":["Miga: localizzatore per non perdere nulla","Mappa del tesoro: briciole che compaiono una a una fino alla X, cerchio a mano che si disegna, ciambella, bersaglio, traccia nel quartiere e nuvola di parole"],
"prod_hw_trailcam":["Vigía: fototrappola","Mirino a infrarossi: volpe 3D che passa e fa scattare la fotocamera, portata del sensore disegnata, cifre, aree per ora, tabella con SOMMA e abbinamento"],
"product_app":["Presentazione di app mobile","App su telefono, tablet e portatile, Trasforma, percorso a frecce, cifre, grafico di fidelizzazione e nuvola di parole"],
"product_car":["Presentazione: auto elettrica","Auto 3D senza bordi tagliati che fa il giro all’ingresso, Trasforma, cifre, grafici ad area e a barre, tabella e votazione"],
"product_eco":["Sostenibilità del prodotto","Verde eco: pianta 3D con Trasforma, ciclo di vita, cascata dell’impronta, barre dei materiali, linee con obiettivo e completa gli spazi"],
"product_furniture":["Collezione di mobili","Stile editoriale: divani e sedie 3D, Trasforma con viste diverse, oscillazione e giro, campioni di colore, tablet e preventivo"],
"product_keynote":["Keynote hardware","Stile bianco premium: lampada iridescente e bottiglia 3D, Trasforma con etichette, fluttuare e avvicinare, cifre, tabella e prezzi"],
"product_roadmap":["Roadmap di prodotto","Strada che si disegna da sola, piramide, cronologia uno alla volta, ora e poi, matrice, barre impilate, voto multiplo e da ordinare"],
"product_robot":["Robot assistente industriale","Stile industriale: robot 3D che saluta, segue un percorso, concatena animazioni e balla; organigramma, ciclo, grafico e quiz"],
"product_saas":["Demo di piattaforma SaaS","Dashboard in finestra del browser con richiami numerati, radiale, imbuto, indicatori, barre impilate, codice per passi e domande"],
"product_security":["Sicurezza del prodotto","Neon verde: bersaglio a strati, flusso con connettori che appare passo dopo passo, codice evidenziato, grafico, scala e attività di abbinamento"],
"product_watch":["Lancio: smartwatch","Nero e oro: orologio 3D che attraversa tre diapositive con Trasforma e arrivi diversi, Text Art oro, radar e prezzi"],
"sci_ai":["Intelligenza artificiale","Neon viola: robot 3D che saluta e viaggia con Trasformazione, cronologia, organigramma, rete neurale che si accende, grafico e nuvola di parole"],
"sci_astro_blackholes":["Buchi neri","Nero assoluto: orizzonte che viaggia con Trasformazione, testo curvo, cifra gigante, tabella con formule, astronauta 3D a spirale e quiz"],
"sci_astro_cosmology":["Dal Big Bang a oggi","Un universo che si raffredda: termometro con Trasformazione, cronologia in catena, fondo cosmico, dispersione, ciambella e calendario con formule"],
"sci_astro_defense":["Difesa planetaria: esercitazione","Sala di crisi: strisce di pericolo, asteroide 3D, scala di Torino in catena, deviazione animata con suono, conto alla rovescia e voto a squadre"],
"sci_astro_exoplanets":["Cercasi altri mondi","Manifesti di viaggio retrò: transito con la curva di luce disegnata, codice Python, oscillazione con traiettorie, area, satellite 3D e votazione"],
"sci_astro_moon":["Selenografia: la Luna","Atlante antico in seppia: Luna incisa in SVG, fasi in catena, rotazione sincrona, maree, modulo lunare 3D con Trasformazione e abbinare"],
"sci_astro_pulsars":["Pulsar: i fari del cosmo","Schermo di oscilloscopio: segnale che si traccia da solo, faro che gira, impulsi che suonano, radiotelescopio e nebulosa 3D, tabella e quiz"],
"sci_astro_skywatch":["Guida per osservare il cielo","Modalità luce rossa: planisfero con testo curvo, conto alla rovescia, costellazioni che si tracciano da sole, magnitudini, barre, tabella e votazione"],
"sci_astro_stars":["Vita e morte delle stelle","Spettro stellare: classi in catena, equilibrio con frecce, diagramma H-R originale, biforcazione per massa, tabella con formule e supernova 3D"],
"sci_astro_sun":["Il Sole, una stella da vicino","Filtro solare cremisi: strati in catena, fusione con equazione, il viaggio di un fotone, ciclo delle macchie, sonda 3D con Trasformazione e quiz"],
"sci_astro_telescopes":["Telescopi: il progetto","Stile progetto tecnico: raggi che si disegnano, Webb 3D con Trasformazione nello spettro, specchio esagonale in catena, viaggio a L2 ed etichettare"],
"sci_brain":["Neuroscienze: il cervello","Stile scuro con bagliori: neurone disegnato con impulso animato, figura 3D che cammina, radiale, organigramma, barre ed etichettare un'immagine"],
"sci_chem":["Chimica: la tavola periodica","Laboratorio pulito: tavola periodica che si compone a cascata, molecole con forme, braciere 3D, equazioni, ciambella e abbinamento"],
"sci_climate":["Il cambiamento climatico in dati","Strisce del riscaldamento, grafici a linee, area e rettangoli, effetto serra che si disegna, satellite 3D, ciclo e voto a scelta multipla"],
"sci_mars":["Missione su Marte","Stile spaziale ruggine: rover 3D della NASA con Trasformazione, astronauta fluttuante, orbita animata, equazione e quiz"],
"sci_med_case":["Caso clinico: febbre e tosse","Stile cartella clinica: cartellina, timbro, radiografia sul diafanoscopio con cerchio che si disegna, CURB-65 con formula, sondaggio e domande"],
"sci_med_ecg":["Cardiologia: leggere un ECG","Carta da ECG: tracciati che si disegnano da soli, impulso che percorre il cuore, tabella con formule, equazione, quiz e conto alla rovescia"],
"sci_med_glucose":["Endocrinologia: glucosio e insulina","Stile app per sensore di glucosio: telefono con lo schermo, ciclo uno alla volta, curve, ciambella, tabella con formule, equazione, avocado 3D e sondaggio"],
"sci_med_immune":["Immunologia: la risposta immunitaria","Microscopio a fluorescenza: cellule che si accendono, anticorpo disegnato, fagocitosi con Trasforma, organigramma e abbinamenti"],
"sci_med_kidney":["Fisiologia renale: il nefrone","Disegno tecnico: nefrone che si disegna, goccia che lo percorre con suono, quote, cascata, equazione, tabella con formule, bottiglia 3D e ciclo"],
"sci_med_knee":["Anatomia: il ginocchio","Stile tavola anatomica antica: testo curvo, incisione seppia, Trasforma verso i menischi, matrice, tabella, figura 3D che cammina ed etichette"],
"sci_med_micro":["Microbiologia: resistenza agli antibiotici","Piastre di Petri: colonie che spuntano con suono, crescita esponenziale, selezione raccontata con Trasforma, antibiogramma, radiale e nuvola di parole"],
"sci_med_pk":["Farmacocinetica: l'emivita","Stile scatola di farmaco: blister che si riempie, LADME uno alla volta, curve a due serie, equazioni, tabella con formule, codice e completamento"],
"sci_med_stroke":["Neurologia: codice ictus","Corsa contro il tempo in urgenza: luci di sirena, cifra gigante con rullo di tamburi, BE-FAST in sequenza, ciambella, frecce, ordinare i passi e conto alla rovescia"],
"sci_med_trial":["Studio clinico: leggere i risultati","Stile rivista scientifica: CONSORT con connettori, curve di sopravvivenza, tabella con formule, NNT, forest plot in sequenza e quiz"],
"sci_newton":["Fisica: le leggi di Newton","Quaderno di fisica: equazioni, auto 3D in movimento, moto parabolico che si disegna, tabella con formule e completamento"],
"sci_nurse_cpr":["RCP di base: supporto vitale","Segnaletica verde di emergenza: mani che comprimono a ritmo, piastre del DAE che volano con suono, due serie, conto alla rovescia e ordinare"],
"sci_nurse_drip":["Fluidoterapia: calcolare il gocciolamento","Deflussore disegnato con gocce che cadono con suono, formula passo passo, esempio svolto, tabella che calcola, pompa e conto alla rovescia"],
"sci_nurse_falls":["Cadute negli anziani: la casa sicura","Casa di notte con lampada 3D: pianta con pericoli risolti con Trasforma, test del cammino con figura 3D, Venn, ciambella e conto alla rovescia"],
"sci_nurse_hands":["Igiene delle mani: i 5 momenti","Piastrelle e bolle: bolle che salgono, i 5 momenti su una pianta, lampada UV con suono, conto alla rovescia di 30 s, barre e quiz"],
"sci_nurse_heat":["Ondata di calore: piano sanitario","Colori di allerta: termometro che sale, Text Art, mappa delle allerte disegnata, dispersione, cellulare con l'SMS, bottiglia 3D, tabella e quiz"],
"sci_nurse_herd":["Vaccini: l'immunità di gregge","Libretto vaccinale con timbri e testo curvo, contagio a catena interrotto con Trasforma, equazione, tabella con formule, miti barrati"],
"sci_nurse_outbreak":["Indagare un focolaio alimentare","Bacheca di sughero: note con puntine e filo rosso che si disegna, curva epidemica, tabella con formule, rischio relativo, codice e votazione"],
"sci_nurse_pressure":["Lesioni da pressione: prevenire","Mappa di pressione termica: macchie che si accendono e si spengono, Braden con formule, orologio dei cambi che gira, strati della pelle ed etichettare"],
"sci_nurse_sbar":["Il passaggio di consegne con SBAR","Lavagna bianca di reparto: pennarello che sottolinea da solo, magneti e note che si attaccano con suono, dialogo a catena, scala con formula e abbinare"],
"sci_nurse_smoking":["Smettere di fumare: cosa guadagna il tuo corpo","Dal fumo all'aria pulita: fumo che sale, sigaretta come linea del tempo, polmoni che cambiano con Trasforma, tabella del risparmio e respirazione"],
"sci_python":["Programmare in Python","Stile editor scuro: terminale che si scrive da solo, codice con passi di evidenziazione, output animato, ordinare righe e sfida a tempo"],
"sci_solar":["Il sistema solare","Pianeti in scala che appaiono in sequenza, tre sonde 3D con viste e movimenti diversi, tabella, diagramma radiale e abbinamento"],
"sci_stats":["Statistica e probabilità","Stile editoriale: campana che si disegna, formule, istogramma, dispersione, area, barre e bolle, e domanda a punti"],
"sci_thesis":["Discussione della tesi di laurea","Accademico sobrio: copertina istituzionale, indice, metodologia con equazione, tabella con totali, risultati in grafici, bibliografia e domande"],
"show_anim_bike":["I rapporti della bici, senza misteri","Movimenti sincronizzati: ingranaggi che girano al loro rapporto reale, ruote che percorrono la loro distanza, due corsie insieme e tabella"],
"show_anim_blueprint":["Ristrutturazione di un appartamento: la pianta","Una pianta che si disegna da sola: muri in catena, quote, demolizione che scompare, Trasforma verso la nuova distribuzione, impianti e cantiere"],
"show_anim_ferries":["Traghetti tra le isole: rotte estive","Traiettorie su una mappa: navi che girano con il percorso, rotte che si disegnano al loro passaggio, tre linee insieme, scalo e orari"],
"show_anim_firefly":["Fiaba: la lucciola senza luce","Una fiaba con entrate e uscite: narrazione visibile solo nel suo passo, dialoghi che appaiono e se ne vanno, voli e luce che ritorna"],
"show_anim_foosball":["Torneo di calciobalilla in ufficio","Animazioni concatenate con suoni come un gioco: passaggi con clic, tiro, gol con applausi, tabellone che avanza, classifica e pronostici"],
"show_anim_guitar":["Anatomia della chitarra spagnola","Trigger: clic su ogni parte della chitarra per vederne la scheda e su ogni corda per farla vibrare; rosetta che gira"],
"show_anim_haiku":["Laboratorio di haiku: parola per parola","Animazione per parole e paragrafi: versi parola per parola, consegna frase per frase, sillabe contate e Trasforma"],
"show_anim_rpg":["Gioco di ruolo da tavolo: la tua prima partita","Personaggi 3D con le loro animazioni: attaccare, parare, lanciare incantesimi e cadere; camminare fino al rivale, dado che rotola e vita che scende"],
"show_anim_speech":["Discorso: salviamo la biblioteca","Enfasi al ritmo di un discorso: frase in primo piano e il resto attenuato, barrare, evidenziare, sottolineatura e cerchio a mano, conto alla rovescia"],
"show_anim_tshirt":["Infografica: il viaggio di una maglietta","Infografica che si rivela: percorso che si disegna con le sue tappe a tempo, pittogramma di gocce che si riempie, cascata, cifre e formula"],
"showcase_3d":["Catalogo: il 3D a fondo","Modelli 3D con tutte le opzioni: viste, movimenti in entrata, rotazione, bordi, margine, clip, camminata e arrivo con Trasformazione"],
"showcase_animations":["Catalogo: animazioni","Tutte le animazioni degli oggetti: entrata, enfasi, uscita, percorsi, disegno, concatenate, suoni e più su un oggetto"],
"showcase_charts":["Catalogo: grafici","I 15 tipi di grafico, due per diapositiva, con serie, combinato, griglia, etichette e titoli degli assi, e la tabella delle opzioni"],
"showcase_diagrams":["Catalogo: diagrammi","I 15 layout di diagramma scritti come schema, i 4 schemi di colore e la comparsa uno a uno durante la presentazione"],
"showcase_morph":["Catalogo: Trasformazione","Trasformazione passo passo: testo che cambia dimensione e posto, forme, barre che crescono, immagine, 3D e lettere che si riordinano"],
"showcase_objects":["Catalogo: multimedia e oggetti","Codice a passi, equazioni, icone, cinque dispositivi, tabelle con stili e formule, zoom di diapositiva e connettori"],
"showcase_polls":["Catalogo: sondaggi e attività","Gli 11 tipi di sondaggio e attività dal cellulare, conto alla rovescia nei suoi tre stili, classifica e modalità aula"],
"showcase_shapes":["Catalogo: forme","Tutte le forme per categoria con il loro nome, linee e tratteggi, sfumature, opacità, tratto a mano, ombre, testo dentro e rotazione"],
"showcase_text":["Catalogo: Text Art e tipografia","I 10 stili di Text Art, testo curvo, colonne, cinque livelli di elenco, le 8 coppie di caratteri, allineamento e spaziatura"],
"showcase_transitions":["Catalogo: transizioni","Le 22 transizioni di diapositiva, una per una: entrata, uscita diversa, direzioni, velocità e avanzamento automatico"]};
