// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Risultati trimestrali al consiglio","Blu scuro e oro: grandi indicatori animati con suono, cascata, imbuto, barre impilate e tabella con formule rispetto al budget"],
"biz_climate":["Sondaggio sul clima aziendale","Viola e partecipativo: conto alla rovescia, barre al 100 %, valutazione da 1 a 5, nuvola di parole, scelta multipla e domande del pubblico"],
"biz_investment":["Presentazione per investitori","Nero e oro: prodotto 3D che ruota e viaggia con Trasforma, cifre giganti, mercato in cerchi, trazione, uso dei fondi e team"],
"biz_marketing":["Piano di marketing della campagna","Stile caldo: testo in cerchio, pubblico target, imbuto, mix di canali, calendario in tabella, budget con formula e votazione"],
"biz_onboarding":["Benvenuto ai nuovi dipendenti","Stile amichevole: robot 3D che saluta e percorre la settimana camminando, organigramma uno alla volta, valori con icone e attività di abbinamento"],
"biz_proposal":["Proposta commerciale a un cliente","Stile carta: sigillo, processo uno alla volta, mockup su portatile e cellulare, prezzi, preventivo con IVA in formule, cronologia e garanzie"],
"biz_roadmap":["Roadmap di un progetto","Stile tecnico scuro: frecce una alla volta, diagramma di Gantt animato, cronologia, auto 3D che avanza con Trasforma e tabella di stato"],
"biz_sales":["Vendite e previsione annuale","Minimalista in grigio: barre e linee combinate, scenari, formula di previsione, tabella con formule, barre impilate e orizzontali"],
"biz_strategy":["Piano strategico e OKR","Stile bianco pulito: cifre che entrano in sequenza, piramide, priorità con icone, tabella degli OKR, barre di avanzamento, radar e frecce"],
"biz_swot":["Analisi SWOT e concorrenza","Sfondo grafite: SWOT per quadranti, matrice delle strategie, mappa di posizionamento, barre raggruppate, Venn, torta e votazione a scelta multipla"],
"creative_bauhaus":["Bauhaus: forma e funzione","Arte geometrica Bauhaus: forme primarie che girano e rimbalzano, cronologia, griglia con Trasforma e attività di abbinamento"],
"creative_brutalism":["Brutalismo: manifesto web","Stile brutalista: tipografia gigante, blocchi neri, testo verticale, ombre nette, barrato animato, tabella e sondaggio"],
"creative_comic":["Fumetto: superpoteri animali","Stile fumetto: vignette, nuvolette di dialogo e pensiero, onomatopee in Text Art che rimbalzano, volpe 3D, grafico e quiz"],
"creative_fashion":["Rivista di moda: autunno lento","Stile rivista: testata con grazie, orologio 3D in copertina, colonne con capolettera, citazione grande, palette di stagione e grafico"],
"creative_glass":["Glassmorphism: app di finanza","Schede traslucide su bagliori colorati, app nel cellulare, grafico ad anello, scheda con Trasforma e sondaggio di valutazione"],
"creative_pixel":["Pixel art: il tuo primo videogioco","Stile videogioco retrò: sprite in pixel, segnapunti, personaggi 3D che camminano e saltano, codice passo passo, quiz e conto alla rovescia"],
"creative_space":["Galassia: guardare il passato","Stile spaziale: stelle, nebulose luminose, modelli 3D della NASA, sonda che percorre i pianeti, testo curvo e quiz"],
"creative_synthwave":["Synthwave: festival Neón 86","Stile retrò anni 80: sole sfumato, griglia che si disegna, neon luminoso, Trasforma, robot 3D che balla e nuvola di parole"],
"creative_watercolor":["Acquerello: orto sul balcone","Stile acquerello e carta: macchie con sfumatura radiale, forme a mano libera, scrittura a mano, disegno che si traccia da solo e 3D"],
"creative_zen":["Minimalismo giapponese: il tè","Minimalismo giapponese: tanto bianco, sole rosso che si trasforma, testo verticale, ensō che si dipinge da solo e conto alla rovescia"],
"data_ab_test":["Esperimento A/B","Equazioni, dispersione a due serie, colonne con etichette, tabella di conversione con formule e cifre di significatività"],
"data_energy":["Energia e consumi","Aree in pila per ora, linee a tre serie, treemap, colonne con etichette e tabella delle tariffe calcolata"],
"data_exec_panel":["Cruscotto direzionale mensile","KPI con semafori e minigrafici, combinato rispetto al budget, piccoli multipli, ciambella e sondaggio"],
"data_home_finance":["Finanze personali","Cascata dallo stipendio al risparmio, grafico a torta, linee e area, tabelle con SOMMA, MEDIA, MAX e MIN"],
"data_market_study":["Ricerca di mercato","Cifre grandi, treemap, bolle, dispersione, barre orizzontali a due serie e matrice 2 × 2"],
"data_population":["Popolazione e demografia","Piramide della popolazione, istogramma, barre orizzontali, linee che si incrociano e tabella di indicatori con formule"],
"data_sales_regions":["Vendite per regione","Barre raggruppate, in pila e al 100 %, grafico combinato con obiettivo, tabella con totali da formula e KPI animati"],
"data_satisfaction":["Sondaggio di soddisfazione","Ciambella con legenda, radar a confronto, colonne con etichette, NPS, valutazione e nuvola di parole dal vivo"],
"data_season_stats":["La stagione in cifre","Cifre giganti con suono, classifica con formule, barre negative, linee, barre in pila e radar della squadra"],
"data_web_metrics":["Metriche web e marketing","KPI con minigrafici, linee a quattro serie, aree, imbuto di conversione, grafico combinato e tabella con formule"],
"edu_body":["Il corpo umano","Stile laboratorio: figura 3D con Trasforma, personaggio che cammina lungo un percorso, grafico a barre, etichettare il corpo e quiz"],
"edu_cell":["La cellula","Cellula disegnata con forme, parti una alla volta, Trasforma per avvicinarsi, abbinare coppie, diagramma, pianta 3D e valutazione"],
"edu_english":["Inglese per principianti","Modalità classe: schede che si girano con suono, robot 3D che cammina e saluta, volpe 3D, tre domande a punti, classifica e applausi"],
"edu_fractions":["Le frazioni","Stile neon: pizze disegnate, equazioni passo passo, somma con Trasforma, completare gli spazi, quiz e sfida con conto alla rovescia"],
"edu_quixote":["Don Chisciotte","Stile inchiostro e carta: mulino che gira con suono, testo curvo, citazioni animate, Trasforma, cronologia, completare gli spazi e quiz"],
"edu_renewables":["Energie rinnovabili","Turbina eolica che gira, schede, grafici ad area, ad anello e a barre raggruppate, nuvola di parole in diretta, sondaggio e conto alla rovescia"],
"edu_revolution":["La Rivoluzione francese","Stile carta antica: testo in cerchio, Trasforma, piramide sociale, cronologia animata con suono, ordinare i fatti e sondaggio"],
"edu_spain":["Geografia della Spagna","Stile atlante: rosa dei venti, rilievo a bersaglio, tabella dei fiumi con formule, grafici di vette e piogge, abbinare coppie e quiz"],
"edu_volcanoes":["I vulcani","Stile fuoco: eruzione animata con suono, parti del vulcano da etichettare, tabella, quiz a tempo e conto alla rovescia"],
"edu_water":["Il ciclo dell'acqua","Diagramma a ciclo uno alla volta, paesaggio con gocce che salgono e pioggia animata con suono, grafici ad anello, abbinare coppie e satellite 3D"],
"life_bookclub":["Club del libro","Libreria a mano libera, copertina fatta di forme, citazioni che si trasformano, diagramma radiale, voto e scelta del prossimo libro"],
"life_cv":["Curriculum visivo","Testo in cerchio, cifre, cronologia passo passo, barre delle competenze animate, radar, schermate nei dispositivi e contatti"],
"life_fitness":["Piano di allenamento: 5 km","Corridore 3D, Text Art fuoco, fasi con sfumature, settimana con formule, grafici dei progressi, piramide, conto alla rovescia e nuvola di parole"],
"life_garden":["Orto urbano","Pianta 3D con Trasforma, calendario di semina in tabella a colori, ciclo, Venn, grafici di irrigazione e crescita, attività di etichettatura"],
"life_graduation":["Diploma e fine anno","Text Art oro, tocchi fatti di forme, polaroid che ruotano all'ingresso, cifre con rullo di tamburi, ringraziamenti, nuvola di parole e applausi"],
"life_italy":["Viaggio in Italia","Testo in cerchio, itinerario con connettori e percorso animato, cronologia, budget con formule, grafici e attività di abbinamento"],
"life_kids_party":["Compleanno per bambini","Colori vivaci: robot 3D che balla, personaggi che festeggiano, palloncini a mano libera, quiz a punti e conto alla rovescia"],
"life_moving":["Trasloco e nuova casa","Casa con forme a mano libera, cronologia, elenco che si barra, mobili 3D che passano alla pianta con Trasforma, budget e attività di ordinamento"],
"life_recipe":["Ricetta: guacamole","Avocado 3D che viaggia tra le diapositive (Trasforma), ingredienti con formule, passaggi uno alla volta, conto alla rovescia e voto"],
"life_wedding":["Invito di nozze","Tipografia classica e oro: Text Art, testo curvo, cronologia della coppia, mappa con percorso animato, sondaggio e conto alla rovescia"],
"product_app":["Presentazione di app mobile","App su telefono, tablet e portatile, Trasforma, percorso a frecce, cifre, grafico di fidelizzazione e nuvola di parole"],
"product_car":["Presentazione: auto elettrica","Auto 3D senza bordi tagliati che fa il giro all’ingresso, Trasforma, cifre, grafici ad area e a barre, tabella e votazione"],
"product_eco":["Sostenibilità del prodotto","Verde eco: pianta 3D con Trasforma, ciclo di vita, cascata dell’impronta, barre dei materiali, linee con obiettivo e completa gli spazi"],
"product_furniture":["Collezione di mobili","Stile editoriale: divani e sedie 3D, Trasforma con viste diverse, oscillazione e giro, campioni di colore, tablet e preventivo"],
"product_keynote":["Keynote hardware","Stile bianco premium: lampada iridescente e bottiglia 3D, Trasforma con etichette, fluttuare e avvicinare, cifre, tabella e prezzi"],
"product_roadmap":["Roadmap di prodotto","Strada che si disegna da sola, piramide, cronologia uno alla volta, ora e poi, matrice, barre impilate, voto multiplo e da ordinare"],
"product_robot":["Robot assistente industriale","Stile industriale: robot 3D che saluta, segue un percorso, concatena animazioni e balla; organigramma, ciclo, grafico e quiz"],
"product_saas":["Demo di piattaforma SaaS","Dashboard in finestra del browser con richiami numerati, radiale, imbuto, indicatori, barre impilate, codice per passi e domande"],
"product_security":["Sicurezza del prodotto","Neon verde: bersaglio a strati, flusso con connettori che appare passo dopo passo, codice evidenziato, grafico, scala e attività di abbinamento"],
"product_watch":["Lancio: smartwatch","Nero e oro: orologio 3D che attraversa tre diapositive con Trasforma e arrivi diversi, Text Art oro, radar e prezzi"],
"sci_ai":["Intelligenza artificiale","Neon viola: robot 3D che saluta e viaggia con Trasformazione, cronologia, organigramma, rete neurale che si accende, grafico e nuvola di parole"],
"sci_brain":["Neuroscienze: il cervello","Stile scuro con bagliori: neurone disegnato con impulso animato, figura 3D che cammina, radiale, organigramma, barre ed etichettare un'immagine"],
"sci_chem":["Chimica: la tavola periodica","Laboratorio pulito: tavola periodica che si compone a cascata, molecole con forme, braciere 3D, equazioni, ciambella e abbinamento"],
"sci_climate":["Il cambiamento climatico in dati","Strisce del riscaldamento, grafici a linee, area e rettangoli, effetto serra che si disegna, satellite 3D, ciclo e voto a scelta multipla"],
"sci_mars":["Missione su Marte","Stile spaziale ruggine: rover 3D della NASA con Trasformazione, astronauta fluttuante, orbita animata, equazione e quiz"],
"sci_newton":["Fisica: le leggi di Newton","Quaderno di fisica: equazioni, auto 3D in movimento, moto parabolico che si disegna, tabella con formule e completamento"],
"sci_python":["Programmare in Python","Stile editor scuro: terminale che si scrive da solo, codice con passi di evidenziazione, output animato, ordinare righe e sfida a tempo"],
"sci_solar":["Il sistema solare","Pianeti in scala che appaiono in sequenza, tre sonde 3D con viste e movimenti diversi, tabella, diagramma radiale e abbinamento"],
"sci_stats":["Statistica e probabilità","Stile editoriale: campana che si disegna, formule, istogramma, dispersione, area, barre e bolle, e domanda a punti"],
"sci_thesis":["Discussione della tesi di laurea","Accademico sobrio: copertina istituzionale, indice, metodologia con equazione, tabella con totali, risultati in grafici, bibliografia e domande"]};
