// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Risultati trimestrali al consiglio","Blu scuro e oro: grandi indicatori animati con suono, cascata, imbuto, barre impilate e tabella con formule rispetto al budget"],
"biz_climate":["Sondaggio sul clima aziendale","Viola e partecipativo: conto alla rovescia, barre al 100 %, valutazione da 1 a 5, nuvola di parole, scelta multipla e domande del pubblico"],
"biz_investment":["Presentazione per investitori","Nero e oro: prodotto 3D che ruota e viaggia con Trasforma, cifre giganti, mercato in cerchi, trazione, uso dei fondi e team"],
"biz_marketing":["Piano di marketing della campagna","Stile caldo: testo in cerchio, pubblico target, imbuto, mix di canali, calendario in tabella, budget con formula e votazione"],
"biz_onboarding":["Benvenuto ai nuovi dipendenti","Stile amichevole: robot 3D che saluta e percorre la settimana camminando, organigramma uno alla volta, valori con icone e attività di abbinamento"],
"biz_proposal":["Proposta commerciale a un cliente","Stile carta: sigillo, processo uno alla volta, mockup su portatile e cellulare, prezzi, preventivo con IVA in formule, cronologia e garanzie"],
"biz_roadmap":["Roadmap di un progetto","Stile tecnico scuro: frecce una alla volta, diagramma di Gantt animato, cronologia, auto 3D che avanza con Trasforma e tabella di stato"],
"biz_sales":["Vendite e previsione annuale","Minimalista in grigio: barre e linee combinate, scenari, formula di previsione, tabella con formule, barre impilate e orizzontali"],
"biz_startup_agrotech":["Pitch agritech: irrigazione con sensori","Vista aerea di campi con mappa dell’umidità, satellite 3D della NASA, telefono, gocce in sequenza con suono, tabella con formule e treemap"],
"biz_startup_edtech":["Pitch edtech: tutor di matematica","Quaderno a quadretti: post-it in sequenza, scrittura a mano, equazioni passo passo, telefono, quiz dal vivo, ciclo e grafici"],
"biz_startup_energy":["Pitch energia: comunità solare","Tetti dall’alba alla notte: sole che sorge e attraversa il cielo ad arco, diagramma radiale, aree orarie, equazione e tabella con formule"],
"biz_startup_fashion":["Pitch moda circolare: Retal","Etichetta d’abito che viaggia con Trasformazione, cuciture tratteggiate, vita di un capo in sequenza, ciclo, anello, radar e voto multiplo"],
"biz_startup_insurance":["Pitch assicurazioni: copertura a giornata","Pioggia grigia e ombrello giallo: pittogramma in sequenza, app con interruttore, equazione del prezzo, tabella con formule, cronologia e voto"],
"biz_startup_kitchen":["Pitch robotica da cucina: Fogón","Cucina professionale: comande sulla barra, Text Art di fuoco, robot 3D che entra camminando e saluta, ricetta in codice, conto alla rovescia e imbuto"],
"biz_startup_lastmile":["Pitch logistica: ultimo miglio","Stile mappa della metro: linee che si disegnano da sole, camion 3D e bici che percorrono la mappa, tabella con formule, area e cascata"],
"biz_startup_mental":["Pitch salute mentale: Remanso","Notte calma: anelli che respirano, minuto di respiro con conto alla rovescia, app sul telefono, scala, valutazione e tabella con formule"],
"biz_startup_pets":["Pitch animali: cibo fresco","Stile adesivo con impronte che appaiono in sequenza, volpe 3D che attraversa camminando, formula della razione in tabella, anello e quiz"],
"biz_startup_rural":["Pitch turismo rurale: Alpende","Montagne al tramonto e cartoline: lanterna 3D, timbro con testo curvo, mappa con auto 3D lungo il percorso, barre, torta e nuvola di parole"],
"biz_strategy":["Piano strategico e OKR","Stile bianco pulito: cifre che entrano in sequenza, piramide, priorità con icone, tabella degli OKR, barre di avanzamento, radar e frecce"],
"biz_swot":["Analisi SWOT e concorrenza","Sfondo grafite: SWOT per quadranti, matrice delle strategie, mappa di posizionamento, barre raggruppate, Venn, torta e votazione a scelta multipla"],
"creative_bauhaus":["Bauhaus: forma e funzione","Arte geometrica Bauhaus: forme primarie che girano e rimbalzano, cronologia, griglia con Trasforma e attività di abbinamento"],
"creative_brutalism":["Brutalismo: manifesto web","Stile brutalista: tipografia gigante, blocchi neri, testo verticale, ombre nette, barrato animato, tabella e sondaggio"],
"creative_comic":["Fumetto: superpoteri animali","Stile fumetto: vignette, nuvolette di dialogo e pensiero, onomatopee in Text Art che rimbalzano, volpe 3D, grafico e quiz"],
"creative_fashion":["Rivista di moda: autunno lento","Stile rivista: testata con grazie, orologio 3D in copertina, colonne con capolettera, citazione grande, palette di stagione e grafico"],
"creative_glass":["Glassmorphism: app di finanza","Schede traslucide su bagliori colorati, app nel cellulare, grafico ad anello, scheda con Trasforma e sondaggio di valutazione"],
"creative_pixel":["Pixel art: il tuo primo videogioco","Stile videogioco retrò: sprite in pixel, segnapunti, personaggi 3D che camminano e saltano, codice passo passo, quiz e conto alla rovescia"],
"creative_space":["Galassia: guardare il passato","Stile spaziale: stelle, nebulose luminose, modelli 3D della NASA, sonda che percorre i pianeti, testo curvo e quiz"],
"creative_swiss_blood":["Campagna: dona il sangue","Manifesto pubblico bianco e rosso: goccia che riempie lo schermo con Trasforma, processo, sì o aspetta, ciambella, barre, cellulare e quiz"],
"creative_swiss_chairs":["Mostra: la sedia moderna","Manifesto svizzero grigio e lime: sedia 3D che gira e viaggia con Trasforma, cronologia, ciambella, poltrona 3D, tabella con formule e ordinare"],
"creative_swiss_designconf":["Congresso di design: Griglia 27","Grafite e ciano: la griglia si monta da sola e cambia con Trasforma, cifra a contorno, formula, cronologia, codice CSS, nuvola e pausa"],
"creative_swiss_film":["Festival del cinema: il programma","Svizzero in nero e rosso: numero gigante che diventa fascia con Trasforma, sezioni a griglia, tabella, barre, sondaggio e conto alla rovescia"],
"creative_swiss_foundation":["Relazione annuale di una fondazione","Svizzero in bianco e blu cobalto: anno gigante, lettera a piena pagina, cifre a catena, equazione, ciambella, area, frecce e conti con formule"],
"creative_swiss_games":["Giochi scolastici: l'identità visiva","Bianco e magenta, tavolozza propria: pittogrammi SVG, figura 3D che attraversa la città, linee, medagliere con formule, gradini e quiz"],
"creative_swiss_museum":["Guida al museo di storia naturale","Segnaletica svizzera nero e giallo: pianta propria con percorso animato, volpe 3D che cammina, colonne, tabella, etichettare e pittogrammi"],
"creative_swiss_orchestra":["Orchestra sinfonica: stagione 26/27","Blu notte e ambra: archi che girano, testo curvo, cifre su un pentagramma, cicli, tabella, equazione, barre, sondaggio e applausi"],
"creative_swiss_publisher":["Catalogo d'autunno di una casa editrice","Carta crema e verde petrolio: scaffale di dorsi verticali, copertine SVG, tablet, torta, ordine con formule, calendario e lacune"],
"creative_swiss_typeface":["Campionario di un nuovo carattere","Campionario bianco e viola: lettere che viaggiano con Trasforma, anatomia misurata, scala con formula, glifi, radar e licenze"],
"creative_synthwave":["Synthwave: festival Neón 86","Stile retrò anni 80: sole sfumato, griglia che si disegna, neon luminoso, Trasforma, robot 3D che balla e nuvola di parole"],
"creative_watercolor":["Acquerello: orto sul balcone","Stile acquerello e carta: macchie con sfumatura radiale, forme a mano libera, scrittura a mano, disegno che si traccia da solo e 3D"],
"creative_zen":["Minimalismo giapponese: il tè","Minimalismo giapponese: tanto bianco, sole rosso che si trasforma, testo verticale, ensō che si dipinge da solo e conto alla rovescia"],
"data_ab_test":["Esperimento A/B","Equazioni, dispersione a due serie, colonne con etichette, tabella di conversione con formule e cifre di significatività"],
"data_energy":["Energia e consumi","Aree in pila per ora, linee a tre serie, treemap, colonne con etichette e tabella delle tariffe calcolata"],
"data_exec_panel":["Cruscotto direzionale mensile","KPI con semafori e minigrafici, combinato rispetto al budget, piccoli multipli, ciambella e sondaggio"],
"data_home_finance":["Finanze personali","Cascata dallo stipendio al risparmio, grafico a torta, linee e area, tabelle con SOMMA, MEDIA, MAX e MIN"],
"data_market_study":["Ricerca di mercato","Cifre grandi, treemap, bolle, dispersione, barre orizzontali a due serie e matrice 2 × 2"],
"data_population":["Popolazione e demografia","Piramide della popolazione, istogramma, barre orizzontali, linee che si incrociano e tabella di indicatori con formule"],
"data_sales_regions":["Vendite per regione","Barre raggruppate, in pila e al 100 %, grafico combinato con obiettivo, tabella con totali da formula e KPI animati"],
"data_satisfaction":["Sondaggio di soddisfazione","Ciambella con legenda, radar a confronto, colonne con etichette, NPS, valutazione e nuvola di parole dal vivo"],
"data_season_stats":["La stagione in cifre","Cifre giganti con suono, classifica con formule, barre negative, linee, barre in pila e radar della squadra"],
"data_web_metrics":["Metriche web e marketing","KPI con minigrafici, linee a quattro serie, aree, imbuto di conversione, grafico combinato e tabella con formule"],
"edu_body":["Il corpo umano","Stile laboratorio: figura 3D con Trasforma, personaggio che cammina lungo un percorso, grafico a barre, etichettare il corpo e quiz"],
"edu_cell":["La cellula","Cellula disegnata con forme, parti una alla volta, Trasforma per avvicinarsi, abbinare coppie, diagramma, pianta 3D e valutazione"],
"edu_english":["Inglese per principianti","Modalità classe: schede che si girano con suono, robot 3D che cammina e saluta, volpe 3D, tre domande a punti, classifica e applausi"],
"edu_fractions":["Le frazioni","Stile neon: pizze disegnate, equazioni passo passo, somma con Trasforma, completare gli spazi, quiz e sfida con conto alla rovescia"],
"edu_hist_alandalus":["Al-Andalus: scienza e giardini","Arco a ferro di cavallo, cronologia passo passo, barre orizzontali, astrolabio che gira, stella con Morph, abbinare coppie e votazione"],
"edu_hist_castle":["Castelli e feudalesimo","Castello notturno e cavaliere 3D che attraversa il ponte, piramide feudale che si alza, etichettare, sole che percorre il giorno, treemap e stemmi"],
"edu_hist_egypt":["Egitto, dono del Nilo","Lapislazzuli e oro: sole che sorge dietro le piramidi, piena animata, grafico ad aree, equazione, Morph, cartiglio geroglifico e ordinare"],
"edu_hist_greece":["Atene: nasce la democrazia","Stile vaso a figure nere: meandro, testo curvo, Morph, ciambella, tempio che si alza, ostraka con suono, votazione e tabella"],
"edu_hist_maya":["I Maya: tempo e stelle","Giungla e giada: numeri a punti e barre, Morph in base 20, equazione, ruote del calendario che girano, serpente di luce e cacao"],
"edu_hist_mesopotamia":["Mesopotamia: nasce la scrittura","Tavoletta d’argilla che si scrive da sola, mappa con fiumi disegnati, ziggurat che cresce, base 60 con formule, completare e radiale"],
"edu_hist_printing":["La stampa: il libro si moltiplica","Pagina di incunabolo: capolettera rosso, caratteri rovesciati composti con Morph, torchio che scende con suono, cifre, barre e lacune"],
"edu_hist_rome":["Roma, ingegneri dell’impero","Marmo e rosso imperiale: Morph, arco trionfale, strada a strati con soldato 3D che marcia, acquedotto, equazione, formule e quiz"],
"edu_hist_silkroad":["La Via della Seta","Seta e zafferano: carovana in marcia, mappa con rotta tracciata, cascata del prezzo, tabella con formule, lanterna 3D, equazione e ordinare"],
"edu_hist_vikings":["Vichinghi, navigatori del nord","Fiordo sotto l’aurora: nave che dondola, rune, miti barrati con timbro, traversata animata, cifre con suono, guerriero 3D, radar e abbinare"],
"edu_math_coordinates":["Coordinate: la mappa del tesoro","Mappa del tesoro: rosa dei venti con testo curvo, punti che compaiono, pirata 3D che segue gli indizi, barca che si disegna ed etichettatura"],
"edu_math_integers":["Numeri interi: mare e montagna","Dal fondo del mare alla vetta: retta con salti, Text Art ghiaccio, temperature sotto zero, sottomarino che sale e scende, ordinare e quiz"],
"edu_math_primes":["Numeri primi","Terminale verde: neon personalizzato, crivello di Eratostene clic dopo clic con 100 caselle, albero dei fattori, codice passo a passo, quiz e sfida"],
"edu_math_probability":["Probabilità: misurare la fortuna","Tavolo da gioco bordeaux e oro: dadi che rotolano con rullo di tamburi, testo curvo, regola di Laplace, albero uno a uno, barre, linee e quiz"],
"edu_math_proportion":["La proporzionalità al supermercato","Scontrino: timbro che rimbalza, tabella di proporzionalità con formule, proporzione passo a passo, sconti calcolati, linee e completamento"],
"edu_math_pythagoras":["Il teorema di Pitagora","Lavagna: figura che si disegna da sola, dimostrazione senza parole con Trasforma, terne con formule, scorciatoia in 3D e quiz"],
"edu_math_sequences":["Successioni e schemi","Libro di botanica: spirale di Fibonacci che si traccia da sola, sassi in catena, fiammiferi con formule, codice, pianta 3D e numero aureo"],
"edu_math_stats":["Statistica: media, mediana e moda","Quaderno a quadretti: post-it a cascata, frequenze con formule, barre, ciambella con gradi, istogramma e sondaggio dal vivo"],
"edu_math_symmetry":["Simmetria e tassellature","Azulejos nasridi: stella che gira, farfalla che si riflette, traslazione, rotazione e simmetria animate, tabella degli angoli e alveare"],
"edu_math_volumes":["Aree e volumi","Disegno tecnico blu: cartiglio in tabella, sviluppo piano, bottiglia 3D misurata, volumi con formule, barre, coni che riempiono e abbinamento"],
"edu_quixote":["Don Chisciotte","Stile inchiostro e carta: mulino che gira con suono, testo curvo, citazioni animate, Trasforma, cronologia, completare gli spazi e quiz"],
"edu_renewables":["Energie rinnovabili","Turbina eolica che gira, schede, grafici ad area, ad anello e a barre raggruppate, nuvola di parole in diretta, sondaggio e conto alla rovescia"],
"edu_revolution":["La Rivoluzione francese","Stile carta antica: testo in cerchio, Trasforma, piramide sociale, cronologia animata con suono, ordinare i fatti e sondaggio"],
"edu_spain":["Geografia della Spagna","Stile atlante: rosa dei venti, rilievo a bersaglio, tabella dei fiumi con formule, grafici di vette e piogge, abbinare coppie e quiz"],
"edu_volcanoes":["I vulcani","Stile fuoco: eruzione animata con suono, parti del vulcano da etichettare, tabella, quiz a tempo e conto alla rovescia"],
"edu_water":["Il ciclo dell'acqua","Diagramma a ciclo uno alla volta, paesaggio con gocce che salgono e pioggia animata con suono, grafici ad anello, abbinare coppie e satellite 3D"],
"life_bookclub":["Club del libro","Libreria a mano libera, copertina fatta di forme, citazioni che si trasformano, diagramma radiale, voto e scelta del prossimo libro"],
"life_cv":["Curriculum visivo","Testo in cerchio, cifre, cronologia passo passo, barre delle competenze animate, radar, schermate nei dispositivi e contatti"],
"life_fitness":["Piano di allenamento: 5 km","Corridore 3D, Text Art fuoco, fasi con sfumature, settimana con formule, grafici dei progressi, piramide, conto alla rovescia e nuvola di parole"],
"life_garden":["Orto urbano","Pianta 3D con Trasforma, calendario di semina in tabella a colori, ciclo, Venn, grafici di irrigazione e crescita, attività di etichettatura"],
"life_graduation":["Diploma e fine anno","Text Art oro, tocchi fatti di forme, polaroid che ruotano all'ingresso, cifre con rullo di tamburi, ringraziamenti, nuvola di parole e applausi"],
"life_italy":["Viaggio in Italia","Testo in cerchio, itinerario con connettori e percorso animato, cronologia, budget con formule, grafici e attività di abbinamento"],
"life_kids_party":["Compleanno per bambini","Colori vivaci: robot 3D che balla, personaggi che festeggiano, palloncini a mano libera, quiz a punti e conto alla rovescia"],
"life_moving":["Trasloco e nuova casa","Casa con forme a mano libera, cronologia, elenco che si barra, mobili 3D che passano alla pianta con Trasforma, budget e attività di ordinamento"],
"life_recipe":["Ricetta: guacamole","Avocado 3D che viaggia tra le diapositive (Trasforma), ingredienti con formule, passaggi uno alla volta, conto alla rovescia e voto"],
"life_travel_eu_amsterdam":["Amsterdam: canali e bici","Facciate sul canale che si montano in sequenza, canali a bersaglio, bici che passa con suono, tabella con formule, linee e voto a torta"],
"life_travel_eu_camino":["Cammino di Santiago: da Sarria","Credenziale che si riempie di timbri con suono, cascata di chilometri, camminatore 3D, equazione dello zaino, ciambella e tappe da ordinare"],
"life_travel_eu_croatia":["Croazia in barca a vela in Dalmazia","Carta nautica, rosa dei venti che gira e viaggia con Trasforma, bandiere, abbinare, miglia con formule, quiz e conto alla rovescia"],
"life_travel_eu_danube":["Il Danubio in bici","Stile ciclocomputer: percorso sul cellulare, file GPX passo a passo, barre impilate, borraccia 3D con Trasforma, formule e rettangoli"],
"life_travel_eu_fjords":["Fiordi norvegesi via acqua","Paesaggio a strati con riflessi, nave che naviga, sezione del fiordo che si disegna, barre, radar, tappe una a una e voto multiplo"],
"life_travel_eu_greece":["Isole greche in traghetto","Villaggio bianco di forme, greca, rotta che si disegna, orari con formule, bolle, occhiali 3D con Trasforma e tramonto"],
"life_travel_eu_iceland":["Islanda: la Ring Road in auto","Aurore in sfumatura, mappa con percorso sonoro, auto 3D, cifre con rullo, equazione del freddo, volpe che cammina e quiz"],
"life_travel_eu_lisbon":["Lisbona: colline e tram","Azulejos in SVG, tram che sale sulle colline lungo un percorso sonoro, profilo altimetrico, carte che girano, tabella con formule e lacune"],
"life_travel_eu_prague":["Praga, la città dalle cento torri","Orologio astronomico di forme che gira e viaggia con Trasforma, sfilata con campanello, conto alla rovescia, mappa da etichettare e tabella"],
"life_travel_eu_scotland":["Scozia: le Highlands in auto","Tartan tessuto di forme, strada che si disegna, auto che si danno la precedenza, castelli che girano, lanterna 3D, barre e domande"],
"life_wedding":["Invito di nozze","Tipografia classica e oro: Text Art, testo curvo, cronologia della coppia, mappa con percorso animato, sondaggio e conto alla rovescia"],
"prod_app_bank":["Cartilla: banca per anziani","Libretto di risparmio in pelle e oro: Text Art oro, Trasforma per avvicinare il telefono, tabella con SOMMA, cascata, timbro e quiz antifrode"],
"prod_app_gym":["Serie: prenotazioni nella tua palestra","Tabellone LED: guerriero 3D che esulta e cammina fino alla lezione, due conti alla rovescia, affluenza per ora, tariffe con formule e quiz"],
"prod_app_health":["Turno: appuntamenti al centro di salute","Clinico: battito che si disegna, prima e dopo, ciclo uno alla volta, paziente 3D che cammina, agenda su monitor, barre e domande"],
"prod_app_language":["Vocablo: app per imparare le lingue","Cartolina via aerea: francobolli, fumetti che saltano con suono, carte che girano, Trasforma, equazione dell'oblio, grafico e abbinamento"],
"prod_app_market":["Plaza: il mercato di quartiere a casa","Tendone e lavagne: furgone 3D che percorre la mappa, banchi in radiale, telefono, rettangoli, commissioni con formule e votazione"],
"prod_app_meditation":["Marea: app di meditazione e sonno","Mare notturno: luna con testo curvo, Trasforma del telefono, respirazione guidata ad anelli concatenati, conto alla rovescia, grafico e lanterna 3D"],
"prod_app_music":["Garaje: musica dal vivo del quartiere","Vinile e neon: disco che viaggia con Trasforma, testo curvo che gira, equalizzatore con rullo di tamburi, portatile, radar, torta e nuvola di parole"],
"prod_app_photo":["Grano: fotografia a pellicola","Camera oscura: striscia di pellicola, foto che si sviluppa con Trasforma, contatore con rullo, istogramma, tablet, tabella ed etichettare"],
"prod_app_recipes":["Sobras: ricette con quello che c'è","Frigo con post-it: avocado 3D con Trasforma, telefono che riconosce gli ingredienti, passi, ciambella, ricetta con formule e conto alla rovescia"],
"prod_app_transit":["Andén: trasporto urbano","Segnaletica della metro: tabellone partenze con conto alla rovescia, mappa che si disegna da sola, viaggio animato, telefono, barre impilate e tariffe"],
"product_app":["Presentazione di app mobile","App su telefono, tablet e portatile, Trasforma, percorso a frecce, cifre, grafico di fidelizzazione e nuvola di parole"],
"product_car":["Presentazione: auto elettrica","Auto 3D senza bordi tagliati che fa il giro all’ingresso, Trasforma, cifre, grafici ad area e a barre, tabella e votazione"],
"product_eco":["Sostenibilità del prodotto","Verde eco: pianta 3D con Trasforma, ciclo di vita, cascata dell’impronta, barre dei materiali, linee con obiettivo e completa gli spazi"],
"product_furniture":["Collezione di mobili","Stile editoriale: divani e sedie 3D, Trasforma con viste diverse, oscillazione e giro, campioni di colore, tablet e preventivo"],
"product_keynote":["Keynote hardware","Stile bianco premium: lampada iridescente e bottiglia 3D, Trasforma con etichette, fluttuare e avvicinare, cifre, tabella e prezzi"],
"product_roadmap":["Roadmap di prodotto","Strada che si disegna da sola, piramide, cronologia uno alla volta, ora e poi, matrice, barre impilate, voto multiplo e da ordinare"],
"product_robot":["Robot assistente industriale","Stile industriale: robot 3D che saluta, segue un percorso, concatena animazioni e balla; organigramma, ciclo, grafico e quiz"],
"product_saas":["Demo di piattaforma SaaS","Dashboard in finestra del browser con richiami numerati, radiale, imbuto, indicatori, barre impilate, codice per passi e domande"],
"product_security":["Sicurezza del prodotto","Neon verde: bersaglio a strati, flusso con connettori che appare passo dopo passo, codice evidenziato, grafico, scala e attività di abbinamento"],
"product_watch":["Lancio: smartwatch","Nero e oro: orologio 3D che attraversa tre diapositive con Trasforma e arrivi diversi, Text Art oro, radar e prezzi"],
"sci_ai":["Intelligenza artificiale","Neon viola: robot 3D che saluta e viaggia con Trasformazione, cronologia, organigramma, rete neurale che si accende, grafico e nuvola di parole"],
"sci_brain":["Neuroscienze: il cervello","Stile scuro con bagliori: neurone disegnato con impulso animato, figura 3D che cammina, radiale, organigramma, barre ed etichettare un'immagine"],
"sci_chem":["Chimica: la tavola periodica","Laboratorio pulito: tavola periodica che si compone a cascata, molecole con forme, braciere 3D, equazioni, ciambella e abbinamento"],
"sci_climate":["Il cambiamento climatico in dati","Strisce del riscaldamento, grafici a linee, area e rettangoli, effetto serra che si disegna, satellite 3D, ciclo e voto a scelta multipla"],
"sci_mars":["Missione su Marte","Stile spaziale ruggine: rover 3D della NASA con Trasformazione, astronauta fluttuante, orbita animata, equazione e quiz"],
"sci_med_case":["Caso clinico: febbre e tosse","Stile cartella clinica: cartellina, timbro, radiografia sul diafanoscopio con cerchio che si disegna, CURB-65 con formula, sondaggio e domande"],
"sci_med_ecg":["Cardiologia: leggere un ECG","Carta da ECG: tracciati che si disegnano da soli, impulso che percorre il cuore, tabella con formule, equazione, quiz e conto alla rovescia"],
"sci_med_glucose":["Endocrinologia: glucosio e insulina","Stile app per sensore di glucosio: telefono con lo schermo, ciclo uno alla volta, curve, ciambella, tabella con formule, equazione, avocado 3D e sondaggio"],
"sci_med_immune":["Immunologia: la risposta immunitaria","Microscopio a fluorescenza: cellule che si accendono, anticorpo disegnato, fagocitosi con Trasforma, organigramma e abbinamenti"],
"sci_med_kidney":["Fisiologia renale: il nefrone","Disegno tecnico: nefrone che si disegna, goccia che lo percorre con suono, quote, cascata, equazione, tabella con formule, bottiglia 3D e ciclo"],
"sci_med_knee":["Anatomia: il ginocchio","Stile tavola anatomica antica: testo curvo, incisione seppia, Trasforma verso i menischi, matrice, tabella, figura 3D che cammina ed etichette"],
"sci_med_micro":["Microbiologia: resistenza agli antibiotici","Piastre di Petri: colonie che spuntano con suono, crescita esponenziale, selezione raccontata con Trasforma, antibiogramma, radiale e nuvola di parole"],
"sci_med_pk":["Farmacocinetica: l'emivita","Stile scatola di farmaco: blister che si riempie, LADME uno alla volta, curve a due serie, equazioni, tabella con formule, codice e completamento"],
"sci_med_stroke":["Neurologia: codice ictus","Corsa contro il tempo in urgenza: luci di sirena, cifra gigante con rullo di tamburi, BE-FAST in sequenza, ciambella, frecce, ordinare i passi e conto alla rovescia"],
"sci_med_trial":["Studio clinico: leggere i risultati","Stile rivista scientifica: CONSORT con connettori, curve di sopravvivenza, tabella con formule, NNT, forest plot in sequenza e quiz"],
"sci_newton":["Fisica: le leggi di Newton","Quaderno di fisica: equazioni, auto 3D in movimento, moto parabolico che si disegna, tabella con formule e completamento"],
"sci_python":["Programmare in Python","Stile editor scuro: terminale che si scrive da solo, codice con passi di evidenziazione, output animato, ordinare righe e sfida a tempo"],
"sci_solar":["Il sistema solare","Pianeti in scala che appaiono in sequenza, tre sonde 3D con viste e movimenti diversi, tabella, diagramma radiale e abbinamento"],
"sci_stats":["Statistica e probabilità","Stile editoriale: campana che si disegna, formule, istogramma, dispersione, area, barre e bolle, e domanda a punti"],
"sci_thesis":["Discussione della tesi di laurea","Accademico sobrio: copertina istituzionale, indice, metodologia con equazione, tabella con totali, risultati in grafici, bibliografia e domande"],
"showcase_3d":["Catalogo: il 3D a fondo","Modelli 3D con tutte le opzioni: viste, movimenti in entrata, rotazione, bordi, margine, clip, camminata e arrivo con Trasformazione"],
"showcase_animations":["Catalogo: animazioni","Tutte le animazioni degli oggetti: entrata, enfasi, uscita, percorsi, disegno, concatenate, suoni e più su un oggetto"],
"showcase_charts":["Catalogo: grafici","I 15 tipi di grafico, due per diapositiva, con serie, combinato, griglia, etichette e titoli degli assi, e la tabella delle opzioni"],
"showcase_diagrams":["Catalogo: diagrammi","I 15 layout di diagramma scritti come schema, i 4 schemi di colore e la comparsa uno a uno durante la presentazione"],
"showcase_morph":["Catalogo: Trasformazione","Trasformazione passo passo: testo che cambia dimensione e posto, forme, barre che crescono, immagine, 3D e lettere che si riordinano"],
"showcase_objects":["Catalogo: multimedia e oggetti","Codice a passi, equazioni, icone, cinque dispositivi, tabelle con stili e formule, zoom di diapositiva e connettori"],
"showcase_polls":["Catalogo: sondaggi e attività","Gli 11 tipi di sondaggio e attività dal cellulare, conto alla rovescia nei suoi tre stili, classifica e modalità aula"],
"showcase_shapes":["Catalogo: forme","Tutte le forme per categoria con il loro nome, linee e tratteggi, sfumature, opacità, tratto a mano, ombre, testo dentro e rotazione"],
"showcase_text":["Catalogo: Text Art e tipografia","I 10 stili di Text Art, testo curvo, colonne, cinque livelli di elenco, le 8 coppie di caratteri, allineamento e spaziatura"],
"showcase_transitions":["Catalogo: transizioni","Le 22 transizioni di diapositiva, una per una: entrata, uscita diversa, direzioni, velocità e avanzamento automatico"]};
