// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Kwartaalresultaten voor de raad","Donkerblauw en goud: grote geanimeerde kpi's met geluid, waterval, trechter, gestapelde staven en tabel met formules tegenover het budget"],
"biz_climate":["Onderzoek naar het werkklimaat","Violet en interactief: aftelklok, 100%-staven, beoordeling van 1 tot 5, woordwolk, meerkeuze en vragen uit het publiek"],
"biz_investment":["Presentatie voor investeerders","Zwart en goud: 3D-product dat draait en meereist met Transformeren, gigantische cijfers, markt in cirkels, tractie, besteding van middelen en team"],
"biz_marketing":["Marketingplan voor een campagne","Warme stijl: tekst in een cirkel, doelgroep, trechter, kanaalmix, kalender als tabel, budget met formule en stemming"],
"biz_onboarding":["Welkom voor nieuwe medewerkers","Vriendelijke stijl: 3D-robot die zwaait en door de week loopt, organigram één voor één, waarden met pictogrammen en een koppelactiviteit"],
"biz_proposal":["Commercieel voorstel aan een klant","Papierstijl: zegel, proces één voor één, mock-ups op laptop en telefoon, prijzen, begroting met btw in formules, tijdlijn en garanties"],
"biz_roadmap":["Roadmap van een project","Donkere technische stijl: chevrons één voor één, geanimeerd Gantt-diagram, tijdlijn, 3D-auto die vooruitgaat met Transformeren en statustabel"],
"biz_sales":["Verkoop en jaarprognose","Minimalistisch grijs: gecombineerde staven en lijnen, scenario's, prognoseformule, tabel met formules, gestapelde en horizontale staven"],
"biz_strategy":["Strategisch plan en OKR's","Strakke witte stijl: cijfers die na elkaar verschijnen, piramide, prioriteiten met pictogrammen, OKR-tabel, voortgangsbalken, radar en chevrons"],
"biz_swot":["SWOT-analyse en concurrentie","Grafietachtergrond: SWOT in kwadranten, strategiematrix, positioneringskaart, gegroepeerde staven, Venn, cirkeldiagram en meerkeuzestemming"],
"creative_bauhaus":["Bauhaus: vorm en functie","Geometrische Bauhauskunst: basisvormen die draaien en stuiteren, tijdlijn, raster met Morph en koppelopdracht"],
"creative_brutalism":["Brutalisme: een webmanifest","Brutalistische stijl: gigantische letters, zwarte blokken, verticale tekst, harde schaduwen, geanimeerd doorhalen, tabel en peiling"],
"creative_comic":["Strip: superkrachten van dieren","Stripstijl: plaatjes, spraak- en denkballonnen, stuiterende klanknabootsingen in Text Art, 3D-vos, grafiek en quiz"],
"creative_fashion":["Modeblad: trage herfst","Tijdschriftstijl: schreefkop, 3D-horloge op de cover, kolommen met initiaal, groot citaat, seizoenspalet en grafiek"],
"creative_glass":["Glassmorphism: financiële app","Doorschijnende kaarten op gekleurde gloed, app in een telefoon, ringdiagram, kaart met Morph en beoordelingspeiling"],
"creative_pixel":["Pixelart: je eerste videogame","Retrogamestijl: pixelsprites, scorebord, 3D-personages die lopen en springen, code stap voor stap, quiz en aftelklok"],
"creative_space":["Melkweg: kijken naar het verleden","Ruimtestijl: sterren, gloeiende nevels, 3D-modellen van NASA, sonde die langs de planeten reist, gebogen tekst en quiz"],
"creative_synthwave":["Synthwave: festival Neón 86","Retrostijl jaren 80: zon met verloop, raster dat zichzelf tekent, gloeiend neon, Morph, dansende 3D-robot en woordwolk"],
"creative_watercolor":["Aquarel: moestuin op het balkon","Aquarel- en papierstijl: vlekken met radiaal verloop, handgetekende vormen, handschrift, tekening die zichzelf tekent en 3D"],
"creative_zen":["Japans minimalisme: thee","Japans minimalisme: veel wit, rode zon met Morph, verticale tekst, een ensō die zichzelf schildert en aftelklok"],
"data_ab_test":["A/B-experiment","Vergelijkingen, spreidingsdiagram met twee reeksen, kolommen met labels, conversietabel met formules en significantiecijfers"],
"data_energy":["Energie en verbruik","Gestapelde vlakken per uur, lijnen met drie reeksen, treemap, kolommen met labels en berekende tarieventabel"],
"data_exec_panel":["Maandelijks managementdashboard","KPI's met verkeerslichten en minigrafieken, combinatie tegenover budget, small multiples, ringdiagram en stemming"],
"data_home_finance":["Persoonlijke financiën","Waterval van salaris naar spaargeld, cirkeldiagram, lijnen en vlak, tabellen met SOM, GEMIDDELDE, MAX en MIN"],
"data_market_study":["Marktonderzoek","Grote cijfers, treemap, bellen, spreidingsdiagram, horizontale staven met twee reeksen en 2 × 2-matrix"],
"data_population":["Bevolking en demografie","Bevolkingspiramide, histogram, horizontale staven, kruisende lijnen en indicatorentabel met formules"],
"data_sales_regions":["Verkoop per regio","Gegroepeerde, gestapelde en 100%-staven, combinatiegrafiek met doel, tabel met formuletotalen en geanimeerde KPI's"],
"data_satisfaction":["Tevredenheidsonderzoek","Ringdiagram met legenda, vergeleken radars, kolommen met labels, NPS, live beoordeling en woordwolk"],
"data_season_stats":["Het seizoen in cijfers","Reuzencijfers met geluid, ranglijst met formules, negatieve staven, lijnen, gestapelde staven en teamradar"],
"data_web_metrics":["Web- en marketingstatistieken","KPI's met minigrafieken, lijnen met vier reeksen, vlakken, conversietrechter, combinatiegrafiek en tabel met formules"],
"edu_body":["Het menselijk lichaam","Labstijl: 3D-figuur met Morph, personage dat een route loopt, staafdiagram, het lichaam benoemen en quiz"],
"edu_cell":["De cel","Cel getekend met vormen, delen één voor één, Morph om in te zoomen, paren koppelen, diagram, 3D-plant en beoordeling"],
"edu_english":["Engels voor beginners","Klasmodus: kaarten die omdraaien met geluid, 3D-robot die loopt en zwaait, 3D-vos, drie vragen met punten, ranglijst en applaus"],
"edu_fractions":["Breuken","Neonstijl: getekende pizza's, vergelijkingen stap voor stap, optellen met Morph, gaten invullen, quiz en uitdaging met aftelklok"],
"edu_quixote":["Don Quichot","Inkt-en-papierstijl: draaiende molen met geluid, gebogen tekst, geanimeerde citaten, Morph, tijdlijn, gaten invullen en quiz"],
"edu_renewables":["Hernieuwbare energie","Draaiende windturbine, kaarten, vlak-, ring- en gegroepeerde staafdiagrammen, live woordwolk, peiling en aftelklok"],
"edu_revolution":["De Franse Revolutie","Oudpapierstijl: tekst in een cirkel, Morph, maatschappijpiramide, geanimeerde tijdlijn met geluid, gebeurtenissen ordenen en peiling"],
"edu_spain":["Aardrijkskunde van Spanje","Atlasstijl: windroos, reliëf als doelwitdiagram, rivierentabel met formules, grafieken van toppen en neerslag, paren koppelen en quiz"],
"edu_volcanoes":["Vulkanen","Vuurstijl: geanimeerde uitbarsting met geluid, delen van de vulkaan benoemen, tabel, quiz op tijd en aftelklok"],
"edu_water":["De waterkringloop","Cyclusdiagram één voor één, landschap met stijgende druppels en geanimeerde regen met geluid, ringdiagrammen, paren koppelen en 3D-satelliet"],
"life_bookclub":["Leesclub","Boekenplank uit de vrije hand, omslag van vormen, citaten die transformeren, radiaal diagram, beoordeling en stemming over het volgende boek"],
"life_cv":["Visueel cv","Tekst in een cirkel, kerncijfers, tijdlijn stap voor stap, geanimeerde vaardigheidsbalken, radardiagram, schermen in apparaten en contact"],
"life_fitness":["Trainingsschema: 5 km","3D-hardloper, Text Art vuur, fasen met kleurverloop, week met formules, voortgangsgrafieken, piramide, aftelling en woordwolk"],
"life_garden":["Stadsmoestuin","3D-plant met Transformeren, zaaikalender als gekleurde tabel, cyclus, Venn, grafieken van water geven en groei, labelopdracht"],
"life_graduation":["Diploma-uitreiking en eind van het schooljaar","Gouden Text Art, afstudeerhoeden van vormen, polaroids die omklappen bij het verschijnen, cijfers met tromgeroffel, dankwoorden, woordwolk en applaus"],
"life_italy":["Reis door Italië","Tekst in een cirkel, route met verbindingslijnen en geanimeerd pad, tijdlijn, begroting met formules, grafieken en koppelopdracht"],
"life_kids_party":["Kinderverjaardag","Felle kleuren: dansende 3D-robot, juichende personages, ballonnen uit de vrije hand, quiz met punten en aftelling"],
"life_moving":["Verhuizing en nieuw thuis","Huis van vormen uit de vrije hand, tijdlijn, lijst die wordt doorgestreept, 3D-meubels die met Transformeren naar de plattegrond gaan, begroting en volgorde-opdracht"],
"life_recipe":["Recept: guacamole","3D-avocado die tussen dia's reist (Transformeren), ingrediënten met formules, stappen één voor één, aftelling en beoordeling"],
"life_wedding":["Huwelijksuitnodiging","Klassieke letters en goud: Text Art, gebogen tekst, tijdlijn van het paar, kaart met geanimeerde route, peiling en aftelling"],
"product_app":["Presentatie van een mobiele app","App op telefoon, tablet en laptop, Morph, gebruikersreis als chevrons, cijfers, retentiegrafiek en woordwolk"],
"product_car":["Presentatie: elektrische auto","3D-auto zonder afgesneden randen die bij binnenkomst rondgaat, Morph, cijfers, vlak- en staafdiagrammen, tabel en stemming"],
"product_eco":["Duurzaamheid van het product","Ecogroen: 3D-plant met Morph, levenscyclus, voetafdruk-waterval, materiaalstaven, lijnen met doel en gatentekst"],
"product_furniture":["Meubelcollectie","Redactionele stijl: 3D-banken en -stoelen, Morph met verschillende aanzichten, schommelen en rondgaan, kleurstalen, tablet en begroting"],
"product_keynote":["Hardware-keynote","Premium witte stijl: iriserende lamp en 3D-fles, Morph met labels, zweven en inzoomen, cijfers, tabel en prijzen"],
"product_roadmap":["Productroadmap","Weg die zichzelf tekent, piramide, tijdlijn één voor één, nu en straks, matrix, gestapelde staven, meerkeuzestemming en ordenen"],
"product_robot":["Industriële assistentrobot","Industriële stijl: 3D-robot die zwaait, een route loopt, animaties koppelt en danst; organigram, cyclus, grafiek en quiz"],
"product_saas":["Demo van een SaaS-platform","Dashboard in een browservenster met genummerde aanwijzingen, radiaal, trechter, KPI’s, gestapelde staven, code in stappen en vragen"],
"product_security":["Productbeveiliging","Groen neon: doelwit in lagen, stroom met verbindingen die stap voor stap verschijnt, gemarkeerde code, grafiek, trap en koppelopdracht"],
"product_watch":["Lancering: smartwatch","Zwart en goud: 3D-horloge reist met Morph en verschillende aankomsten over drie dia’s, gouden Text Art, radar en prijzen"],
"sci_ai":["Kunstmatige intelligentie","Violet neon: 3D-robot die zwaait en met Morph meereist, tijdlijn, organigram, neuraal netwerk dat oplicht, grafiek en woordwolk"],
"sci_brain":["Neurowetenschap: de hersenen","Donkere stijl met gloed: getekend neuron met geanimeerde impuls, lopende 3D-figuur, radiaal, organigram, staven en een afbeelding labelen"],
"sci_chem":["Scheikunde: het periodiek systeem","Strak lab: periodiek systeem dat zich als een waterval opbouwt, moleculen van vormen, 3D-vuurpot, vergelijkingen, ringdiagram en koppelen"],
"sci_climate":["Klimaatverandering in cijfers","Opwarmingsstrepen, lijn-, vlak- en treemapdiagram, broeikaseffect dat zichzelf tekent, 3D-satelliet, kringloop en meerkeuzestemming"],
"sci_mars":["Missie naar Mars","Roestkleurige ruimtestijl: 3D-rover van NASA met Morph, zwevende astronaut, geanimeerde baan, vergelijking en quiz"],
"sci_newton":["Natuurkunde: de wetten van Newton","Natuurkundeschrift: vergelijkingen, rijdende 3D-auto, kogelbaan die zichzelf tekent, tabel met formules en invuloefening"],
"sci_python":["Programmeren in Python","Donkere editorstijl: terminal die zichzelf typt, code met markeerstappen, geanimeerde uitvoer, regels ordenen en uitdaging met aftelklok"],
"sci_solar":["Het zonnestelsel","Planeten op schaal die na elkaar verschijnen, drie 3D-sondes met verschillende aanzichten en bewegingen, tabel, radiaal diagram en koppelen"],
"sci_stats":["Statistiek en kansrekening","Redactionele stijl: klokcurve die zichzelf tekent, formules, histogram, spreidings-, vlak-, staaf- en bellendiagram, en een vraag met punten"],
"sci_thesis":["Verdediging van de bachelorscriptie","Sober academisch: institutionele titelpagina, inhoud, methode met vergelijking, tabel met totalen, resultaten in grafieken, literatuur en vragen"]};
