// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Kwartaalresultaten voor de raad","Donkerblauw en goud: grote geanimeerde kpi's met geluid, waterval, trechter, gestapelde staven en tabel met formules tegenover het budget"],
"biz_climate":["Onderzoek naar het werkklimaat","Violet en interactief: aftelklok, 100%-staven, beoordeling van 1 tot 5, woordwolk, meerkeuze en vragen uit het publiek"],
"biz_investment":["Presentatie voor investeerders","Zwart en goud: 3D-product dat draait en meereist met Transformeren, gigantische cijfers, markt in cirkels, tractie, besteding van middelen en team"],
"biz_marketing":["Marketingplan voor een campagne","Warme stijl: tekst in een cirkel, doelgroep, trechter, kanaalmix, kalender als tabel, budget met formule en stemming"],
"biz_onboarding":["Welkom voor nieuwe medewerkers","Vriendelijke stijl: 3D-robot die zwaait en door de week loopt, organigram één voor één, waarden met pictogrammen en een koppelactiviteit"],
"biz_proposal":["Commercieel voorstel aan een klant","Papierstijl: zegel, proces één voor één, mock-ups op laptop en telefoon, prijzen, begroting met btw in formules, tijdlijn en garanties"],
"biz_roadmap":["Roadmap van een project","Donkere technische stijl: chevrons één voor één, geanimeerd Gantt-diagram, tijdlijn, 3D-auto die vooruitgaat met Transformeren en statustabel"],
"biz_sales":["Verkoop en jaarprognose","Minimalistisch grijs: gecombineerde staven en lijnen, scenario's, prognoseformule, tabel met formules, gestapelde en horizontale staven"],
"biz_startup_agrotech":["Agritech-pitch: irrigatie met sensoren","Luchtbeeld van percelen met vochtkaart, 3D-satelliet van NASA, telefoon, druppels in een keten met geluid, tabel met formules en treemap"],
"biz_startup_edtech":["Edtech-pitch: wiskundetutor","Ruitjesschrift: plakbriefjes in een keten, handschrift, vergelijkingen stap voor stap, telefoon, live quiz, cyclus en grafieken"],
"biz_startup_energy":["Energiepitch: zonnegemeenschap","Daken van dageraad tot nacht: zon die opkomt en in een boog door de lucht gaat, radiaal diagram, vlakken per uur, vergelijking en tabel met formules"],
"biz_startup_fashion":["Pitch circulaire mode: Retal","Kledinglabel dat reist met Morph, gestippelde naden, leven van een kledingstuk in een keten, cyclus, ring, radar en meerkeuzestemming"],
"biz_startup_insurance":["Verzekeringspitch: dekking per dag","Grijze regen en gele paraplu: pictogram in een keten, app met schakelaar, prijsvergelijking, tabel met formules, tijdlijn en stemming"],
"biz_startup_kitchen":["Pitch keukenrobotica: Fogón","Profkeuken: bonnen aan de rail, vuur-Text Art, 3D-robot die binnenloopt en zwaait, recept als code, aftelklok en trechter"],
"biz_startup_lastmile":["Logistiek-pitch: laatste kilometer","Metrokaartstijl: lijnen die zichzelf tekenen, 3D-vrachtwagen en fietsen die over de kaart rijden, tabel met formules, vlak en waterval"],
"biz_startup_mental":["Pitch mentale gezondheid: Remanso","Rustige nacht: ademende ringen, ademminuut met aftelklok, app op de telefoon, trap, beoordeling en tabel met formules"],
"biz_startup_pets":["Huisdierenpitch: vers voer","Stickerstijl met pootafdrukken in een keten, 3D-vos die overloopt, portieformule in een tabel, ring en quiz"],
"biz_startup_rural":["Pitch plattelandstoerisme: Alpende","Bergen bij schemering en ansichtkaarten: 3D-lantaarn, poststempel met gebogen tekst, kaart met 3D-auto langs de route, staven, taart en woordwolk"],
"biz_strategy":["Strategisch plan en OKR's","Strakke witte stijl: cijfers die na elkaar verschijnen, piramide, prioriteiten met pictogrammen, OKR-tabel, voortgangsbalken, radar en chevrons"],
"biz_swot":["SWOT-analyse en concurrentie","Grafietachtergrond: SWOT in kwadranten, strategiematrix, positioneringskaart, gegroepeerde staven, Venn, cirkeldiagram en meerkeuzestemming"],
"creative_bauhaus":["Bauhaus: vorm en functie","Geometrische Bauhauskunst: basisvormen die draaien en stuiteren, tijdlijn, raster met Morph en koppelopdracht"],
"creative_brutalism":["Brutalisme: een webmanifest","Brutalistische stijl: gigantische letters, zwarte blokken, verticale tekst, harde schaduwen, geanimeerd doorhalen, tabel en peiling"],
"creative_comic":["Strip: superkrachten van dieren","Stripstijl: plaatjes, spraak- en denkballonnen, stuiterende klanknabootsingen in Text Art, 3D-vos, grafiek en quiz"],
"creative_fashion":["Modeblad: trage herfst","Tijdschriftstijl: schreefkop, 3D-horloge op de cover, kolommen met initiaal, groot citaat, seizoenspalet en grafiek"],
"creative_glass":["Glassmorphism: financiële app","Doorschijnende kaarten op gekleurde gloed, app in een telefoon, ringdiagram, kaart met Morph en beoordelingspeiling"],
"creative_pixel":["Pixelart: je eerste videogame","Retrogamestijl: pixelsprites, scorebord, 3D-personages die lopen en springen, code stap voor stap, quiz en aftelklok"],
"creative_space":["Melkweg: kijken naar het verleden","Ruimtestijl: sterren, gloeiende nevels, 3D-modellen van NASA, sonde die langs de planeten reist, gebogen tekst en quiz"],
"creative_swiss_blood":["Campagne: geef bloed","Openbare affiche in wit en rood: druppel die met Morphen het scherm vult, proces, ja of wacht, ring, staven, mobiel en quiz"],
"creative_swiss_chairs":["Tentoonstelling: de moderne stoel","Zwitserse affiche in grijs en limoen: 3D-stoel die draait en reist met Morphen, tijdlijn, ring, 3D-fauteuil, tabel met formules en ordenen"],
"creative_swiss_designconf":["Designcongres: Raster 27","Grafiet en cyaan: het raster bouwt zichzelf op en verandert met Morphen, contourcijfer, formule, tijdlijn, CSS-code, woordwolk en pauze"],
"creative_swiss_film":["Filmfestival: het programma","Zwitsers in zwart en rood: reuzengetal dat met Morphen een band wordt, raster, tabel, staven, peiling en aftelling"],
"creative_swiss_foundation":["Jaarverslag van een stichting","Zwitsers in wit en kobaltblauw: reuzenjaartal, brief over de hele pagina, getallen na elkaar, formule, ring, vlak, pijlen en rekeningen met formules"],
"creative_swiss_games":["Schoolspelen: de huisstijl","Wit en magenta, eigen palet: SVG-pictogrammen, 3D-figuur door de stad, lijnen, medaillespiegel met formules, treden en quiz"],
"creative_swiss_museum":["Gids van het natuurhistorisch museum","Zwitserse bewegwijzering in zwart en geel: eigen plattegrond met geanimeerde route, lopende 3D-vos, kolommen, tabel, labelen en pictogrammen"],
"creative_swiss_orchestra":["Symfonieorkest: seizoen 26/27","Nachtblauw en amber: draaiende bogen, gebogen tekst, getallen op een notenbalk, cycli, tabel, formule, staven, peiling en applaus"],
"creative_swiss_publisher":["Najaarscatalogus van een uitgeverij","Crèmepapier en petrolgroen: boekenplank met verticale ruggen, SVG-omslagen, tablet, taart, bestelling met formules, kalender en gaten"],
"creative_swiss_typeface":["Proefboek van een nieuwe letter","Proefboek in wit en violet: letters die reizen met Morphen, gemeten anatomie, schaal met formule, glyphs, radar en licenties"],
"creative_synthwave":["Synthwave: festival Neón 86","Retrostijl jaren 80: zon met verloop, raster dat zichzelf tekent, gloeiend neon, Morph, dansende 3D-robot en woordwolk"],
"creative_watercolor":["Aquarel: moestuin op het balkon","Aquarel- en papierstijl: vlekken met radiaal verloop, handgetekende vormen, handschrift, tekening die zichzelf tekent en 3D"],
"creative_zen":["Japans minimalisme: thee","Japans minimalisme: veel wit, rode zon met Morph, verticale tekst, een ensō die zichzelf schildert en aftelklok"],
"data_ab_test":["A/B-experiment","Vergelijkingen, spreidingsdiagram met twee reeksen, kolommen met labels, conversietabel met formules en significantiecijfers"],
"data_energy":["Energie en verbruik","Gestapelde vlakken per uur, lijnen met drie reeksen, treemap, kolommen met labels en berekende tarieventabel"],
"data_exec_panel":["Maandelijks managementdashboard","KPI's met verkeerslichten en minigrafieken, combinatie tegenover budget, small multiples, ringdiagram en stemming"],
"data_home_finance":["Persoonlijke financiën","Waterval van salaris naar spaargeld, cirkeldiagram, lijnen en vlak, tabellen met SOM, GEMIDDELDE, MAX en MIN"],
"data_market_study":["Marktonderzoek","Grote cijfers, treemap, bellen, spreidingsdiagram, horizontale staven met twee reeksen en 2 × 2-matrix"],
"data_population":["Bevolking en demografie","Bevolkingspiramide, histogram, horizontale staven, kruisende lijnen en indicatorentabel met formules"],
"data_sales_regions":["Verkoop per regio","Gegroepeerde, gestapelde en 100%-staven, combinatiegrafiek met doel, tabel met formuletotalen en geanimeerde KPI's"],
"data_satisfaction":["Tevredenheidsonderzoek","Ringdiagram met legenda, vergeleken radars, kolommen met labels, NPS, live beoordeling en woordwolk"],
"data_season_stats":["Het seizoen in cijfers","Reuzencijfers met geluid, ranglijst met formules, negatieve staven, lijnen, gestapelde staven en teamradar"],
"data_web_metrics":["Web- en marketingstatistieken","KPI's met minigrafieken, lijnen met vier reeksen, vlakken, conversietrechter, combinatiegrafiek en tabel met formules"],
"edu_body":["Het menselijk lichaam","Labstijl: 3D-figuur met Morph, personage dat een route loopt, staafdiagram, het lichaam benoemen en quiz"],
"edu_cell":["De cel","Cel getekend met vormen, delen één voor één, Morph om in te zoomen, paren koppelen, diagram, 3D-plant en beoordeling"],
"edu_english":["Engels voor beginners","Klasmodus: kaarten die omdraaien met geluid, 3D-robot die loopt en zwaait, 3D-vos, drie vragen met punten, ranglijst en applaus"],
"edu_fractions":["Breuken","Neonstijl: getekende pizza's, vergelijkingen stap voor stap, optellen met Morph, gaten invullen, quiz en uitdaging met aftelklok"],
"edu_hist_alandalus":["Al-Andalus: wetenschap en tuinen","Hoefijzerboog, tijdlijn stap voor stap, horizontale balken, draaiend astrolabium, ster met Morph, paren koppelen en peiling"],
"edu_hist_castle":["Kastelen en feodalisme","Kasteel bij nacht en 3D-ridder die de brug oversteekt, feodale piramide die verrijst, labelen, zon die de dag doorloopt, treemap en wapenschilden"],
"edu_hist_egypt":["Egypte, geschenk van de Nijl","Lapis lazuli en goud: zon die achter de piramides opkomt, geanimeerde overstroming, vlakdiagram, vergelijking, Morph, hiërogliefencartouche en ordenen"],
"edu_hist_greece":["Athene: de democratie ontstaat","Stijl zwartfigurige vaas: meander, gebogen tekst, Morph, ring, tempel die verrijst, ostraka met geluid, peiling en tabel"],
"edu_hist_maya":["De Maya: tijd en sterren","Jungle en jade: getallen van stippen en strepen, Morph naar grondtal 20, vergelijking, draaiende kalenderwielen, lichtslang en cacao"],
"edu_hist_mesopotamia":["Mesopotamië: het schrift ontstaat","Kleitablet die zichzelf schrijft, kaart met getekende rivieren, groeiende ziggoerat, grondtal 60 met formules, gatentekst en radiaal"],
"edu_hist_printing":["De boekdrukkunst: het boek vermenigvuldigt zich","Incunabelpagina: rode initiaal, gespiegelde letters gezet met Morph, pers die met geluid neerkomt, cijfers, balken en gatentekst"],
"edu_hist_rome":["Rome, ingenieurs van het rijk","Marmer en keizerlijk rood: Morph, triomfboog, weg in lagen met marcherende 3D-soldaat, aquaduct, vergelijking, formules en quiz"],
"edu_hist_silkroad":["De Zijderoute","Zijde en saffraan: karavaan op weg, kaart met getekende route, prijswaterval, tabel met formules, 3D-lantaarn, vergelijking en ordenen"],
"edu_hist_vikings":["Vikingen, zeevaarders van het noorden","Fjord onder het noorderlicht: schommelend schip, runen, doorgestreepte mythes met stempel, geanimeerde overtocht, cijfers met geluid, 3D-krijger, radar en koppelen"],
"edu_math_coordinates":["Coördinaten: de schatkaart","Schatkaart: windroos met gebogen tekst, verschijnende punten, 3D-piraat die aanwijzingen volgt, boot die zichzelf tekent en labelen"],
"edu_math_integers":["Gehele getallen: zee en berg","Van zeebodem tot bergtop: getallenlijn met sprongen, Text Art ijs, temperaturen onder nul, onderzeeër die stijgt en daalt, ordenen en quiz"],
"edu_math_primes":["Priemgetallen","Groene terminal: eigen neon, zeef van Eratosthenes klik voor klik met 100 vakjes, factorboom, code stap voor stap, quiz en uitdaging"],
"edu_math_probability":["Kansrekening: geluk meten","Speeltafel in bordeaux en goud: rollende dobbelstenen met tromgeroffel, gebogen tekst, regel van Laplace, boom stap voor stap, staven, lijnen en quiz"],
"edu_math_proportion":["Evenredigheid in de supermarkt","Kassabon: stuiterende stempel, evenredigheidstabel met formules, regel van drie stap voor stap, berekende kortingen, lijnen en invuloefening"],
"edu_math_pythagoras":["De stelling van Pythagoras","Krijtbord: figuur die zichzelf tekent, bewijs zonder woorden met Morph, drietallen met formules, 3D-kortere weg en quiz"],
"edu_math_sequences":["Rijen en patronen","Botanisch boek: Fibonacci-spiraal die zichzelf tekent, steentjes in een ketting, lucifers met formules, code, 3D-plant en de gulden snede"],
"edu_math_stats":["Statistiek: gemiddelde, mediaan en modus","Ruitjesschrift: memoblaadjes in cascade, frequenties met formules, staven, ring met graden, histogram en live peiling"],
"edu_math_symmetry":["Symmetrie en betegelingen","Nasridische tegels: draaiende ster, spiegelende vlinder, geanimeerde verschuiving, draaiing en spiegeling, hoekentabel en honingraat"],
"edu_math_volumes":["Oppervlakten en inhouden","Blauwe bouwtekening: titelblok als tabel, uitslag, gemeten 3D-fles, inhouden met formules, staven, vullende kegels en koppelen"],
"edu_quixote":["Don Quichot","Inkt-en-papierstijl: draaiende molen met geluid, gebogen tekst, geanimeerde citaten, Morph, tijdlijn, gaten invullen en quiz"],
"edu_renewables":["Hernieuwbare energie","Draaiende windturbine, kaarten, vlak-, ring- en gegroepeerde staafdiagrammen, live woordwolk, peiling en aftelklok"],
"edu_revolution":["De Franse Revolutie","Oudpapierstijl: tekst in een cirkel, Morph, maatschappijpiramide, geanimeerde tijdlijn met geluid, gebeurtenissen ordenen en peiling"],
"edu_spain":["Aardrijkskunde van Spanje","Atlasstijl: windroos, reliëf als doelwitdiagram, rivierentabel met formules, grafieken van toppen en neerslag, paren koppelen en quiz"],
"edu_volcanoes":["Vulkanen","Vuurstijl: geanimeerde uitbarsting met geluid, delen van de vulkaan benoemen, tabel, quiz op tijd en aftelklok"],
"edu_water":["De waterkringloop","Cyclusdiagram één voor één, landschap met stijgende druppels en geanimeerde regen met geluid, ringdiagrammen, paren koppelen en 3D-satelliet"],
"life_bookclub":["Leesclub","Boekenplank uit de vrije hand, omslag van vormen, citaten die transformeren, radiaal diagram, beoordeling en stemming over het volgende boek"],
"life_cv":["Visueel cv","Tekst in een cirkel, kerncijfers, tijdlijn stap voor stap, geanimeerde vaardigheidsbalken, radardiagram, schermen in apparaten en contact"],
"life_fitness":["Trainingsschema: 5 km","3D-hardloper, Text Art vuur, fasen met kleurverloop, week met formules, voortgangsgrafieken, piramide, aftelling en woordwolk"],
"life_garden":["Stadsmoestuin","3D-plant met Transformeren, zaaikalender als gekleurde tabel, cyclus, Venn, grafieken van water geven en groei, labelopdracht"],
"life_graduation":["Diploma-uitreiking en eind van het schooljaar","Gouden Text Art, afstudeerhoeden van vormen, polaroids die omklappen bij het verschijnen, cijfers met tromgeroffel, dankwoorden, woordwolk en applaus"],
"life_italy":["Reis door Italië","Tekst in een cirkel, route met verbindingslijnen en geanimeerd pad, tijdlijn, begroting met formules, grafieken en koppelopdracht"],
"life_kids_party":["Kinderverjaardag","Felle kleuren: dansende 3D-robot, juichende personages, ballonnen uit de vrije hand, quiz met punten en aftelling"],
"life_moving":["Verhuizing en nieuw thuis","Huis van vormen uit de vrije hand, tijdlijn, lijst die wordt doorgestreept, 3D-meubels die met Transformeren naar de plattegrond gaan, begroting en volgorde-opdracht"],
"life_recipe":["Recept: guacamole","3D-avocado die tussen dia's reist (Transformeren), ingrediënten met formules, stappen één voor één, aftelling en beoordeling"],
"life_travel_eu_amsterdam":["Amsterdam: grachten en fietsen","Grachtengevels die zich na elkaar opbouwen, grachten als schietschijf, fiets met geluid, tabel met formules, lijnen en taartpeiling"],
"life_travel_eu_camino":["Camino de Santiago: vanaf Sarria","Pelgrimspas die zich vult met stempels met geluid, kilometerwaterval, 3D-wandelaar, rugzakformule, ring en etappes ordenen"],
"life_travel_eu_croatia":["Kroatië: zeilen langs Dalmatië","Zeekaart, windroos die draait en reist met Morph, vlaggen, koppelen, mijlen met formules, quiz en aftelling"],
"life_travel_eu_danube":["De Donau op de fiets","Fietscomputerstijl: route op de telefoon, GPX-bestand stap voor stap, gestapelde staven, 3D-bidon met Morph, formules en rechthoeken"],
"life_travel_eu_fjords":["Noorse fjorden over het water","Gelaagd landschap met spiegelingen, varend schip, fjorddoorsnede die zichzelf tekent, staven, radar, etappes en meerkeuzepeiling"],
"life_travel_eu_greece":["Griekse eilanden per veerboot","Wit dorp van vormen, meander, route die zichzelf tekent, dienstregeling met formules, bellen, 3D-zonnebril met Morph en zonsondergang"],
"life_travel_eu_iceland":["IJsland: de Ring Road met de auto","Poollicht met verlopen, kaart met klinkend pad, 3D-auto, cijfers met tromgeroffel, kouformule, lopende vos en quiz"],
"life_travel_eu_lisbon":["Lissabon: heuvels en trams","SVG-tegels, tram die heuvels op rijdt langs een pad met geluid, hoogteprofiel, draaiende kaarten, tabel met formules en gaten"],
"life_travel_eu_prague":["Praag, de stad van honderd torens","Astronomische klok van vormen die draait en reist met Morph, optocht met klokje, aftelling, kaart om te labelen en tabel"],
"life_travel_eu_scotland":["Schotland: de Highlands met de auto","Tartan geweven uit vormen, weg die zichzelf tekent, auto’s die voorrang geven, draaiende kastelen, 3D-lantaarn, staven en vragen"],
"life_wedding":["Huwelijksuitnodiging","Klassieke letters en goud: Text Art, gebogen tekst, tijdlijn van het paar, kaart met geanimeerde route, peiling en aftelling"],
"prod_app_bank":["Cartilla: bankieren voor ouderen","Spaarboekje in leer en goud: gouden Text Art, Morphen om in te zoomen op de telefoon, tabel met SOM, waterval, stempel en quiz tegen fraude"],
"prod_app_gym":["Serie: reserveringen in je sportschool","LED-scorebord: 3D-vechter die juicht en naar de les loopt, twee aftelklokken, bezetting per uur, tarieven met formules en quiz"],
"prod_app_health":["Turno: afspraken bij het gezondheidscentrum","Klinisch: hartslag die zichzelf tekent, voor en na, cyclus één voor één, lopende 3D-patiënt, agenda op monitor, staven en vragen"],
"prod_app_language":["Vocablo: app om talen te leren","Luchtpostkaart: postzegels, tekstballonnen die met geluid opspringen, draaiende kaarten, Morphen, vergeetformule, grafiek en koppelen"],
"prod_app_market":["Plaza: de buurtmarkt aan huis","Luifel en krijtborden: 3D-bestelbus die de kaart afrijdt, kramen in radiaal, telefoon, rechthoeken, commissies met formules en stemming"],
"prod_app_meditation":["Marea: app voor meditatie en slaap","Nachtzee: maan met gebogen tekst, Morphen van de telefoon, begeleide ademhaling met ringen na elkaar, aftelklok, grafiek en 3D-lantaarn"],
"prod_app_music":["Garaje: livemuziek uit de buurt","Vinyl en neon: plaat die meereist met Morphen, draaiende gebogen tekst, equalizer met tromgeroffel, laptop, radar, taart en woordwolk"],
"prod_app_photo":["Grano: analoge fotografie","Donkere kamer: filmstrook, foto die zich ontwikkelt met Morphen, teller met tromgeroffel, histogram, tablet, tabel en labelen"],
"prod_app_recipes":["Sobras: recepten met wat er is","Koelkast met memoblaadjes: 3D-avocado met Morphen, telefoon die ingrediënten herkent, stappen, ring, recept met formules en aftelklok"],
"prod_app_transit":["Andén: stadsvervoer","Metrobewegwijzering: vertrekbord met aftelklok, kaart die zichzelf tekent, geanimeerde rit, telefoon, gestapelde staven en tarieven"],
"product_app":["Presentatie van een mobiele app","App op telefoon, tablet en laptop, Morph, gebruikersreis als chevrons, cijfers, retentiegrafiek en woordwolk"],
"product_car":["Presentatie: elektrische auto","3D-auto zonder afgesneden randen die bij binnenkomst rondgaat, Morph, cijfers, vlak- en staafdiagrammen, tabel en stemming"],
"product_eco":["Duurzaamheid van het product","Ecogroen: 3D-plant met Morph, levenscyclus, voetafdruk-waterval, materiaalstaven, lijnen met doel en gatentekst"],
"product_furniture":["Meubelcollectie","Redactionele stijl: 3D-banken en -stoelen, Morph met verschillende aanzichten, schommelen en rondgaan, kleurstalen, tablet en begroting"],
"product_keynote":["Hardware-keynote","Premium witte stijl: iriserende lamp en 3D-fles, Morph met labels, zweven en inzoomen, cijfers, tabel en prijzen"],
"product_roadmap":["Productroadmap","Weg die zichzelf tekent, piramide, tijdlijn één voor één, nu en straks, matrix, gestapelde staven, meerkeuzestemming en ordenen"],
"product_robot":["Industriële assistentrobot","Industriële stijl: 3D-robot die zwaait, een route loopt, animaties koppelt en danst; organigram, cyclus, grafiek en quiz"],
"product_saas":["Demo van een SaaS-platform","Dashboard in een browservenster met genummerde aanwijzingen, radiaal, trechter, KPI’s, gestapelde staven, code in stappen en vragen"],
"product_security":["Productbeveiliging","Groen neon: doelwit in lagen, stroom met verbindingen die stap voor stap verschijnt, gemarkeerde code, grafiek, trap en koppelopdracht"],
"product_watch":["Lancering: smartwatch","Zwart en goud: 3D-horloge reist met Morph en verschillende aankomsten over drie dia’s, gouden Text Art, radar en prijzen"],
"sci_ai":["Kunstmatige intelligentie","Violet neon: 3D-robot die zwaait en met Morph meereist, tijdlijn, organigram, neuraal netwerk dat oplicht, grafiek en woordwolk"],
"sci_brain":["Neurowetenschap: de hersenen","Donkere stijl met gloed: getekend neuron met geanimeerde impuls, lopende 3D-figuur, radiaal, organigram, staven en een afbeelding labelen"],
"sci_chem":["Scheikunde: het periodiek systeem","Strak lab: periodiek systeem dat zich als een waterval opbouwt, moleculen van vormen, 3D-vuurpot, vergelijkingen, ringdiagram en koppelen"],
"sci_climate":["Klimaatverandering in cijfers","Opwarmingsstrepen, lijn-, vlak- en treemapdiagram, broeikaseffect dat zichzelf tekent, 3D-satelliet, kringloop en meerkeuzestemming"],
"sci_mars":["Missie naar Mars","Roestkleurige ruimtestijl: 3D-rover van NASA met Morph, zwevende astronaut, geanimeerde baan, vergelijking en quiz"],
"sci_med_case":["Klinische casus: koorts en hoest","Stijl medisch dossier: map, stempel, röntgenfoto op lichtbak met cirkel die zichzelf tekent, CURB-65 met formule, peiling en vragen"],
"sci_med_ecg":["Cardiologie: een ecg lezen","Ecg-papier: curves die zichzelf tekenen, impuls door het hart, tabel met formules, vergelijking, quiz en aftelling"],
"sci_med_glucose":["Endocrinologie: glucose en insuline","Stijl glucosesensor-app: telefoon met scherm, cyclus één voor één, curves, ring, tabel met formules, vergelijking, 3D-avocado en peiling"],
"sci_med_immune":["Immunologie: de immuunrespons","Fluorescentiemicroscoop: cellen die oplichten, getekend antilichaam, fagocytose met Morph, organogram en koppelen"],
"sci_med_kidney":["Nierfysiologie: het nefron","Technische tekening: nefron dat zichzelf tekent, druppel die erdoor reist met geluid, maatlijnen, watervaldiagram, vergelijking, tabel met formules, 3D-fles en cyclus"],
"sci_med_knee":["Anatomie: de knie","Stijl oude anatomische plaat: gebogen tekst, sepiagravure, Morph naar de menisci, matrix, tabel, lopende 3D-figuur en labelen"],
"sci_med_micro":["Microbiologie: antibioticaresistentie","Petrischalen: kolonies die opduiken met geluid, exponentiële groei, selectie verteld met Morph, antibiogram, radiaal diagram en woordwolk"],
"sci_med_pk":["Farmacokinetiek: de halfwaardetijd","Stijl medicijndoosje: blister die zich vult, LADME één voor één, curves met twee reeksen, vergelijkingen, tabel met formules, code en invuloefening"],
"sci_med_stroke":["Neurologie: beroertecode","Race tegen de klok op de spoed: sirenelichten, reuzengetal met tromgeroffel, BE-FAST na elkaar, ring, chevrons, stappen ordenen en aftelling"],
"sci_med_trial":["Klinische studie: de resultaten lezen","Stijl wetenschappelijk tijdschrift: CONSORT met verbindingslijnen, overlevingscurves, tabel met formules, NNT, forest plot na elkaar en quiz"],
"sci_newton":["Natuurkunde: de wetten van Newton","Natuurkundeschrift: vergelijkingen, rijdende 3D-auto, kogelbaan die zichzelf tekent, tabel met formules en invuloefening"],
"sci_python":["Programmeren in Python","Donkere editorstijl: terminal die zichzelf typt, code met markeerstappen, geanimeerde uitvoer, regels ordenen en uitdaging met aftelklok"],
"sci_solar":["Het zonnestelsel","Planeten op schaal die na elkaar verschijnen, drie 3D-sondes met verschillende aanzichten en bewegingen, tabel, radiaal diagram en koppelen"],
"sci_stats":["Statistiek en kansrekening","Redactionele stijl: klokcurve die zichzelf tekent, formules, histogram, spreidings-, vlak-, staaf- en bellendiagram, en een vraag met punten"],
"sci_thesis":["Verdediging van de bachelorscriptie","Sober academisch: institutionele titelpagina, inhoud, methode met vergelijking, tabel met totalen, resultaten in grafieken, literatuur en vragen"],
"showcase_3d":["Catalogus: 3D tot in detail","3D-modellen met alle opties: weergaven, bewegingen bij binnenkomst, draaien, randen, marge, clips, lopen en aankomst met Morphen"],
"showcase_animations":["Catalogus: animaties","Alle objectanimaties: ingang, nadruk, uitgang, bewegingspaden, tekenen, gekoppeld, geluiden en meerdere op één object"],
"showcase_charts":["Catalogus: grafieken","De 15 grafiektypen, twee per dia, met reeksen, combinatie, raster, labels en astitels, plus de optietabel"],
"showcase_diagrams":["Catalogus: diagrammen","De 15 diagramindelingen als overzicht geschreven, de 4 kleurenschema’s en één voor één verschijnen tijdens het presenteren"],
"showcase_morph":["Catalogus: Morphen","Morphen stap voor stap: tekst die van grootte en plaats verandert, vormen, groeiende balken, afbeelding, 3D en letters die van plaats wisselen"],
"showcase_objects":["Catalogus: multimedia en objecten","Code met stappen, vergelijkingen, pictogrammen, vijf apparaten, tabellen met stijlen en formules, diazoom en verbindingslijnen"],
"showcase_polls":["Catalogus: peilingen en activiteiten","De 11 soorten peilingen en activiteiten via de telefoon, aftellen in drie stijlen, ranglijst en klasmodus"],
"showcase_shapes":["Catalogus: vormen","Alle vormen per categorie met hun naam, lijnen en streepjes, verlopen, dekking, handgetekend, schaduwen, tekst erin en draaien"],
"showcase_text":["Catalogus: Text Art en typografie","De 10 Text Art-stijlen, gebogen tekst, kolommen, vijf opsommingsniveaus, de 8 lettertypeparen, uitlijning en afstand"],
"showcase_transitions":["Catalogus: overgangen","Alle 22 dia-overgangen, één voor één: ingang, andere uitgang, richtingen, snelheid en automatisch doorgaan"]};
