// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Kwartaalresultaten voor de raad","Donkerblauw en goud: grote geanimeerde kpi's met geluid, waterval, trechter, gestapelde staven en tabel met formules tegenover het budget"],
"biz_climate":["Onderzoek naar het werkklimaat","Violet en interactief: aftelklok, 100%-staven, beoordeling van 1 tot 5, woordwolk, meerkeuze en vragen uit het publiek"],
"biz_investment":["Presentatie voor investeerders","Zwart en goud: 3D-product dat draait en meereist met Transformeren, gigantische cijfers, markt in cirkels, tractie, besteding van middelen en team"],
"biz_marketing":["Marketingplan voor een campagne","Warme stijl: tekst in een cirkel, doelgroep, trechter, kanaalmix, kalender als tabel, budget met formule en stemming"],
"biz_onboarding":["Welkom voor nieuwe medewerkers","Vriendelijke stijl: 3D-robot die zwaait en door de week loopt, organigram één voor één, waarden met pictogrammen en een koppelactiviteit"],
"biz_proposal":["Commercieel voorstel aan een klant","Papierstijl: zegel, proces één voor één, mock-ups op laptop en telefoon, prijzen, begroting met btw in formules, tijdlijn en garanties"],
"biz_retail_basket":["Mandjesanalyse: wat een kassabon vertelt","Kassabon die zichzelf afdrukt, vergelijking van het gemiddelde bonbedrag, waterval, spreidingsdiagram, productnetwerk, tabel, SQL-query, donut en quiz"],
"biz_retail_blackfriday":["Black Friday-campagne","Zwart en neon: prijskaartjes, cijfers met geluid, doorgestreepte prijzen, lijnen per uur, trechter, tabel met formules, quiz en aftelklok"],
"biz_retail_cx":["Klantbeleving: de reis van Marta","Getekende persona, emotiecurve die zichzelf tekent met gezichten na elkaar, citaten, NPS met vergelijking, matrix, Morph en beoordeling"],
"biz_retail_inventory":["Voorraad: geen tekorten, geen overschot","Getekend magazijn met stellingen en etiketten, contrast, Pareto als combinatiegrafiek, vergelijking, tabel met formules, code, 3D-lamp en ordenen"],
"biz_retail_loyalty":["Klantenbinding: de bakkerijclub","Stempelkaart die zich na elkaar vult met geluid en applaus, vergelijking van de klantwaarde, piramide van niveaus, tabel met formules en app"],
"biz_retail_market":["Gemeentelijke markthal: plan om hem nieuw leven in te blazen","IJzeren gevel met gebogen naam, krijtborden na elkaar, treemap, vlakken per uur, seizoenskalender in een tabel, 3D-avocado en woordwolk"],
"biz_retail_omni":["Omnichannel: online kopen, ophalen in de winkel","Getekende app in een telefoon en website in een browser, route die zichzelf tekent, 3D-bestelbus die door de straat rijdt, tabel met formule, code en 100 %-gestapelde staven"],
"biz_retail_opening":["Opening van een boekwinkel met café","Getekende gevel met luifel, buurtkaart met punten na elkaar, Venn, 3D-fauteuil, tijdlijn, tabel met formules en aftelklok"],
"biz_retail_supermarket":["Supermarkt: nieuwe indeling","Plattegrond van vormen, winkelwagen die door de winkel rijdt, heatmap, afdelingen die verschuiven met Morph, schap en tabel"],
"biz_retail_window":["Etalage: de herfstetalage","Editoriaal in zwart en ivoor: 3D-zonnebril met Morph, tekst in een cirkel, kleurstalen, getekende etalage met driehoek en blikvangers"],
"biz_roadmap":["Roadmap van een project","Donkere technische stijl: chevrons één voor één, geanimeerd Gantt-diagram, tijdlijn, 3D-auto die vooruitgaat met Transformeren en statustabel"],
"biz_sales":["Verkoop en jaarprognose","Minimalistisch grijs: gecombineerde staven en lijnen, scenario's, prognoseformule, tabel met formules, gestapelde en horizontale staven"],
"biz_startup_agrotech":["Agritech-pitch: irrigatie met sensoren","Luchtbeeld van percelen met vochtkaart, 3D-satelliet van NASA, telefoon, druppels in een keten met geluid, tabel met formules en treemap"],
"biz_startup_edtech":["Edtech-pitch: wiskundetutor","Ruitjesschrift: plakbriefjes in een keten, handschrift, vergelijkingen stap voor stap, telefoon, live quiz, cyclus en grafieken"],
"biz_startup_energy":["Energiepitch: zonnegemeenschap","Daken van dageraad tot nacht: zon die opkomt en in een boog door de lucht gaat, radiaal diagram, vlakken per uur, vergelijking en tabel met formules"],
"biz_startup_fashion":["Pitch circulaire mode: Retal","Kledinglabel dat reist met Morph, gestippelde naden, leven van een kledingstuk in een keten, cyclus, ring, radar en meerkeuzestemming"],
"biz_startup_insurance":["Verzekeringspitch: dekking per dag","Grijze regen en gele paraplu: pictogram in een keten, app met schakelaar, prijsvergelijking, tabel met formules, tijdlijn en stemming"],
"biz_startup_kitchen":["Pitch keukenrobotica: Fogón","Profkeuken: bonnen aan de rail, vuur-Text Art, 3D-robot die binnenloopt en zwaait, recept als code, aftelklok en trechter"],
"biz_startup_lastmile":["Logistiek-pitch: laatste kilometer","Metrokaartstijl: lijnen die zichzelf tekenen, 3D-vrachtwagen en fietsen die over de kaart rijden, tabel met formules, vlak en waterval"],
"biz_startup_mental":["Pitch mentale gezondheid: Remanso","Rustige nacht: ademende ringen, ademminuut met aftelklok, app op de telefoon, trap, beoordeling en tabel met formules"],
"biz_startup_pets":["Huisdierenpitch: vers voer","Stickerstijl met pootafdrukken in een keten, 3D-vos die overloopt, portieformule in een tabel, ring en quiz"],
"biz_startup_rural":["Pitch plattelandstoerisme: Alpende","Bergen bij schemering en ansichtkaarten: 3D-lantaarn, poststempel met gebogen tekst, kaart met 3D-auto langs de route, staven, taart en woordwolk"],
"biz_strategy":["Strategisch plan en OKR's","Strakke witte stijl: cijfers die na elkaar verschijnen, piramide, prioriteiten met pictogrammen, OKR-tabel, voortgangsbalken, radar en chevrons"],
"biz_swot":["SWOT-analyse en concurrentie","Grafietachtergrond: SWOT in kwadranten, strategiematrix, positioneringskaart, gegroepeerde staven, Venn, cirkeldiagram en meerkeuzestemming"],
"creative_bauhaus":["Bauhaus: vorm en functie","Geometrische Bauhauskunst: basisvormen die draaien en stuiteren, tijdlijn, raster met Morph en koppelopdracht"],
"creative_brutalism":["Brutalisme: een webmanifest","Brutalistische stijl: gigantische letters, zwarte blokken, verticale tekst, harde schaduwen, geanimeerd doorhalen, tabel en peiling"],
"creative_comic":["Strip: superkrachten van dieren","Stripstijl: plaatjes, spraak- en denkballonnen, stuiterende klanknabootsingen in Text Art, 3D-vos, grafiek en quiz"],
"creative_fashion":["Modeblad: trage herfst","Tijdschriftstijl: schreefkop, 3D-horloge op de cover, kolommen met initiaal, groot citaat, seizoenspalet en grafiek"],
"creative_glass":["Glassmorphism: financiële app","Doorschijnende kaarten op gekleurde gloed, app in een telefoon, ringdiagram, kaart met Morph en beoordelingspeiling"],
"creative_pixel":["Pixelart: je eerste videogame","Retrogamestijl: pixelsprites, scorebord, 3D-personages die lopen en springen, code stap voor stap, quiz en aftelklok"],
"creative_space":["Melkweg: kijken naar het verleden","Ruimtestijl: sterren, gloeiende nevels, 3D-modellen van NASA, sonde die langs de planeten reist, gebogen tekst en quiz"],
"creative_swiss_blood":["Campagne: geef bloed","Openbare affiche in wit en rood: druppel die met Morphen het scherm vult, proces, ja of wacht, ring, staven, mobiel en quiz"],
"creative_swiss_chairs":["Tentoonstelling: de moderne stoel","Zwitserse affiche in grijs en limoen: 3D-stoel die draait en reist met Morphen, tijdlijn, ring, 3D-fauteuil, tabel met formules en ordenen"],
"creative_swiss_designconf":["Designcongres: Raster 27","Grafiet en cyaan: het raster bouwt zichzelf op en verandert met Morphen, contourcijfer, formule, tijdlijn, CSS-code, woordwolk en pauze"],
"creative_swiss_film":["Filmfestival: het programma","Zwitsers in zwart en rood: reuzengetal dat met Morphen een band wordt, raster, tabel, staven, peiling en aftelling"],
"creative_swiss_foundation":["Jaarverslag van een stichting","Zwitsers in wit en kobaltblauw: reuzenjaartal, brief over de hele pagina, getallen na elkaar, formule, ring, vlak, pijlen en rekeningen met formules"],
"creative_swiss_games":["Schoolspelen: de huisstijl","Wit en magenta, eigen palet: SVG-pictogrammen, 3D-figuur door de stad, lijnen, medaillespiegel met formules, treden en quiz"],
"creative_swiss_museum":["Gids van het natuurhistorisch museum","Zwitserse bewegwijzering in zwart en geel: eigen plattegrond met geanimeerde route, lopende 3D-vos, kolommen, tabel, labelen en pictogrammen"],
"creative_swiss_orchestra":["Symfonieorkest: seizoen 26/27","Nachtblauw en amber: draaiende bogen, gebogen tekst, getallen op een notenbalk, cycli, tabel, formule, staven, peiling en applaus"],
"creative_swiss_publisher":["Najaarscatalogus van een uitgeverij","Crèmepapier en petrolgroen: boekenplank met verticale ruggen, SVG-omslagen, tablet, taart, bestelling met formules, kalender en gaten"],
"creative_swiss_typeface":["Proefboek van een nieuwe letter","Proefboek in wit en violet: letters die reizen met Morphen, gemeten anatomie, schaal met formule, glyphs, radar en licenties"],
"creative_synthwave":["Synthwave: festival Neón 86","Retrostijl jaren 80: zon met verloop, raster dat zichzelf tekent, gloeiend neon, Morph, dansende 3D-robot en woordwolk"],
"creative_watercolor":["Aquarel: moestuin op het balkon","Aquarel- en papierstijl: vlekken met radiaal verloop, handgetekende vormen, handschrift, tekening die zichzelf tekent en 3D"],
"creative_zen":["Japans minimalisme: thee","Japans minimalisme: veel wit, rode zon met Morph, verticale tekst, een ensō die zichzelf schildert en aftelklok"],
"data_ab_test":["A/B-experiment","Vergelijkingen, spreidingsdiagram met twee reeksen, kolommen met labels, conversietabel met formules en significantiecijfers"],
"data_city_air":["Luchtkwaliteit in Brisamar","Lucht die opklaart met Morph, wijzermeter, vergelijking, lijnen met gaten, radar, tabel met formules en beoordeling"],
"data_city_bikes":["Pedalia: een jaar deelfietsen","Kaart in metrostijl, fiets die een lijn volgt, cijfers met geluid, lijnen, gestapeld, app op telefoon, tabel en code"],
"data_city_budget":["Participatieve begroting","Burgeraffiche: stembus met vallende stembiljetten, ring, chevrons, combinatiegrafiek, uitslag met tromgeroffel, tabel met formules"],
"data_city_housing":["Wonen: de prijs van blijven","Architectentekening: plattegrond in SVG, oppervlakken op schaal, combinatiegrafiek, vergelijking, tabel met formules, spreiding en 3D-bank"],
"data_city_noise":["Het lawaai van Sotoverde","Golf die vanzelf opkomt, decibelliniaal met geluiden, vergelijking, geluidskaart, gestapelde staven, quiz en aftelling"],
"data_city_tourism":["Toerisme op Isla Marena","Reisaffiche: zon met gebogen tekst, pictogram, vlakken, rechthoeken, 100%-staven, 3D-wandelaar, tabel en ansichtkaart"],
"data_city_traffic":["Spitsverkeer","Nachtelijke controlekamer: kaart met getekende files, verkeerslicht dat aangaat, warmtetabel, formule van Webster, code en 3D-vrachtwagen"],
"data_city_trees":["Inventaris van de stadsbomen","Herbariumvel: getekende boom, 3D-plant met Morph, rechthoeken, histogram, vergelijking, tabel en koppelen"],
"data_city_waste":["Wat we weggooien in Villa Cardo","Containers die springen met geluid, reuzengetal, waterval, gestapeld, cirkeldiagram per kleur, trechter, koppelen en tabel"],
"data_city_water":["Het water van Fuentelinda","Stuwmeer dat leegloopt met Morph, lijnen, ring, staven, tarief met vergelijking en formules, douche met aftelling"],
"data_energy":["Energie en verbruik","Gestapelde vlakken per uur, lijnen met drie reeksen, treemap, kolommen met labels en berekende tarieventabel"],
"data_exec_panel":["Maandelijks managementdashboard","KPI's met verkeerslichten en minigrafieken, combinatie tegenover budget, small multiples, ringdiagram en stemming"],
"data_home_finance":["Persoonlijke financiën","Waterval van salaris naar spaargeld, cirkeldiagram, lijnen en vlak, tabellen met SOM, GEMIDDELDE, MAX en MIN"],
"data_market_study":["Marktonderzoek","Grote cijfers, treemap, bellen, spreidingsdiagram, horizontale staven met twee reeksen en 2 × 2-matrix"],
"data_population":["Bevolking en demografie","Bevolkingspiramide, histogram, horizontale staven, kruisende lijnen en indicatorentabel met formules"],
"data_sales_regions":["Verkoop per regio","Gegroepeerde, gestapelde en 100%-staven, combinatiegrafiek met doel, tabel met formuletotalen en geanimeerde KPI's"],
"data_satisfaction":["Tevredenheidsonderzoek","Ringdiagram met legenda, vergeleken radars, kolommen met labels, NPS, live beoordeling en woordwolk"],
"data_season_stats":["Het seizoen in cijfers","Reuzencijfers met geluid, ranglijst met formules, negatieve staven, lijnen, gestapelde staven en teamradar"],
"data_web_metrics":["Web- en marketingstatistieken","KPI's met minigrafieken, lijnen met vier reeksen, vlakken, conversietrechter, combinatiegrafiek en tabel met formules"],
"edu_bio_digestion":["De reis van een broodje","Metrokaart: lijn D tekent zichzelf, een broodje rijdt mee, vertrekbord als tabel, enzymen, staven, haltes ordenen en Text Art"],
"edu_bio_dna":["DNA, het recept van het leven","Neonlab: helix die zichzelf opbouwt, Text Art, basen die paren, Python-code stap voor stap, staven, mutatie en paren verbinden"],
"edu_bio_ecosystem":["Het bos: wie eet wie","Veldschrift van kraftpapier: lopende 3D-vos, voedselketen, web dat zichzelf tekent, piramide en 10 %-tabel, lijnen en labelen"],
"edu_bio_evolution":["Aanpassing: de snavel van de vinken","Nachtelijke zeekaart: schip dat een route vaart, getekende snavels, staven van de droogte, spreiding, cyclus, Transformeren van de snavel en quiz"],
"edu_bio_heart":["Het hart, een onvermoeibare pomp","Rood en blauw: getekende hartslag, reuzengetallen, getekende circuits, druppel door het hart, polsslag met aftellen en formules, 3D en quiz"],
"edu_bio_mendel":["Mendel en de erwten","Moestuinschrift: erwten die verschijnen, generaties met Transformeren, Punnett-vierkant, staven en ring, tijdlijn en quiz"],
"edu_bio_microbes":["Microben: de onzichtbare wereld","Oculair van een microscoop: gebogen tekst, Transformeren van 40 naar 400 keer, vormen van bacteriën, gist in lijnen, peiling en Text Art"],
"edu_bio_photosynthesis":["Fotosynthese: de groene fabriek","Blad in de zon: 3D-plant, geanimeerde in- en uitvoer, Transformeren naar de bladgroenkorrel, vergelijking, tabel met gemiddelden, aftellen, lijnen en gaten"],
"edu_bio_pollination":["Van bloem tot vrucht","Voorjaarsweide: vliegende bij, delen van de bloem, labelen, treemap, Transformeren van bloem tot vrucht, 3D-avocado, tijdlijn en woordwolk"],
"edu_bio_respiration":["Ademen: de reis van de lucht","Open lucht: ademende longen, weg van de lucht, Transformeren bij in- en uitademen, twee ringen, 3D-fles, aftellen en quiz"],
"edu_body":["Het menselijk lichaam","Labstijl: 3D-figuur met Morph, personage dat een route loopt, staafdiagram, het lichaam benoemen en quiz"],
"edu_cell":["De cel","Cel getekend met vormen, delen één voor één, Morph om in te zoomen, paren koppelen, diagram, 3D-plant en beoordeling"],
"edu_english":["Engels voor beginners","Klasmodus: kaarten die omdraaien met geluid, 3D-robot die loopt en zwaait, 3D-vos, drie vragen met punten, ranglijst en applaus"],
"edu_fractions":["Breuken","Neonstijl: getekende pizza's, vergelijkingen stap voor stap, optellen met Morph, gaten invullen, quiz en uitdaging met aftelklok"],
"edu_geo_cities":["De stad: hoe ze groeit","Stad bij nacht van bovenaf: neon-Text Art, vlakdiagram, getekende plattegronden, ringen met Transformeren, radiaal diagram en 3D-auto"],
"edu_geo_climograph":["Een klimaatdiagram lezen","Weerstation: stijgende thermometer, staven met lijn, tabel met formules, vergelijkingen, 3D-satelliet, koppelen en uitdaging met aftelklok"],
"edu_geo_coasts":["Kusten en getijden","Vuurtoren met draaiende lichtbundel, kustvormen een voor een, eroderende klif, getijden in diagram en tabel met formules, labelen"],
"edu_geo_continents":["Continenten en oceanen","Kinderatlas: continenten die met geluid verschijnen, treemap, ringdiagram van oceanen, 3D-robot die de wereld doorkruist, koppelen en labelen"],
"edu_geo_deserts":["Woestijnen","Duinen bij zonsondergang: trekkende karavaan, gouden Text Art, staaf- en lijndiagrammen, 3D-vos, getekende oase, doorgestreepte mythes en quiz"],
"edu_geo_mountains":["Bergen","Alpenposter: delen van het reliëf een voor een, temperatuurvergelijking en -tabel, vegetatiegordels als piramide, klimmende 3D-wandelaar en ordenen"],
"edu_geo_pyramids":["Bevolkingspiramides","Volkstellingsposter: piramide die staaf voor staaf ontstaat, drie vormen met Transformeren, lijndiagram, vergelijkingen, ordenen en quiz"],
"edu_geo_river":["De reis van een rivier","Aquarel: rivier die zich tekent terwijl een druppel hem volgt, zoom met Transformeren, debiet met vergelijking, tabel met formules en labelen"],
"edu_geo_timezones":["Tijdzones","Luchthavenbord met draaiende rijen, draaiende aarde met vergelijking, zon die de zones doorkruist, tabel met formules, 3D-horloge en invuloefening"],
"edu_geo_topomap":["Een topografische kaart lezen","Oriëntatiekaart: parcours dat zich tekent, schaal met vergelijking, tabel met formules, hoogtelijnen met Transformeren en 3D-loopster"],
"edu_hist_alandalus":["Al-Andalus: wetenschap en tuinen","Hoefijzerboog, tijdlijn stap voor stap, horizontale balken, draaiend astrolabium, ster met Morph, paren koppelen en peiling"],
"edu_hist_castle":["Kastelen en feodalisme","Kasteel bij nacht en 3D-ridder die de brug oversteekt, feodale piramide die verrijst, labelen, zon die de dag doorloopt, treemap en wapenschilden"],
"edu_hist_egypt":["Egypte, geschenk van de Nijl","Lapis lazuli en goud: zon die achter de piramides opkomt, geanimeerde overstroming, vlakdiagram, vergelijking, Morph, hiërogliefencartouche en ordenen"],
"edu_hist_greece":["Athene: de democratie ontstaat","Stijl zwartfigurige vaas: meander, gebogen tekst, Morph, ring, tempel die verrijst, ostraka met geluid, peiling en tabel"],
"edu_hist_maya":["De Maya: tijd en sterren","Jungle en jade: getallen van stippen en strepen, Morph naar grondtal 20, vergelijking, draaiende kalenderwielen, lichtslang en cacao"],
"edu_hist_mesopotamia":["Mesopotamië: het schrift ontstaat","Kleitablet die zichzelf schrijft, kaart met getekende rivieren, groeiende ziggoerat, grondtal 60 met formules, gatentekst en radiaal"],
"edu_hist_printing":["De boekdrukkunst: het boek vermenigvuldigt zich","Incunabelpagina: rode initiaal, gespiegelde letters gezet met Morph, pers die met geluid neerkomt, cijfers, balken en gatentekst"],
"edu_hist_rome":["Rome, ingenieurs van het rijk","Marmer en keizerlijk rood: Morph, triomfboog, weg in lagen met marcherende 3D-soldaat, aquaduct, vergelijking, formules en quiz"],
"edu_hist_silkroad":["De Zijderoute","Zijde en saffraan: karavaan op weg, kaart met getekende route, prijswaterval, tabel met formules, 3D-lantaarn, vergelijking en ordenen"],
"edu_hist_vikings":["Vikingen, zeevaarders van het noorden","Fjord onder het noorderlicht: schommelend schip, runen, doorgestreepte mythes met stempel, geanimeerde overtocht, cijfers met geluid, 3D-krijger, radar en koppelen"],
"edu_kids_colors":["De kleuren","Schildertafel: regenboog die zichzelf tekent, verfpotten met geluid, mengen met Morph, pictogrammen, koppelen, peiling en aftelling"],
"edu_kids_emotions":["Hoe voel ik me?","Een getekend gezicht dat van emotie wisselt met Morph, slinger van gezichten, ballon om te ademen, peiling en koppelen"],
"edu_kids_farm":["De dieren op de boerderij","Getekende boerderij met eigen dieren, lijnen die zichzelf trekken, tabel met som, rijdende 3D-vrachtwagen, lopende 3D-vos, quiz en labelen"],
"edu_kids_numbers":["De getallentrein","Getekende trein die binnenrijdt met geluid, één voor één tellen, verborgen getallen, som als vergelijking, grafiek, ordenen, quiz en aftelling"],
"edu_kids_sea":["Onder de zee","Zeebodem in verloop, getekende vissen die zwemmen, bellen, groot en klein, 3D-fles in de container, koppelen en woordwolk"],
"edu_kids_seasons":["De vier seizoenen","Een boom die met Morph door vier seizoenen verandert, vallende bladeren en sneeuw, jaarwiel, kringloop, koppelen en peiling"],
"edu_kids_senses":["De vijf zintuigen","Uitgeknipt karton: getekend gezicht, radiaal diagram, raadsels, knoppen met vijf geluiden, kaarten die omdraaien, labelen en aftelling"],
"edu_kids_shapes":["Vormen en blokken","Speelkleed: blokken met geluid, vormen die zichzelf tekenen, een huis dat met Morph een robot wordt, 3D-robot en piramide"],
"edu_kids_space":["Reis naar de maan","Nachthemel: raket die met geluid opstijgt, aftelling, maan die rond de aarde draait, fasen, 3D-astronaut en maanlander"],
"edu_kids_transport":["Hoe reizen we?","Wegenkleed: 3D-speelgoedauto, voertuigen die met geluid oversteken, verkeerslicht dat verspringt, grafiek, 3D-auto, koppelen en peiling"],
"edu_lang2_advent":["Duits: advent en kerst","Besneeuwde nacht: gouden Text Art, 3D-lantaarn, vallende sneeuwvlokken, adventskalender die opengaat, tijdlijn, labelen en recept met formules"],
"edu_lang2_artikel":["Duits: der, die, das","Bauhaus-affiche: vormen die met geluid verschijnen, uitgangen in een tabel, ringdiagram, Transformeren naar de accusatief, koppelen en quiz"],
"edu_lang2_cafe":["Frans: au café","Bistrobord onder de luifel: gebogen tekst, rekening met formules in de tabel, prijsvergelijking, dialoog, staven en invuloefening"],
"edu_lang2_directions":["Engels: hoe kom ik bij…?","Verzonnen metrokaart: een trein rijdt de route via een bewegingspad, zinnen onderweg, dialoog, getekende straat, ordenen, quiz en aftelklok"],
"edu_lang2_falsefriends":["Valse vrienden in het Engels","Detectivedossier: stempel met geluid, 3D-zonnebril, verdachten die omdraaien, bewijstabel, staven, doorhalingen en peiling"],
"edu_lang2_ola":["Portugees: Olá, Lisboa!","Tegeltjes en een gele tram die via een pad de heuvel op rijdt, groeten die omdraaien, klanktabel, chat op een telefoon en treemap"],
"edu_lang2_passato":["Italiaans: il passato prossimo","Ansichtkaart van de Rivièra: 3D-auto rijdt via een pad langs de kust, vergelijking, deelwoorden in een tabel, congruentie, invuloefening en quiz"],
"edu_lang2_phrasal":["Phrasal verbs: level up","Neonarcade: Text Art, Transformeren dat werkwoord en partikel verbindt, 3D-ridder die vooruitgaat, staven, doorhalen, koppelen en aftelklok"],
"edu_lang2_sons":["Frans: de klanken","Draaiende vinylplaat met gebogen tekst, nummers met geluid, verbindingen als boog getekend, regeltabel, radar, quiz en aftelklok"],
"edu_lang2_tenses":["Present perfect of past simple","Horlogerie: 3D-horloge met Transformeren, tijdlijn met een boog die zichzelf tekent, vergelijkingen, tabel, 100%-staven, boom en aftelklok"],
"edu_lang_accent":["Klemtonen zonder angst","Geruit schrift en rode pen: lettergrepen die klinken als ze oplichten, tabel, beslisboom, geanimeerde doorhalingen, plakbriefjes en quiz"],
"edu_lang_becquer":["Bécquer en de Rimas","Romantische nacht: zwaluwen die langs de maan vliegen, gebogen tekst, verzen die vanzelf verschijnen, 3D-lantaarn, tijdlijn, metrum in een tabel en invuloefening"],
"edu_lang_calderon":["Het leven is een droom","Doek dat opengaat en sluit met geluid, plattegrond van het theater, 3D-troon met Morph, monoloog vers voor vers, radiaal, weegschaal en quiz"],
"edu_lang_commentary":["Hoe je een tekst analyseert","Pagina met markeerstiften die zichzelf trekken en kanttekeningen, pijlen één voor één, tijdlijn, formule, aftelklok, rubric en radar"],
"edu_lang_fables":["Fabels: de vos en de druiven","Verhalenboek: 3D-vos die binnenwandelt, gebogen titel, tijdlijn, getekende wijnrank, treden, tabel, ordenen en woordwolk"],
"edu_lang_figures":["Stijlfiguren als strip","Popstrip: plaatjes, tekstballonnen en explosies met geluid, 3D-horloge dat langs een pad vliegt, verzen die kleuren en quiz"],
"edu_lang_genres":["Literaire genres","Bibliotheek bij nacht: boeken die op de plank springen, gestempelde fiches met geluid, Venn, hiërarchie, ring, peiling, koppelen en 3D-fauteuil"],
"edu_lang_lazarillo":["Lazarillo de Tormes","Perkament en lak: 3D-schelm die de kaart afloopt van meester naar meester, kaarten, tabel van meesters, hongerlijn, quiz en ordenen"],
"edu_lang_meter":["De muziek van het vers: metriek","Geluidsstudio: golf die zichzelf tekent, lettergrepen die tikken als een metronoom, formule met gevallen, synalefe, sonnet als sporen en quiz"],
"edu_lang_syntax":["Onderwerp en gezegde, als bouwtekening","Technische bouwtekening: stukken die op hun plek vallen met Morph, haken die zichzelf trekken, zinsboom, tabel, afbeelding labelen en quiz"],
"edu_math_coordinates":["Coördinaten: de schatkaart","Schatkaart: windroos met gebogen tekst, verschijnende punten, 3D-piraat die aanwijzingen volgt, boot die zichzelf tekent en labelen"],
"edu_math_integers":["Gehele getallen: zee en berg","Van zeebodem tot bergtop: getallenlijn met sprongen, Text Art ijs, temperaturen onder nul, onderzeeër die stijgt en daalt, ordenen en quiz"],
"edu_math_primes":["Priemgetallen","Groene terminal: eigen neon, zeef van Eratosthenes klik voor klik met 100 vakjes, factorboom, code stap voor stap, quiz en uitdaging"],
"edu_math_probability":["Kansrekening: geluk meten","Speeltafel in bordeaux en goud: rollende dobbelstenen met tromgeroffel, gebogen tekst, regel van Laplace, boom stap voor stap, staven, lijnen en quiz"],
"edu_math_proportion":["Evenredigheid in de supermarkt","Kassabon: stuiterende stempel, evenredigheidstabel met formules, regel van drie stap voor stap, berekende kortingen, lijnen en invuloefening"],
"edu_math_pythagoras":["De stelling van Pythagoras","Krijtbord: figuur die zichzelf tekent, bewijs zonder woorden met Morph, drietallen met formules, 3D-kortere weg en quiz"],
"edu_math_sequences":["Rijen en patronen","Botanisch boek: Fibonacci-spiraal die zichzelf tekent, steentjes in een ketting, lucifers met formules, code, 3D-plant en de gulden snede"],
"edu_math_stats":["Statistiek: gemiddelde, mediaan en modus","Ruitjesschrift: memoblaadjes in cascade, frequenties met formules, staven, ring met graden, histogram en live peiling"],
"edu_math_symmetry":["Symmetrie en betegelingen","Nasridische tegels: draaiende ster, spiegelende vlinder, geanimeerde verschuiving, draaiing en spiegeling, hoekentabel en honingraat"],
"edu_math_volumes":["Oppervlakten en inhouden","Blauwe bouwtekening: titelblok als tabel, uitslag, gemeten 3D-fles, inhouden met formules, staven, vullende kegels en koppelen"],
"edu_pe_active":["60 minuten per dag","Prikbord van kurk: notities met punaises, 3D-figuur die springt, week met formules, gestapelde staven, ring, code en ideeënmuur"],
"edu_pe_athletics":["Atletiek: lopen, springen, werpen","Tartanbaan: 3D-figuur, pictogrammen die draaien, vergelijking en tabel van de banen, start met geluid, histogram, ordenen en podium"],
"edu_pe_basketball":["Basketbal: schot en lay-up","Trainersbord: bal die met geluid stuitert, bemaat veld, getekende parabool, uitgetekende aanval, tabel met formules en benoemen"],
"edu_pe_calm":["Cooling-down: rekken en ademen","Rustige dageraad: 3D-plant, boxademhaling met bewegingspad, cirkel die groeit en krimpt, rekoefeningen, doelwit en woordwolk"],
"edu_pe_heart":["Het hart in beweging","Hartmonitor: ecg dat zichzelf tekent, polsaftelling, vergelijking, zones met formules, vlakdiagram, telefoon met app en quiz"],
"edu_pe_hydration":["Drink voordat je dorst hebt","Water en bellen: 3D-fles, lichaam dat volloopt, zweetstaven, glas met Morph, kleurenschaal en invuloefening"],
"edu_pe_nutrition":["Het bord van de sporter","Geruit tafelkleed: bord dat deel voor deel wordt opgediend, ring, 3D-avocado, ontbijtjes met formules, mythes die omdraaien, koppelen en woordwolk"],
"edu_pe_posture":["Een rug voor het leven","Sepiaplaat: wervelkolom wervel voor wervel, labels in een keten, rugzak met formules, zo niet en zo wel, 3D-stoel, aftelklok en benoemen"],
"edu_pe_sleep":["Slapen is ook trainen","Nachtraam: sterren die oplichten, 3D-lamp, hypnogram, cyclus, radiaal, telefoon met berichten, routine in een keten en beoordeling"],
"edu_pe_warmup":["Opwarmen voor het spel","Sportzaalparket: 3D-robot die rent, temperatuurlijn, chevrons, gewrichten met geluid, aftelklok, ordenen en quiz"],
"edu_quixote":["Don Quichot","Inkt-en-papierstijl: draaiende molen met geluid, gebogen tekst, geanimeerde citaten, Morph, tijdlijn, gaten invullen en quiz"],
"edu_renewables":["Hernieuwbare energie","Draaiende windturbine, kaarten, vlak-, ring- en gegroepeerde staafdiagrammen, live woordwolk, peiling en aftelklok"],
"edu_revolution":["De Franse Revolutie","Oudpapierstijl: tekst in een cirkel, Morph, maatschappijpiramide, geanimeerde tijdlijn met geluid, gebeurtenissen ordenen en peiling"],
"edu_spain":["Aardrijkskunde van Spanje","Atlasstijl: windroos, reliëf als doelwitdiagram, rivierentabel met formules, grafieken van toppen en neerslag, paren koppelen en quiz"],
"edu_volcanoes":["Vulkanen","Vuurstijl: geanimeerde uitbarsting met geluid, delen van de vulkaan benoemen, tabel, quiz op tijd en aftelklok"],
"edu_water":["De waterkringloop","Cyclusdiagram één voor één, landschap met stijgende druppels en geanimeerde regen met geluid, ringdiagrammen, paren koppelen en 3D-satelliet"],
"life_bookclub":["Leesclub","Boekenplank uit de vrije hand, omslag van vormen, citaten die transformeren, radiaal diagram, beoordeling en stemming over het volgende boek"],
"life_cv":["Visueel cv","Tekst in een cirkel, kerncijfers, tijdlijn stap voor stap, geanimeerde vaardigheidsbalken, radardiagram, schermen in apparaten en contact"],
"life_fitness":["Trainingsschema: 5 km","3D-hardloper, Text Art vuur, fasen met kleurverloop, week met formules, voortgangsgrafieken, piramide, aftelling en woordwolk"],
"life_garden":["Stadsmoestuin","3D-plant met Transformeren, zaaikalender als gekleurde tabel, cyclus, Venn, grafieken van water geven en groei, labelopdracht"],
"life_graduation":["Diploma-uitreiking en eind van het schooljaar","Gouden Text Art, afstudeerhoeden van vormen, polaroids die omklappen bij het verschijnen, cijfers met tromgeroffel, dankwoorden, woordwolk en applaus"],
"life_italy":["Reis door Italië","Tekst in een cirkel, route met verbindingslijnen en geanimeerd pad, tijdlijn, begroting met formules, grafieken en koppelopdracht"],
"life_kids_party":["Kinderverjaardag","Felle kleuren: dansende 3D-robot, juichende personages, ballonnen uit de vrije hand, quiz met punten en aftelling"],
"life_moving":["Verhuizing en nieuw thuis","Huis van vormen uit de vrije hand, tijdlijn, lijst die wordt doorgestreept, 3D-meubels die met Transformeren naar de plattegrond gaan, begroting en volgorde-opdracht"],
"life_recipe":["Recept: guacamole","3D-avocado die tussen dia's reist (Transformeren), ingrediënten met formules, stappen één voor één, aftelling en beoordeling"],
"life_travel_eu_amsterdam":["Amsterdam: grachten en fietsen","Grachtengevels die zich na elkaar opbouwen, grachten als schietschijf, fiets met geluid, tabel met formules, lijnen en taartpeiling"],
"life_travel_eu_camino":["Camino de Santiago: vanaf Sarria","Pelgrimspas die zich vult met stempels met geluid, kilometerwaterval, 3D-wandelaar, rugzakformule, ring en etappes ordenen"],
"life_travel_eu_croatia":["Kroatië: zeilen langs Dalmatië","Zeekaart, windroos die draait en reist met Morph, vlaggen, koppelen, mijlen met formules, quiz en aftelling"],
"life_travel_eu_danube":["De Donau op de fiets","Fietscomputerstijl: route op de telefoon, GPX-bestand stap voor stap, gestapelde staven, 3D-bidon met Morph, formules en rechthoeken"],
"life_travel_eu_fjords":["Noorse fjorden over het water","Gelaagd landschap met spiegelingen, varend schip, fjorddoorsnede die zichzelf tekent, staven, radar, etappes en meerkeuzepeiling"],
"life_travel_eu_greece":["Griekse eilanden per veerboot","Wit dorp van vormen, meander, route die zichzelf tekent, dienstregeling met formules, bellen, 3D-zonnebril met Morph en zonsondergang"],
"life_travel_eu_iceland":["IJsland: de Ring Road met de auto","Poollicht met verlopen, kaart met klinkend pad, 3D-auto, cijfers met tromgeroffel, kouformule, lopende vos en quiz"],
"life_travel_eu_lisbon":["Lissabon: heuvels en trams","SVG-tegels, tram die heuvels op rijdt langs een pad met geluid, hoogteprofiel, draaiende kaarten, tabel met formules en gaten"],
"life_travel_eu_prague":["Praag, de stad van honderd torens","Astronomische klok van vormen die draait en reist met Morph, optocht met klokje, aftelling, kaart om te labelen en tabel"],
"life_travel_eu_scotland":["Schotland: de Highlands met de auto","Tartan geweven uit vormen, weg die zichzelf tekent, auto’s die voorrang geven, draaiende kastelen, 3D-lantaarn, staven en vragen"],
"life_wedding":["Huwelijksuitnodiging","Klassieke letters en goud: Text Art, gebogen tekst, tijdlijn van het paar, kaart met geanimeerde route, peiling en aftelling"],
"prod_app_bank":["Cartilla: bankieren voor ouderen","Spaarboekje in leer en goud: gouden Text Art, Morphen om in te zoomen op de telefoon, tabel met SOM, waterval, stempel en quiz tegen fraude"],
"prod_app_gym":["Serie: reserveringen in je sportschool","LED-scorebord: 3D-vechter die juicht en naar de les loopt, twee aftelklokken, bezetting per uur, tarieven met formules en quiz"],
"prod_app_health":["Turno: afspraken bij het gezondheidscentrum","Klinisch: hartslag die zichzelf tekent, voor en na, cyclus één voor één, lopende 3D-patiënt, agenda op monitor, staven en vragen"],
"prod_app_language":["Vocablo: app om talen te leren","Luchtpostkaart: postzegels, tekstballonnen die met geluid opspringen, draaiende kaarten, Morphen, vergeetformule, grafiek en koppelen"],
"prod_app_market":["Plaza: de buurtmarkt aan huis","Luifel en krijtborden: 3D-bestelbus die de kaart afrijdt, kramen in radiaal, telefoon, rechthoeken, commissies met formules en stemming"],
"prod_app_meditation":["Marea: app voor meditatie en slaap","Nachtzee: maan met gebogen tekst, Morphen van de telefoon, begeleide ademhaling met ringen na elkaar, aftelklok, grafiek en 3D-lantaarn"],
"prod_app_music":["Garaje: livemuziek uit de buurt","Vinyl en neon: plaat die meereist met Morphen, draaiende gebogen tekst, equalizer met tromgeroffel, laptop, radar, taart en woordwolk"],
"prod_app_photo":["Grano: analoge fotografie","Donkere kamer: filmstrook, foto die zich ontwikkelt met Morphen, teller met tromgeroffel, histogram, tablet, tabel en labelen"],
"prod_app_recipes":["Sobras: recepten met wat er is","Koelkast met memoblaadjes: 3D-avocado met Morphen, telefoon die ingrediënten herkent, stappen, ring, recept met formules en aftelklok"],
"prod_app_transit":["Andén: stadsvervoer","Metrobewegwijzering: vertrekbord met aftelklok, kaart die zichzelf tekent, geanimeerde rit, telefoon, gestapelde staven en tarieven"],
"product_app":["Presentatie van een mobiele app","App op telefoon, tablet en laptop, Morph, gebruikersreis als chevrons, cijfers, retentiegrafiek en woordwolk"],
"product_car":["Presentatie: elektrische auto","3D-auto zonder afgesneden randen die bij binnenkomst rondgaat, Morph, cijfers, vlak- en staafdiagrammen, tabel en stemming"],
"product_eco":["Duurzaamheid van het product","Ecogroen: 3D-plant met Morph, levenscyclus, voetafdruk-waterval, materiaalstaven, lijnen met doel en gatentekst"],
"product_furniture":["Meubelcollectie","Redactionele stijl: 3D-banken en -stoelen, Morph met verschillende aanzichten, schommelen en rondgaan, kleurstalen, tablet en begroting"],
"product_keynote":["Hardware-keynote","Premium witte stijl: iriserende lamp en 3D-fles, Morph met labels, zweven en inzoomen, cijfers, tabel en prijzen"],
"product_roadmap":["Productroadmap","Weg die zichzelf tekent, piramide, tijdlijn één voor één, nu en straks, matrix, gestapelde staven, meerkeuzestemming en ordenen"],
"product_robot":["Industriële assistentrobot","Industriële stijl: 3D-robot die zwaait, een route loopt, animaties koppelt en danst; organigram, cyclus, grafiek en quiz"],
"product_saas":["Demo van een SaaS-platform","Dashboard in een browservenster met genummerde aanwijzingen, radiaal, trechter, KPI’s, gestapelde staven, code in stappen en vragen"],
"product_security":["Productbeveiliging","Groen neon: doelwit in lagen, stroom met verbindingen die stap voor stap verschijnt, gemarkeerde code, grafiek, trap en koppelopdracht"],
"product_watch":["Lancering: smartwatch","Zwart en goud: 3D-horloge reist met Morph en verschillende aankomsten over drie dia’s, gouden Text Art, radar en prijzen"],
"sci_ai":["Kunstmatige intelligentie","Violet neon: 3D-robot die zwaait en met Morph meereist, tijdlijn, organigram, neuraal netwerk dat oplicht, grafiek en woordwolk"],
"sci_astro_blackholes":["Zwarte gaten","Diepzwart: een horizon die meereist met Morph, gebogen tekst, reuzengetal, tabel met formules, 3D-astronaut in een spiraal en quiz"],
"sci_astro_cosmology":["Van de oerknal tot nu","Een heelal dat afkoelt: thermometer met Morph, tijdlijn in een ketting, kosmische achtergrond, spreiding, ring en kalender met formules"],
"sci_astro_defense":["Planetaire verdediging: oefening","Crisiskamer: gevarenstrepen, 3D-planetoïde, Torino-schaal in een ketting, geanimeerde afbuiging met geluid, aftelklok en teamstemming"],
"sci_astro_exoplanets":["Gezocht: andere werelden","Retro reisaffiches: een transit met getekende lichtcurve, Python-code, wiebelen met bewegingspaden, vlakdiagram, 3D-satelliet en peiling"],
"sci_astro_moon":["Selenografie: de Maan","Oude sepia-atlas: gegraveerde SVG-maan, fasen in een ketting, synchrone rotatie, getijden, 3D-maanlander met Morph en koppelen"],
"sci_astro_pulsars":["Pulsars: de vuurtorens van de kosmos","Oscilloscoopscherm: een signaal dat zichzelf tekent, een draaiende vuurtoren, hoorbare pulsen, 3D-radiotelescoop en -nevel, tabel en quiz"],
"sci_astro_skywatch":["Gids om de sterrenhemel te bekijken","Roodlichtmodus: planisfeer met gebogen tekst, aftelklok, sterrenbeelden die zichzelf tekenen, magnitudes, staven, tabel en peiling"],
"sci_astro_stars":["Leven en dood van sterren","Sterrenspectrum: klassen in een ketting, evenwicht met pijlen, eigen HR-diagram, splitsing naar massa, tabel met formules en 3D-supernova"],
"sci_astro_sun":["De zon, een ster van dichtbij","Karmozijnrood zonnefilter: lagen in een ketting, fusie met vergelijking, de reis van een foton, zonnevlekkencyclus, 3D-sonde met Morph en quiz"],
"sci_astro_telescopes":["Telescopen: de bouwtekening","Technische bouwtekening: stralen die zichzelf tekenen, 3D-Webb met Morph door het spectrum, zeshoekige spiegel in een ketting, reis naar L2 en labelen"],
"sci_brain":["Neurowetenschap: de hersenen","Donkere stijl met gloed: getekend neuron met geanimeerde impuls, lopende 3D-figuur, radiaal, organigram, staven en een afbeelding labelen"],
"sci_chem":["Scheikunde: het periodiek systeem","Strak lab: periodiek systeem dat zich als een waterval opbouwt, moleculen van vormen, 3D-vuurpot, vergelijkingen, ringdiagram en koppelen"],
"sci_climate":["Klimaatverandering in cijfers","Opwarmingsstrepen, lijn-, vlak- en treemapdiagram, broeikaseffect dat zichzelf tekent, 3D-satelliet, kringloop en meerkeuzestemming"],
"sci_mars":["Missie naar Mars","Roestkleurige ruimtestijl: 3D-rover van NASA met Morph, zwevende astronaut, geanimeerde baan, vergelijking en quiz"],
"sci_med_case":["Klinische casus: koorts en hoest","Stijl medisch dossier: map, stempel, röntgenfoto op lichtbak met cirkel die zichzelf tekent, CURB-65 met formule, peiling en vragen"],
"sci_med_ecg":["Cardiologie: een ecg lezen","Ecg-papier: curves die zichzelf tekenen, impuls door het hart, tabel met formules, vergelijking, quiz en aftelling"],
"sci_med_glucose":["Endocrinologie: glucose en insuline","Stijl glucosesensor-app: telefoon met scherm, cyclus één voor één, curves, ring, tabel met formules, vergelijking, 3D-avocado en peiling"],
"sci_med_immune":["Immunologie: de immuunrespons","Fluorescentiemicroscoop: cellen die oplichten, getekend antilichaam, fagocytose met Morph, organogram en koppelen"],
"sci_med_kidney":["Nierfysiologie: het nefron","Technische tekening: nefron dat zichzelf tekent, druppel die erdoor reist met geluid, maatlijnen, watervaldiagram, vergelijking, tabel met formules, 3D-fles en cyclus"],
"sci_med_knee":["Anatomie: de knie","Stijl oude anatomische plaat: gebogen tekst, sepiagravure, Morph naar de menisci, matrix, tabel, lopende 3D-figuur en labelen"],
"sci_med_micro":["Microbiologie: antibioticaresistentie","Petrischalen: kolonies die opduiken met geluid, exponentiële groei, selectie verteld met Morph, antibiogram, radiaal diagram en woordwolk"],
"sci_med_pk":["Farmacokinetiek: de halfwaardetijd","Stijl medicijndoosje: blister die zich vult, LADME één voor één, curves met twee reeksen, vergelijkingen, tabel met formules, code en invuloefening"],
"sci_med_stroke":["Neurologie: beroertecode","Race tegen de klok op de spoed: sirenelichten, reuzengetal met tromgeroffel, BE-FAST na elkaar, ring, chevrons, stappen ordenen en aftelling"],
"sci_med_trial":["Klinische studie: de resultaten lezen","Stijl wetenschappelijk tijdschrift: CONSORT met verbindingslijnen, overlevingscurves, tabel met formules, NNT, forest plot na elkaar en quiz"],
"sci_newton":["Natuurkunde: de wetten van Newton","Natuurkundeschrift: vergelijkingen, rijdende 3D-auto, kogelbaan die zichzelf tekent, tabel met formules en invuloefening"],
"sci_nurse_cpr":["Basale reanimatie: levensreddend handelen","Groene noodsignalisatie: handen die op het ritme drukken, AED-elektroden die met geluid vliegen, twee reeksen, aftelklok en ordenen"],
"sci_nurse_drip":["Infuustherapie: de druppelsnelheid berekenen","Getekende infuusset met vallende druppels en geluid, formule stap voor stap, uitgewerkt voorbeeld, rekenende tabel, pomp en aftelklok"],
"sci_nurse_falls":["Vallen bij ouderen: het veilige huis","Huis bij nacht met 3D-lamp: plattegrond met gevaren die met Morph worden opgelost, looptest met 3D-figuur, venn, donut en aftelklok"],
"sci_nurse_hands":["Handhygiëne: de 5 momenten","Tegels en bellen: opstijgende zeepbellen, de 5 momenten op een plattegrond, uv-lamp met geluid, aftelklok van 30 s, staven en quiz"],
"sci_nurse_heat":["Hittegolf: gezondheidsplan","Waarschuwingskleuren: stijgende thermometer, Text Art, getekende waarschuwingskaart, spreidingsdiagram, telefoon met de sms, 3D-fles, tabel en quiz"],
"sci_nurse_herd":["Vaccins: groepsimmuniteit","Vaccinatieboekje met stempels en gebogen tekst, besmettingsketen doorbroken met Morph, vergelijking, tabel met formules, doorgestreepte mythes"],
"sci_nurse_outbreak":["Een voedselgerelateerde uitbraak onderzoeken","Prikbord van kurk: vastgeprikte notities en rood draad dat zich tekent, epidemische curve, tabel met formules, relatief risico, code en peiling"],
"sci_nurse_pressure":["Doorligwonden: voorkomen","Thermische drukkaart: vlekken die oplichten en doven, Braden met formules, draaiende wisselligklok, huidlagen en labelen"],
"sci_nurse_sbar":["De dienstoverdracht met SBAR","Whiteboard van de afdeling: stift die vanzelf onderstreept, magneten en notities die met geluid plakken, dialoog in ketting, score met formule en koppelen"],
"sci_nurse_smoking":["Stoppen met roken: wat je lichaam wint","Van rook naar schone lucht: opstijgende rook, sigaret als tijdlijn, longen die veranderen met Morph, spaartabel en ademhaling"],
"sci_python":["Programmeren in Python","Donkere editorstijl: terminal die zichzelf typt, code met markeerstappen, geanimeerde uitvoer, regels ordenen en uitdaging met aftelklok"],
"sci_solar":["Het zonnestelsel","Planeten op schaal die na elkaar verschijnen, drie 3D-sondes met verschillende aanzichten en bewegingen, tabel, radiaal diagram en koppelen"],
"sci_stats":["Statistiek en kansrekening","Redactionele stijl: klokcurve die zichzelf tekent, formules, histogram, spreidings-, vlak-, staaf- en bellendiagram, en een vraag met punten"],
"sci_thesis":["Verdediging van de bachelorscriptie","Sober academisch: institutionele titelpagina, inhoud, methode met vergelijking, tabel met totalen, resultaten in grafieken, literatuur en vragen"],
"show_anim_bike":["Fietsversnellingen zonder geheimen","Gesynchroniseerde bewegingen: tandwielen die draaien in hun echte verhouding, wielen die hun afstand rollen, twee banen tegelijk en tabel"],
"show_anim_blueprint":["Verbouwing van een appartement: de plattegrond","Plattegrond die zichzelf tekent: muren na elkaar, maten, sloop die verdwijnt, Morph naar de nieuwe indeling, installaties en planning"],
"show_anim_ferries":["Veerboten tussen eilanden: zomerroutes","Bewegingspaden op een kaart: boten die meedraaien met de route, routes die zich tekenen terwijl ze varen, drie lijnen tegelijk, tussenstop en dienstregeling"],
"show_anim_firefly":["Verhaal: het vuurvliegje zonder licht","Een verhaal met in- en uitgangen: vertelling alleen zichtbaar in haar stap, dialogen die komen en gaan, vluchten en licht dat terugkeert"],
"show_anim_foosball":["Tafelvoetbaltoernooi op kantoor","Gekoppelde animaties met geluid als een spel: passes met een klik, schot, doelpunt met applaus, schema dat vordert, stand en pool"],
"show_anim_guitar":["Anatomie van de Spaanse gitaar","Triggers: klik op elk onderdeel van de gitaar voor de kaart en op elke snaar om die te laten trillen; draaiende rozet"],
"show_anim_haiku":["Haikuworkshop: woord voor woord","Animatie per woord en alinea: verzen woord voor woord, opdracht zin voor zin, getelde lettergrepen en Morph"],
"show_anim_rpg":["Tafelrollenspel: je eerste spel","3D-personages met hun animaties: aanvallen, blokkeren, spreuken werpen en vallen; naar de tegenstander lopen, rollende dobbelsteen en dalende levenspunten"],
"show_anim_speech":["Toespraak: red de bibliotheek","Nadruk op het ritme van een toespraak: zin in focus en de rest gedimd, doorstrepen, markeren, onderstreping en cirkel met de hand, aftellen"],
"show_anim_tshirt":["Infographic: de reis van een T-shirt","Infographic die zich onthult: route die zich tekent met haar haltes op tijd, pictogram van druppels dat zich vult, waterval, cijfers en formule"],
"showcase_3d":["Catalogus: 3D tot in detail","3D-modellen met alle opties: weergaven, bewegingen bij binnenkomst, draaien, randen, marge, clips, lopen en aankomst met Morphen"],
"showcase_animations":["Catalogus: animaties","Alle objectanimaties: ingang, nadruk, uitgang, bewegingspaden, tekenen, gekoppeld, geluiden en meerdere op één object"],
"showcase_charts":["Catalogus: grafieken","De 15 grafiektypen, twee per dia, met reeksen, combinatie, raster, labels en astitels, plus de optietabel"],
"showcase_diagrams":["Catalogus: diagrammen","De 15 diagramindelingen als overzicht geschreven, de 4 kleurenschema’s en één voor één verschijnen tijdens het presenteren"],
"showcase_morph":["Catalogus: Morphen","Morphen stap voor stap: tekst die van grootte en plaats verandert, vormen, groeiende balken, afbeelding, 3D en letters die van plaats wisselen"],
"showcase_objects":["Catalogus: multimedia en objecten","Code met stappen, vergelijkingen, pictogrammen, vijf apparaten, tabellen met stijlen en formules, diazoom en verbindingslijnen"],
"showcase_polls":["Catalogus: peilingen en activiteiten","De 11 soorten peilingen en activiteiten via de telefoon, aftellen in drie stijlen, ranglijst en klasmodus"],
"showcase_shapes":["Catalogus: vormen","Alle vormen per categorie met hun naam, lijnen en streepjes, verlopen, dekking, handgetekend, schaduwen, tekst erin en draaien"],
"showcase_text":["Catalogus: Text Art en typografie","De 10 Text Art-stijlen, gebogen tekst, kolommen, vijf opsommingsniveaus, de 8 lettertypeparen, uitlijning en afstand"],
"showcase_transitions":["Catalogus: overgangen","Alle 22 dia-overgangen, één voor één: ingang, andere uitgang, richtingen, snelheid en automatisch doorgaan"]};
