// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Resultados trimestrais ao conselho","Azul-escuro e dourado: grandes indicadores animados com som, cascata, funil, barras empilhadas e tabela com fórmulas face ao orçamento"],
"biz_climate":["Pesquisa de clima organizacional","Violeta e participativo: contagem decrescente, barras a 100 %, avaliação de 1 a 5, nuvem de palavras, escolha múltipla e perguntas do público"],
"biz_investment":["Apresentação para investidores","Preto e dourado: produto 3D que gira e viaja com Transformar, números gigantes, mercado em círculos, tração, uso dos fundos e equipa"],
"biz_marketing":["Plano de marketing de campanha","Estilo quente: texto em círculo, público-alvo, funil, mix de canais, calendário em tabela, orçamento com fórmula e votação"],
"biz_onboarding":["Boas-vindas a novos funcionários","Estilo amigável: robô 3D que acena e percorre a semana a andar, organograma um a um, valores com ícones e atividade de associar"],
"biz_proposal":["Proposta comercial a um cliente","Estilo papel: selo, processo um a um, maquetas em portátil e telemóvel, preços, orçamento com IVA em fórmulas, cronologia e garantias"],
"biz_retail_basket":["Análise do cabaz: o que conta um talão","Talão de caixa que se imprime, equação do talão médio, cascata, dispersão, rede de produtos, tabela, consulta SQL, anel e quiz"],
"biz_retail_blackfriday":["Campanha de Black Friday","Preto e néon: etiquetas de preço, números com som, preços riscados, linhas por hora, funil, tabela com fórmulas, quiz e contagem decrescente"],
"biz_retail_cx":["Experiência do cliente: a jornada da Marta","Persona desenhada, curva de emoções que se traça sozinha com caras em cadeia, citações, NPS com equação, matriz, Transformar e avaliação"],
"biz_retail_inventory":["Inventário: nem ruturas nem excessos","Armazém desenhado com estantes e etiquetas, comparação, Pareto em gráfico combinado, equação, tabela com fórmulas, código, candeeiro 3D e ordenar"],
"biz_retail_loyalty":["Fidelização: o clube da padaria","Cartão de carimbos que se enche em cadeia com som e aplausos, equação do valor do cliente, pirâmide de níveis, tabela com fórmulas e app"],
"biz_retail_market":["Mercado municipal: plano para o reavivar","Fachada de ferro com nome curvo, quadros de giz em cadeia, treemap, áreas por hora, calendário da época em tabela, abacate 3D e nuvem de palavras"],
"biz_retail_omni":["Omnicanal: compra online, levanta na loja","App no telemóvel e site no navegador desenhados, rota que se traça sozinha, carrinha 3D que percorre a rua, tabela com fórmula, código e barras empilhadas a 100 %"],
"biz_retail_opening":["Abertura de uma livraria-café","Fachada desenhada com toldo, mapa do bairro com pontos em cadeia, Venn, cadeirão 3D, cronologia, tabela com fórmulas e contagem decrescente"],
"biz_retail_supermarket":["Supermercado: nova disposição","Planta feita de formas, carrinho que percorre a loja, mapa de calor, secções que se reposicionam com Transformar, linear e tabela"],
"biz_retail_window":["Vitrinismo: a montra de outono","Editorial em preto e marfim: óculos 3D com Transformar, texto em círculo, amostras de cor, montra desenhada com triângulo e pontos focais"],
"biz_roadmap":["Roteiro de um projeto","Estilo técnico escuro: divisas uma a uma, diagrama de Gantt animado, cronologia, carro 3D que avança com Transformar e tabela de estado"],
"biz_sales":["Vendas e previsão anual","Minimalista em cinzento: barras e linhas combinadas, cenários, fórmula de previsão, tabela com fórmulas, barras empilhadas e horizontais"],
"biz_startup_agrotech":["Pitch agrotech: rega com sensores","Vista aérea de parcelas com mapa de humidade, satélite 3D da NASA, telemóvel, gotas em cadeia com som, tabela com fórmulas e treemap"],
"biz_startup_edtech":["Pitch edtech: tutor de matemática","Caderno quadriculado: post-its em cadeia, letra manuscrita, equações passo a passo, telemóvel, quiz ao vivo, ciclo e gráficos"],
"biz_startup_energy":["Pitch energia: comunidade solar","Telhados da madrugada à noite: sol que nasce e cruza o céu em arco, diagrama radial, áreas por hora, equação e tabela com fórmulas"],
"biz_startup_fashion":["Pitch moda circular: Retal","Etiqueta de roupa que viaja com Transformar, costuras tracejadas, vida de uma peça em cadeia, ciclo, anel, radar e votação múltipla"],
"biz_startup_insurance":["Pitch seguros: cobertura por dias","Chuva cinzenta e guarda-chuva amarelo: pictograma em cadeia, app com interruptor, equação do preço, tabela com fórmulas, cronologia e votação"],
"biz_startup_kitchen":["Pitch robótica de cozinha: Fogón","Cozinha profissional: comandas no trilho, Text Art de fogo, robô 3D que entra a andar e acena, receita em código, contagem decrescente e funil"],
"biz_startup_lastmile":["Pitch logística: última milha","Estilo mapa de metro: linhas que se desenham sozinhas, camião 3D e bicicletas que percorrem o mapa, tabela com fórmulas, área e cascata"],
"biz_startup_mental":["Pitch saúde mental: Remanso","Noite calma: anéis que respiram, minuto de respiração com contagem decrescente, app no telemóvel, escada, avaliação e tabela com fórmulas"],
"biz_startup_pets":["Pitch animais: comida fresca","Estilo autocolante com pegadas que aparecem em cadeia, raposa 3D que atravessa a andar, fórmula da ração numa tabela, anel e quiz"],
"biz_startup_rural":["Pitch turismo rural: Alpende","Montanhas ao entardecer e postais: lanterna 3D, carimbo com texto curvo, mapa com carro 3D pela rota, barras, circular e nuvem de palavras"],
"biz_strategy":["Plano estratégico e OKR","Estilo branco e limpo: números que entram em sequência, pirâmide, prioridades com ícones, tabela de OKR, barras de progresso, radar e divisas"],
"biz_swot":["Análise SWOT e concorrência","Fundo grafite: SWOT por quadrantes, matriz de estratégias, mapa de posicionamento, barras agrupadas, Venn, gráfico circular e votação múltipla"],
"creative_bauhaus":["Bauhaus: forma e função","Arte geométrica Bauhaus: formas primárias que giram e quicam, cronologia, grade com Transformar e atividade de associar"],
"creative_brutalism":["Brutalismo: manifesto web","Estilo brutalista: tipografia gigante, blocos pretos, texto vertical, sombras duras, riscado animado, tabela e votação"],
"creative_comic":["Quadrinhos: superpoderes animais","Estilo quadrinhos: quadros, balões de fala e pensamento, onomatopeias em Text Art que quicam, raposa 3D, gráfico e quiz"],
"creative_fashion":["Revista de moda: outono lento","Estilo revista: cabeçalho com serifa, relógio 3D na capa, colunas com capitular, citação grande, paleta da estação e gráfico"],
"creative_glass":["Glassmorphism: app de finanças","Cartões translúcidos sobre brilhos coloridos, app no celular, gráfico de rosca, cartão com Transformar e votação de avaliação"],
"creative_pixel":["Pixel art: o teu primeiro videojogo","Estilo videogame retrô: sprites de pixels, placar, personagens 3D que andam e pulam, código passo a passo, quiz e contagem regressiva"],
"creative_retro_atomic":["Retrofuturismo: o futuro de 1962","Era atómica: casa disco voador que se transforma, acertos e falhas em cadeia, robô 3D que anda, radar, matriz, contagem decrescente e nuvem de palavras"],
"creative_retro_deco":["Art déco: o Grande Hotel faz 100 anos","Art déco em ouro e preto: leque que se transforma, Text Art dourado, elevador como cronologia, sofá 3D, tabela com fórmulas e quiz"],
"creative_retro_desktop90":["Anos 90: cópias de segurança","Ambiente de trabalho dos anos 90: janelas cinzentas, erros em cascata, barra de progresso, equação, tabela com fórmulas, código passo a passo e quiz"],
"creative_retro_diner":["Anos 50: o café reabre","Café dos anos 50: letreiro de néon, chão xadrez, toldo, camião 3D na estrada, ementa com fórmulas, anel, selo que gira e votação"],
"creative_retro_letterpress":["Cartaz de tipografia: as festas do bairro","Cartaz de tipos de madeira: tinta desalinhada, letras que caem com som, programa, barras empilhadas, cascata, edital, votação e contagem decrescente"],
"creative_retro_sepia":["Álbum sépia: procura os teus avós","Álbum sépia: cantos de fotografia, letra manuscrita, equação dos antepassados, árvore que cresce, mapa com viagem desenhada, circular, associar e Transformar"],
"creative_retro_teletext":["Teletexto: a liga do bairro","Páginas de teletexto: linhas que carregam sozinhas, marcador e classificação com fórmulas, barras, colunas, quiz e contagem decrescente"],
"creative_retro_typewriter":["Máquina de escrever: oficina de conto","Folha e máquina de escrever: linhas datilografadas com som, riscado e correção à mão, arco que se desenha, barras, lacunas e contagem decrescente"],
"creative_retro_vapor":["Vaporwave: a música das lojas","Vaporwave pastel: lua que se transforma, palmeiras em SVG, títulos glitch, dispersão, candeeiro 3D, tabela com média e avaliação"],
"creative_retro_vinyl":["Anos 70: o clube do vinil","Estilo setentista: arco-íris às riscas, discos desenhados que giram, número gigante, linhas, barras, sofá 3D, atividade de ordenar e autocolante"],
"creative_space":["Galáxia: olhar para o passado","Estilo espacial: estrelas, nebulosas brilhantes, modelos 3D da NASA, sonda que percorre os planetas, texto curvo e quiz"],
"creative_swiss_blood":["Campanha: doe sangue","Cartaz público em branco e vermelho: gota que enche o ecrã com Transformar, processo, sim ou espera, anel, barras, telemóvel e quiz"],
"creative_swiss_chairs":["Exposição: a cadeira moderna","Cartaz suíço cinzento e lima: cadeira 3D que gira e viaja com Transformar, cronologia, anel, poltrona 3D, tabela com fórmulas e ordenar"],
"creative_swiss_designconf":["Congresso de design: Grelha 27","Grafite e ciano: a grelha monta-se sozinha e muda com Transformar, número em contorno, fórmula, cronologia, código CSS, nuvem e pausa"],
"creative_swiss_film":["Festival de cinema: o programa","Suíço em preto e vermelho: número gigante que vira faixa com Transformar, secções em grelha, tabela, barras, votação e contagem"],
"creative_swiss_foundation":["Relatório anual de uma fundação","Suíço em branco e azul-cobalto: ano gigante, carta a toda a cor, números em cadeia, equação, anel, área, setas e contas com fórmulas"],
"creative_swiss_games":["Jogos escolares: a identidade","Branco e magenta, paleta própria: pictogramas SVG, figura 3D que percorre a cidade, linhas, quadro de medalhas com fórmulas, degraus e quiz"],
"creative_swiss_museum":["Guia do museu de história natural","Sinalética suíça em preto e amarelo: planta própria com percurso animado, raposa 3D que anda, colunas, tabela, legendar e pictogramas"],
"creative_swiss_orchestra":["Orquestra sinfónica: temporada 26/27","Azul-noite e âmbar: arcos que giram, texto curvo, números numa pauta, ciclos, tabela, equação, barras, votação e aplausos"],
"creative_swiss_publisher":["Catálogo de outono de uma editora","Papel creme e verde-petróleo: estante de lombadas verticais, capas em SVG, tablet, tarte, encomenda com fórmulas, calendário e lacunas"],
"creative_swiss_typeface":["Mostruário de uma nova tipografia","Mostruário em branco e violeta: letras que viajam com Transformar, anatomia medida, escala com fórmula, glifos, radar e licenças"],
"creative_synthwave":["Synthwave: festival Neón 86","Estilo retrô anos 80: sol em degradê, grade que se desenha, néon brilhante, Transformar, robô 3D que dança e nuvem de palavras"],
"creative_watercolor":["Aquarela: horta na varanda","Estilo aquarela e papel: manchas com degradê radial, formas à mão livre, letra manuscrita, desenho que se traça sozinho e 3D"],
"creative_zen":["Minimalismo japonês: o chá","Minimalismo japonês: muito branco, sol vermelho que se transforma, texto vertical, ensō que se pinta sozinho e contagem regressiva"],
"data_ab_test":["Experimento A/B","Equações, dispersão de duas séries, colunas com rótulos, tabela de conversão com fórmulas e números de significância"],
"data_city_air":["Qualidade do ar em Brisamar","Céu que limpa com Transformar, índice com ponteiro, equação, linhas com falhas, radar, tabela com fórmulas e avaliação"],
"data_city_bikes":["Pedalia: um ano de bicicleta partilhada","Mapa tipo metro, bicicleta que percorre uma linha, números com som, linhas, empilhadas, app no telemóvel, tabela e código"],
"data_city_budget":["Orçamento participativo","Cartaz cívico: urna com boletins a cair, anel, divisas, gráfico combinado, resultados com rufar de tambores, tabela com fórmulas"],
"data_city_housing":["Habitação: o preço de ficar","Planta de arquiteto: planta em SVG, áreas à escala, gráfico combinado, equação, tabela com fórmulas, dispersão e sofá 3D"],
"data_city_noise":["O ruído de Sotoverde","Onda que sobe sozinha, régua de decibéis com sons, equação, mapa de ruído, barras empilhadas, quiz e contagem decrescente"],
"data_city_tourism":["Turismo na Isla Marena","Cartaz de viagem: sol com texto curvo, pictograma, áreas, retângulos, barras a 100 %, caminhante 3D, tabela e postal"],
"data_city_traffic":["Trânsito na hora de ponta","Sala de controlo noturna: mapa com filas traçadas, semáforo que acende, tabela de calor, fórmula de Webster, código e camião 3D"],
"data_city_trees":["Inventário das árvores urbanas","Folha de herbário: árvore desenhada, planta 3D com Transformar, retângulos, histograma, equação, tabela e associar"],
"data_city_waste":["O que deitamos fora em Villa Cardo","Contentores que saltam com som, número gigante, cascata, empilhadas, circular por cores, funil, associar e tabela"],
"data_city_water":["A água de Fuentelinda","Albufeira que se esvazia com Transformar, linhas, anel, barras, tarifa com equação e fórmulas, duche com contagem decrescente"],
"data_energy":["Energia e consumo","Áreas empilhadas por hora, linhas de três séries, mapa de árvore, colunas com rótulos e tabela de tarifas calculada"],
"data_exec_panel":["Painel executivo mensal","KPIs com semáforos e minigráficos, combinado face ao orçamento, pequenos múltiplos, rosca e votação"],
"data_home_finance":["Finanças pessoais","Cascata do salário à poupança, gráfico de pizza, linhas e área, tabelas com SOMA, MÉDIA, MÁXIMO e MÍNIMO"],
"data_market_study":["Estudo de mercado","Números grandes, mapa de árvore, bolhas, dispersão, barras horizontais de duas séries e matriz 2 × 2"],
"data_population":["População e demografia","Pirâmide etária, histograma, barras horizontais, linhas que se cruzam e tabela de indicadores com fórmulas"],
"data_sales_regions":["Vendas por região","Barras agrupadas, empilhadas e a 100 %, gráfico combinado com meta, tabela com totais por fórmula e KPIs animados"],
"data_satisfaction":["Pesquisa de satisfação","Rosca com legenda, radares comparados, colunas com rótulos, NPS, avaliação e nuvem de palavras ao vivo"],
"data_season_stats":["A temporada em números","Números gigantes com som, classificação com fórmulas, barras negativas, linhas, empilhadas e radar da equipe"],
"data_sport_climb":["Etapa rainha: o Alto de Peñaroja","Livro de estrada: perfil colorido que um ciclista sobe, tabela de subidas com fórmulas, equação da potência, dispersão, anel e óculos 3D"],
"data_sport_elo":["Elo: como se mede a força","Tabuleiro noturno: cavaleiro 3D, equações, curva esperada, exemplo passo a passo, histograma, tabela com fórmulas, código e quiz"],
"data_sport_load":["Carga de treino e lesões","Ficha de fisioterapia: mapa do corpo, equação ACWR com marcador que avança, linhas, colunas empilhadas, código, tabela com fórmulas, ciclo e figura 3D"],
"data_sport_marathon":["Maratona: o que contam as chegadas","Dorsal na capa, números com som, histograma de chegadas, o muro do km 30, lebre robô 3D que corre, tabela com fórmulas e medalha"],
"data_sport_serve":["Anatomia de um serviço","Terra batida: bola que salta, serviços no court e zoom ao quadrado com Transformar, radar, barras a 100 %, equação e votação"],
"data_sport_shots":["De onde se ganha: o mapa de lançamentos","Parquet de madeira: lançamento traçado, equação eFG, meio campo com zonas por eficácia, barras a 100 %, linhas que se cruzam e quiz"],
"data_sport_sprint":["100 metros em 9,94 segundos","Estádio à noite: marca em néon, fases em divisas, velocidade a cada 10 m, tabela com fórmulas, photo finish, relógio 3D e contagem decrescente"],
"data_sport_stadium":["Encher o estádio","Bilhete de jogo: bancadas por ocupação, áreas, dispersão de duas séries, retângulos, funil, tabela com fórmulas, votação e cadeira 3D"],
"data_sport_swim":["Braçada a braçada: 200 m livres","Piscina vista de cima: nadadora que faz quatro piscinas, equação, pequenos múltiplos, colunas empilhadas, tabela com fórmulas e nuvem de palavras"],
"data_sport_xg":["Golos esperados (xG)","Quadro sobre a relva: remates traçados, marcador frente ao xG, mapa de remates um a um, equação logística, código, tabela e quiz"],
"data_web_metrics":["Métricas web e marketing","KPIs com minigráficos, linhas de quatro séries, áreas, funil de conversão, gráfico combinado e tabela com fórmulas"],
"edu_bio_digestion":["A viagem de uma sandes","Mapa do metro: a linha D desenha-se, uma sandes percorre-a, painel de partidas em tabela, enzimas, barras, ordenar paragens e Text Art"],
"edu_bio_dna":["O ADN, a receita da vida","Laboratório néon: hélice que se monta sozinha, Text Art, bases que emparelham, código Python passo a passo, barras, mutação e unir pares"],
"edu_bio_ecosystem":["O bosque: quem come quem","Caderno de campo em papel kraft: raposa 3D que anda, cadeia trófica, rede que se desenha, pirâmide e tabela dos 10 %, linhas e legendar"],
"edu_bio_evolution":["Adaptação: o bico dos tentilhões","Carta náutica noturna: barco que navega uma rota, bicos desenhados, barras da seca, dispersão, ciclo, Transformar do bico e quiz"],
"edu_bio_heart":["O coração, uma bomba incansável","Vermelho e azul: batimento desenhado, números gigantes, circuitos traçados, gota pelo coração, pulso com contagem decrescente e fórmulas, 3D e quiz"],
"edu_bio_mendel":["Mendel e as ervilhas","Caderno de horta: ervilhas que aparecem, gerações com Transformar, quadro de Punnett, barras e anel, linha do tempo e quiz"],
"edu_bio_microbes":["Micróbios: o mundo invisível","Ocular de microscópio: texto curvo, Transformar de 40 a 400 aumentos, formas de bactérias, levedura em linhas, votação e Text Art"],
"edu_bio_photosynthesis":["Fotossíntese: a fábrica verde","Folha ao sol: planta 3D, entradas e saídas animadas, Transformar até ao cloroplasto, equação, tabela com médias, contagem decrescente, linhas e lacunas"],
"edu_bio_pollination":["Da flor ao fruto","Prado de primavera: abelha que voa, partes da flor, legendar, treemap, Transformar de flor em fruto, abacate 3D, cronologia e nuvem"],
"edu_bio_respiration":["Respirar: a viagem do ar","Céu aberto: pulmões que respiram, caminho do ar, Transformar ao inspirar e expirar, dois anéis, garrafa 3D, contagem decrescente e quiz"],
"edu_body":["O corpo humano","Estilo laboratório: figura 3D com Transformar, personagem que caminha por um percurso, gráfico de barras, legendar o corpo e questionário"],
"edu_cell":["A célula","Célula desenhada com formas, partes uma a uma, Transformar para aproximar, associar pares, diagrama, planta 3D e avaliação"],
"edu_english":["Inglês para iniciantes","Modo aula: cartões que viram com som, robô 3D que anda e acena, raposa 3D, três perguntas com pontos, classificação e aplausos"],
"edu_fractions":["Frações","Estilo néon: pizas desenhadas, equações passo a passo, soma com Transformar, preencher lacunas, questionário e desafio com contagem decrescente"],
"edu_geo_cities":["A cidade: como cresce","Cidade noturna vista de cima: Text Art néon, gráfico de área, plantas desenhadas, anéis com Transformar, diagrama radial e carro 3D"],
"edu_geo_climograph":["Ler um climograma","Estação meteorológica: termómetro que sobe, barras com linha, tabela com fórmulas, equações, satélite 3D, associar e desafio com contagem decrescente"],
"edu_geo_coasts":["Costas e marés","Farol com feixe que gira, formas da costa uma a uma, falésia que se erode, marés em gráfico e tabela com fórmulas, legendar"],
"edu_geo_continents":["Continentes e oceanos","Atlas infantil: continentes que aparecem com som, mapa de árvore, anel dos oceanos, robô 3D que atravessa o mundo, associar e legendar"],
"edu_geo_deserts":["Os desertos","Dunas ao pôr do sol: caravana que avança, Text Art dourado, gráficos de barras e de linhas, raposa 3D, oásis desenhado, mitos riscados e quiz"],
"edu_geo_mountains":["As montanhas","Cartaz alpino: partes do relevo uma a uma, equação e tabela de temperatura, andares em pirâmide, caminhante 3D que sobe e ordenar"],
"edu_geo_pyramids":["Pirâmides etárias","Cartaz de recenseamento: pirâmide construída barra a barra, três formas com Transformar, gráfico de linhas, equações, ordenar e quiz"],
"edu_geo_river":["A viagem de um rio","Aguarela: rio que se desenha enquanto uma gota o percorre, zoom com Transformar, caudal com equação, tabela com fórmulas e legendar"],
"edu_geo_timezones":["Fusos horários","Painel de aeroporto com linhas que giram, Terra que roda com equação, Sol que cruza os fusos, tabela com fórmulas, relógio 3D e lacunas"],
"edu_geo_topomap":["Ler um mapa topográfico","Mapa de orientação: percurso que se desenha, escala com equação, tabela com fórmulas, curvas de nível com Transformar e corredora 3D"],
"edu_hist_alandalus":["Al-Andalus: ciência e jardins","Arco em ferradura, cronologia um a um, barras horizontais, astrolábio que gira, estrela com Transformar, associar pares e votação"],
"edu_hist_castle":["Castelos e feudalismo","Castelo noturno e cavaleiro 3D que atravessa a ponte, pirâmide feudal que se ergue, legendar, sol que percorre o dia, treemap e brasões"],
"edu_hist_egypt":["Egito, a dádiva do Nilo","Lápis-lazúli e ouro: sol a nascer atrás das pirâmides, cheia animada, gráfico de áreas, equação, Transformar, cartucho hieroglífico e ordenar"],
"edu_hist_greece":["Atenas: nasce a democracia","Estilo vaso de figuras negras: meandro, texto curvo, Transformar, anel, templo que se ergue, óstraka com som, votação e tabela"],
"edu_hist_maya":["Os maias: tempo e estrelas","Selva e jade: números de pontos e barras, Transformar para base 20, equação, rodas de calendário que giram, serpente de luz e cacau"],
"edu_hist_mesopotamia":["Mesopotâmia: nasce a escrita","Tábua de argila que se escreve sozinha, mapa com rios desenhados, zigurate que cresce, base 60 com fórmulas, completar lacunas e radial"],
"edu_hist_printing":["A imprensa: o livro multiplica-se","Página incunábula: capitular vermelha, tipos invertidos compostos com Transformar, prensa que desce com som, números, barras e lacunas"],
"edu_hist_rome":["Roma, engenheiros do império","Mármore e vermelho imperial: Transformar, arco triunfal, estrada em camadas com soldado 3D a marchar, aqueduto, equação, fórmulas e concurso"],
"edu_hist_silkroad":["A Rota da Seda","Seda e açafrão: caravana em marcha, mapa com rota traçada, cascata do preço, tabela com fórmulas, lanterna 3D, equação e ordenar"],
"edu_hist_vikings":["Vikings, navegadores do norte","Fiorde sob a aurora: barco que balança, runas, mitos riscados com carimbo, travessia animada, números com som, guerreiro 3D, radar e associar"],
"edu_kids_colors":["As cores","Mesa de pintura: arco-íris que se desenha sozinho, frascos com som, misturas com Transformar, ícones, associar, votação e contagem decrescente"],
"edu_kids_emotions":["Como me sinto?","Uma cara desenhada que muda de emoção com Transformar, grinalda de caras, balão para respirar, votação e associar"],
"edu_kids_farm":["Os animais da quinta","Quinta desenhada com animais próprios, linhas que se traçam, tabela com soma, camião 3D em andamento, raposa 3D que caminha, quiz e legendar"],
"edu_kids_numbers":["O comboio dos números","Comboio desenhado que entra com som, contar um a um, números escondidos, soma em equação, gráfico, ordenar, quiz e contagem decrescente"],
"edu_kids_sea":["Debaixo do mar","Fundo do mar em degradê, peixes desenhados que nadam, bolhas, grande e pequeno, garrafa 3D para o contentor, associar e nuvem de palavras"],
"edu_kids_seasons":["As quatro estações","Uma árvore que muda com Transformar nas quatro estações, folhas e neve a cair, roda do ano, ciclo, associar e votação"],
"edu_kids_senses":["Os cinco sentidos","Cartolina recortada: cara desenhada, diagrama radial, adivinhas, botões com cinco sons, cartões que viram, legendar e contagem decrescente"],
"edu_kids_shapes":["Formas e blocos","Tapete de jogos: blocos com som, formas que se desenham sozinhas, casa que vira robô com Transformar, robô 3D e pirâmide"],
"edu_kids_space":["Viagem à Lua","Céu noturno: foguetão que descola com som, contagem decrescente, Lua que gira à volta da Terra, fases, astronauta e módulo lunar 3D"],
"edu_kids_transport":["Como viajamos?","Tapete de estradas: carro de brincar 3D, veículos que passam com som, semáforo que muda, gráfico, carro 3D, associar e votação"],
"edu_lang2_advent":["Alemão: Advento e Natal","Noite de neve: Text Art dourado, lanterna 3D, flocos a cair, calendário do Advento que se abre, cronologia, legendar e receita com fórmulas"],
"edu_lang2_artikel":["Alemão: der, die, das","Cartaz Bauhaus: formas que entram com som, terminações em tabela, anel, Transformar para o acusativo, associar e quiz"],
"edu_lang2_cafe":["Francês: au café","Quadro de bistrô sob o toldo: texto curvo, conta com fórmulas na tabela, equação de preços, diálogo, barras e lacunas"],
"edu_lang2_directions":["Inglês: como chegar a…","Mapa de metro inventado: um comboio percorre o trajeto com uma trajetória, frases pelo caminho, diálogo, rua desenhada, ordenar, quiz e contagem decrescente"],
"edu_lang2_falsefriends":["Falsos amigos em inglês","Processo de detetive: carimbo com som, óculos 3D, suspeitos que viram, tabela de provas, barras, riscados e votação"],
"edu_lang2_ola":["Português: Olá, Lisboa!","Azulejos e elétrico amarelo que sobe a colina com uma trajetória, saudações que viram, tabela de sons, chat num telemóvel e mapa em árvore"],
"edu_lang2_passato":["Italiano: il passato prossimo","Postal da Riviera: carro 3D que percorre a costa com uma trajetória, equação, particípios em tabela, concordância, lacunas e quiz"],
"edu_lang2_phrasal":["Phrasal verbs: level up","Arcade de néon: Text Art, Transformar que une verbo e partícula, cavaleiro 3D que avança, barras, riscado, associar e contagem decrescente"],
"edu_lang2_sons":["Francês: os sons","Vinil que gira com texto curvo, faixas com som, ligações desenhadas em arco, tabela de regras, radar, quiz e contagem decrescente"],
"edu_lang2_tenses":["Present perfect ou past simple","Relojoaria: relógio 3D com Transformar, linha do tempo com arco que se desenha, equações, tabela, barras a 100 %, árvore e contagem decrescente"],
"edu_lang_accent":["O acento sem medo","Caderno quadriculado e caneta vermelha: sílabas que soam ao acender, tabela, árvore de decisão, riscos animados, post-its e quiz"],
"edu_lang_becquer":["Bécquer e as Rimas","Noite romântica: andorinhas que cruzam a lua, texto curvo, versos que aparecem sozinhos, lanterna 3D, cronologia, métrica em tabela e lacunas"],
"edu_lang_calderon":["A vida é sonho","Pano que abre e fecha com som, planta do corral, trono 3D com Transformar, monólogo verso a verso, radial, balança e quiz"],
"edu_lang_commentary":["Como comentar um texto","Página com marcadores que se traçam sozinhos e notas na margem, setas uma a uma, cronologia, equação, contagem decrescente, rubrica e radar"],
"edu_lang_fables":["Fábulas: a raposa e as uvas","Livro de contos: raposa 3D que entra a andar, título curvo, cronologia, parreira desenhada, degraus, tabela, ordenar e nuvem de palavras"],
"edu_lang_figures":["Figuras de estilo em banda desenhada","Banda desenhada pop: vinhetas, balões e explosões com som, relógio 3D que voa por uma trajetória, versos que se colorem e quiz"],
"edu_lang_genres":["Os géneros literários","Biblioteca à noite: livros que sobem à estante, fichas carimbadas com som, Venn, hierarquia, anel, votação, associar e poltrona 3D"],
"edu_lang_lazarillo":["O Lazarilho de Tormes","Pergaminho e lacre: pícaro 3D que percorre o mapa de amo em amo, cartões, tabela de amos, linha da fome, quiz e ordenar"],
"edu_lang_meter":["A música do verso: métrica","Estúdio de som: onda que se desenha, sílabas que soam como um metrónomo, equação por casos, sinalefa, soneto por pistas e quiz"],
"edu_lang_syntax":["Sujeito e predicado, em planta","Planta técnica: peças que se ordenam com Transformar, parênteses que se traçam, árvore sintática, tabela, legendar imagem e quiz"],
"edu_math_coordinates":["Coordenadas: o mapa do tesouro","Mapa do tesouro: rosa dos ventos com texto curvo, pontos que aparecem, pirata 3D que segue pistas, barco que se desenha e legendar"],
"edu_math_integers":["Números inteiros: mar e montanha","Do fundo do mar ao cume: reta com saltos, Text Art gelo, temperaturas negativas, submarino que sobe e desce, ordenar e quiz"],
"edu_math_primes":["Números primos","Terminal verde: néon próprio, crivo de Eratóstenes clique a clique com 100 casas, árvore de fatores, código passo a passo, quiz e desafio"],
"edu_math_probability":["Probabilidade: medir a sorte","Mesa de jogo bordô e ouro: dados que rolam com rufar de tambor, texto curvo, regra de Laplace, árvore um a um, barras, linhas e quiz"],
"edu_math_proportion":["Proporcionalidade no supermercado","Talão de compras: carimbo que salta, tabela de proporcionalidade com fórmulas, regra de três passo a passo, descontos calculados, linhas e lacunas"],
"edu_math_pythagoras":["O teorema de Pitágoras","Quadro de giz: figura que se desenha sozinha, demonstração sem palavras com Transformar, ternos com fórmulas, atalho em 3D e quiz"],
"edu_math_sequences":["Sequências e padrões","Livro de botânica: espiral de Fibonacci que se traça sozinha, pedras em cadeia, palitos com fórmulas, código, planta 3D e número de ouro"],
"edu_math_stats":["Estatística: média, mediana e moda","Caderno quadriculado: notas adesivas em cascata, frequências com fórmulas, barras, rosca com graus, histograma e votação ao vivo"],
"edu_math_symmetry":["Simetria e mosaicos","Azulejos nasridas: estrela que gira, borboleta que se reflete, translação, rotação e simetria animadas, tabela de ângulos e favo"],
"edu_math_volumes":["Áreas e volumes","Planta técnica azul: carimbo em tabela, planificação, garrafa 3D medida, volumes com fórmulas, barras, cones que enchem e associação"],
"edu_pe_active":["60 minutos por dia","Quadro de cortiça: notas com pioneses, personagem 3D que salta, semana com fórmulas, barras empilhadas, anel, código e mural de ideias"],
"edu_pe_athletics":["Atletismo: correr, saltar, lançar","Pista de tartan: personagem 3D, pictogramas que viram, equação e tabela de pistas, partida com sons, histograma, ordenar e pódio"],
"edu_pe_basketball":["Basquetebol: lançamento e bandeja","Quadro de treinador: bola que salta com som, campo cotado, parábola traçada, jogada desenhada, tabela com fórmulas e legendar"],
"edu_pe_calm":["Retorno à calma: alongar e respirar","Amanhecer calmo: planta 3D, respiração em caixa com trajetória, círculo que cresce e encolhe, alongamentos, alvo e nuvem de palavras"],
"edu_pe_heart":["O coração em movimento","Monitor cardíaco: eletro que se traça sozinho, contagem do pulso, equação, zonas com fórmulas, área, telemóvel com app e quiz"],
"edu_pe_hydration":["Bebe antes de ter sede","Água e bolhas: garrafa 3D, corpo que se enche, barras do suor, copo com Transformar, escala de cor e preencher lacunas"],
"edu_pe_nutrition":["O prato do desportista","Toalha aos quadrados: prato servido por partes, anel, abacate 3D, pequenos-almoços com fórmulas, mitos que viram, associar e nuvem de palavras"],
"edu_pe_posture":["Umas costas para toda a vida","Lâmina sépia: coluna vértebra a vértebra, legendas em cadeia, mochila com fórmulas, assim não e assim sim, cadeira 3D, contagem decrescente e legendar"],
"edu_pe_sleep":["Dormir também é treinar","Janela noturna: estrelas que se acendem, candeeiro 3D, hipnograma, ciclo, radial, telemóvel com mensagens, rotina em cadeia e avaliação"],
"edu_pe_warmup":["Aquecer antes de jogar","Parquet de pavilhão: robô 3D que corre, linha de temperatura, divisas, articulações com som, contagem decrescente, ordenar e quiz"],
"edu_quixote":["Dom Quixote","Estilo tinta e papel: moinho que gira com som, texto curvo, citações animadas, Transformar, cronologia, preencher lacunas e questionário"],
"edu_renewables":["Energias renováveis","Aerogerador que gira, cartões, gráficos de área, anel e barras agrupadas, nuvem de palavras ao vivo, votação e contagem decrescente"],
"edu_revolution":["A Revolução Francesa","Estilo papel antigo: texto em círculo, Transformar, pirâmide social, cronologia animada com som, ordenar factos e votação"],
"edu_spain":["Geografia de Espanha","Estilo atlas: rosa dos ventos, relevo em alvo, tabela de rios com fórmulas, gráficos de picos e chuvas, associar pares e questionário"],
"edu_volcanoes":["Os vulcões","Estilo fogo: erupção animada com som, partes do vulcão para legendar, tabela, questionário com tempo e contagem decrescente"],
"edu_water":["O ciclo da água","Diagrama de ciclo um a um, paisagem com gotas que sobem e chuva animada com som, gráficos de anel, associar pares e satélite 3D"],
"learn_revela_ai":["A IA do Revela","Uma conversa sob a aurora: criar uma apresentação, reescrever textos (com Transformar por palavras), imagens, o assistente e mais ajudas"],
"learn_revela_anim":["Animações passo a passo","Um teatro: entrada, ênfase, saída e trajetórias, início com ou após a anterior, painel de animação, mais efeitos e sons"],
"learn_revela_collab":["Colaborar e partilhar","Um quadro de cortiça: colaborar ao mesmo tempo, permissões de partilha, comentários e tarefas reais, ligações, versões e uma atividade de associar"],
"learn_revela_design":["Design: modelo global, temas e cores","Um mostruário: modelo global e esquemas, temas, paletas e tipos de letra, contraste calculado, Text Art, texto curvo e ideias de design"],
"learn_revela_export":["Exportar e levá-la contigo","Um painel de partidas: PDF, PowerPoint, vídeo, página web, SCORM, imprimir com notas e atalhos de teclado, com votação final"],
"learn_revela_first":["A tua primeira apresentação em 5 minutos","Uma receita em cinco passos: galeria de exemplos, esquemas de diapositivo, escrever, inserir uma imagem e apresentar, com contagem decrescente"],
"learn_revela_live":["Votações e atividades em direto","Um estúdio de concurso: votação, nuvem de palavras, questionário com pontos, contagem decrescente, classificação e atividade de ordenar, a sério"],
"learn_revela_morph":["Transformar: a metamorfose","Da lagarta à borboleta com Transformar: duplicar para animar, por objetos, por palavras e por carateres, em diapositivos que se transformam"],
"learn_revela_pptx":["Importar um PowerPoint e continuar","Uma mudança: como importar um .pptx, o que se mantém (modelo global, animações, Transformar, notas) e como voltar a exportá-lo"],
"learn_revela_present":["Apresentar como um profissional","Um cockpit: vista do orador, notas, comando no telemóvel, ponteiro laser e tinta, quadro branco, contagem decrescente e atalhos"],
"life_bookclub":["Clube de leitura","Estante à mão livre, capa feita de formas, citações que se transformam, diagrama radial, avaliação e votação do próximo livro"],
"life_cv":["Currículo visual","Texto em círculo, números, cronologia passo a passo, barras de competências animadas, radar, ecrãs em dispositivos e contacto"],
"life_fitness":["Plano de treino: 5 km","Corredor 3D, Text Art fogo, fases com gradientes, semana com fórmulas, gráficos de progresso, pirâmide, contagem decrescente e nuvem de palavras"],
"life_garden":["Horta urbana","Planta 3D com Transformar, calendário de sementeira em tabela de cores, ciclo, Venn, gráficos de rega e crescimento, atividade de legendar"],
"life_graduation":["Formatura e fim de ano letivo","Text Art dourado, capelos feitos de formas, polaroides que giram ao entrar, números com rufar de tambores, agradecimentos, nuvem de palavras e aplausos"],
"life_italy":["Viagem pela Itália","Texto em círculo, rota com conectores e percurso animado, cronologia, orçamento com fórmulas, gráficos e atividade de associar"],
"life_kids_party":["Aniversário infantil","Cores vivas: robô 3D que dança, personagens que celebram, balões à mão livre, concurso com pontos e contagem decrescente"],
"life_moving":["Mudança e novo lar","Casa com formas à mão livre, cronologia, lista que se risca, móveis 3D que passam para a planta com Transformar, orçamento e atividade de ordenar"],
"life_recipe":["Receita: guacamole","Abacate 3D que viaja entre diapositivos (Transformar), ingredientes com fórmulas, passos um a um, contagem decrescente e avaliação"],
"life_travel_eu_amsterdam":["Amesterdão: canais e bicicletas","Fachadas de canal que se montam em cadeia, canais em alvo, bicicleta que passa com som, tabela com fórmulas, linhas e votação em tarte"],
"life_travel_eu_camino":["Caminho de Santiago: desde Sarria","Credencial que se enche de carimbos com som, cascata de quilómetros, caminhante 3D, equação da mochila, anel e ordenar etapas"],
"life_travel_eu_croatia":["Croácia à vela pela Dalmácia","Carta náutica, rosa dos ventos que gira e viaja com Transformar, bandeiras, associar, milhas com fórmulas, quiz e contagem decrescente"],
"life_travel_eu_danube":["O Danúbio de bicicleta","Estilo ciclocomputador: rota no telemóvel, ficheiro GPX passo a passo, barras empilhadas, garrafa 3D com Transformar, fórmulas e retângulos"],
"life_travel_eu_fjords":["Fiordes noruegueses pela água","Paisagem em camadas com reflexos, barco a navegar, corte do fiorde que se desenha, barras, radar, etapas uma a uma e votação múltipla"],
"life_travel_eu_greece":["Ilhas gregas de ferry","Aldeia branca de formas, grega, rota que se desenha, horários com fórmulas, bolhas, óculos 3D com Transformar e pôr do sol"],
"life_travel_eu_iceland":["Islândia: a Ring Road de carro","Auroras em degradê, mapa com percurso sonoro, carro 3D, números com rufar, equação do frio, raposa que caminha e quiz"],
"life_travel_eu_lisbon":["Lisboa: colinas e elétricos","Azulejos em SVG, elétrico que sobe as colinas num percurso com som, perfil de altitude, cartões que giram, tabela com fórmulas e lacunas"],
"life_travel_eu_prague":["Praga, a cidade das cem torres","Relógio astronómico de formas que gira e viaja com Transformar, desfile com sino, contagem decrescente, mapa para legendar e tabela"],
"life_travel_eu_scotland":["Escócia: Highlands de carro","Tartã tecido com formas, estrada que se desenha, carros que cedem passagem, castelos que giram, lanterna 3D, barras e perguntas"],
"life_wedding":["Convite de casamento","Tipografia clássica e dourado: Text Art, texto curvo, cronologia do casal, mapa com percurso animado, votação e contagem decrescente"],
"prod_app_bank":["Cartilla: banco para idosos","Caderneta de poupança em pele e ouro: Text Art ouro, Transformar para aproximar o telemóvel, tabela com SOMA, cascata, carimbo e quiz contra a fraude"],
"prod_app_gym":["Serie: reservas no teu ginásio","Placar LED: lutador 3D que celebra e anda até à aula, duas contagens decrescentes, ocupação por hora, tarifas com fórmulas e quiz"],
"prod_app_health":["Turno: consultas no centro de saúde","Clínico: batimento que se desenha, antes e depois, ciclo um a um, paciente 3D que anda, agenda no monitor, barras e perguntas"],
"prod_app_language":["Vocablo: app para aprender idiomas","Postal de correio aéreo: selos, balões que saltam com som, cartões que viram, Transformar, equação do esquecimento, gráfico e associar"],
"prod_app_market":["Plaza: o mercado do bairro em casa","Toldo e quadros de giz: carrinha 3D que percorre o mapa, bancas em radial, telemóvel, retângulos, comissões com fórmulas e votação"],
"prod_app_meditation":["Marea: app de meditação e sono","Mar noturno: lua com texto curvo, Transformar do telemóvel, respiração guiada com anéis encadeados, contagem decrescente, gráfico e lanterna 3D"],
"prod_app_music":["Garaje: música ao vivo do bairro","Vinil e néon: disco que viaja com Transformar, texto curvo que gira, equalizador com rufar, portátil, radar, circular e nuvem de palavras"],
"prod_app_photo":["Grano: fotografia de rolo","Câmara escura: tira de filme, foto que se revela com Transformar, contador com rufar, histograma, tablet, tabela e legendar"],
"prod_app_recipes":["Sobras: receitas com o que há","Frigorífico com post-its: abacate 3D com Transformar, telemóvel que reconhece ingredientes, passos, anel, receita com fórmulas e contagem decrescente"],
"prod_app_transit":["Andén: transporte urbano","Sinalética de metro: painel de partidas com contagem decrescente, mapa que se desenha sozinho, viagem animada, telemóvel, barras empilhadas e tarifas"],
"prod_hw_drone":["Cernícalo: drone de resgate em montanha","Mapa topográfico: voo que se desenha com o drone a percorrê-lo, helicóptero 3D da NASA, vista térmica, contagem decrescente, fórmulas e quiz"],
"prod_hw_ereader":["Folio: leitor de tinta eletrónica","Livro com virar de página: capitular, leitor desenhado, microcápsulas que aparecem, número e barras, citação, tabela com fórmulas e lacunas"],
"prod_hw_glasses":["Horizonte: óculos com dados para ciclistas","A estrada através da lente: óculos 3D com Transformar, partes numeradas com som, barras, código YAML passo a passo, radial e votação"],
"prod_hw_headphones":["Silencio: auscultadores com cancelamento de ruído","Câmara anecoica: ondas que se desenham e se anulam, equação, processo passo a passo, curva por frequências, tabela com fórmulas e votação"],
"prod_hw_keyboard":["Tecla: teclado mecânico modular","Teclas que saltam com som de clique, curvas de força, vista explodida por camadas, mapa de teclas em código, orçamento com fórmulas e ordenar"],
"prod_hw_lamp":["Alba: candeeiro despertador","Amanhecer em degradê: o sol sobe com Transformar, candeeiro 3D que viaja, cronologia, curva de luz com equação, escala Kelvin e avaliação"],
"prod_hw_thermostat":["Templa: termóstato inteligente","Mostrador de termóstato e casa em corte com temperaturas que aparecem, cascata de poupança, equações, linhas de 24 horas, matriz e votação"],
"prod_hw_toycar":["Chispa: carro para aprender a programar","Tapete de jogo: carro 3D com Transformar, cartas que saltam com som, tabuleiro percorrido, código, quiz, escada e donut"],
"prod_hw_tracker":["Miga: localizador para não perder nada","Mapa do tesouro: migalhas que aparecem uma a uma até ao X, círculo à mão que se desenha, donut, alvo, rasto pelo bairro e nuvem de palavras"],
"prod_hw_trailcam":["Vigía: câmara de armadilha fotográfica","Visor infravermelho: raposa 3D que passa e dispara a câmara, alcance do sensor desenhado, números, áreas por hora, tabela com SOMA e associar"],
"product_app":["Apresentação de app móvel","App em telemóvel, tablet e portátil, Transformar, percurso em divisas, números, gráfico de retenção e nuvem de palavras"],
"product_car":["Apresentação: carro elétrico","Carro 3D sem corte nas bordas que dá a volta ao entrar, Transformar, números, gráficos de área e barras, tabela e votação"],
"product_eco":["Sustentabilidade do produto","Verde eco: planta 3D com Transformar, ciclo de vida, cascata da pegada, barras de materiais, linhas com meta e preencher lacunas"],
"product_furniture":["Coleção de móveis","Estilo editorial: sofás e cadeiras 3D, Transformar com vistas diferentes, balanço e volta, amostras de cor, tablet e orçamento"],
"product_keynote":["Keynote de hardware","Estilo branco premium: candeeiro iridescente e garrafa 3D, Transformar com etiquetas, flutuar e aproximar, números, tabela e preços"],
"product_roadmap":["Roteiro de produto","Caminho que se desenha sozinho, pirâmide, cronologia um a um, agora e depois, matriz, barras empilhadas, votação múltipla e de ordenar"],
"product_robot":["Robô assistente industrial","Estilo industrial: robô 3D que acena, percorre um caminho, encadeia animações e dança; organograma, ciclo, gráfico e quiz"],
"product_saas":["Demo de plataforma SaaS","Painel em janela de navegador com chamadas numeradas, radial, funil, indicadores, barras empilhadas, código por passos e perguntas"],
"product_security":["Segurança do produto","Néon verde: alvo em camadas, fluxo com conectores que aparece passo a passo, código destacado, gráfico, escada e atividade de correspondência"],
"product_watch":["Lançamento: relógio inteligente","Preto e ouro: relógio 3D que viaja por três diapositivos com Transformar e chegadas diferentes, Text Art dourado, radar e preços"],
"sci_ai":["Inteligência artificial","Néon violeta: robô 3D que acena e viaja com Transformar, cronologia, organograma, rede neuronal que se acende, gráfico e nuvem de palavras"],
"sci_astro_blackholes":["Buracos negros","Negro absoluto: horizonte que viaja com Transformar, texto curvo, número gigante, tabela com fórmulas, astronauta 3D em espiral e quiz"],
"sci_astro_cosmology":["Do Big Bang até hoje","Um universo que arrefece: termómetro com Transformar, cronologia em cadeia, fundo cósmico, dispersão, anel e calendário com fórmulas"],
"sci_astro_defense":["Defesa planetária: simulacro","Sala de crise: faixas de perigo, asteroide 3D, escala de Turim em cadeia, desvio animado com som, contagem decrescente e votação de equipas"],
"sci_astro_exoplanets":["Procuram-se outros mundos","Cartazes de viagem retro: trânsito com a curva de luz desenhada, código Python, oscilação com trajetórias, área, satélite 3D e votação"],
"sci_astro_moon":["Selenografia: a Lua","Atlas antigo em sépia: Lua gravada em SVG, fases em cadeia, rotação síncrona, marés, módulo lunar 3D com Transformar e emparelhar"],
"sci_astro_pulsars":["Pulsares: os faróis do cosmos","Ecrã de osciloscópio: sinal que se traça sozinho, farol que gira, pulsos que soam, radiotelescópio e nebulosa 3D, tabela e quiz"],
"sci_astro_skywatch":["Guia para observar o céu","Modo luz vermelha: planisfério com texto curvo, contagem decrescente, constelações que se traçam sozinhas, magnitudes, barras, tabela e votação"],
"sci_astro_stars":["Vida e morte das estrelas","Espectro estelar: classes em cadeia, equilíbrio com setas, diagrama H-R próprio, bifurcação por massa, tabela com fórmulas e supernova 3D"],
"sci_astro_sun":["O Sol, uma estrela de perto","Filtro solar carmesim: camadas em cadeia, fusão com equação, a viagem de um fotão, ciclo de manchas, sonda 3D com Transformar e quiz"],
"sci_astro_telescopes":["Telescópios: a planta","Estilo planta técnica: raios que se desenham, Webb 3D com Transformar pelo espetro, espelho hexagonal em cadeia, viagem a L2 e legendar"],
"sci_brain":["Neurociência: o cérebro","Estilo escuro com brilhos: neurónio desenhado com impulso animado, figura 3D que caminha, radial, organograma, barras e legendar uma imagem"],
"sci_chem":["Química: a tabela periódica","Laboratório limpo: tabela periódica que se monta em cascata, moléculas com formas, braseiro 3D, equações, anel e associação"],
"sci_climate":["As alterações climáticas em dados","Faixas de aquecimento, gráficos de linhas, área e retângulos, efeito de estufa que se desenha, satélite 3D, ciclo e votação múltipla"],
"sci_mars":["Missão a Marte","Estilo espacial ferrugem: rover 3D da NASA com Transformar, astronauta a flutuar, órbita animada, equação e concurso"],
"sci_med_case":["Caso clínico: febre e tosse","Estilo processo clínico: pasta, carimbo, radiografia no negatoscópio com círculo que se desenha, CURB-65 com fórmula, votação e perguntas"],
"sci_med_ecg":["Cardiologia: ler um ECG","Papel de ECG: traçados que se desenham sozinhos, impulso que percorre o coração, tabela com fórmulas, equação, quiz e contagem regressiva"],
"sci_med_glucose":["Endocrinologia: glicose e insulina","Estilo app de sensor de glicose: telemóvel com o ecrã, ciclo um a um, curvas, rosca, tabela com fórmulas, equação, abacate 3D e votação"],
"sci_med_immune":["Imunologia: a resposta imune","Microscópio de fluorescência: células que se acendem, anticorpo desenhado, fagocitose com Transformar, organograma e correspondência"],
"sci_med_kidney":["Fisiologia renal: o néfron","Planta técnica: néfron que se desenha, gota que o percorre com som, cotas, cascata, equação, tabela com fórmulas, garrafa 3D e ciclo"],
"sci_med_knee":["Anatomia: o joelho","Estilo prancha anatômica antiga: texto curvo, gravura sépia, Transformar para os meniscos, matriz, tabela, figura 3D que caminha e etiquetar"],
"sci_med_micro":["Microbiologia: resistência antibiótica","Placas de Petri: colónias que surgem com som, crescimento exponencial, seleção contada com Transformar, antibiograma, radial e nuvem de palavras"],
"sci_med_pk":["Farmacocinética: a meia-vida","Estilo caixa de medicamento: blister que se enche, LADME um a um, curvas de duas séries, equações, tabela com fórmulas, código e lacunas"],
"sci_med_stroke":["Neurologia: código AVC","Contrarrelógio de urgência: luzes de sirene, número gigante com rufar de tambores, BE-FAST em cadeia, rosca, setas, ordenar passos e contagem regressiva"],
"sci_med_trial":["Ensaio clínico: ler os resultados","Estilo revista científica: CONSORT com conectores, curvas de sobrevivência, tabela com fórmulas, NNT, forest plot em cadeia e quiz"],
"sci_newton":["Física: as leis de Newton","Caderno de física: equações, carro 3D em movimento, lançamento oblíquo que se desenha, tabela com fórmulas e preencher lacunas"],
"sci_nurse_cpr":["RCP básica: suporte de vida","Sinalética verde de emergência: mãos que comprimem ao ritmo, elétrodos do DAE que voam com som, duas séries, contagem decrescente e ordenar"],
"sci_nurse_drip":["Fluidoterapia: calcular o gotejamento","Sistema de soro desenhado com gotas que caem com som, fórmula passo a passo, exemplo resolvido, tabela que calcula, bomba e contagem decrescente"],
"sci_nurse_falls":["Quedas em idosos: a casa segura","Casa à noite com candeeiro 3D: planta com perigos corrigidos com Transformar, teste de marcha com figura 3D, Venn, anel e contagem decrescente"],
"sci_nurse_hands":["Higiene das mãos: os 5 momentos","Azulejos e bolhas: bolhas que sobem, os 5 momentos numa planta, lâmpada UV com som, contagem decrescente de 30 s, barras e quiz"],
"sci_nurse_heat":["Onda de calor: plano de saúde","Cores de alerta: termómetro que sobe, Text Art, mapa de avisos desenhado, dispersão, telemóvel com o SMS, garrafa 3D, tabela e quiz"],
"sci_nurse_herd":["Vacinas: a imunidade de grupo","Boletim de vacinas com carimbos e texto curvo, contágio em cadeia cortado com Transformar, equação, tabela com fórmulas, mitos riscados"],
"sci_nurse_outbreak":["Investigar um surto alimentar","Quadro de cortiça: notas com pioneses e fio vermelho que se desenha, curva epidémica, tabela com fórmulas, risco relativo, código e votação"],
"sci_nurse_pressure":["Úlceras por pressão: prevenir","Mapa de pressão térmico: manchas que acendem e apagam, Braden com fórmulas, relógio de mudanças que gira, camadas da pele e legendar"],
"sci_nurse_sbar":["A passagem de turno com SBAR","Quadro branco do serviço: marcador que sublinha sozinho, ímanes e notas que se colam com som, diálogo em cadeia, escala com fórmula e associar"],
"sci_nurse_smoking":["Deixar de fumar: o que o teu corpo ganha","Do fumo ao ar limpo: fumo que sobe, cigarro como linha do tempo, pulmões que mudam com Transformar, tabela de poupança e respiração"],
"sci_python":["Programação em Python","Estilo editor escuro: terminal que se escreve sozinho, código com passos de destaque, saída animada, ordenar linhas e desafio com contagem decrescente"],
"sci_solar":["O sistema solar","Planetas à escala que aparecem em cadeia, três sondas 3D com vistas e movimentos diferentes, tabela, diagrama radial e associação"],
"sci_stats":["Estatística e probabilidade","Estilo editorial: curva normal que se desenha, fórmulas, histograma, dispersão, área, barras e bolhas, e pergunta com pontos"],
"sci_thesis":["Defesa do trabalho de fim de curso","Académico sóbrio: capa institucional, índice, metodologia com equação, tabela com totais, resultados em gráficos, bibliografia e perguntas"],
"show_anim_bike":["As mudanças da bicicleta, sem mistério","Movimentos sincronizados: engrenagens que giram à sua relação real, rodas que rolam a sua distância, duas faixas ao mesmo tempo e tabela"],
"show_anim_blueprint":["Remodelação de um apartamento: a planta","Planta que se desenha sozinha: paredes em cadeia, cotas, demolição que desaparece, Transformar para a nova distribuição, instalações e obra"],
"show_anim_ferries":["Ferries entre ilhas: rotas de verão","Trajetórias num mapa: barcos que rodam com o caminho, rotas que se desenham à sua passagem, três linhas ao mesmo tempo, escala e horários"],
"show_anim_firefly":["Conto: o pirilampo sem luz","Um conto com entradas e saídas: narração visível só no seu passo, diálogos que aparecem e desaparecem, voos e uma luz que regressa"],
"show_anim_foosball":["Torneio de matraquilhos no escritório","Animações encadeadas com sons como num jogo: passes com clique, remate, golo com aplausos, quadro que avança, tabela e apostas"],
"show_anim_guitar":["Anatomia da guitarra espanhola","Acionadores: clique em cada parte da guitarra para ver a sua ficha e em cada corda para a fazer vibrar; roseta que gira"],
"show_anim_haiku":["Oficina de haiku: palavra a palavra","Animação por palavras e parágrafos: versos palavra a palavra, proposta frase a frase, sílabas contadas e Transformar"],
"show_anim_rpg":["RPG de mesa: a tua primeira partida","Personagens 3D com as suas animações: atacar, bloquear, lançar feitiços e cair; caminhar até ao rival, dado que rola e vida que desce"],
"show_anim_speech":["Discurso: salvemos a biblioteca","Ênfase ao ritmo de um discurso: frase em foco e o resto atenuado, riscar, realçar, sublinhado e círculo à mão, contagem decrescente"],
"show_anim_tshirt":["Infografia: a viagem de uma t-shirt","Infografia que se revela: rota que se desenha com as paragens a tempo, pictograma de gotas que se enche, cascata, números e fórmula"],
"showcase_3d":["Catálogo: o 3D a fundo","Modelos 3D com todas as opções: vistas, movimentos ao entrar, rotação, bordas, margem, clips, andar e chegada com Transformar"],
"showcase_animations":["Catálogo: animações","Todas as animações de objeto: entrada, ênfase, saída, trajetórias, desenhar, encadeadas, sons e várias num objeto"],
"showcase_charts":["Catálogo: gráficos","Os 15 tipos de gráfico, dois por diapositivo, com séries, combinado, grelha, etiquetas e títulos dos eixos, e a tabela de opções"],
"showcase_diagrams":["Catálogo: diagramas","Os 15 esquemas de diagrama escritos como estrutura, os 4 esquemas de cor e o aparecimento um a um ao apresentar"],
"showcase_morph":["Catálogo: Transformar","Transformar passo a passo: texto que muda de tamanho e lugar, formas, barras que crescem, imagem, 3D e letras que se reordenam"],
"showcase_objects":["Catálogo: multimédia e objetos","Código com passos, equações, ícones, cinco dispositivos, tabelas com estilos e fórmulas, zoom de diapositivo e conectores"],
"showcase_polls":["Catálogo: votações e atividades","Os 11 tipos de votação e atividade pelo telemóvel, contagem decrescente nos três estilos, classificação e modo sala de aula"],
"showcase_shapes":["Catálogo: formas","Todas as formas por categorias com o nome, linhas e tracejados, gradientes, opacidade, traço à mão, sombras, texto dentro e rotação"],
"showcase_text":["Catálogo: Text Art e tipografia","Os 10 estilos de Text Art, texto curvo, colunas, cinco níveis de marcadores, os 8 pares de letra, alinhamento e espaçamento"],
"showcase_transitions":["Catálogo: transições","As 22 transições de diapositivo, uma a uma: entrada, saída diferente, direções, velocidade e avanço automático"]};
