// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Resultados trimestrais ao conselho","Azul-escuro e dourado: grandes indicadores animados com som, cascata, funil, barras empilhadas e tabela com fórmulas face ao orçamento"],
"biz_climate":["Pesquisa de clima organizacional","Violeta e participativo: contagem decrescente, barras a 100 %, avaliação de 1 a 5, nuvem de palavras, escolha múltipla e perguntas do público"],
"biz_investment":["Apresentação para investidores","Preto e dourado: produto 3D que gira e viaja com Transformar, números gigantes, mercado em círculos, tração, uso dos fundos e equipa"],
"biz_marketing":["Plano de marketing de campanha","Estilo quente: texto em círculo, público-alvo, funil, mix de canais, calendário em tabela, orçamento com fórmula e votação"],
"biz_onboarding":["Boas-vindas a novos funcionários","Estilo amigável: robô 3D que acena e percorre a semana a andar, organograma um a um, valores com ícones e atividade de associar"],
"biz_proposal":["Proposta comercial a um cliente","Estilo papel: selo, processo um a um, maquetas em portátil e telemóvel, preços, orçamento com IVA em fórmulas, cronologia e garantias"],
"biz_roadmap":["Roteiro de um projeto","Estilo técnico escuro: divisas uma a uma, diagrama de Gantt animado, cronologia, carro 3D que avança com Transformar e tabela de estado"],
"biz_sales":["Vendas e previsão anual","Minimalista em cinzento: barras e linhas combinadas, cenários, fórmula de previsão, tabela com fórmulas, barras empilhadas e horizontais"],
"biz_strategy":["Plano estratégico e OKR","Estilo branco e limpo: números que entram em sequência, pirâmide, prioridades com ícones, tabela de OKR, barras de progresso, radar e divisas"],
"biz_swot":["Análise SWOT e concorrência","Fundo grafite: SWOT por quadrantes, matriz de estratégias, mapa de posicionamento, barras agrupadas, Venn, gráfico circular e votação múltipla"],
"creative_bauhaus":["Bauhaus: forma e função","Arte geométrica Bauhaus: formas primárias que giram e quicam, cronologia, grade com Transformar e atividade de associar"],
"creative_brutalism":["Brutalismo: manifesto web","Estilo brutalista: tipografia gigante, blocos pretos, texto vertical, sombras duras, riscado animado, tabela e votação"],
"creative_comic":["Quadrinhos: superpoderes animais","Estilo quadrinhos: quadros, balões de fala e pensamento, onomatopeias em Text Art que quicam, raposa 3D, gráfico e quiz"],
"creative_fashion":["Revista de moda: outono lento","Estilo revista: cabeçalho com serifa, relógio 3D na capa, colunas com capitular, citação grande, paleta da estação e gráfico"],
"creative_glass":["Glassmorphism: app de finanças","Cartões translúcidos sobre brilhos coloridos, app no celular, gráfico de rosca, cartão com Transformar e votação de avaliação"],
"creative_pixel":["Pixel art: o teu primeiro videojogo","Estilo videogame retrô: sprites de pixels, placar, personagens 3D que andam e pulam, código passo a passo, quiz e contagem regressiva"],
"creative_space":["Galáxia: olhar para o passado","Estilo espacial: estrelas, nebulosas brilhantes, modelos 3D da NASA, sonda que percorre os planetas, texto curvo e quiz"],
"creative_synthwave":["Synthwave: festival Neón 86","Estilo retrô anos 80: sol em degradê, grade que se desenha, néon brilhante, Transformar, robô 3D que dança e nuvem de palavras"],
"creative_watercolor":["Aquarela: horta na varanda","Estilo aquarela e papel: manchas com degradê radial, formas à mão livre, letra manuscrita, desenho que se traça sozinho e 3D"],
"creative_zen":["Minimalismo japonês: o chá","Minimalismo japonês: muito branco, sol vermelho que se transforma, texto vertical, ensō que se pinta sozinho e contagem regressiva"],
"data_ab_test":["Experimento A/B","Equações, dispersão de duas séries, colunas com rótulos, tabela de conversão com fórmulas e números de significância"],
"data_energy":["Energia e consumo","Áreas empilhadas por hora, linhas de três séries, mapa de árvore, colunas com rótulos e tabela de tarifas calculada"],
"data_exec_panel":["Painel executivo mensal","KPIs com semáforos e minigráficos, combinado face ao orçamento, pequenos múltiplos, rosca e votação"],
"data_home_finance":["Finanças pessoais","Cascata do salário à poupança, gráfico de pizza, linhas e área, tabelas com SOMA, MÉDIA, MÁXIMO e MÍNIMO"],
"data_market_study":["Estudo de mercado","Números grandes, mapa de árvore, bolhas, dispersão, barras horizontais de duas séries e matriz 2 × 2"],
"data_population":["População e demografia","Pirâmide etária, histograma, barras horizontais, linhas que se cruzam e tabela de indicadores com fórmulas"],
"data_sales_regions":["Vendas por região","Barras agrupadas, empilhadas e a 100 %, gráfico combinado com meta, tabela com totais por fórmula e KPIs animados"],
"data_satisfaction":["Pesquisa de satisfação","Rosca com legenda, radares comparados, colunas com rótulos, NPS, avaliação e nuvem de palavras ao vivo"],
"data_season_stats":["A temporada em números","Números gigantes com som, classificação com fórmulas, barras negativas, linhas, empilhadas e radar da equipe"],
"data_web_metrics":["Métricas web e marketing","KPIs com minigráficos, linhas de quatro séries, áreas, funil de conversão, gráfico combinado e tabela com fórmulas"],
"edu_body":["O corpo humano","Estilo laboratório: figura 3D com Transformar, personagem que caminha por um percurso, gráfico de barras, legendar o corpo e questionário"],
"edu_cell":["A célula","Célula desenhada com formas, partes uma a uma, Transformar para aproximar, associar pares, diagrama, planta 3D e avaliação"],
"edu_english":["Inglês para iniciantes","Modo aula: cartões que viram com som, robô 3D que anda e acena, raposa 3D, três perguntas com pontos, classificação e aplausos"],
"edu_fractions":["Frações","Estilo néon: pizas desenhadas, equações passo a passo, soma com Transformar, preencher lacunas, questionário e desafio com contagem decrescente"],
"edu_quixote":["Dom Quixote","Estilo tinta e papel: moinho que gira com som, texto curvo, citações animadas, Transformar, cronologia, preencher lacunas e questionário"],
"edu_renewables":["Energias renováveis","Aerogerador que gira, cartões, gráficos de área, anel e barras agrupadas, nuvem de palavras ao vivo, votação e contagem decrescente"],
"edu_revolution":["A Revolução Francesa","Estilo papel antigo: texto em círculo, Transformar, pirâmide social, cronologia animada com som, ordenar factos e votação"],
"edu_spain":["Geografia de Espanha","Estilo atlas: rosa dos ventos, relevo em alvo, tabela de rios com fórmulas, gráficos de picos e chuvas, associar pares e questionário"],
"edu_volcanoes":["Os vulcões","Estilo fogo: erupção animada com som, partes do vulcão para legendar, tabela, questionário com tempo e contagem decrescente"],
"edu_water":["O ciclo da água","Diagrama de ciclo um a um, paisagem com gotas que sobem e chuva animada com som, gráficos de anel, associar pares e satélite 3D"],
"life_bookclub":["Clube de leitura","Estante à mão livre, capa feita de formas, citações que se transformam, diagrama radial, avaliação e votação do próximo livro"],
"life_cv":["Currículo visual","Texto em círculo, números, cronologia passo a passo, barras de competências animadas, radar, ecrãs em dispositivos e contacto"],
"life_fitness":["Plano de treino: 5 km","Corredor 3D, Text Art fogo, fases com gradientes, semana com fórmulas, gráficos de progresso, pirâmide, contagem decrescente e nuvem de palavras"],
"life_garden":["Horta urbana","Planta 3D com Transformar, calendário de sementeira em tabela de cores, ciclo, Venn, gráficos de rega e crescimento, atividade de legendar"],
"life_graduation":["Formatura e fim de ano letivo","Text Art dourado, capelos feitos de formas, polaroides que giram ao entrar, números com rufar de tambores, agradecimentos, nuvem de palavras e aplausos"],
"life_italy":["Viagem pela Itália","Texto em círculo, rota com conectores e percurso animado, cronologia, orçamento com fórmulas, gráficos e atividade de associar"],
"life_kids_party":["Aniversário infantil","Cores vivas: robô 3D que dança, personagens que celebram, balões à mão livre, concurso com pontos e contagem decrescente"],
"life_moving":["Mudança e novo lar","Casa com formas à mão livre, cronologia, lista que se risca, móveis 3D que passam para a planta com Transformar, orçamento e atividade de ordenar"],
"life_recipe":["Receita: guacamole","Abacate 3D que viaja entre diapositivos (Transformar), ingredientes com fórmulas, passos um a um, contagem decrescente e avaliação"],
"life_wedding":["Convite de casamento","Tipografia clássica e dourado: Text Art, texto curvo, cronologia do casal, mapa com percurso animado, votação e contagem decrescente"],
"product_app":["Apresentação de app móvel","App em telemóvel, tablet e portátil, Transformar, percurso em divisas, números, gráfico de retenção e nuvem de palavras"],
"product_car":["Apresentação: carro elétrico","Carro 3D sem corte nas bordas que dá a volta ao entrar, Transformar, números, gráficos de área e barras, tabela e votação"],
"product_eco":["Sustentabilidade do produto","Verde eco: planta 3D com Transformar, ciclo de vida, cascata da pegada, barras de materiais, linhas com meta e preencher lacunas"],
"product_furniture":["Coleção de móveis","Estilo editorial: sofás e cadeiras 3D, Transformar com vistas diferentes, balanço e volta, amostras de cor, tablet e orçamento"],
"product_keynote":["Keynote de hardware","Estilo branco premium: candeeiro iridescente e garrafa 3D, Transformar com etiquetas, flutuar e aproximar, números, tabela e preços"],
"product_roadmap":["Roteiro de produto","Caminho que se desenha sozinho, pirâmide, cronologia um a um, agora e depois, matriz, barras empilhadas, votação múltipla e de ordenar"],
"product_robot":["Robô assistente industrial","Estilo industrial: robô 3D que acena, percorre um caminho, encadeia animações e dança; organograma, ciclo, gráfico e quiz"],
"product_saas":["Demo de plataforma SaaS","Painel em janela de navegador com chamadas numeradas, radial, funil, indicadores, barras empilhadas, código por passos e perguntas"],
"product_security":["Segurança do produto","Néon verde: alvo em camadas, fluxo com conectores que aparece passo a passo, código destacado, gráfico, escada e atividade de correspondência"],
"product_watch":["Lançamento: relógio inteligente","Preto e ouro: relógio 3D que viaja por três diapositivos com Transformar e chegadas diferentes, Text Art dourado, radar e preços"],
"sci_ai":["Inteligência artificial","Néon violeta: robô 3D que acena e viaja com Transformar, cronologia, organograma, rede neuronal que se acende, gráfico e nuvem de palavras"],
"sci_brain":["Neurociência: o cérebro","Estilo escuro com brilhos: neurónio desenhado com impulso animado, figura 3D que caminha, radial, organograma, barras e legendar uma imagem"],
"sci_chem":["Química: a tabela periódica","Laboratório limpo: tabela periódica que se monta em cascata, moléculas com formas, braseiro 3D, equações, anel e associação"],
"sci_climate":["As alterações climáticas em dados","Faixas de aquecimento, gráficos de linhas, área e retângulos, efeito de estufa que se desenha, satélite 3D, ciclo e votação múltipla"],
"sci_mars":["Missão a Marte","Estilo espacial ferrugem: rover 3D da NASA com Transformar, astronauta a flutuar, órbita animada, equação e concurso"],
"sci_newton":["Física: as leis de Newton","Caderno de física: equações, carro 3D em movimento, lançamento oblíquo que se desenha, tabela com fórmulas e preencher lacunas"],
"sci_python":["Programação em Python","Estilo editor escuro: terminal que se escreve sozinho, código com passos de destaque, saída animada, ordenar linhas e desafio com contagem decrescente"],
"sci_solar":["O sistema solar","Planetas à escala que aparecem em cadeia, três sondas 3D com vistas e movimentos diferentes, tabela, diagrama radial e associação"],
"sci_stats":["Estatística e probabilidade","Estilo editorial: curva normal que se desenha, fórmulas, histograma, dispersão, área, barras e bolhas, e pergunta com pontos"],
"sci_thesis":["Defesa do trabalho de fim de curso","Académico sóbrio: capa institucional, índice, metodologia com equação, tabela com totais, resultados em gráficos, bibliografia e perguntas"],
"showcase_3d":["Catálogo: o 3D a fundo","Modelos 3D com todas as opções: vistas, movimentos ao entrar, rotação, bordas, margem, clips, andar e chegada com Transformar"],
"showcase_animations":["Catálogo: animações","Todas as animações de objeto: entrada, ênfase, saída, trajetórias, desenhar, encadeadas, sons e várias num objeto"],
"showcase_charts":["Catálogo: gráficos","Os 15 tipos de gráfico, dois por diapositivo, com séries, combinado, grelha, etiquetas e títulos dos eixos, e a tabela de opções"],
"showcase_diagrams":["Catálogo: diagramas","Os 15 esquemas de diagrama escritos como estrutura, os 4 esquemas de cor e o aparecimento um a um ao apresentar"],
"showcase_morph":["Catálogo: Transformar","Transformar passo a passo: texto que muda de tamanho e lugar, formas, barras que crescem, imagem, 3D e letras que se reordenam"],
"showcase_objects":["Catálogo: multimédia e objetos","Código com passos, equações, ícones, cinco dispositivos, tabelas com estilos e fórmulas, zoom de diapositivo e conectores"],
"showcase_polls":["Catálogo: votações e atividades","Os 11 tipos de votação e atividade pelo telemóvel, contagem decrescente nos três estilos, classificação e modo sala de aula"],
"showcase_shapes":["Catálogo: formas","Todas as formas por categorias com o nome, linhas e tracejados, gradientes, opacidade, traço à mão, sombras, texto dentro e rotação"],
"showcase_text":["Catálogo: Text Art e tipografia","Os 10 estilos de Text Art, texto curvo, colunas, cinco níveis de marcadores, os 8 pares de letra, alinhamento e espaçamento"],
"showcase_transitions":["Catálogo: transições","As 22 transições de diapositivo, uma a uma: entrada, saída diferente, direções, velocidade e avanço automático"]};
