// Made by tools/template-names.mjs: key → [name, summary] in this language.
export default {"biz_board":["Resultados trimestrais ao conselho","Azul-escuro e dourado: grandes indicadores animados com som, cascata, funil, barras empilhadas e tabela com fórmulas face ao orçamento"],
"biz_climate":["Pesquisa de clima organizacional","Violeta e participativo: contagem decrescente, barras a 100 %, avaliação de 1 a 5, nuvem de palavras, escolha múltipla e perguntas do público"],
"biz_investment":["Apresentação para investidores","Preto e dourado: produto 3D que gira e viaja com Transformar, números gigantes, mercado em círculos, tração, uso dos fundos e equipa"],
"biz_marketing":["Plano de marketing de campanha","Estilo quente: texto em círculo, público-alvo, funil, mix de canais, calendário em tabela, orçamento com fórmula e votação"],
"biz_onboarding":["Boas-vindas a novos funcionários","Estilo amigável: robô 3D que acena e percorre a semana a andar, organograma um a um, valores com ícones e atividade de associar"],
"biz_proposal":["Proposta comercial a um cliente","Estilo papel: selo, processo um a um, maquetas em portátil e telemóvel, preços, orçamento com IVA em fórmulas, cronologia e garantias"],
"biz_roadmap":["Roteiro de um projeto","Estilo técnico escuro: divisas uma a uma, diagrama de Gantt animado, cronologia, carro 3D que avança com Transformar e tabela de estado"],
"biz_sales":["Vendas e previsão anual","Minimalista em cinzento: barras e linhas combinadas, cenários, fórmula de previsão, tabela com fórmulas, barras empilhadas e horizontais"],
"biz_startup_agrotech":["Pitch agrotech: rega com sensores","Vista aérea de parcelas com mapa de humidade, satélite 3D da NASA, telemóvel, gotas em cadeia com som, tabela com fórmulas e treemap"],
"biz_startup_edtech":["Pitch edtech: tutor de matemática","Caderno quadriculado: post-its em cadeia, letra manuscrita, equações passo a passo, telemóvel, quiz ao vivo, ciclo e gráficos"],
"biz_startup_energy":["Pitch energia: comunidade solar","Telhados da madrugada à noite: sol que nasce e cruza o céu em arco, diagrama radial, áreas por hora, equação e tabela com fórmulas"],
"biz_startup_fashion":["Pitch moda circular: Retal","Etiqueta de roupa que viaja com Transformar, costuras tracejadas, vida de uma peça em cadeia, ciclo, anel, radar e votação múltipla"],
"biz_startup_insurance":["Pitch seguros: cobertura por dias","Chuva cinzenta e guarda-chuva amarelo: pictograma em cadeia, app com interruptor, equação do preço, tabela com fórmulas, cronologia e votação"],
"biz_startup_kitchen":["Pitch robótica de cozinha: Fogón","Cozinha profissional: comandas no trilho, Text Art de fogo, robô 3D que entra a andar e acena, receita em código, contagem decrescente e funil"],
"biz_startup_lastmile":["Pitch logística: última milha","Estilo mapa de metro: linhas que se desenham sozinhas, camião 3D e bicicletas que percorrem o mapa, tabela com fórmulas, área e cascata"],
"biz_startup_mental":["Pitch saúde mental: Remanso","Noite calma: anéis que respiram, minuto de respiração com contagem decrescente, app no telemóvel, escada, avaliação e tabela com fórmulas"],
"biz_startup_pets":["Pitch animais: comida fresca","Estilo autocolante com pegadas que aparecem em cadeia, raposa 3D que atravessa a andar, fórmula da ração numa tabela, anel e quiz"],
"biz_startup_rural":["Pitch turismo rural: Alpende","Montanhas ao entardecer e postais: lanterna 3D, carimbo com texto curvo, mapa com carro 3D pela rota, barras, circular e nuvem de palavras"],
"biz_strategy":["Plano estratégico e OKR","Estilo branco e limpo: números que entram em sequência, pirâmide, prioridades com ícones, tabela de OKR, barras de progresso, radar e divisas"],
"biz_swot":["Análise SWOT e concorrência","Fundo grafite: SWOT por quadrantes, matriz de estratégias, mapa de posicionamento, barras agrupadas, Venn, gráfico circular e votação múltipla"],
"creative_bauhaus":["Bauhaus: forma e função","Arte geométrica Bauhaus: formas primárias que giram e quicam, cronologia, grade com Transformar e atividade de associar"],
"creative_brutalism":["Brutalismo: manifesto web","Estilo brutalista: tipografia gigante, blocos pretos, texto vertical, sombras duras, riscado animado, tabela e votação"],
"creative_comic":["Quadrinhos: superpoderes animais","Estilo quadrinhos: quadros, balões de fala e pensamento, onomatopeias em Text Art que quicam, raposa 3D, gráfico e quiz"],
"creative_fashion":["Revista de moda: outono lento","Estilo revista: cabeçalho com serifa, relógio 3D na capa, colunas com capitular, citação grande, paleta da estação e gráfico"],
"creative_glass":["Glassmorphism: app de finanças","Cartões translúcidos sobre brilhos coloridos, app no celular, gráfico de rosca, cartão com Transformar e votação de avaliação"],
"creative_pixel":["Pixel art: o teu primeiro videojogo","Estilo videogame retrô: sprites de pixels, placar, personagens 3D que andam e pulam, código passo a passo, quiz e contagem regressiva"],
"creative_space":["Galáxia: olhar para o passado","Estilo espacial: estrelas, nebulosas brilhantes, modelos 3D da NASA, sonda que percorre os planetas, texto curvo e quiz"],
"creative_swiss_blood":["Campanha: doe sangue","Cartaz público em branco e vermelho: gota que enche o ecrã com Transformar, processo, sim ou espera, anel, barras, telemóvel e quiz"],
"creative_swiss_chairs":["Exposição: a cadeira moderna","Cartaz suíço cinzento e lima: cadeira 3D que gira e viaja com Transformar, cronologia, anel, poltrona 3D, tabela com fórmulas e ordenar"],
"creative_swiss_designconf":["Congresso de design: Grelha 27","Grafite e ciano: a grelha monta-se sozinha e muda com Transformar, número em contorno, fórmula, cronologia, código CSS, nuvem e pausa"],
"creative_swiss_film":["Festival de cinema: o programa","Suíço em preto e vermelho: número gigante que vira faixa com Transformar, secções em grelha, tabela, barras, votação e contagem"],
"creative_swiss_foundation":["Relatório anual de uma fundação","Suíço em branco e azul-cobalto: ano gigante, carta a toda a cor, números em cadeia, equação, anel, área, setas e contas com fórmulas"],
"creative_swiss_games":["Jogos escolares: a identidade","Branco e magenta, paleta própria: pictogramas SVG, figura 3D que percorre a cidade, linhas, quadro de medalhas com fórmulas, degraus e quiz"],
"creative_swiss_museum":["Guia do museu de história natural","Sinalética suíça em preto e amarelo: planta própria com percurso animado, raposa 3D que anda, colunas, tabela, legendar e pictogramas"],
"creative_swiss_orchestra":["Orquestra sinfónica: temporada 26/27","Azul-noite e âmbar: arcos que giram, texto curvo, números numa pauta, ciclos, tabela, equação, barras, votação e aplausos"],
"creative_swiss_publisher":["Catálogo de outono de uma editora","Papel creme e verde-petróleo: estante de lombadas verticais, capas em SVG, tablet, tarte, encomenda com fórmulas, calendário e lacunas"],
"creative_swiss_typeface":["Mostruário de uma nova tipografia","Mostruário em branco e violeta: letras que viajam com Transformar, anatomia medida, escala com fórmula, glifos, radar e licenças"],
"creative_synthwave":["Synthwave: festival Neón 86","Estilo retrô anos 80: sol em degradê, grade que se desenha, néon brilhante, Transformar, robô 3D que dança e nuvem de palavras"],
"creative_watercolor":["Aquarela: horta na varanda","Estilo aquarela e papel: manchas com degradê radial, formas à mão livre, letra manuscrita, desenho que se traça sozinho e 3D"],
"creative_zen":["Minimalismo japonês: o chá","Minimalismo japonês: muito branco, sol vermelho que se transforma, texto vertical, ensō que se pinta sozinho e contagem regressiva"],
"data_ab_test":["Experimento A/B","Equações, dispersão de duas séries, colunas com rótulos, tabela de conversão com fórmulas e números de significância"],
"data_energy":["Energia e consumo","Áreas empilhadas por hora, linhas de três séries, mapa de árvore, colunas com rótulos e tabela de tarifas calculada"],
"data_exec_panel":["Painel executivo mensal","KPIs com semáforos e minigráficos, combinado face ao orçamento, pequenos múltiplos, rosca e votação"],
"data_home_finance":["Finanças pessoais","Cascata do salário à poupança, gráfico de pizza, linhas e área, tabelas com SOMA, MÉDIA, MÁXIMO e MÍNIMO"],
"data_market_study":["Estudo de mercado","Números grandes, mapa de árvore, bolhas, dispersão, barras horizontais de duas séries e matriz 2 × 2"],
"data_population":["População e demografia","Pirâmide etária, histograma, barras horizontais, linhas que se cruzam e tabela de indicadores com fórmulas"],
"data_sales_regions":["Vendas por região","Barras agrupadas, empilhadas e a 100 %, gráfico combinado com meta, tabela com totais por fórmula e KPIs animados"],
"data_satisfaction":["Pesquisa de satisfação","Rosca com legenda, radares comparados, colunas com rótulos, NPS, avaliação e nuvem de palavras ao vivo"],
"data_season_stats":["A temporada em números","Números gigantes com som, classificação com fórmulas, barras negativas, linhas, empilhadas e radar da equipe"],
"data_web_metrics":["Métricas web e marketing","KPIs com minigráficos, linhas de quatro séries, áreas, funil de conversão, gráfico combinado e tabela com fórmulas"],
"edu_body":["O corpo humano","Estilo laboratório: figura 3D com Transformar, personagem que caminha por um percurso, gráfico de barras, legendar o corpo e questionário"],
"edu_cell":["A célula","Célula desenhada com formas, partes uma a uma, Transformar para aproximar, associar pares, diagrama, planta 3D e avaliação"],
"edu_english":["Inglês para iniciantes","Modo aula: cartões que viram com som, robô 3D que anda e acena, raposa 3D, três perguntas com pontos, classificação e aplausos"],
"edu_fractions":["Frações","Estilo néon: pizas desenhadas, equações passo a passo, soma com Transformar, preencher lacunas, questionário e desafio com contagem decrescente"],
"edu_hist_alandalus":["Al-Andalus: ciência e jardins","Arco em ferradura, cronologia um a um, barras horizontais, astrolábio que gira, estrela com Transformar, associar pares e votação"],
"edu_hist_castle":["Castelos e feudalismo","Castelo noturno e cavaleiro 3D que atravessa a ponte, pirâmide feudal que se ergue, legendar, sol que percorre o dia, treemap e brasões"],
"edu_hist_egypt":["Egito, a dádiva do Nilo","Lápis-lazúli e ouro: sol a nascer atrás das pirâmides, cheia animada, gráfico de áreas, equação, Transformar, cartucho hieroglífico e ordenar"],
"edu_hist_greece":["Atenas: nasce a democracia","Estilo vaso de figuras negras: meandro, texto curvo, Transformar, anel, templo que se ergue, óstraka com som, votação e tabela"],
"edu_hist_maya":["Os maias: tempo e estrelas","Selva e jade: números de pontos e barras, Transformar para base 20, equação, rodas de calendário que giram, serpente de luz e cacau"],
"edu_hist_mesopotamia":["Mesopotâmia: nasce a escrita","Tábua de argila que se escreve sozinha, mapa com rios desenhados, zigurate que cresce, base 60 com fórmulas, completar lacunas e radial"],
"edu_hist_printing":["A imprensa: o livro multiplica-se","Página incunábula: capitular vermelha, tipos invertidos compostos com Transformar, prensa que desce com som, números, barras e lacunas"],
"edu_hist_rome":["Roma, engenheiros do império","Mármore e vermelho imperial: Transformar, arco triunfal, estrada em camadas com soldado 3D a marchar, aqueduto, equação, fórmulas e concurso"],
"edu_hist_silkroad":["A Rota da Seda","Seda e açafrão: caravana em marcha, mapa com rota traçada, cascata do preço, tabela com fórmulas, lanterna 3D, equação e ordenar"],
"edu_hist_vikings":["Vikings, navegadores do norte","Fiorde sob a aurora: barco que balança, runas, mitos riscados com carimbo, travessia animada, números com som, guerreiro 3D, radar e associar"],
"edu_math_coordinates":["Coordenadas: o mapa do tesouro","Mapa do tesouro: rosa dos ventos com texto curvo, pontos que aparecem, pirata 3D que segue pistas, barco que se desenha e legendar"],
"edu_math_integers":["Números inteiros: mar e montanha","Do fundo do mar ao cume: reta com saltos, Text Art gelo, temperaturas negativas, submarino que sobe e desce, ordenar e quiz"],
"edu_math_primes":["Números primos","Terminal verde: néon próprio, crivo de Eratóstenes clique a clique com 100 casas, árvore de fatores, código passo a passo, quiz e desafio"],
"edu_math_probability":["Probabilidade: medir a sorte","Mesa de jogo bordô e ouro: dados que rolam com rufar de tambor, texto curvo, regra de Laplace, árvore um a um, barras, linhas e quiz"],
"edu_math_proportion":["Proporcionalidade no supermercado","Talão de compras: carimbo que salta, tabela de proporcionalidade com fórmulas, regra de três passo a passo, descontos calculados, linhas e lacunas"],
"edu_math_pythagoras":["O teorema de Pitágoras","Quadro de giz: figura que se desenha sozinha, demonstração sem palavras com Transformar, ternos com fórmulas, atalho em 3D e quiz"],
"edu_math_sequences":["Sequências e padrões","Livro de botânica: espiral de Fibonacci que se traça sozinha, pedras em cadeia, palitos com fórmulas, código, planta 3D e número de ouro"],
"edu_math_stats":["Estatística: média, mediana e moda","Caderno quadriculado: notas adesivas em cascata, frequências com fórmulas, barras, rosca com graus, histograma e votação ao vivo"],
"edu_math_symmetry":["Simetria e mosaicos","Azulejos nasridas: estrela que gira, borboleta que se reflete, translação, rotação e simetria animadas, tabela de ângulos e favo"],
"edu_math_volumes":["Áreas e volumes","Planta técnica azul: carimbo em tabela, planificação, garrafa 3D medida, volumes com fórmulas, barras, cones que enchem e associação"],
"edu_quixote":["Dom Quixote","Estilo tinta e papel: moinho que gira com som, texto curvo, citações animadas, Transformar, cronologia, preencher lacunas e questionário"],
"edu_renewables":["Energias renováveis","Aerogerador que gira, cartões, gráficos de área, anel e barras agrupadas, nuvem de palavras ao vivo, votação e contagem decrescente"],
"edu_revolution":["A Revolução Francesa","Estilo papel antigo: texto em círculo, Transformar, pirâmide social, cronologia animada com som, ordenar factos e votação"],
"edu_spain":["Geografia de Espanha","Estilo atlas: rosa dos ventos, relevo em alvo, tabela de rios com fórmulas, gráficos de picos e chuvas, associar pares e questionário"],
"edu_volcanoes":["Os vulcões","Estilo fogo: erupção animada com som, partes do vulcão para legendar, tabela, questionário com tempo e contagem decrescente"],
"edu_water":["O ciclo da água","Diagrama de ciclo um a um, paisagem com gotas que sobem e chuva animada com som, gráficos de anel, associar pares e satélite 3D"],
"life_bookclub":["Clube de leitura","Estante à mão livre, capa feita de formas, citações que se transformam, diagrama radial, avaliação e votação do próximo livro"],
"life_cv":["Currículo visual","Texto em círculo, números, cronologia passo a passo, barras de competências animadas, radar, ecrãs em dispositivos e contacto"],
"life_fitness":["Plano de treino: 5 km","Corredor 3D, Text Art fogo, fases com gradientes, semana com fórmulas, gráficos de progresso, pirâmide, contagem decrescente e nuvem de palavras"],
"life_garden":["Horta urbana","Planta 3D com Transformar, calendário de sementeira em tabela de cores, ciclo, Venn, gráficos de rega e crescimento, atividade de legendar"],
"life_graduation":["Formatura e fim de ano letivo","Text Art dourado, capelos feitos de formas, polaroides que giram ao entrar, números com rufar de tambores, agradecimentos, nuvem de palavras e aplausos"],
"life_italy":["Viagem pela Itália","Texto em círculo, rota com conectores e percurso animado, cronologia, orçamento com fórmulas, gráficos e atividade de associar"],
"life_kids_party":["Aniversário infantil","Cores vivas: robô 3D que dança, personagens que celebram, balões à mão livre, concurso com pontos e contagem decrescente"],
"life_moving":["Mudança e novo lar","Casa com formas à mão livre, cronologia, lista que se risca, móveis 3D que passam para a planta com Transformar, orçamento e atividade de ordenar"],
"life_recipe":["Receita: guacamole","Abacate 3D que viaja entre diapositivos (Transformar), ingredientes com fórmulas, passos um a um, contagem decrescente e avaliação"],
"life_travel_eu_amsterdam":["Amesterdão: canais e bicicletas","Fachadas de canal que se montam em cadeia, canais em alvo, bicicleta que passa com som, tabela com fórmulas, linhas e votação em tarte"],
"life_travel_eu_camino":["Caminho de Santiago: desde Sarria","Credencial que se enche de carimbos com som, cascata de quilómetros, caminhante 3D, equação da mochila, anel e ordenar etapas"],
"life_travel_eu_croatia":["Croácia à vela pela Dalmácia","Carta náutica, rosa dos ventos que gira e viaja com Transformar, bandeiras, associar, milhas com fórmulas, quiz e contagem decrescente"],
"life_travel_eu_danube":["O Danúbio de bicicleta","Estilo ciclocomputador: rota no telemóvel, ficheiro GPX passo a passo, barras empilhadas, garrafa 3D com Transformar, fórmulas e retângulos"],
"life_travel_eu_fjords":["Fiordes noruegueses pela água","Paisagem em camadas com reflexos, barco a navegar, corte do fiorde que se desenha, barras, radar, etapas uma a uma e votação múltipla"],
"life_travel_eu_greece":["Ilhas gregas de ferry","Aldeia branca de formas, grega, rota que se desenha, horários com fórmulas, bolhas, óculos 3D com Transformar e pôr do sol"],
"life_travel_eu_iceland":["Islândia: a Ring Road de carro","Auroras em degradê, mapa com percurso sonoro, carro 3D, números com rufar, equação do frio, raposa que caminha e quiz"],
"life_travel_eu_lisbon":["Lisboa: colinas e elétricos","Azulejos em SVG, elétrico que sobe as colinas num percurso com som, perfil de altitude, cartões que giram, tabela com fórmulas e lacunas"],
"life_travel_eu_prague":["Praga, a cidade das cem torres","Relógio astronómico de formas que gira e viaja com Transformar, desfile com sino, contagem decrescente, mapa para legendar e tabela"],
"life_travel_eu_scotland":["Escócia: Highlands de carro","Tartã tecido com formas, estrada que se desenha, carros que cedem passagem, castelos que giram, lanterna 3D, barras e perguntas"],
"life_wedding":["Convite de casamento","Tipografia clássica e dourado: Text Art, texto curvo, cronologia do casal, mapa com percurso animado, votação e contagem decrescente"],
"prod_app_bank":["Cartilla: banco para idosos","Caderneta de poupança em pele e ouro: Text Art ouro, Transformar para aproximar o telemóvel, tabela com SOMA, cascata, carimbo e quiz contra a fraude"],
"prod_app_gym":["Serie: reservas no teu ginásio","Placar LED: lutador 3D que celebra e anda até à aula, duas contagens decrescentes, ocupação por hora, tarifas com fórmulas e quiz"],
"prod_app_health":["Turno: consultas no centro de saúde","Clínico: batimento que se desenha, antes e depois, ciclo um a um, paciente 3D que anda, agenda no monitor, barras e perguntas"],
"prod_app_language":["Vocablo: app para aprender idiomas","Postal de correio aéreo: selos, balões que saltam com som, cartões que viram, Transformar, equação do esquecimento, gráfico e associar"],
"prod_app_market":["Plaza: o mercado do bairro em casa","Toldo e quadros de giz: carrinha 3D que percorre o mapa, bancas em radial, telemóvel, retângulos, comissões com fórmulas e votação"],
"prod_app_meditation":["Marea: app de meditação e sono","Mar noturno: lua com texto curvo, Transformar do telemóvel, respiração guiada com anéis encadeados, contagem decrescente, gráfico e lanterna 3D"],
"prod_app_music":["Garaje: música ao vivo do bairro","Vinil e néon: disco que viaja com Transformar, texto curvo que gira, equalizador com rufar, portátil, radar, circular e nuvem de palavras"],
"prod_app_photo":["Grano: fotografia de rolo","Câmara escura: tira de filme, foto que se revela com Transformar, contador com rufar, histograma, tablet, tabela e legendar"],
"prod_app_recipes":["Sobras: receitas com o que há","Frigorífico com post-its: abacate 3D com Transformar, telemóvel que reconhece ingredientes, passos, anel, receita com fórmulas e contagem decrescente"],
"prod_app_transit":["Andén: transporte urbano","Sinalética de metro: painel de partidas com contagem decrescente, mapa que se desenha sozinho, viagem animada, telemóvel, barras empilhadas e tarifas"],
"product_app":["Apresentação de app móvel","App em telemóvel, tablet e portátil, Transformar, percurso em divisas, números, gráfico de retenção e nuvem de palavras"],
"product_car":["Apresentação: carro elétrico","Carro 3D sem corte nas bordas que dá a volta ao entrar, Transformar, números, gráficos de área e barras, tabela e votação"],
"product_eco":["Sustentabilidade do produto","Verde eco: planta 3D com Transformar, ciclo de vida, cascata da pegada, barras de materiais, linhas com meta e preencher lacunas"],
"product_furniture":["Coleção de móveis","Estilo editorial: sofás e cadeiras 3D, Transformar com vistas diferentes, balanço e volta, amostras de cor, tablet e orçamento"],
"product_keynote":["Keynote de hardware","Estilo branco premium: candeeiro iridescente e garrafa 3D, Transformar com etiquetas, flutuar e aproximar, números, tabela e preços"],
"product_roadmap":["Roteiro de produto","Caminho que se desenha sozinho, pirâmide, cronologia um a um, agora e depois, matriz, barras empilhadas, votação múltipla e de ordenar"],
"product_robot":["Robô assistente industrial","Estilo industrial: robô 3D que acena, percorre um caminho, encadeia animações e dança; organograma, ciclo, gráfico e quiz"],
"product_saas":["Demo de plataforma SaaS","Painel em janela de navegador com chamadas numeradas, radial, funil, indicadores, barras empilhadas, código por passos e perguntas"],
"product_security":["Segurança do produto","Néon verde: alvo em camadas, fluxo com conectores que aparece passo a passo, código destacado, gráfico, escada e atividade de correspondência"],
"product_watch":["Lançamento: relógio inteligente","Preto e ouro: relógio 3D que viaja por três diapositivos com Transformar e chegadas diferentes, Text Art dourado, radar e preços"],
"sci_ai":["Inteligência artificial","Néon violeta: robô 3D que acena e viaja com Transformar, cronologia, organograma, rede neuronal que se acende, gráfico e nuvem de palavras"],
"sci_brain":["Neurociência: o cérebro","Estilo escuro com brilhos: neurónio desenhado com impulso animado, figura 3D que caminha, radial, organograma, barras e legendar uma imagem"],
"sci_chem":["Química: a tabela periódica","Laboratório limpo: tabela periódica que se monta em cascata, moléculas com formas, braseiro 3D, equações, anel e associação"],
"sci_climate":["As alterações climáticas em dados","Faixas de aquecimento, gráficos de linhas, área e retângulos, efeito de estufa que se desenha, satélite 3D, ciclo e votação múltipla"],
"sci_mars":["Missão a Marte","Estilo espacial ferrugem: rover 3D da NASA com Transformar, astronauta a flutuar, órbita animada, equação e concurso"],
"sci_med_case":["Caso clínico: febre e tosse","Estilo processo clínico: pasta, carimbo, radiografia no negatoscópio com círculo que se desenha, CURB-65 com fórmula, votação e perguntas"],
"sci_med_ecg":["Cardiologia: ler um ECG","Papel de ECG: traçados que se desenham sozinhos, impulso que percorre o coração, tabela com fórmulas, equação, quiz e contagem regressiva"],
"sci_med_glucose":["Endocrinologia: glicose e insulina","Estilo app de sensor de glicose: telemóvel com o ecrã, ciclo um a um, curvas, rosca, tabela com fórmulas, equação, abacate 3D e votação"],
"sci_med_immune":["Imunologia: a resposta imune","Microscópio de fluorescência: células que se acendem, anticorpo desenhado, fagocitose com Transformar, organograma e correspondência"],
"sci_med_kidney":["Fisiologia renal: o néfron","Planta técnica: néfron que se desenha, gota que o percorre com som, cotas, cascata, equação, tabela com fórmulas, garrafa 3D e ciclo"],
"sci_med_knee":["Anatomia: o joelho","Estilo prancha anatômica antiga: texto curvo, gravura sépia, Transformar para os meniscos, matriz, tabela, figura 3D que caminha e etiquetar"],
"sci_med_micro":["Microbiologia: resistência antibiótica","Placas de Petri: colónias que surgem com som, crescimento exponencial, seleção contada com Transformar, antibiograma, radial e nuvem de palavras"],
"sci_med_pk":["Farmacocinética: a meia-vida","Estilo caixa de medicamento: blister que se enche, LADME um a um, curvas de duas séries, equações, tabela com fórmulas, código e lacunas"],
"sci_med_stroke":["Neurologia: código AVC","Contrarrelógio de urgência: luzes de sirene, número gigante com rufar de tambores, BE-FAST em cadeia, rosca, setas, ordenar passos e contagem regressiva"],
"sci_med_trial":["Ensaio clínico: ler os resultados","Estilo revista científica: CONSORT com conectores, curvas de sobrevivência, tabela com fórmulas, NNT, forest plot em cadeia e quiz"],
"sci_newton":["Física: as leis de Newton","Caderno de física: equações, carro 3D em movimento, lançamento oblíquo que se desenha, tabela com fórmulas e preencher lacunas"],
"sci_python":["Programação em Python","Estilo editor escuro: terminal que se escreve sozinho, código com passos de destaque, saída animada, ordenar linhas e desafio com contagem decrescente"],
"sci_solar":["O sistema solar","Planetas à escala que aparecem em cadeia, três sondas 3D com vistas e movimentos diferentes, tabela, diagrama radial e associação"],
"sci_stats":["Estatística e probabilidade","Estilo editorial: curva normal que se desenha, fórmulas, histograma, dispersão, área, barras e bolhas, e pergunta com pontos"],
"sci_thesis":["Defesa do trabalho de fim de curso","Académico sóbrio: capa institucional, índice, metodologia com equação, tabela com totais, resultados em gráficos, bibliografia e perguntas"],
"showcase_3d":["Catálogo: o 3D a fundo","Modelos 3D com todas as opções: vistas, movimentos ao entrar, rotação, bordas, margem, clips, andar e chegada com Transformar"],
"showcase_animations":["Catálogo: animações","Todas as animações de objeto: entrada, ênfase, saída, trajetórias, desenhar, encadeadas, sons e várias num objeto"],
"showcase_charts":["Catálogo: gráficos","Os 15 tipos de gráfico, dois por diapositivo, com séries, combinado, grelha, etiquetas e títulos dos eixos, e a tabela de opções"],
"showcase_diagrams":["Catálogo: diagramas","Os 15 esquemas de diagrama escritos como estrutura, os 4 esquemas de cor e o aparecimento um a um ao apresentar"],
"showcase_morph":["Catálogo: Transformar","Transformar passo a passo: texto que muda de tamanho e lugar, formas, barras que crescem, imagem, 3D e letras que se reordenam"],
"showcase_objects":["Catálogo: multimédia e objetos","Código com passos, equações, ícones, cinco dispositivos, tabelas com estilos e fórmulas, zoom de diapositivo e conectores"],
"showcase_polls":["Catálogo: votações e atividades","Os 11 tipos de votação e atividade pelo telemóvel, contagem decrescente nos três estilos, classificação e modo sala de aula"],
"showcase_shapes":["Catálogo: formas","Todas as formas por categorias com o nome, linhas e tracejados, gradientes, opacidade, traço à mão, sombras, texto dentro e rotação"],
"showcase_text":["Catálogo: Text Art e tipografia","Os 10 estilos de Text Art, texto curvo, colunas, cinco níveis de marcadores, os 8 pares de letra, alinhamento e espaçamento"],
"showcase_transitions":["Catálogo: transições","As 22 transições de diapositivo, uma a uma: entrada, saída diferente, direções, velocidade e avanço automático"]};
